### ISSUE TITLE
Click Function geht nicht 

### ISSUE THREAD

**Issue by SelinaMaz** [JirkaDellOro/EIA2#10]
Bei einem Klick auf eins der Felder möchte ich ein "Hallo" in der Console ausgeben lassen.
Eclipse zeigt mir keine Fehler an und ich selbst kann mir auch nicht erklären wieso das nicht klappt. 
Kann mir jemand vielleicht auf die Sprünge helfen ?

Hier ist mein Code:

let x: number = 0;
let divList: NodeList = document.getElementsByTagName("div");

divList[x].addEventListener("click", function (): void {
    console.log("Hallo");
});

**Comment by saenglert** [comment]
Hallo Selina,
wird denn kein Fehler in der Konsole ausgegeben? Außerdem könntest du deinen aktuellen Stand bitte auf Github pushen, damit ich einen Blick auf das Gesamtwerk werfen kann, ich sehe hier nämlich mehrere Punkte, an denen etwas schief laufen könnte:

- Hast du überhaupt divs im HTML Dokument platziert, die gefunden werden können?
- Sind diese divs zum Zeitpunkt des Aufrufs getElementsByTagName überhaupt schon im DOM

**Comment by SelinaMaz** [comment]
Danke für die schnelle Rückmeldung. 
Ja es wird was angegeben aber ich verstehs leider nicht. 
Ja eigentlich habe ich Divs erzeugt die gefunden werden könnten. 
Und ja eigentlich sollten die auch bereits im DOM sein. 

Hier ist der Link zu meiner Datei:
https://selinamaz.github.io/EIA2/aufgabe_03/js/a03a.js

**Comment by saenglert** [comment]
Huch, was macht denn dein TypeScript Code in einer JavaScript Datei?
JavaScript Code ist valider TypeScript Code, aber umgekehrt funktioniert das leider nicht.

Dein Problem ist, wann dein Programmcode ausgeführt wird. Schau dir mal an, wann er von der Webseite gelesen wird und auf was er dann versucht zuzugreifen.

**Comment by SelinaMaz** [comment]
ok... welchen Part meinst du genau mit TypeScript in JavaScript Datei, denn eigentlich schreibe ich die Codes immer nur in der Ts. Datei ?

**Comment by saenglert** [comment]
Den Link den du gepostet hast führt zu einer Datei namens a03a.js
Darin sollte sich eigentlich reiner JavaScript Code befinden. Allerdings befinden sich dort TypeScript Konstrukte wie z.B. Variablendeklaration mit dem let Schlüsselwort, was nur in der .ts Datei passieren sollte. Ist dein TS Compiler eingeschalten? Rechtklick auf das Projekt > Configure > Enable Typescript Compiler

**Comment by moritzhfu** [comment]
Ich sehe hier auch gerade keinen Typescript-Code in der Javascript-Datei. _Let_ ist offiziell seit 2015 ECMAScript-Standard: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/let

Unabhängig davon hast Du ja folgende Fehlermeldung in der Konsole stehen:
_Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at a03a.js:78_

D.h. in Zeile 78 wird versucht einem Element einen EventListener zu verpassen. Dies schlägt allerdings fehl, da das Element nicht gefunden wird. Im Debugger des Browsers wird in der Typescript-Datei auch die Stelle rot unterkringelt. Hier ist es die Zeile 91, da die Fehlermeldung von der Javascript-Datei gemeldet wurde, hier unterscheiden sich die Zeilennummern etwas.
Da Du diesen Aufruf nicht in der anonymen Methode des EventListeners "DOMContentLoaded" ausführst, ist vermutlich der DOM noch nicht komplett aufgebaut und das Element wird nicht gefunden.
Verschiebe doch mal Zeile 88-93 in die diese Methode. Danach sollte es funktionieren.

Für die Zukunft: Gerne immer auf die HTML-Datei verlinken. Somit kann man viel schneller helfen. So musste ich jetzt auf dein Repository gehen und mir die richtige HTML-Datei raussuchen und den Pfad dazu manuell einfügen.

**Comment by JirkaDellOro** [comment]
@saenglert : wenn wir nach Ecma6 kompilieren kommt let so raus wie es reinkam. JavaScript kommt langsam den dafür vereinbarten Standards nach, die TypeScript schon eine Weile unterstützt.

**Comment by saenglert** [comment]
@JirkaDellOro Zu meiner Zeit .... verdammtes neumodisches Zeugs ... grml grml ....

**Comment by JirkaDellOro** [comment]
@saenglert: tja, so schnell ist man oldschool

**Comment by SelinaMaz** [comment]
@moritzhfu 
Ok das nächste Mal verlinke ich die HTML Datei.
Ich probiers mal aus und schau ob dass mit dem Verschieben funktioniert.

**Comment by SelinaMaz** [comment]
@moritzhfu 
Es hat funktioniert vielen Dank :)
