### ISSUE TITLE
ts compiled nicht zu js Dokument 

### ISSUE THREAD

**Issue by nessrebe** [JirkaDellOro/EIA2#100]
Hallo, meine ts Datei compiled nicht zu meinem js. Hacken bei "Einstellungen" - "TypeScript" - "Compiler" - "Compile all TypeScript files" ist gesetzt.

**Comment by saenglert** [comment]
Hallo Rebeca,
hast du den TypeScript Compiler auch im Projekt aktiviert?
Linkes Übersichtsfenster > Rechtsklick auf Projekt > Configure > Enable TypeScript Compiler (ist er bereits aktiv steht dort stattdessen 'Disable TypeScript Compiler' )

**Comment by nessrebe** [comment]
okay hat geklappt, danke!
