### ISSUE TITLE
Random Funktion geht nicht

### ISSUE THREAD

**Issue by Leah1995** [JirkaDellOro/EIA2#101]
Aus irgendeinem Grund funktioniert es nicht, dass Bäume und Schneeflocken zufällig platziert werden.
Ich hatte einen ähnlichen Code schon früher benutzt und dann ging es, aber hier auf einmal nicht und ich verstehe nicht, warum. 
Es zeigt mir auch keine Fehler an und ich komme einfach nicht weiter.
Das hier ist die Aufgabe: https://leah1995.github.io/EIA2/Aufg2/Aufg2.html
Über Hilfe würde ich mich sehr freuen!

**Comment by moritzhfu** [comment]
Randomfunktion funktioniert wunderbar. 
Das Problem ist:
Du übergibst der Methode `drawBaum1 `& `drawBaum2 `jeweils einen zufälligen x- und y-Wert, arbeitest damit aber nie weiter, sondern zeichnest den Baum jeweils an einer festen Position.

**Comment by Leah1995** [comment]
Ah danke, sowas dachte ich mir. Jetzt kann ich es lösen, denke ich.
