### ISSUE TITLE
Bäume mit Funktion zeichnen

### ISSUE THREAD

**Issue by koechelj** [JirkaDellOro/EIA2#102]
Hallo,
die Bäume, die ich mithilfe der function drawTree zeichnen möchte, erscheinen als grüne Striche, nicht als grün gefüllte Dreiecke. Woran könnte das liegen? 

https://koechelj.github.io/EIA2_Aufgaben/Aufgabe%2002,Functions-Skipiste/Functions-Skipiste.html

**Comment by RedImp1470** [comment]
Ich denke das liegt an diesen beiden Zeilen in der Funktion (76, 77):
crc2.lineTo(x + 30, y + 5);
crc2.lineTo(x - 30, y - 5);

Diese beiden befehle zeichnen zusammen eine Diagonale. D.h. die Berechnung für den Zweiten Punkt (Zeile 77)stimmt so nicht. Zeichne dir das Ergebnis doch mal zur Veranschaulichung in ein Koordinatensystem ein.

**Comment by RedImp1470** [comment]
Anmerkung: Bitte keine Funktionen schachteln. D.h. "drawTree" und "Schneesturm" bitte außerhalb von "init" schreiben.

**Comment by koechelj** [comment]
Super, danke
