### ISSUE TITLE
Eclipse lässt sich nicht mehr öffnen

### ISSUE THREAD

**Issue by AnjaOtt** [JirkaDellOro/EIA2#103]
Mein Eclipse lässt sich nicht mehr öffnen. Sobald ich es starte kommt noch der Startbildschirm und ich kann mein workspace auswählen, aber danach kommt nichts mehr. Auch keine Fehlermeldung. Weiß jemand, was das Problem sein könnte?

**Comment by JirkaDellOro** [comment]
Haben Sie sicher auch den Project-Explorer geöffnet? Siehe Window->Show View

**Comment by AnjaOtt** [comment]
Ich hab das Problem gefunden, danke!

**Comment by JirkaDellOro** [comment]
Was war es denn?
