### ISSUE TITLE
Dateien sind fehlerhaft

### ISSUE THREAD

**Issue by MonettaMarchiano** [JirkaDellOro/EIA2#104]
Ich hab das Problem, dass meine Dateien fehlerhaft sind. Zuerst dachte, dass am Workspace liegen würde, als es das nicht war, habe ich den selben Workspace auf einen anderen Stick gewechselt und die neuste Version von Eclipse heruntergeladen, da sah es erst so aus als wenn es funktioniert hätte, aber nach dem ich auf die Ordner geklickt habe, waren die Dateien weg und Eclipse zeigt mir wieder Fehler an. Jetzt gerade kann ich Eclipse gar nicht öffnen. Weiß jemand eine Rat?

**Comment by moritzhfu** [comment]
Welche Ordner hast du angeklickt?
Welche Dateien sind fehlerhaft; woher weißt Du, dass sie fehlerhaft sind?
Welche Fehler zeigt Eclipse an?

Gerne das Problem immer etwas ausführlicher beschreiben oder Screenshots anhängen.

**Comment by MonettaMarchiano** [comment]
Die Aufgabenordner im EIA-2 Ordner selbst. 
Zuerst sah es so aus, als wenn der Pfad nicht richtig ist, weil die Project-Datei nicht gefunden werden konnte. Die ist allerdings noch im Ordner enthalten. Allerdings habe ich seit dem letzten Mal, als ich Eclipse verwendet hatte, keine Probleme gehabt. 

Das ist der aktuelle Fehler zu Eclipse:
![eclipde](https://user-images.githubusercontent.com/32566125/32292384-534d7ccc-bf40-11e7-9e86-5750dea0b129.JPG)

**Comment by moritzhfu** [comment]
Soweit ich das sehe, wurden die Fehlermeldungen in einer Log-Datei gespeichert.
Kannst Du diese Datei mal öffnen (z.B. mit Notepad) und den Inhalt hier posten.
Dann kann man diese Fehlermeldungen interpretieren und (hoffentlich) beheben.

**Comment by MonettaMarchiano** [comment]
das Problem ist, dass einige Dateien, bspw. die Plugins, von der alten Version nicht gelöscht werden konnten und ich deshalb nicht weiß, in welchem Ordner ich die fehlerhafte Datei finde, auch wenn ich in der Suchleiste die Zahlen am Ende eingebe.
