### ISSUE TITLE
Es wird nichts angezeigt

### ISSUE THREAD

**Issue by vanessanova** [JirkaDellOro/EIA2#105]
Leider wird bei mir nicht mal die Berge, Himmel etc. angezeigt die nicht über eine Funktion generiert werden. Habe eben geschaut in der alten Aufgabe geht es auch nicht mehr..
Warum?

**Comment by JirkaDellOro** [comment]
Ist der aktuelle Code gepusht? Ich sehe nämlich noch alles...

**Comment by vanessanova** [comment]
Habe eben grade den Neuen Hochgeladen, leider wird immernoch nicht das angezeigt was nicht über eine funktion generiert wird. Ich kann aber lokal nicht mal die alten Aufgaben anschauen, ich sehe immer nur ein e weiße seite und mein .js wird auch nicht angezeigt.

**Comment by JirkaDellOro** [comment]
Hallo Vanessa,
ich kann in Skipisteneu den Aufruf der Main-Funktion nicht finden. Ist der verloren gegangen?

**Comment by vanessanova** [comment]
Hallo, ich habe es jetzt wieder gefixed bekommen. Danke :+1:

**Comment by JirkaDellOro** [comment]
Was war das Problem? Allein der fehlende Aufruf, oder gab es noch mehr?
