### ISSUE TITLE
Position des zweiten Skifahrers

### ISSUE THREAD

**Issue by koechelj** [JirkaDellOro/EIA2#106]
Hallo,
mein zweiter Skifahrer fährt identisch auf dem ersten. Welchen Wert ändere ich da am besten, damit der zweite Skifahrer an einer anderen Stelle herunterfährt? Habe schon versucht, einzelne X Werte von Kopf, Körper und Skibretter abzuändern. Leider verschiebt sich dann alles etwas ungünstig.

**Comment by JirkaDellOro** [comment]
Achtung, hier liegt ein Denkfehler vor. Sie haben derzeit im Fahrer-Array Daten für nur einen Skifahrer. Mit diesem einen Datensatz versuchen Sie zwei unterschiedliche Funktionen (ersterSkifahrer und zweiterSkifahrer) zu füttern. Mit diesem Ansatz müssten Sie für jeden weiteren Skifahrer eine neue Funktion schreiben...!
Der richtige Ansatz ist genau umgekehrt: Es gibt eine Funktion (deren Namen übrigens eine Aktivität wie z.B. drawSkier darstellen sollte) welche einen Datensatz entgegen nimmt und anhand dessen einen Skifahrer zeichnet. Im Array liegen viele solcher Datensätze für unterschiedliche Skifahrer. In einer Schleife werden die Daten abgearbeitet und für jeden Skifahrer die Funktion aufgerufen.
Schauen Sie sich bitte noch einmal meinen Code aus der Vorlesung an!

**Comment by koechelj** [comment]
Danke :)
