### ISSUE TITLE
fehlende Objekte

### ISSUE THREAD

**Issue by MarciAlka** [JirkaDellOro/EIA2#107]
Ich habe nun Klassen für Skifahrer, Wolken und Schnee erstellt und die methoden in animate aufgerufen. Ich verwende immernoch Arrays in den Klassen.

Meine animate scheint jedoch nicht aufgerufen zu werden, da ich nicht mal die Bäume angezeigt bekomme, die in keiner Klasse stehen, sondern direkt in der Funktion. (Skifahrer, Wolken Schnee werden natürlich nicht angezeigt). Fehler werden mir nicht angezeigt. Nun weiß ich nicht genau, wo mein Denkfehler lag. (der Code ist noch etwas unübersichtlich, da altes noch drinnen steht, bis das neue funktioniert)

ts/js sind auf hier:
https://github.com/MarciAlka/EIA2/tree/master/Aufgabe5

**Comment by JirkaDellOro** [comment]
Die Klassen sind nicht im HTML-Dokument eingebunden. Außerdem soll eine Klasse nur genau ein Objekt beschreiben. Die Arrays zur Verwaltung mehrere Objekte gehören ganz klar in das Hauptprogramm!
