### ISSUE TITLE
Schnee und Bäume werden nicht generiert

### ISSUE THREAD

**Issue by hoeriglisa** [JirkaDellOro/EIA2#108]
Sowohl Eclipse als auch die Konsole zeigen keinen Fehler an. 
Die Wolken und die Skifahrer funktionieren, beim Schnee und den Bäumen finde ich die Fehlerquelle nicht..

Der Link zur Aufgabe:
https://hoeriglisa.github.io/EIA2/CanvasAufgabe5/Canvasfile5.html

**Comment by RedImp1470** [comment]
In den Konstruktoren von Tree und Snow musst du den Variablen Werte zuweisen, nicht verändern. D. h. dort sollte z.B. this.x = _x stehen und nicht this.x +=x.
Deine Bäume werden dann gemalt, aber an einer Position außerhalb des Canvas. Der mit Math.random berechnete y-Wert ist zu groß (über 600).

**Comment by JirkaDellOro** [comment]
Im Constructor dieser Klassen werden die übergebenen Werte der Koordinaten nicht zugewiesen, sondern nur auf die aktuellen draufaddiert. Da diese aber zu dem Zeitpunkt noch nicht definiert sind, kommt auch ein undefinierter Wert heraus...

**Comment by JirkaDellOro** [comment]
Sarah hat gewonnen um ein paar Sekunden...

**Comment by hoeriglisa** [comment]
Ach, doch einfacher als gedacht :)

Vielen Dank!
