### ISSUE TITLE
Keine Anzeige

### ISSUE THREAD

**Issue by Leah1995** [JirkaDellOro/EIA2#109]
Hallo,

mein Problem ist, dass nichts angezeigt wird und ich verstehe nicht, warum.
Es werden mir in Eclipse auch keine Fehler angezeigt.
In der Konsole werden mir Fehler angezeigt, die aber teilweise einfach verschwinden oder wieder auftauchen. Z.B: Uncaught TypeError: Class extends value undefined is not a constructor or null.

Hier ist die Aufgabe: https://leah1995.github.io/EIA2/Aufg5/Aufg5.html

Danke schon mal im Voraus!

**Comment by saenglert** [comment]
Hi, Leah!
dann schauen wir mal:
> TypeError: class heritage Classes.Trees is not an object or null

Du hast vergessen deine in Baum.ts, die deine Tree Superklasse enthält, in deiner HTML Datei zu verlinken. Entsprechend wird die Klasse nicht gefunden.

> TypeError: Classes.crc2 is undefined

Überlege dir nochmal, wann deine Hintergrundlandschaft in deiner main.ts gemalt werden soll und wann auch der RenderingContext in Form von crc2 dafür verfügbar ist. Da gibt es im Moment eine große Differenz zwischen was du glaubst was passiert und was tatsächlich passiert.

**Comment by Leah1995** [comment]
Dankeschön, das hat mir sehr geholfen!
