### ISSUE TITLE
Fehler bei Zugriff auf div

### ISSUE THREAD

**Issue by JanaBurger** [JirkaDellOro/EIA2#11]
hallo,
wir sitzen schon lange an der Aufgabe 3b). Bis jetzt hat alles einigermaßen geklappt, aber nun wollen wir, dass bei Click auf die erstellten divs im Handstapel diese verschwinden und zum Ablagestapel dazugezählt werden. Jedoch erkennt es bei uns die Klick Funktion nicht und wir wissen nicht warum :(
Erkennt jemand den Fehler? 

Hier der Link:
https://janaburger.github.io/EIA2/aufgabe3/aufgabe3.html

Danke schonmal :)

**Comment by saenglert** [comment]
Hallo Jana,
das liegt daran, dass dein Programm nie bis zu der Stelle kommt, an der der EventListener angehängt wird. Schau doch mal in die Konsole deiners Browser und überprüfe was dir dort für Fehler ausgegeben werden.

**Comment by JanaBurger** [comment]
Danke für die schnelle Antwort,
aber in der Konsole werden bei uns irgendwie keine Fehler ausgegeben...

**Comment by saenglert** [comment]
Also wenn ich die von dir verlinkte Seite in Firefox öffne und auf deinen blauen Stapel klicke, wird eine grüne Karte erstellt und in der Konsole der fehler
`TypeError: handcards is undefined`
ausgeben.

**Comment by JanaBurger** [comment]
Ahja, das haben wir jetzt auch gesehen, jedoch wissen wir einfach nicht wie wir den Fehler beheben können.

**Comment by moritzhfu** [comment]
Das Problem ist hier u.a. der Aufbau des Codes. Hier ist eine Funktion innerhalb einer Funktion geschachtelt. Deshalb ist auch der Gültigkeitsbereich von Variablen teilweise verschoben bzw. nicht so wie man es erwarten würde.

In einem ersten Schritt alle Funktionen, die innerhalb der anonymen Funktion des EventListeners "DOMContentLoaded" definiert sind, komplett nach außen umlagern.

**Comment by JirkaDellOro** [comment]
Bestehen die Probleme noch und ist der Code im Repository aktuell?

**Comment by JirkaDellOro** [comment]
Bitte außerdem meinen Code aus der Vorlesung nochmal studieren und euren Code analog aufbauen:
- namespace anlegen, damit die verwendeten Namen sich von denen in anderen Dateien im Projekt abgrenzen
- Alle Funktionen auf der ersten Ebene im namespace anlegen. Keine Funktionen innerhalb anderer Funktionen definieren.
- Keine anonymen Funktionen verwenden
-- also statt ...addEventListener("click", function(...): void {.....}
-- immer schreiben ...addEventListener("click", nameDerFunktion);
