### ISSUE TITLE
Fehlermeldung 

### ISSUE THREAD

**Issue by vanessanova** [JirkaDellOro/EIA2#110]
In meiner Konsole kommt immer diese Fehlermeldung:
schnee.js:4 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (schnee.js:4)
    at schnee.ts:2
    at Aufgabe6 (schnee.ts:2)
    at schnee.ts:51

und in meinem js steht immer prototype obwohl es in meinem ts nicht ist.
In Eclipse ist keine Fehlermeldung.

Danke schonmal im vorraus :smile:

**Comment by JirkaDellOro** [comment]
Ist der Code schon auf Github zu finden?

**Comment by vanessanova** [comment]
Ja habe Aufgabe 6 hochgeladen

**Comment by JirkaDellOro** [comment]
Ich habe das Projekt importiert und erhalte in Eclipse zwei Fehlermeldungen zur Entwicklungszeit
1. in movingobjects.ts steht in Zeile 57 eine verlorene Klammer
2. in skipiste6.ts fehlen in Zeile 36 die Parameter für den Contructor

Wenn ich die beiden Fehler behebe tut sich etwas

**Comment by vanessanova** [comment]
Habe es jetzt gefixed danke :+1:
