### ISSUE TITLE
Gezeichnet, aber nicht bewegt

### ISSUE THREAD

**Issue by hoeriglisa** [JirkaDellOro/EIA2#111]
Hallo,

leider bewegt sich nichts in meinem Canvas. Alles wird gezeichnet, jedoch nicht bewegt.

Eine Idee woran es liegen könnte?
Eclipse und die Konsole zeigen keine Fehlermeldungen mehr...

Zum Canvas: https://hoeriglisa.github.io/EIA2/CanvasAufgabe6/Canvasfile6.html

**Comment by JirkaDellOro** [comment]
Animate wird nur einmal aufgerufen, weil setTimeout außerhalb steht...

**Comment by hoeriglisa** [comment]
Danke!
