### ISSUE TITLE
students[i] is undefined

### ISSUE THREAD

**Issue by weisshab** [JirkaDellOro/EIA2#112]
Meine Ausgabe queryData() erzeugt ein Error "student[i] is undefined".

**Comment by saenglert** [comment]
Betreuer.exe hat einen schwerwiegenden Fehler festgestellt: Zu wenig Information fuer konkrete Antwort.

Um diesen Fehler zu beheben geben Sie bitte folgende Information an:

- Aktuelle Aufgabe an der zuletzt gearbeitet wurde
- Speicherort der aktuellsten Version der Aufgabe (github.com stark bevorzug) 
- Grobe Uebersicht ueber erwartetes Programmverhalten

Um diese Fehlermeldung zu schliessen druecken Sie bitte Alt+F4

**Comment by JirkaDellOro** [comment]
Es wirklich geschickt wäre, gleich einen Link auf die aktuelle Lösung mitzuschicken. Ich habe den Code nun aber gefunden. Bitte überlegen und im Code nachvollziehen, an welcher Stelle im Array erste Eintrag gespeichert wird! Dies dann besser korrigieren. Wir haben auch einen geschickteren Befehl bereits kennen gelernt, um einen neuen Eintrag hinten an ein bestehendes Array anzuhängen.
