### ISSUE TITLE
Löschen der bereits erstellten Buchstaben

### ISSUE THREAD

**Issue by saileral** [JirkaDellOro/EIA2#113]
Ich versuche die bereits erstellten div-Elemente in Sequenz 2 zu löschen, dazu habe ich auf diese einen EventListener angesetzt... Nun scheint es ein Problem damit zu geben, dass ich in der dazugehörigen Funktion zwei Parameter(MouseEvent und KeyboardEvent) übergebe. Tipps wie dieses Problem umgangen werden kann?
Link zur Aufgabe:
https://saileral.github.io/EIA_2/Aufgabe9/start_aufgabe9.html

**Comment by saenglert** [comment]
Hi Alica,
wie du schon richtig erkannt hast, liegt das Problem daran, dass du versuchst zwei Events in einer Funktion zu empfangen.

Der onClick Eventlistener wird immer dann aufgerufen wenn die linke oder rechte Maustaste betätigt wird, aber nicht wenn du eine Taste auf dem Keyboard drückst (Touchpads lassen wir jetzt mal außen vor). Dementsprechend wird alles was du vom onKeyDown/Up Event erwartest, nicht an den onClick Eventlistener weitergegeben. Ein Eventlistener liefert dir immer nur die Info für dieses eine spezifische Event.

Events liefern in aller Regel nicht nur die primäre Information wie z.B. folgendes Element wurde angeklickt oder diese Taste wurde betätigt, sonder auch zusätzliche Properties(Eigenschaften) oder Metadaten. Schau dir mal an, was das MouseEvent noch so alles zu bieten hat: 

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent

**Comment by saileral** [comment]
Hallo Jascha!
Das war ja simpler als gedacht, vielen Dank :)
