### ISSUE TITLE
Buchstaben bleiben "undefined"?

### ISSUE THREAD

**Issue by AdrianaGudic** [JirkaDellOro/EIA2#114]
Hallo,
ich habe das Problem, dass meine div Boxen als undefined dargestellt werden.
Es werden keine Buchstaben gezeichnet, trotz Funktionsaufruf.

  let alphabet: string [] = []
  function init(): void {
         for (let i = 65; i <= 90; i++) {
            alphabet.push(String.fromCharCode(i));
            drawBox(alphabet[i]);
        }

function drawBox(_alphabet: string): void {

        let div: HTMLDivElement = document.createElement("div");

        div.innerText = _alphabet;
        div.style.backgroundColor = "cccccc";
        div.style.width = "30px";
        div.style.height = "30px";
        div.style.margin = "1px";
        div.style.fontSize = "20px";
        div.style.textAlign = "center";
        div.id = _alphabet;
        div.className = "letter";

Woran könnte das liegen? Danke schonmal im Voraus.

**Comment by JirkaDellOro** [comment]
Hallo Adriana,
wir können in der Regel viel besser helfen, wenn der Code schon in Ihrem Repository liegt. Bitte beim nächsten Mal erst diesen hochladen.
In diesem Fall ist der Fehler aber anhand ihres Posts zu erkennen. alphabet ist zu Beginn ein leeres Array, dorthinein werden die Buchstaben-Strings gepusht. Der erste kommt also auf Position 0. Im Aufruf zu drawBox wird aber auf Position 65 zugegriffen...

Frage: was haben Sie eigentlich mit dem alphabet-Array noch vor?
Hinweis: der Parameter von drawBox sollte besser _letter heißen. Und vielleicht fällt Ihnen auch noch ein anderer Name für drawBox ein, der die Aufgabe besser beschreibt (z.B. createLetterSelectionBox)

**Comment by AdrianaGudic** [comment]
Danke Herr Dell'Oro für die schnelle Antwort und die Hinweise.
Ich habe meiner init Funktion eine weitere For-Schleife zugefügt, die das Array von 0 bis 25 durchgeht. Die Buchstaben werden nun korrekt erzeugt. :)

**Comment by JirkaDellOro** [comment]
Schön. Allerdings haben Sie meine Frage nicht beantwortet. Aus dem Code im Repository kann ich aber erkennen, dass das alphabet-Array derzeit nicht weiter genutzt wird. unter diesen Umständen hätten Sie, statt eine zweite Schleife zu bauen, auch einfach auf das Array verzichten und folgendes schreiben können:
```
 for (let i = 65; i <= 90; i++) {
            drawBox(String.fromCharCode(i));
  }
```

**Comment by AdrianaGudic** [comment]
Stimmt, das Array wird nicht weiter genutzt. Da habe ich wohl zu kompliziert gedacht. Ist gefixed, danke!
