### ISSUE TITLE
Buchstaben mit Alt löschen 

### ISSUE THREAD

**Issue by koechelj** [JirkaDellOro/EIA2#115]
Hallo, 
ich habe das Problem, dass ich meine Buchstaben mit Alt nicht mehr aus dem Textfeld löschen kann. Ich weiß leider nicht, was ich im Code falsch gemacht habe.

**Comment by JirkaDellOro** [comment]
Ich habe den Code kommentiert und einen Pull-Request erstellt, bitte reinschauen:
https://github.com/koechelj/EIA2_Aufgaben/pull/1/commits/53d75c195fba44a7c299f305f2de59d0c10d0608

Meine Kommentare habe ich mit >>>> gekennzeichnet. Es gibt einiges zu verbessern, der Kern des Problem aber findet man ganz unten.

**Comment by koechelj** [comment]
Vielen Dank Herr Dell'Oro für die schnelle Rückmeldung

**Comment by JirkaDellOro** [comment]
Kommen Sie mit dem Pullrequest klar?

**Comment by koechelj** [comment]
Ja
