### ISSUE TITLE
Werte einer select-Box auslesen

### ISSUE THREAD

**Issue by saileral** [JirkaDellOro/EIA2#116]
Hallo zusammen:)
Ich habe etwas Probleme die Werte meiner select-box auszulesen.. Ich wollte es über den selectedIndex probieren, allerdings bekomme ich dann die Fehlermeldung, dass options keine Eigenschaft von EventTarget ist(wodurch ich auch nicht auf den selectedIndex zugreifen kann) und ich finde keine gute Lösung hierfür. Über value kann ich zwar den Wert auslesen, aber wenn der Nutzer den Wert der selectBox nicht ändert, da das richtige bereits ausgewählt ist, bekomme ich (natürlich bedingt durch meinen EventListener onchange) auch keinen Wert.
Ich benötige einen kleinen Tipp wie diese Probleme umgangen werden können.
Danke, schonmal im Voraus!

Hier der Link zur Aufgabe (nicht erschrecken, ich habe die Aufgabe noch nicht gestylt):
https://saileral.github.io/EIA_2/Aufgabe10/start_aufgabe10.html

**Comment by JirkaDellOro** [comment]
Hallo Alica,

ich nehme an, dass Sie einen Entwicklungszeitfehler meinen, der also schon von Typescript in Eclipse angezeigt wird. Und ich nehme an, dass Sie sich auf die Zeile 161 beziehen, die derzeit auskommentiert ist.

//  console.log(_event.target.options.selectedIndex);

Wenn wir uns daran erinnern, dass das Target eines Events zunächst vom Typ der Superklasse EventTarget ist, welche auch die Eigenschaften value etc. nicht besitzt, wird auch Zeile 162 wieder klarer:

        let target: HTMLInputElement = <HTMLInputElement>_event.target;

Mit den spitzen Klammern wird dem Compiler mitgeteilt, dass _event.target als Objekt der Subklasse HTMLInputElement betrachtet werden soll. Das ist ein sogenannter Typecast. Somit hat man dann Zugriff auf die weiteren Eigenschaften. 

Wenn Sie nun wissen, dass das Element eine SelectBox ist, können Sie einen Typecast zum weiter spezifizierten Typ HTMLSelectElement verwenden, dann sollten also auch die hier spezifisch erweiterten Eigenschaften erreichbar sein.

**Comment by JirkaDellOro** [comment]
PS: gut, dass Sie zunächst die Funktionalität angehen und das Styling später.

**Comment by saileral** [comment]
Das hatte ich bereits probiert, allerdings bringt es mich nicht weiter. "options" ist eine Eigenschaft von HTMLSelectBox, allerdings fehlt dann immernoch der Zugriff auf den selectedIndex.
Wenn ich mir in der Konsole _event.target ausgeben lasse, finde ich unter "options" die Eigenschaften length und selectedIndex, daher würde es für mich so Sinn machen:
console.log(target.options.selectedIndex); 
Komischerweise kann ich auf die Eigenschaft length zugreifen, auf selectedIndex allerdings nicht und ich verstehe nicht weshalb das so ist. Ich erhalte die Entwicklungsfehlermeldung "property selectedIndex does not exist on type HTMLCollection", was mich leider nicht weiter bringt, auch nach Recherchen zu HTMLCollection.

**Comment by JirkaDellOro** [comment]
Bitte den aktuellen Code hochladen!

**Comment by JirkaDellOro** [comment]
Und damit Sie selbst vielleicht schon gleich weiter machen können, habe ich den Code aus der Vorlesung um einen if-Block erweitert, der den Zugriff demonstriert:
```
    function handleChange(_event: Event): void {
        //console.log(_event);
        //*/
        let target: HTMLInputElement = <HTMLInputElement>_event.target;
        console.log("Changed " + target.name + " to " + target.value);

        //*/ für Alica 
        if (target.id == "select") {
            let selectElement: HTMLSelectElement = <HTMLSelectElement>_event.target;
            let index: number = selectElement.selectedIndex;
            console.log("Index: " + index);
            console.log("Options: " + selectElement.options);
            console.log("Selected: " + selectElement.options[index]);
        }
        
        //*/ note: this == _event.currentTarget in an event-handler
        if (this.id == "checkbox")
            console.log("Changed " + target.name + " to " + target.checked);
        //*/
        //*/
        if (target.name == "Slider") {
            let progress: HTMLProgressElement = <HTMLProgressElement>document.getElementsByTagName("progress")[0];
            progress.value = parseFloat(target.value);
        }
        //*/
        //*/
        if (target.name == "Stepper") {
            let progress: HTMLProgressElement = <HTMLProgressElement>document.getElementsByTagName("meter")[0];
            progress.value = parseFloat(target.value);
        }
        //*/
    }
```

**Comment by saileral** [comment]
Aktueller Code ist oben. Vielen Dank für dieses Codebeispiel! Ich denke, ich weiß nun wo mein Denkfehler lag und werde jetzt weiter daran rumbasteln.

**Comment by JirkaDellOro** [comment]
Super. Bitte gleich melden, wenn es wieder hakt. Manche Features werden nämlich vielleicht von der installierten Typescript-Version nicht unterstützt. Das sollten wir uns dann gemeinsam anschauen.

**Comment by saileral** [comment]
Hallo Herr Dell'Oro!
Das wäre nun der Fall. Hier ist der aktuelle Stand der Aufgabe:
https://saileral.github.io/EIA_2/Aufgabe10/start_aufgabe10.html
Ich arbeite garade am if-Block ab Zeile 242. Meine Idee war Folgende: Ich habe eine for-Schleife gebaut, die das array in dem meine Schmuckartikel gespeichert sind abläuft und dann prüft, ob das Element checked == true ist. Wenn das er Fall ist, möchte ich den innerText des Elements in ein array zwischenspeichern, um im nächten Schritt die Länge dieses arrays abzulaufen und den innerText dem body anzuhängen. Das Problem ist aktuell, dass trotz der Bedingung if (inputElement.checked == true) alle Werte in das array gespeichert werden. Aktuell verstehe ich nicht warum.

**Comment by saileral** [comment]
Die Punkte Halterung und Lieferoptionen funktionieren schon, allerdings mit sehr viel Code, weshalb ich nun bei den Schmuckartikeln versuchen wollte, das Problem etwas kompakter zu lösen. Selbst wenn das Problem mit dem array gelöst ist, hätte ich dann das Problem auf die zugehörigen Preise zuzugreifen, da ich dafür in diesem Fall auch noch keine Lösung habe.

**Comment by JirkaDellOro** [comment]
Hallo Alica,
ich sehe mehrere Probleme
1. die IDs der HTML-Elemente sollten immer eindeutig sein. Die Checkboxen im Schmuckartikel-Div tragen aber alle die id "check". Das ist nicht gut.
2. tatsächlich muss eine andere Lösung her, auch für Halterung und Lieferoptionen. Derzeit funktioniert das nur, weil der Code genau auf die Daten abgestimmt ist. Kommt jetzt aber bei den Daten eine Halterung oder eine Lieferoption dazu, muss auch der Programmcode erweitert werden. Das soll laut Aufgabenstellung nicht so sein: "Somit genügt es, in dieser Datei die Daten zu verändern oder zu ergänzen, um das Angebot des Weihnachtsbaumkonfigurators anzupassen."
3. in der Schleife werden alle Schmuckelemente durchlaufen, es wird dabei jedesmal geprüft, ob das geänderte target "gecheckt" ist. Ist es das, landen alle labeltexte im checkedId-array, oder gar keins, wenn es nicht der Fall ist.

**Comment by JirkaDellOro** [comment]
Grundsätzlich ist die Idee gut, bei einem Change nicht nur auf das angeklickte Element zu reagieren, sondern mit den Ausgangsdaten zu arbeiten bzw. das ganze Formular zu betrachten. Ein einfacher und zielführender Ansatz ist es, bei jeder Änderung das ganze Formular durchzugehen und den aktuellen Zustand zu ermitteln. Es ist dann nicht relevant, WAS sich geändert hat, sondern nur DASS sich etwas geändert hat. Dann kann nämlich auch die Warenkorbanzeige bei jeder Änderung einfach komplett neu aufgebaut werden. Sonst muss man diese auch zwischenspeichern und parallel ändern.

**Comment by JirkaDellOro** [comment]
Auch den Wert eine Radiobutton-Group kann man anhand des Namens folgendermaßen ermitteln, ohne dass hierzu eine Schleife erforderlich wäre, welche die einzelnen Radiobuttons prüft:  
```
let radiogroup: HTMLInputElement;
radiogroup = <HTMLInputElement>(document.querySelector("input[name=Radiogroup]:checked"));
console.log(radiogroup.value);
```
Der Code ist wieder bezogen auf mein Vorlesungsbeispiel, da heißt die Gruppe "Radiogroup"

**Comment by JirkaDellOro** [comment]
Die Preise einzubinden ist einfach, wenn man mit den Ausgangsdaten arbeitet, so wie bereits in der Datendatei vorgesehen sind. Dann geht man diese durch, prüft, welchen das korrespondierende Formularelement entspricht und hat dabei ja gleich den Preis parat.  
Übrigens:
- da die Interfaces bei Ihnen alle identisch sind, würde sich ein allgemeineres, z.B.mit dem Namen Bestellposten oder OrderItem, anbieten.
- der export sollte bei den Arrays genügen, es muss nicht jeder Einzelposten exportiert sein, da er nur zum Befüllen der Arrays dient
- überhaupt sollte man das kompakter, übersichtlicher und mit weniger Variablen machen können, z.B. so:
```
export let baumarten: Baumart[] = [
   { art: "Nordmanntanne", preis: 31.55 },
   { art: "Blaufichte", preis: 48.36 },
   { art: "Fichte", preis: 29.99 },
   { art: "Kiefer", preis: 56.84 }
];
```

**Comment by saileral** [comment]
Danke für die Tipps!

**Comment by JirkaDellOro** [comment]
Gerne, und bitte bei Bedarf weiter fragen.

Nun sind alle Daten in einem einzigen Array gelandet, dadurch muss man sie per Code wieder auseinander friemeln. Ein Array pro Produktart (Baumart, Schmuck, etc) wäre noch deutlich einfacher.
