### ISSUE TITLE
Programm streikt?

### ISSUE THREAD

**Issue by Leah1995** [JirkaDellOro/EIA2#117]
Wenn ich versuche ts-Datein zu erstellen oder zu öffnen, geht das nicht und ich bekomme nur eine Menge Fehlermeldungen. Der TypeScript-Builder und der TSLint-Builder sind enabled, und ich weiß nicht, wie ich das wieder beheben kann. Für Hilfe wäre ich dankbar!

![help](https://user-images.githubusercontent.com/26458497/34641077-a81f0166-f2fe-11e7-8414-b4aeb54a5727.JPG)

**Comment by saenglert** [comment]
Hi Leah,
der Workspace Log sieht für mich schwer danach aus, dass das Problem bei den Palantir Plugins liegt (typescript und tslint).

Erstmal die Klassiker:

- Hast du Eclipse neugestartet?
- Hast du die Plugins TSCompiler und TSlint deaktiviert und wieder aktiviert?

Im nächsten Schritt schlage ich vor sämtliche Eclipse Software auf Updates zu prüfen:
_Help > Check for Updates_
Anschließend wieder die Klassiker versuchen.

**Comment by Leah1995** [comment]
Die Klassiker helfen mir klassischerweise leider nicht weiter und wenn ich auf Updates prüfe kommt das:

![helpp](https://user-images.githubusercontent.com/26458497/34643603-5184e176-f327-11e7-8bbe-1c0321247255.JPG)

**Comment by JirkaDellOro** [comment]
Seit wann besteht das Problem? Hat es vorher mit derselben Installation funktioniert? Was wurde gemacht, bevor der Fehler zum ersten mal auftrat? Vielleicht kann man daraus Erkenntnisse gewinnen...

**Comment by Leah1995** [comment]
Das Problem besteht seit heute, vorher hat es keine Probleme gemacht. Ich weiß auch nicht, was es ausgelöst haben könnte, es ist direkt nachdem ich Eclipse geöffnet habe aufgetaucht.

**Comment by saenglert** [comment]
Hm, wir könnten zwar jetzt noch durch den Eclipse error.log gehen, aber der ist normalerweise sehr kryptisch.

Meine Empfehlung: Deinstalliere und installiere Eclipse neu. Dein Workspace/Project bleibt ja vorhanden, du musst nur die Einstellungen in Eclipse (TypeScript, TSLint installieren) nochmal machen, was ja nicht viel Aufwand ist.

**Comment by Leah1995** [comment]
Ja, dann bleibt mir wohl nur noch das übrig. Danke für die Hilfe
