### ISSUE TITLE
Result wird nicht angezeigt

### ISSUE THREAD

**Issue by LorenaEberhart** [JirkaDellOro/EIA2#119]
Hallo, 
ich habe mir bei mLab eine Datenbank angelegt und wollte dann durch die passende URL meine Datenbank aufrufen. Bei Result bekomme ich aber nur einen Error:

Unable to connect to database, error: MongoNetworkError: failed to connect to server [ds.263367.mlab.com:63367] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND ds.263367.mlab.com ds.263367.mlab.com:63367]

Was habe ich falsch gemacht?

**Comment by RedImp1470** [comment]
Das klingt als hättest du einen Fehler im Query in der URL, z.B. falsches Passwort oder Nutzername etc.
Mit welcher URL hast du es denn versucht?

**Comment by LorenaEberhart** [comment]
ich habe folgende URL benutzt: 

https://mongodbrowser.herokuapp.com/?u=lorena&p=1234&a=ds.263367.mlab.com:63367/datenbank&n=datenbank&c=Bauernhof

**Comment by RedImp1470** [comment]
Wenn ich den Punkt hinter ds bei "a=ds.263367.mlab.com:63367/datenbank" entferne geht es :)

**Comment by LorenaEberhart** [comment]
Ah super jetzt funktioniert es danke!
