### ISSUE TITLE
Übergabe eines Wertes durch eine Funktion

### ISSUE THREAD

**Issue by braundominik** [JirkaDellOro/EIA2#12]
Hallo ich habe folgende Probleme bei Aufgabe 4.2:

**Problem 1**

Ich habe auf meine div Container welche meine Hand darstellen Event Listener gesetzt. 

`handDivs[0].addEventListener("click", function(): void { ablegen(0); });
    handDivs[1].addEventListener("click", function(): void { ablegen(1); });
    handDivs[2].addEventListener("click", function(): void { ablegen(2); });
    handDivs[3].addEventListener("click", function(): void { ablegen(3); });
    handDivs[4].addEventListener("click", function(): void { ablegen(4); });`

Diese Lösung mit einer anonymen Funktion welche lediglich die ablegen Funktion mit der entsprechenden Zahl aufruft funktioniert auch.

Wenn man es jedoch so schreibt:

`handDivs[0].addEventListener("click", ablegen(0));`

Gibt er folgende Fehlermeldung aus: 

> - Argument of type 'void' is not assignable to parameter of type 'EventListener | EventListenerObject'.
  Type 'void' is not assignable to type 'EventListenerObject'.

Die Funktion ablegen ist natürlich vom Typ "void" da sie nur Dinge ausführt und nicht zurückgibt
Gibt es einen Weg die Übergabe der number zu erzwingen ?

**Problem 2**

Ebenfalls könnte man anstatt die Event Listener manuell anzulegen diese mithilfe einer for Schleife anlegen.

`for (var i: number = 0; i < handDivs.length; i++) {
       handDivs[i].addEventListener("click", ablegen);
    }`

Hier müsste man der Funktion "ablegen()" jeweils den Wert von i übergeben. Der i Wer muss jedoch dem i Wert entsprechen welcher zum Zeitpunkt des Hinzufügens des Event Listeners vorhanden war.
Gibt es hier irgendeine Möglichkeit i zu einem konkreten Zeitpunkt mit einem bestimmten Event Listener zu verbinden ?

[Vollständiger Code](https://github.com/braundominik/EIA2/tree/master/aufgabe4.2)

Grüße
Dominik

**Comment by saenglert** [comment]
**Problem 1**
Wenn du .addEventListener(a, b) auf ein Element anwendest passiert praktisch folgendes: Du sagts dem Element wenn A passiert arbeite mit B weiter. 
```
document.addEventListener("click", function(): void {});
```
sagt also aus, wenn jemand klickt, arbeite mit dieser Funktion weiter.
```
document.addEventListener("click", clickFunktion);
function clickFunktion(): void {}
```
Macht dasselbe nur das die Funktion nicht anonyme ist. Wenn geklickt wird, rufe die Funktion clickFunktion auf.
```

document.addEventListener("click", clickFunktion(1));
function clickFunktion(num: number): void {}
```
Ist ein kleiner aber feiner Unterschied: Sobald du die zusätzlichen Klammern ins Spiel bringst, wird das als Funktionsaufruf interpretiert, nicht nur reine Angabe was zu tun ist. Hier steht jetzt praktisch "Wenn geklickt wird, Rufe die Funktion clickFunktion mit dem Übergabewert 1 auf und arbeite mit dem Ergebnis weiter. 

Deine Funktion hat aber ein Ergebnis (Rückgabewert) vom Typ Void, also gibt es nichts womit das Programm weiterarbeiten kann, deswegen die Fehlermeldung. Die sagt nämlich "Ich erwarte an dieser Stelle etwas vom Typ EventListener oder EventListenerObject. Das einfachste Element dafür was wir bisher kennen ist eine Funktion, die wir dann wie in Beispiel 1 oder 2 übergeben.

Aber sicher fragst du dich jetzt, wie bekommst du dann deine Information welche Karte angeklick wurde an das Event übergeben? Dazu gehen wir jetzt fließend ins **Problem 2** über:

Ich sage es einfach mal ganz direkt: Du brauchst garnicht einen manuellen Wert an deine Funktion  übergeben. Alles was du brauchst steht in dem EventObject, das automatisch generiert wird, wenn ein Event ausgelöst wird. Schau dir dazu mal das [Schaubild von Herrn Dell'Oro](https://github.com/JirkaDellOro/EIA2/blob/master/DO-Hierarchy.pdf) an und recherchiere wie du darauf zugreifen kannst.

**Comment by moritzhfu** [comment]
Zuerst direkt die Antwort. Ja funktioniert. Folgender Code funktioniert:

`document.addEventListener("DOMContentLoaded", init);

function init(): void {
    let divElement: HTMLDivElement = <HTMLDivElement>document.getElementById("test");
    divElement.addEventListener("click", iExpectTwoVariables.bind(this, 10));
}

function iExpectTwoVariables( _e: Event, _i: number): void {
    console.log(_e)
    console.log(_i);
}`

Mehr dazu: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

Jetzt aber die große Frage warum Du das benötigst? Normalerweise ist dies nicht notwendig. Vor allem nicht bei der gestellten Aufgabe. Möchtest du z.B. wissen auf welches Element du nun gedrückt hast, so kannst Du einfach den textContent auslesen und diesen an den Ablagestapel übergeben.
Ebenso könntest Du auch jeder Karte eine id entsprechend dem Iterator der for-Schleife geben.

**Comment by moritzhfu** [comment]
Noch eine kleine Korrektur, total Off-Topic:

> Wenn geklickt wird, Rufe die Funktion clickFunktion mit dem Übergabewert 1 auf und arbeite mit dem Ergebnis weiter.

Das Verhalten von Typescript ist hier eigentlich folgendes: Die Funktion wird nicht an das "click"-Event gebunden und wartet deshalb nicht auf dieses sondern wird unabhängig, direkt nach dem Laden, bzw. beim Parsen der Datei aufgerufen.

Beispielcode zum Testen:

```
document.addEventListener("DOMContentLoaded", init);

function init(): void {
    let divElement: HTMLDivElement = <HTMLDivElement>document.getElementById("test");
    divElement.addEventListener("click", iExpectTwoVariables(this, 10));
}

function iExpectTwoVariables( _e: Event, _i: number): EventListener {
    console.log(_e)
    console.log(_i);
    return null;
}
```

**Comment by JirkaDellOro** [comment]
@saenglert: "Hier steht jetzt praktisch 'Wenn geklickt wird, Rufe die Funktion clickFunktion mit dem Übergabewert 1 auf und arbeite mit dem Ergebnis weiter.' " ist eine etwas unglückliche Formulierung.

Besser ist "Hier steht jetzt praktisch 'Rufe die Funktion clickFunktion mit dem Übergabewert 1 auf und merke dir das Ergebnis.  Wenn später mal ein Klick kommt, rufe das Ergebnis auf.' "
