### ISSUE TITLE
Keine Veränderung im Browser

### ISSUE THREAD

**Issue by LorenaEberhart** [JirkaDellOro/EIA2#120]
Hallo,
wenn ich versuche in Eclipse etwas zu ändern, zeigt es mir keine Änderung im Browser an. Was kann ich dagegen tun? Den Cache habe ich schon geleert.

**Comment by LorenaEberhart** [comment]
Außerdem bekomme ich immer wieder die selbe Fehlermeldung, dass egal was ich eingebe es nicht zu meinem Interface zuweisbar ist. Egal ob ich mit einem Namen aus dem Interface arbeite oder auch nicht, ständig taucht derselbe Fehler auf?

**Comment by JirkaDellOro** [comment]
Hallo Lorena,
ist der aktuelle Code in Ihrem Github-Repository zu finden?

**Comment by JirkaDellOro** [comment]
Bitte pushen!

**Comment by LorenaEberhart** [comment]
Oh ok, ich habe ihn gepusht!

**Comment by JirkaDellOro** [comment]
![image](https://user-images.githubusercontent.com/6279994/35471323-3946c68c-0359-11e8-8b58-4f06c4ab5fd0.png)

Eclipse zeigt mir gleich die Fehler an: Type 'string' is not assignable to type 'Produkte'.

Bezüglich der korrekten Verwendung der Datentypen müsste es eher so heißen:
baum[0].name = currentTree;
baum[0].price = currentPrice;

Allerdings frage ich mich, ob sie wirklich das Array mit der Liste der erhältlichen Bäume verändern wollen, wenn der Nutzer eine Formularänderung durchführt.

**Comment by JirkaDellOro** [comment]
PS: solange noch Fehler im TS-Code sind, wird kein neues JS-Kompilat erstellt und man sieht nur die letzte kompilierte Version.
