### ISSUE TITLE
assoziative arrays

### ISSUE THREAD

**Issue by saileral** [JirkaDellOro/EIA2#121]
Guten Abend :)
Ich habe eine Frage bezüglich der korrekten Unterscheidung zwischen homogenen/ heterogenen assoziativen arrays, da ich mittlerweile zwei verschiedene Erklärungen gefunden habe, die Folgendes besagen:
1. Unterscheidung nach Datentyp: homogen--> selber Datentyp, heterogen--> verschiedene Datentypen
2. Unterscheidung danach, ob key vorgegeben ist: wenn vorgegeben--> heterogen, wenn nicht--> homogen
Welche der beiden Erklärungen ist richtig?
Vielen Dank schon im Voraus,
Alica

**Comment by JirkaDellOro** [comment]
Hallo Alica,

die beiden Erklärungen schließen sich nicht aus, sondern ergänzen sich. In TypeScript können wir ein homogenes assoziatives Array z.B. mit folgendem Interface beschreiben:
```
interface Prices {
   [key: string] : number
}
```
Das sagt lediglich aus, dass die Schlüssel vom Typ string und die Werte vom Typ number sein sollen. Alle Werte sind also vom gleichen Typ (number) und die Schlüssel sind nicht vordefiniert, sondern werden erst bei der Verwendung vergeben, z.B.
```
let price: Price = [ ];
price["Tanne"] = 22.99;
price["Lärche"] = 19.99;
```
Die jetzt vergebenen Schlüssel sind "Tanne" und "Lärche"
<hr/>

Ein heterogenes Array dagegen definieren wir derart:
```
interface Article {
   name: string,
   price: number
}
```
Hier sind also die Schlüssel vordefiniert (name und price) und die dadurch referenzierten Werte sind von unterschiedlichem Typ (string und number)

**Comment by saileral** [comment]
Bedeutet das, dass bei einem heterogenen assoziativen array beides gegeben sein muss? Also zum einen der unterschiedliche Datentyp, als auch die Festlegung von Schlüsseln?

**Comment by JirkaDellOro** [comment]
Das sind sehr gute Fragen, sie (und Sie) zwingen mich zum Nachdenken. Und die Antwort ist ein unklares JEIN, denn man kann auch folgendes kreieren:
```
interface Homo {
    [key: string]: any;
}

let hetero: Homo = { "string": "Hallo", "number": 123, "bool": true };
console.log(hetero);

interface Hetero {
    name: string;
    firstname: string;
    address: string;
}

let homo: Hetero = { name: "Dampf", firstname: "Hans", address: "In allen Gassen" };
console.log(homo);
```
Das Interface Homo erlaubt jetzt Werte unterschiedlicher Datentypen (any haben wir aber in unserem Kurs ausgeschlossen, damit so etwas nicht passiert), und ich kann damit also ein bezüglich der Werttypen heterogenes Array erstellen. Im Interface Hetero hingegen sind alle Werte vom Typ string, das damit kreierte Array ist also diesbezüglich homogen.

Letztendlich ist die Art und Weise, wie die Schlüssel definiert sind, das entscheidendere Kriterium. Vermeidet man any, führt das im Homo-Interface auch bezüglich der Werttypen zu einem homogenen Array. Beim Hetero-Interface hat man dagegen zumindest die Möglichkeit, unterschiedliche Werttypen zu definieren.

Es gibt auch noch ein weiteres Unterscheidungsmerkmal. Beim homogenen Array ist die Zahl der Einträge unbegrenzt, beim heterogenen auf die Zahl der vordefinierten Schlüssel beschränkt.

Zu beachten ist vor allem, dass die Bezeichnungen homogen und heterogen für assoziative Arrays keine offiziellen sind, sondern von uns im Rahmen des Kurses zur Unterscheidung herangezogen werden und unsere Anwendungsfälle beschreiben.

Man kann nämlich das Ganze auch noch vermischen:
```
interface Mix {
    [key: string]: number | string;
    x: number;
    name: string;
}

let mix: Mix = { x: 123, name: "Dampf", mehr: 123 };
mix["undnochmehr"] = "herrje";
```

**Comment by saileral** [comment]
Ok, ich denke das habe ich soweit verstanden, wenn ich mir auch nur schwer ein Anwendungsbeispiel für interface Mix vorstellen kann. (Und bei let mix müsste 'mehr', wenn ich es richtig verstanden habe, in Anführungszeichen stehen, oder?) Danke, für Ihre ausführliche Erklärung!

Wenn Sie schon so schön beim Erklären sind hätte ich noch eine weitere Frage :)
Und zwar ist mir noch nicht ganz klar geworden, was für eine Rolle mongoDB bei mLab spielt. Mein Verständnis sieht aktuell so aus: mongoDB bietet mir die Datenbasis für meine mLab-Datenbank in der Cloud und kann sich an dieser automatisch versorgen und die Datenbasen skalieren/ändern.

**Comment by JirkaDellOro** [comment]
Das interface ist nur ein akademisches Beispiel, eine praktische Verwendung ist nicht gegeben. Solcherlei interfaces können aber durchaus in der fortgeschrittenen Anwendung relevant sein. Die Schlüssel müssen bei der Zuweisung eines literalen Objektes nicht unbedingt in Anführungszeichen stehen, kann man aber machen.

mLab ist ein Service, der einen einfachen Zugang zu MongoDB-Instanzen in der Cloud bietet. Auf den Servern läuft also MongoDB und über mLab kann ich mir dort Datenbanken für mich anlegen und nutzen. Analog dazu läuft auf den Heroku-Servern Node und auf Github läuft git.

**Comment by saileral** [comment]
Alles klar, dankeschön.
