### ISSUE TITLE
Bezierkurven als Ellipse

### ISSUE THREAD

**Issue by MarciAlka** [JirkaDellOro/EIA2#122]
Hallo!
Ich habe mich für die Endaufgabe bei einem Objekt an Bezierkurven gewagt, um eine Ellipse zu erschaffen. Diese Ellipse soll nachher der Körper einer Krabbe werden, doch ist sie etwas groß geraten und ich verstehe das mit den Werten nicht ganz (egal was ich ändere, es lässt sich nicht wirklich verkleinern). Der Krabbenkörper sollte in etwa so groß sein wie die herunterfallenden Kokosnüsse, doch es klappt einfach nicht... was muss ich ändern?
Code:
   //Krabbe
    crc2.beginPath();
    crc2.moveTo(75, 25);
    crc2.quadraticCurveTo(25, 25, 25, 62.5);
    crc2.quadraticCurveTo(25, 100, 65, 100);
    crc2.quadraticCurveTo(125, 105, 125, 62.5);
    crc2.quadraticCurveTo(125, 25, 75, 25);
    crc2.stroke();
    crc2.fillStyle = "#DB2929";
    crc2.fill();

// https://marcialka.github.io/EIA2/Endaufgabe/End.html

**Comment by saenglert** [comment]
Hey Denise!
Die quadraticCurveTo Methode nimmt 4 Werte engegen, Wert 1 und 2 repraesentieren einen Kontrollpunkt (1 = x, 2 = y Komponente), 3 und 4 stellen den Endpunkt deiner Kurve da (auch wieder x und y jeweils).

Das Mozilla Developer Network hat eine super Seite mit einigen Beispielen zum Ausprobieren:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/quadraticCurveTo

Ich gebe dir einen Tipp: 
Du hast voellig richtig erkannt, dass du eine Bezierkurve brauchst um eine Ellipse zu erstellen. Allerdings klappt das im Moment nicht so ganz aufgrund der Kontrollpunkte. Es gibt eine weitere Methode des Canvas die dich Bezierkurven zeichnen laesst. Vergleich die beiden mal und ueberlege was die Unterschiede dir bringen koennen.

Zur Groesse empfehle ich dir einfach mal eine Ellipse in ein Koordinatensystem zu zeichnen. Die Mitte sollte auf dem Ursprung liegen. Versuche jetzt die Ellipse ohne feste Zahlenwerte also nur mit den Variablen X und Y ( die den Mittelpunkt darstellen sollen) zu definieren.

PS: Bitte nicht ueber Umlaute wundern, ich schreibe auf der Arbeit im US Layout :)

**Comment by MarciAlka** [comment]
Vielen Dank, habe es geschafft :)
