### ISSUE TITLE
Eventlistener "onmousedown"/Bewegung eines Objekts durch Buttons

### ISSUE THREAD

**Issue by MarciAlka** [JirkaDellOro/EIA2#123]
Hallo!
Nachdem mein Objekt nun fertig gebaut wurde (in einer Klasse), möchte ich, dass es sich bewegt, wenn man den jeweiligen Button gedrückt hält. 
(Linker Button -> nach links laufen, Rechter Button -> nach rechts; es soll nun nur der x Wert verschoben werden)  -> es funktioniert aber nicht so, wie ich es mir vorgestellt habe (es bewegt sich gar nichts, habe schon mehrere Ansätze durchprobiert). Buttons habe ich genommen, weil es auch auf dem Handy funktioniert, evtl wird noch erweitert für die Tastatur mit den Pfeiltasten, aber erst möchte ich die Buttons hinbekommen.

hier mal der Ansatz, an dem ich jetzt gerade hänge:
Ich habe zwei Buttons mit onmousedown in html erstellt, die beide eine jeweilige Funktion in ts aufrufen
d.h.: html:
<button class="button" id="linksButton" type="button" onmousedown="move_Krabbe_links()">Links</button>
<button class="button" id="rechtsButton" type="button" onmousedown="move_Krabbe_rechts()">Rechts</button>

in ts werden die folgenden Funktionen aufgerufen: (nur mal für den Linken Button)
function move_Krabbe_links(){
   var krabbeLinks = document.getElementById('linksButton');
    krabbeLinks.addEventListener('onmousedown',move_links); 
}

function move_links(){
    clkrabbe.move_Krabbe_links;
    
}

Wobei clkrabbe die Klasse für mein Objekt ist.. d.h. ich rufe eine Methode auf, die in der Klasse Krabbe ist und das x von der draw() funktion aufzählt.

Klasse Krabbe (nur Methode)
move_Krabbe_links(): void{
for (let i: number = 800; i >= 0; i--){
    this.x =- i;
    this.draw();
    }
}
move_Krabbe_rechts(): void{
for (let i: number = 0; i < 800; i++){
    this.x =+ i;
    this.draw();
    }
}

in draw() wird die Krabbe gezeichnet. Was muss ich ändern bzw wie vorgehen, dass ich die Krabbe dazu bekomme sich um x nach links bei der funktion zu verschieben? Wie kann cih die alte position entfernen (das erste draw)?

**Comment by MarciAlka** [comment]
Korrektur: die Methode in der Klasse (move_Krabbe_links()) ist eig für den rechten Button; links fan ich bei i nicht bei 0 an und zähle solange >=0; und es wäre dann this.x=-i .... (also theoretisch, praktisch klappt es immer noch nicht.)

**Comment by saenglert** [comment]
Hi Denise,
Ich hab mal ein bisschen in deinem Quellcode gestöbert und hier erstmal die Gardinenpredigt, die jeder von mir zu hören bekommt: Einrückungen sind nicht zum Spaß da! Damit macht man den Code um einiges lesbarer und **Eclipse** bietet dir auch einen **Auto Formatter**, der das zum größten Teil übernimmt (**Strg + Shift + F**).

Zum Problem:
Die _draw_ Funktion hat erstmal nur zweitranging mit der Position zu tun. Sie nimmt die aktuell unter _x_ und _y_ gespeicherten Werte und nutzt sie um an der Stelle etwas zu zeichenen, aber sie verändert sie nicht. D.h. wenn du vor dem nächsten Aufruf deiner _draw_ Funktion nichts an diesen Werten änderst, wird die Krabbe natürlich wieder an derselben Stelle gezeichnet.

Die Aufgabe die Positionsdaten zu ändern sollte eine oder wie in deinem Fall mehrere andere Funktionen übernehmen (Guter Stil ist eine Aufgabe für eine Funktion). Mit deinen _move_Krabbe_links/rechts_ Funktionen hast du auf jeden Fall schonmal die richtige Idee gehabt, nur stockt es verständlicherweise noch etwas an der Umsetzung:

```
move_Krabbe_links(): void{
  for (let i: number = 800; i >= 0; i--){
  this.x =- i;
  this.draw();
}
```
Ich gehe davon aus, dass dein Plan so aussieht, dass wenn der User auf den linken Button klickt die Krabbe sich, solange der Button gedrückt ist, nach links bewegt. Desweiteren gehe ich davon aus, dass wir auf einem Canvas genormt nach Original Herr Dell'Oro Standards (TM) _800x600_ arbeiten und die Krabbe mittig im Bild sitzt (_x: 400 y: 300)_.

Was passiert also nun, wenn jemand auf den Button klickt und die Methode aufruft:

Schleifendurchlauf | i | x
-------------------|----|----
0 | | 400
1 | 800 | -800
2 | 799 | -799
... | ... | ...
800 | 0 | 0

Die Krabbe bewegt sich also von _x: -800_ bis _x: 0_ in einem Aufruft der _move_ Funktion. Dass negative Positionswerte im Canvas nicht sichtbar sind (da sie ja außerhalb des Canvas liegen) mal kurz zur Seite gestellt: Das ist eine verdammt schnelle Krabbe. Ein einfaches _this.x = this.x - 1_ statt der Schleife würde zum Testen erstmal völlig ausreichen. Schneller oder langsamer kann man die Krabbe dann immernoch machen, in dem  man den Wert der subtrahiert (Bewegung links) oder addiert (Bewegung rechts) anpasst.

Dann wäre da noch der Aufruf von _this.draw()_ in der Funktion. Einerseits ist das ein Stilbruch bei der Aufgabenverteilung (den man erstmal vernachlässigen kann), andererseits bekommst du damit ein schwerwiegenderes Problem: Wer kümmert sich darum, dass die Krabbe gezeichnet wird, wenn der User nicht auf einen Button drückt? Das Zeichnen könnte doch sicherlich eine gewisse Funktion übernehmen, die sich auch darum kümmert, dass unser Hintergrund up to date ist, oder?

Die Krabbe hat die entsprechenden Fähigkeiten, die Aufgaben sind verteilt, jetzt brauchen wir nur noch den Stein des Anstoßens, die Eventlistener:

```
function move_Krabbe_links(){
  var krabbeLinks = document.getElementById('linksButton');
  krabbeLinks.addEventListener('onmousedown',move_links);
}
```
Du kannst dir an dieser Stelle ruhig etwas Programmzeilen sparen und dem Eventlistener direkt die Funktion der Krabbe übergeben:

`krabbeLinks.addEventListener('mousedown', clkrabbe.move_Krabbe_links)`

Und jetzt nochmal ein letzter Stolperstein: Das _onmousedown_ Event. Aber damit lass ich dich erstmal selbst werkeln. Einfach wieder melden, wenn es nicht klappt :)

**Comment by JirkaDellOro** [comment]
Hat das hier geklappt, kann man den Issue schließen?
