### ISSUE TITLE
Listener CanvasElement

### ISSUE THREAD

**Issue by hasemama** [JirkaDellOro/EIA2#124]
Hi,
Ich suche nach einem Weg den Bäumen die ich auf dem Canvas zeichne EventListener zu geben. Im Internet habe ich dazu keine verständliche Hilfestellung gefunden. Habt ihr vielleicht einen Tipp oder so?
Danke im Vorraus

**Comment by saenglert** [comment]
Hey Marcel,
eine direkte Lösung gibt es dafür auch leider nicht. Dazu musst du bedenken, dass wenn etwas einmal auf das Canvas "aufgetragen" ist, gehört es zum Canvas selbst. Herr Dell'Oro benutzt dazu häufig den direkten Vergleich mit der namensgebenden Leinwand: Einmal aufgetragen, ist die Farbe fest mit der Leinwand verbunden und du kannst sie nicht mehr einzeln betrachten. EventListener können also maximal an das komlette Canvas angehängt werden.

Wir haben aber einen Vorteil gegenüber der klassischen Leinwand: Wir wissen wie sämtliche Farbkleckse (oder eben Bäume) auf dem Canvas zustande kommen und zwar über Wege/Paths.  Und es gibt da eine Methode die dir sagen kann, ob ein bestimmter Punkt (wie etwa ein ... Mausklick vielleicht?) innerhalb eines Pfads liegt:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInPath

**Comment by JirkaDellOro** [comment]
Anders ausgedrückt: Das HTMLCanvasElement ist ein DOM-Node und verfügt daher über die Fähigkeit, in das Eventsystem eingebunden zu werden. Ihr Baum dagegen ist wahrscheinlich lediglich ein Objekt, welches gezielt auf den vom CanvasElement zur Verfügung gestellten Bereich zeichnet, also Pixel manipuliert. Das HTMLCanvasElement kann nun also auf Mausklicks reagieren und beispielsweise die Mausposition bezogen auf die linke obere Ecke des Zeichenbereichs errechnen. Was es dann allerdings damit macht, bleibt der individuellen Programmierung überlassen.

**Comment by JirkaDellOro** [comment]
PS: zur Abschlussarbeit konnte ich zwar Code, aber kein Konzept finden... Wenn die Hinweise zur Aufgabenstellung beachtet werden, könnten wir viel besser helfen!!
