### ISSUE TITLE
Alert und Animation starten nicht

### ISSUE THREAD

**Issue by luiaj** [JirkaDellOro/EIA2#125]
Wenn ich mein html aus Eclipse direkt in den Browswe ziehe, funktioniert das Alert und auch die Animation (Starten beide, sobald man zwei Getränke gewählt hat und auf "MIX IT" klickt).

Ich habe alles hochgeladen und in den Steckbrief gespeichert und wenn man es dann öffnet, gibt es weder ein Alert noch eine Animation.

Woran liegt das?

**Comment by braundominik** [comment]
Hi,

Also in deiner HTML lädst du:
<script type="text/javascript" src="Sternchen.js"></script>

Deine .js Datei heißt jedoch **s**ternchen.js

Also am besten die Datei umbenennen. Dann wird das Skript auch geladen.

Bin mir nicht 100% sicher, dass dies das Problem löst.

**Comment by luiaj** [comment]
Super, danke! Jetzt klappt es :)

**Comment by JirkaDellOro** [comment]
Ich schätze, hier ist ein Deckel drauf. Super, dass ihr euch gegenseitig unterstützt!!
