### ISSUE TITLE
Images positionieren auf canvas

### ISSUE THREAD

**Issue by koechelj** [JirkaDellOro/EIA2#126]
Hallo, 
gerne würde ich mehrere Info-Images an bestimmten Stellen auf dem Canvas verteilen. Diese sollen sich beim Bewegen des Browserfensters mit der Zeichnung auf dem Canvas mitbewegen und an der vorgesehenen Stelle bleiben. Welche Positionierungsangaben sind hier richtig?

https://koechelj.github.io/EIA2_Aufgaben/Abschlussarbeit-interaktive%20Pflanze/interaktivePflanze.html

**Comment by JirkaDellOro** [comment]
Hier sollte zunächst geklärt werden, ob die Images über die Canvas-API direkt auf die Zeichenfläche gemalt werden sollen, oder ob sie als eigenständige HTML-Elemente über dem Canvas-Element dargestellt werden sollen. Bei letzterem wäre die Positionierung absolut bezogen auf ein gemeinsames Eltern-Element sinnvoll.

**Comment by koechelj** [comment]
Danke, hat geklappt :)
