### ISSUE TITLE
Bestehenden Canvas überschreiben

### ISSUE THREAD

**Issue by hoeriglisa** [JirkaDellOro/EIA2#127]
Hallo,

ich habe eine Frage zur Abschlussabgabe:

Wie lösche ich am besten den bestehenden Canvas, sodass der neue Winscreen gezeichnet wird? Ich habe bereits clearRect probiert, jedoch funktioniert das nicht.

Dadurch wird der Winscreen nicht gezeichnet. Außerdem wird beim erneuten "Startbutton" drücken eine neue Oma generiert, ohne dass die alte gelöscht wird.

LG

Die Abschlussabgabe: https://hoeriglisa.github.io/EIA2/Abschlussaufgabe/Abschlussaufgabe.html

**Comment by JirkaDellOro** [comment]
Hallo Lisa,

ich habe einen Pull-Request mit einigen Anmerkungen für Sie erstellt. Ein Kernproblem, was daraus nicht vordergründig ersichtlich ist, ist das Löschen der Arrays. Unabhängig von der Tatsache, dass es zu viele redundante Arrays gibt, funktioniert das Löschen per Splice so wie programmiert nicht. Es wird nämlich z.B. das Element an Index 0 gelöscht, die anderen rutschen nach und dann wird das Element an Index 1 gelöscht. Somit bleibt das nachgerutschte an Index 0 bestehen...
Einfach in init das Array (oder ggf. die Arrays) mit dem Zuweisungsoperator neu als leer definieren

a = [ ];

**Comment by JirkaDellOro** [comment]
PS: unbedingt die Konsolenausgaben beachten! Es kommen einige Fehlermeldungen.... :-(
