### ISSUE TITLE
auf div zugreifen

### ISSUE THREAD

**Issue by LorenaEberhart** [JirkaDellOro/EIA2#128]
Hallo,
ich versuche die Umrandung beim auswählen einer Flagge zu bearbeiten, dass sie wieder verschwinden kann, wenn ich eine andere Flagge anklicke. Schlussendlich sollten nämlich immer nur 2 Flaggen klickbar sein. Ich habe daher im html Dokument divs erstellt für die jeweiligen Fahnen sowie auch über TypeScript. Jedoch erscheinen die angelegten divs aus ts nicht und ich kann daher nicht auf diese zugreifen. Gibt es einen kleinen Tipp, wie ich das mit der Auswahl machen kann?

Hier der Link zu meinem Repository: [https://github.com/LorenaEberhart/EIA2/tree/master/Abschlussaufgabe](url)

und hier mein bisheriges Canvas: 
[https://lorenaeberhart.github.io/EIA2/Abschlussaufgabe/Abschluss.html](url)

**Comment by JirkaDellOro** [comment]
Hallo Lorena,

beide Links funktionieren nicht. Sie müssten so lauten:
https://github.com/LorenaEberhart/EIA2/tree/master/Abschlussaufgabe
https://lorenaeberhart.github.io/EIA2/Abschlussaufgabe/Abschluss.html

Zum Problem:
leider kann ich kein Konzept finden, daher ist es kaum möglich wirklich zielführend zu helfen. Grundsätzlich "fühlt" sich die Verquickung von der Darstellung auf dem Canvas und HTML-Elementen zur Interaktion in Ihrem speziellen Fall nicht optimal an. Sinnvoller erscheint es, sich zu entscheiden alles per Canvas oder per HTML-Elements (z.B. Image-Tags mit einem speziellen Stil für die Markierung) zu erledigen. Wenn Sie es auf dem Canvas machen, müssten Sie nur den Flags, bzw. deren Superklasse (die mit FlagsArray sehr irreführend benannt ist) beibringen, einen Markierungsrahmen zu zeichen...
