### ISSUE TITLE
div kann nicht mehrmals angeklickt werden

### ISSUE THREAD

**Issue by LienNgo1** [JirkaDellOro/EIA2#129]
Hallo,
folgende Probleme konnte ich leider auch mit der Hilfe von Google nicht beheben:

- ich kann die Objekte nicht mehrmals klicken. Wenn ich Anzahl der Klicks auf zB == 5 veränder dann kann man nicht mehr drauf klicken
- Eigentlich soll nach dem Klicken auf dem Baumstamm und dem oberen Teil des Wasserfalls ein Baumstamm und eine Alert Box erscheinen. Das geschieht auch aber der Baumstamm verschwindet aber wieder und bliebt nicht im Canvas
- Gerne würde ich noch wissen wie ich die Chemikalien im Wasserfall (die Funktion animate) aufhalte. Mit break und die Anzahl der Chemikalien auf 0 setzten habe ich leider nicht hinbekommen.

https://lienngo1.github.io/EIA2/Abschlussaufgabe/Abschluss.html

**Comment by braundominik** [comment]
zu 1: Die Variable Blub1 existiert zwar, jedoch wurde ihr kein Wert zugewiesen. 
zu 3: Du kannst die Arrays einfach als leer definieren z.B.:  `arrayX = []; `

zu 2: Kann ich nichts zu sagen, da bei mir sämtliche Elemente verschoben sind (siehe Bild).
![screenshot_10](https://user-images.githubusercontent.com/26409265/36322802-fa880720-134e-11e8-9d6d-492ea7b80dbe.png)

**Comment by LienNgo1** [comment]
Ahhh alles klar Danke!
wie fixe ich die Elemente denn am Besten? mit% funktioniert das auch nicht so wirklich...

**Comment by braundominik** [comment]
Die animate Funktion zeichnet alle Objekte mehrere Male in der Sekunden neu auf den Canvas.
DIe Funktion "drawwoodonwater()" zeichnet den Baum nur ein einziges mal.
Sobald die animate Funktion also ein weiteres mal ausgeführt wird überschreibt sie alle gezeichneten Objekte. In diesem Fall auch den Baum.
