### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by moritzgiuliani** [JirkaDellOro/EIA2#13]
Hallo,

ich habe mal mit altem Code von Animationen und dem neuen requestAnimationFrame rumgespielt und bin über ein Speicherproblem gestolpert.

Derzeit lasse ich Wolken darüber animieren allerdings wird die Wolke jedesmal neu gezeichnet glaube ich. So dass mit der Zeit hunderte / tausende davon im Speicher landen. Zumindest glaube ich das.

Ich kann die Zeichnung zwar in einen Array pushen und den auch beliebig zurück setzen aber das ändert denke ich nichts daran, dass der Speicher immer voller wird (und Firefox entsprechend langsam).

Muss man die Zeichnung der Animation an anderer Stelle machen und nur die Position innerhalb der animation verändern oder habe ich etwas grundsätzliches nicht verstanden?

Bin nach w3c vorgegangen. Ist alles hochgeladen.

Danke!

Schöner Ostersonntag!
Moritz

**Comment by saenglert** [comment]
Hi Moritz,
hab mich gerade mal in deinen Code eingelesen und das Problem ist tatsächlich, dass du in jedem Durchlauf der Animationsfunktion eine neues Objekt mithilfe deiner drawCloud Funktion erzeugst und in das jeweilige Array pusht.

Nach ein paar Sekunden gibt es z.B. bei mir schon gut 1600 Einträge im Array A, B hat gut 800 und C rund 500. Das schlägt natürlich auf die Performance.

Ich bin mir nicht 100% sicher, warum du den kompletten Funktionsaufruf speichern möchtest. Die einzige Information die du aus dem alten Frame brauchst ist die Position an der die Wolke gezeichnet wurde. Dafür hast du ja bereits ein Array, das du auch entsprechend pro Fame entsprechend manipulierst um die Position zu verschieben.

Wie Herr Dell'Oro bereits erwähnt hat haben wir im Moment keinen (einfachen) Weg Objekte persistent zu speichern (das lernen wir im späteren Verlauf). Deswegen ist meiner Ansicht nach aktuell die beste Möglichkeit lediglich die Position eines Objekts in einem (oder zwei für X und Y) Array zu speichern, im neuen Frame den Wert entsprechend abzuändern und dann die draw Funktion des Objekts mit den neuen Werten aufzurufen.

PS: Selbes Problem mit dem Projektil des Peashooters

**Comment by moritzgiuliani** [comment]
Hallo,

danke für die rasche Antwort. Ja sowas hatte ich mir auch gedacht.

Ich habe es jetzt mal wie folgt gemacht:
xPosition wird im Array gespeichert.

xPosition wird in der animate() modifiziert.

draw() des Objektes wird DANACH, also ausserhalb der animate() in der background() aufgerufen. Zwar wird der Background in der animate() immer wieder geladen, aber da er ja nicht neu gezeichnet wird wirken sich die Positions-Änderungen nicht aus. Stehe irgendwie auf dem Schlauch.

Habe es dennoch mal hoch geladen. Jetzt verändert sich optisch natürlich nichts (Wolken und Projektil ist an der Ausgangsposition) aber man kann per Konsole trotzdem mitverfolgen, wie sich die positionswerte korrekt verändern. Nur sieht man es halt nicht...

**Comment by saenglert** [comment]
Wir kommen der Sache schon näher, aber zuerst musst du nochmal einen Schritt zurückgehen und daran denken, was das Canvas eigentlich grundlegend ist: Eine Leinwand, auf der du Farbe aufbringen kannst. Sobald die Farbe einmal drauf ist, kannst du sie nicht mehr verändern, außer du malst direkt darüber. D.h. wenn du Befehle wie .rect() usw. ausführst, steuerst du den Pinsel, nicht die fertige Farbe auf dem Canvas.

Wenn man nun also eine Animation zeichnen möchte, muss man zwischen statischen und animierten Elementen unterscheiden. Der Hintergrund mit der Wiese, den Bergen etc. ändert sich ja nicht. Es genügt also diese Elemente einmal beim Start des Programms zu zeichnen, was du ja aktuell mit deiner background() Funktion machst.

DIe Elemente die bewegt sein sollen, wie deine Wolken, ändern sich ja praktisch in jedem Frame. Daher ist es notwendig diese immer wieder neu zu zeichnen, wofür du auch wieder ganz korrekt deine animate() Funktion bisher verwendet hast. 

Was dir gerade noch fehlt, ist die logische Verbindung welche Information wann benötigt wird und wie sie dort am Besten hinkommt. Ich hab dazu einfach mal kurz ein Beispiel geschrieben, dass ein Rechteck quer über das Canvas bewegt. 

Schau es dir an und überlege was ich da anstelle. Wir wildern zwar gerade sehr stark im Revier von Herrn Dell'Oros nächster Vorlesung, allerdings wird dich a) keiner hier bremsen, wenn du etwas voranpreschen willst und b) werden genau dieselben Fragen so oder so kommen, von daher haben wir direkt einen Thread auf den wir verweisen können.

PS : Hör mit den Funktionen innerhalb von Funktionen auf. Du brichst dir die Hände und im späteren Verlauf wird das sowieso nicht mehr funktionieren.
```

let context: CanvasRenderingContext2D;
let x: number = 0;
let y: number = 0;
let background: ImageData;

window.onload = init;

function init(): void {
    let canvas: HTMLCanvasElement = document.createElement("canvas");
    canvas.width = 800;
    canvas.height =  600;
    document.body.appendChild(canvas);

    context = canvas.getContext("2d");
    context.fillStyle = "#00ff00";
    context.fillRect(0, 0, context.canvas.width, context.canvas.height);

    background = context.getImageData(0, 0, context.canvas.width, context.canvas.height);
    animate();
}

function animate(): void {
    context.putImageData(background, 0, 0);
    
    x++;
    if (x >= context.canvas.width)
        x = -20;
    y++;
    if (y >= context.canvas.height)
        y = -20;

    drawRect(x, y);
    
    requestAnimationFrame(animate);
}

function drawRect(_x: number, y: number): void {
    context.fillStyle = "#0000ff";
    context.fillRect(_x, _y, 20, 20);
}

```

**Comment by JirkaDellOro** [comment]
Ihr dürft gerne vorarbeiten, ich habe eher Probleme wenn Leute hinterherhinken. Nested Functions vermeiden, die sind kein Standardkonstrukt imperativer Programmiersprachen. Mit TypeScript können wir näher an üblichen Standards arbeiten, wenngleich es dann JS-spezifischen Output erzeugt.

Ich werde übrigens weiter mit setTimeout arbeiten und nicht mit requestAnimationFrame. Die Animation ist für uns nur ein Spezialfall. Da man bei setTimeout die Verzögerung angeben kann, ist es noch in ganz anderen Kontexten verwendbar und daher interessanter.

**Comment by moritzgiuliani** [comment]
Danke für die ausführlichen Antworten.

Ja den Denkfehler habe ich dann irgendwann auch bemerkt. Ich dachte irgendwie, dass mit jeder draw() eine neue Instanz, ähnlich eines 3D-objekts erstellt wird, anstatt dass es einfach nur "übermalt" wird. Daher hatte ich es in den array gepusht um per Konsole auszulesen ob dem so sei. Dadurch hab ich mir selber einen Streich gespielt.

Ich habe es jetzt entsprechend angepasst und auch wieder mit setTimeout abgeändert. 
Was das Nesting anbelangt, habe ich eigentlich nur alle Funktionen in der ini drin oder ganz separat. Wenn ich sie aber alle separat mache und einzeln in der ini nur abfeuere habe ich derzeit noch riesige Probleme mit dem Scoping da sich viele Funktionen variablen teilen und sie dann nicht mehr verfügbar  / not defined sind. Muss ich alle erforderlichen Werte immer strickt mit Parametern übergeben oder gibt es eine Möglichkeit die variablen global anzulegen?

**Comment by JirkaDellOro** [comment]
Variablen, die außerhalb von Funktionen im Namespace angelegt werden, sind global für alle Funktionen des gleichen Namespaces zugänglich (Tatsächlich kommt beim Kompilieren wieder ein analoges Konstrukt heraus, wie das von dir zuvor explizit angelegte).
Grundsätzlich sollte man immer bestrebt sein, die Anzahl erforderlicher globalen Variablen möglichst zu reduzieren und eher mit Parametern zu arbeiten. Wenn wir in die objektorientierte Programmierung kommen, wird sich das Problem teilweise wieder etwas vereinfachen und es werden elegantere Lösungen ermöglicht.
