### ISSUE TITLE
Kollisions-Funktion funktioniert nur so halb

### ISSUE THREAD

**Issue by hasemama** [JirkaDellOro/EIA2#130]
Hi, 
Ich habe ein Problem mit meiner collision Funktion. Manchmal reagiert sie auf eine Kollision und manchmal nicht und ich weiss nicht genau wieso. Eigentlich sollte sie, so wie sie aktuell aufgebaut ist meiner Meinung nach funktionieren. Des Weiteren funktioniert aus irgendeinem Grund die Erkennung der Bildschirmbreiten nicht richtig. Deshalb würd ich das Ganze am Besten in der Smartphoneversion ansehen.
https://hasemama.github.io/EiA2_2/Frogger/main.html

**Comment by JirkaDellOro** [comment]
Kollision: scheint zuverlässig zu funktionieren, allerdings wird wohl geprüft, ob der Mittelpunkt des Kreises innerhalb eines Quadrates mit der Kantenlänge 20px um die linke obere Ecke eines Autos liegt. Es wäre geschickter, wenn die Kollisionsfunktion eine Methode der Autos wäre, denn die kennen ihre Dimensionen. Dann könnte man in Main.ts einfach formulieren:
```
if  (  object[i].isHit ( object[0] ) )
                loose();
}
```
Ich würde zudem die Spielfigur nicht in das Objekt-Array packen, sondern über eine eigene Variable ansprechen. object[0] ist nicht sehr aussagekräftig. Lieber noch andere Autos bauen...

**Comment by JirkaDellOro** [comment]
Die Collision-Funktion, so wie sie jetzt ist, kann übrigens stark vereinfacht werden zu 
```
 function collision(): void {
        //
        for (let i: number = 1; i < object.length; i++) {
            let x: number;
            let y: number;
            x = Math.abs(object[i].x - object[0].x);
            y = Math.abs(object[i].y - object[0].y);

            if (x < hitbox && y < hitbox) {
                loose();
            }
        }
    }
```

**Comment by JirkaDellOro** [comment]
Aber es wäre trotzdem besser, die Autos selbst die Kollision prüfen zu lassen und dabei die Methode isPointInPath des CanvasRenderingContext zu nutzen

**Comment by JirkaDellOro** [comment]
Habe eine Pull-Request für Main.ts erstellt

**Comment by hasemama** [comment]
Erstmal Danke
Ich habe ein paar Veränderung vorgenommen, allerdings wird jetzt nichts bis auf die Strasse gezeichnet. In der Konsole heisst es:
Uncaught TypeError: Abschlussaufgabe.Guy is not a constructor
    at Abschlussaufgabe (main.ts:16)
    at main.ts:143
Abschlussaufgabe @ main.ts:16
(anonymous) @ main.ts:143
main.ts:25 Uncaught ReferenceError: guy is not defined
    at init (main.ts:25)
init @ main.ts:25

Wieso guy nicht defined ist und das Ganze jetzt nicht funktioniert verstehe ich gerade nicht. Vielleicht stehe ich auch nur auf dem Schlauch. Wieso bekomme ich diese Ausgabe und wie kann ich den Fehler beheben?

**Comment by braundominik** [comment]
Das Dokument hat das entsprechende Dokument nicht schnell genug geladen glaube ich.
Einfach "guy" oben definieren und dann in der init Funktion initialisieren: "guy = new Guy(400, 500);"

**Comment by JirkaDellOro** [comment]
Guy.js ist wird in der HTML-Datei erst nach main.js eingebunden, sollte anders herum sein. Auf welchem Browser testen Sie? Firefox ist da wohl mittlerweile toleranter, auf Chrome bekomme ich auch noch dieses Verhalten.
