### ISSUE TITLE
Version aus dem Steckbrief stimmt nicht mit lokaler Datei überein

### ISSUE THREAD

**Issue by muellisa** [JirkaDellOro/EIA2#131]
Obwohl meine aktuellen files auf github geladen sind, wird eine veraltete Version über meine Steckbrief-Verlinkung angezeigt.
Die Verlinkung hat sich nicht geändert und soweit ich gesehen habe werden auch die .ts Dateien  zu .js Dateien kompiliert.
Habe meinen Browser Cache bereits mehrmals gelöscht und komme nicht darauf woran es liegen könnte, dass sich dieser Online noch an den alten Dateien orientiert.
Version aus der Steckbrief Verlinkung:
https://muellisa.github.io/EIA2/Abschlussaufgabe/abschlussaufgabe.html
Dateien auf Github:
https://github.com/muellisa/EIA2/tree/master/Abschlussaufgabe

**Comment by JirkaDellOro** [comment]
Ich glaube, dass ich die aktuelle Version zu sehen bekomme. Zumindest sind die jüngsten Änderungen wie z.B. "Autsch!Das Riff..." auch über github.io zu sehen. Manchmal dauert es einen Moment, bis die Daten von github auf pages veröffentlicht werden, vielleicht lag es daran?

**Comment by muellisa** [comment]
Ja genau das ist die aktuelle Version. Auf meinem Handy ist es beispielsweise auch die aktuelle Version. Allerdings sobald ich meinen Laptop benutze greift er auf alte Versionen zurück. Seit heute selbst wennn ich die Dateien lokal im Browser öffne. Das muss aber irgendwie an meinem Laptop / Browser liegen. Die Hauptsache ist ja dass es normalerweise funktioniert. Ich versuche es mal mit einem anderen Browser.
Vielen lieben Dank !
