### ISSUE TITLE
klickbarer div container generieren

### ISSUE THREAD

**Issue by MexXxy777** [JirkaDellOro/EIA2#132]
hallo,

ich möchte, dass die Vögel in
https://github.com/MexXxy777/EIA2/blob/master/Abschluss/Birds.ts
als div container erstellt werden, damit diese anklickbar sind, diese werden momentan ja nur pseudo ohne tag o.Ä. erstellt

main ts, vögel werden in Zeile 48 erstellt:
https://github.com/MexXxy777/EIA2/blob/master/Abschluss/Shooter.ts

Site:
https://mexxxy777.github.io/EIA2/Abschluss/Birdshoot.html

kann mir jemand weiterhelfen?

**Comment by JirkaDellOro** [comment]
Hallo Max,

das kann man machen, es wäre aber sehr ungewöhnlich HTMLElemente hierfür zu nutzen, wenn man das Spiel ohnehin schon auf dem Canvas hat. Standardmäßig würde man eher den Vögeln eine isHit-Methode spendieren, welche eine Position auf dem Canvas entgegen nimmt und prüft, ob diese in der Nähe der Vogelkoordinaten liegt (je nachdem, wie geschickt der Vogel um diese Koordinaten gezeichnet wird.) Man kann das mit der Methode isPointInPath bei Bedarf auch kantenscharf machen.

**Comment by MexXxy777** [comment]
Okay Danke!
das hört sich gut an, wird aber beim googlen immer komplizierter.. :-) haben Sie mir einen Tipp für einen Ansatz? muss ich hier mit dem click/move Handler arbeiten?

viele Grüße

**Comment by JirkaDellOro** [comment]
Ja. Einfach einen Click- oder MouseDown-Listener am Canvas installieren. Der Handler kann sich dann die Koordinaten aus dem Event holen. Ähnlich hattet ihr es bereits beim Erpresserbrief gemacht.
