### ISSUE TITLE
setTimeout funktioniert am Handy nicht

### ISSUE THREAD

**Issue by LorenaEberhart** [JirkaDellOro/EIA2#133]
Hallo,

ich habe setTimeout benutzt um meine Seite nach einer bestimmten Zeit neu zu laden. Dies funktioniert auf dem Browser ohne Probleme. Allerdings funktioniert es auf dem Handy nicht. Gibt es dafür einen Trick, dass es auch auf Mobilgeräten klappt?

https://github.com/LorenaEberhart/EIA2/tree/master/Abschlussaufgabe
https://lorenaeberhart.github.io/EIA2/Abschlussaufgabe/Abschluss.html

**Comment by saenglert** [comment]
Was hast du denn fuer ein Handy? Bonuspunkte wenn du auch das Betriebssystem und die Browserversion herausfindest.

**Comment by LorenaEberhart** [comment]
Ich habe ein iPhone 6s, Browserversion von Safari müsste 604.1 sein und das Betriebssystem ist iOS 11.2.6

**Comment by saenglert** [comment]
Hab mich heute mal mit Arbeitskollegen ueber das Problem unterhalten und offenbar kann es passieren, dass Timeouts auf Mobile effektiv eingefroren werden um Energie zu sparen.

Ich muss ich da erstmal etwas einlesen. Ich wuerde mich Anfang naechster Woche wieder melden (hab morgen meinen letzten Arbeitstag in der Schweiz und ziehe am WE um). Bis wann habt ihr Abgabe? 

@JirkaDellOro Vielleicht waere das auch was interessantes fuer dich zum Anschauen, falls das in Zukunft oefter auftritt.

**Comment by LorenaEberhart** [comment]
Wir haben morgen die Abgabe, aber kein Problem ich habe das setTimeOut einfach komplett aus dem Code raus genommen. Es macht ja wenig Sinn, wenn es nicht auf allen Geräten funktioniert. Trotzdem danke!
