### ISSUE TITLE
fehlende Animation in Abschlussaufgabe + Feedback

### ISSUE THREAD

**Issue by pfaffver** [JirkaDellOro/EIA2#134]
Hallo zusammen,
ich wollte mich auf diesem Weg schnell rückversichern, dass eine Animation für die Abschlussaufgabe nicht zwingend ist?! 
Was ist mit der Anforderung "Es ist eine während des Programmverlaufs variable Anzahl von Objekten zu erkennen" genau gemeint?

Ich bräuchte ein kurzes Feedback zu folgendem Link
https://pfaffver.github.io/EIA2/Final/final.html

Vielen Dank.

**Comment by JirkaDellOro** [comment]
Eine Animation ist nicht erforderlich.  Die Anzahl der Objekte soll während des Programmlaufs variabel sein, es müssen also Objekte hinzukommen oder entfernt werden. Derzeit ist die Applikation sehr schlicht, die Objektzahl fix. Zudem ist der Einsatz der Subklasse gerade sinnlos und der Code in final.ts unnötig komplex.

Vorstellbar wäre, mehrere Level mit unterschiedlichen Motiven zu implementieren und bei jedem Start die Anzahl der Objekte zu variieren.
