### ISSUE TITLE
translate Canvas

### ISSUE THREAD

**Issue by bandlepeter** [JirkaDellOro/EIA2#135]
Hey, habe das Problem, dass wenn ich mit rotate mein Canvas drehe ihn nicht in mein Mittelpunkt (Mitte der Seite.) verschieben kann. Translate funktioniert nicht, da sich dann das Objekt sich nicht mehr um den eigentlichen Objektmittelpunkt dreht. Wie kann ich dies beheben/umgehen?

**Comment by saenglert** [comment]
Hey Peter,
die Sache mit _rotate_ und _translate_ ist, dass sie auf das komplette Canvas angewendet werden und nicht nur auf den aktuellen Pfad. D.h. um wieder um wieder in die Ausgangsstellung zu kommen, musst du diese Veraenderung rueckgaengig machen.

Option A:
```
let x = 2;
let y = 3;
let angle = 45;

context.translate(x, y);
context.rotatet(angle);
// do something here
context.translate(-x, -y);
context.rotate(-angle);
```
Wenn dich das etwas umstaendlich anschaut, dann nur weil es dass auch ist: Du musst jeden Aufruf einer Transformation mit einem Gegenaufruf danach wieder neutralisieren, aber es sollte dir erstmal das Problem und die logisch einfache Loesung verdeutlichen.

Weniger Schreibaufwand ist folgende Moeglichkeit:
```
let x = 2;
let y = 3;
let angle = 45;

context.translate(x, y);
context.rotatet(angle);
// do something here
context.setTransform(1,0,0,1,0,0);
```
Was das Canvas naemlich im Hintergrund macht, wenn du eine Transformation wie _rotate_ oder _translate_ ausfuehrst ist, das die Informationen ueber die aktuelle Summe dieser Transformationen in einer 3x3 Matrix gespeichert werden, die mit der Funktion _setTransform_ ueberschrieben werden koennen. Die 3x3 Matrix mit den Werten 1,0,0,1,0,0 stellt die Ausgangsform des Canvas dar, also ohne jegliche Drehung oder Verschiebung.

**Comment by JirkaDellOro** [comment]
Noch einfacher geht es mit save() und restore() !!

**Comment by bandlepeter** [comment]
ich glaube Sie haben mich nicht recht verstanden. save & restore lösen das eigentliche Problem nicht. Das Problem liegt daran, dass sich das Objekt am falschen Eck dreht und dieser Punkt muss verschoben werden. Wenn translate verwendet wird dann dreht das Objekt sich nicht mehr um den Objektmittelpunkt sondern einen am rechten Rand? und wird "herumgeschleudert". In dem Code sind die Vorschläge und translate auskommentiert. Bei den prompt Fenstern reicht es einfach durch zu entern dann steht automatisch etwas da. Funktionieren tut es, jedoch sieht es noch naja aus.

https://bandlepeter.github.io/EIA2/Abschlussaufgabe/index.html

**Comment by saenglert** [comment]
Hey Peter, dann haben wir beide aneinander vorbeigeredet:
Die _rotate_ Funktion rotiert das Canvas um den Koordinatenursprung, der bei (0/0) liegt (also standardmäßig oben linke Ecke).
Die _translate_ Funktion wiederum verschiebt den Ursprung um die beiden übergebenen Werte. D.h., wenn sich die Flasche um ihren eigenen Mittelpunkt drehen soll, musst du den Canvas Ursprung mit _translate_ an den Mittelpunkt der Flasche verschieben:

```
context.translate(xFlasche, yFlasche);
context.rotate(aktuellerWinkel)
drawFlasche
context.restore() 
```

**Comment by bandlepeter** [comment]
funktioniert nicht.
Hier wurde es mal angepasst https://bandlepeter.github.io/EIA2/Abschlussaufgabe/index.html jedoch verschiebt sich der Nullpunkt nicht. Der Pfel (Flasche) ist so programmiert, dass der Nullpunkt in ihm liegt. Der Canvas hat eine Größe von 640 x 640 und der Nullpunkt soll genau an 320 x 320 liegen. Jedoch bei der Anpassung bekomme ich kein rotierenden Pfeil (Dreieck), sondern ein undefiniertes Dreieckskarussell. Zum Vergleich das funktionierende, jedoch mit falschem Nullpunkt http://www.peterbandle.de/html/flaschendrehen/index.html

**Comment by JirkaDellOro** [comment]
Save and restore sind wichtig, damit die Transformationen nicht akkumulieren und es ist damit einfacher, als die Transformation rückgängig zu machen. Für die Animation selbst ist letztlich die Reihenfolge der Transformationen entscheidend. Hierzu gibt es in der MindMap einen Link auf ein Experimentierprogramm in Flash: https://sftp.hs-furtwangen.de/~del/Apps/Transformation/Transformation.html
