### ISSUE TITLE
alert box

### ISSUE THREAD

**Issue by saileral** [JirkaDellOro/EIA2#136]
Hallo zusammen!

Ich bin soweit schon fertig mit meiner Aufgabe, dass einzige Problem ist aktuell in Zeile 129/130. Am Ende des Durchlaufs soll eine alert-Box erscheinen. Diese erscheint auch auf Desktopgröße, allerdings nicht bei kleineren Bildschirmbreiten. Weshalb ist mir leider ein Rätsel.. Tipps?

Gruß,
Alica

**Comment by saileral** [comment]
https://saileral.github.io/EIA_2/Final/start.html

**Comment by bandlepeter** [comment]
Es kann sein, dass Firefox die nicht anzeigen will, wenn man sie im "Simulator" öffnet. Meine prompt Abfragen erscheinen dort auch nicht. Jedoch wenn man das Fenster schmal zieht oder die Seite auf Mobilgeräten öffnet, funktionieren sie.

**Comment by saileral** [comment]
Oha stimmt... Danke Peter !:)
