### ISSUE TITLE
Fragen nicht Random

### ISSUE THREAD

**Issue by vanessanova** [JirkaDellOro/EIA2#137]
Hallo,

ich weiß leider etwas spät aber mir ist eben Aufgefallen das meine Fragen nicht ganz Random generiert werden, es wird immer nur zwischen den ersten 3 gewechselt. 
Warum? 
Hoffe es ist nicht zu Spät für eine Antwort :-)

**Comment by JirkaDellOro** [comment]
Hallo Vanessa,

so wie ich das sehe, werden die Fragen mit Hilfe der Variablen random2 als Index aus dem Fragen-Array geholt. Der Wert dieser Variablen wird folgendermaßen definiert:
```
        let random2: number = Math.round(Math.random() * 2);
```
Somit kommt hier nur ein Wert von 0, 1 oder 2 vor, und damit nur die ersten drei Fragen...

Übrigens ist die Verwendung von Round hier ungeschickt. Es führt dazu, dass die 1 mit doppelter Wahrscheinlichkeit im Vergleich zur 0 und zur 2 gewählt wird. Vielleicht kommen Sie selbst darauf, warum das so ist.
