### ISSUE TITLE
Registrierung auf der Kursseite

### ISSUE THREAD

**Issue by YannicHermann** [JirkaDellOro/EIA2#138]
So wie es aussieht, war meine Registrierung nicht ganz erfolgreich.. 
Jedenfalls zeigt mir mein Browser nur eine Fehlermeldung an, aus der ich aber nicht schlau werde.
 
Ich könnte mir vorstellen, dass ich nicht den richtigen Ordner verlinkt habe, wobei im verlinkten auch die benötigten Dateien abgelegt sind. Kann ich das noch ändern oder soll ich mich nochmal neu registrieren?

Über eine Hilfestellung wäre ich sehr dankbar!

**Comment by JirkaDellOro** [comment]
Hallo Yannic,
sie hatten in das Repository verlinkt und nicht auf Pages. Ich habe den Link korrigiert.

**Comment by YannicHermann** [comment]
Vielen Dank, hat sehr geholfen.
