### ISSUE TITLE
MiniWebseite

### ISSUE THREAD

**Issue by FranziskaHeiss** [JirkaDellOro/EIA2#139]
Ich kann meine Mini Webseite nicht so verlinken, dass sie geöffnet wird. Hab den gesamten Ordner nach FranziskaHeiss.github.io verschoben, von dort aus lässt es sich verlinken, warum nicht aus EIA2?

**Comment by saenglert** [comment]
Hallo Franzi,
hast du für das EIA2 Repository auch die Pages unter Settings eingerichtet?

**Comment by FranziskaHeiss** [comment]
Ich denke ja, zumindest ist es so eingestellt wie in der Mindmap beschrieben

**Comment by JirkaDellOro** [comment]
Github-Pages werden immer unter github.io gehostet, auch die Veröffentlichung der anderen Repositories neben der Userpage. Diese sind dann in gleichnamigen Unterordnern zu finden. Die richtige Adresse lautet in Ihrem Fall

https://franziskaheiss.github.io/EIA2/Aufgabe00/Aufgabe00.html

**Comment by FranziskaHeiss** [comment]
ja irgendwie is das jetzt über den Link von Ihnen über den EIA2 Ordner verlinkt, ich weiß zwar nich warum, aber es funktioniert. Danke für die Hilfe :)

**Comment by JirkaDellOro** [comment]
Löschen Sie bitte Aufgabe0 aus dem Userpage-Repo
