### ISSUE TITLE
Variablen im Namespace werden nicht erkannt

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#14]
Hallo, 
ich habe das Problem, dass meine globalen Variablen nicht von den Funktionen erkannt werden. 
Zuvor hatte ich ein DOMContentLoaded um den Kompletten Code, da wurden sie noch von den Funktionen erkannt. Jetzt habe ich einen Namespace und eine init Funktion stattdessen eigebaut und nun geht es nicht mehr. Sieht jemand woran das liegt? 

Hier ist der Link:
https://github.com/aliciaburger/EIA2/blob/master/Aufgabe%204/a4.ts

**Comment by moritzhfu** [comment]
Zeile 17-20 sollte in die init-Methode.

Hier wird der Canvas aus dem DOM geholt, obwohl dieser vermutlich noch gar nicht vollständig geladen ist.
Die init-Methode wird erst aufgerufen, sobald das komplette Dokument geladen hat.

**Comment by aliciaburger** [comment]
Jap das wars, Dankeschön!
