### ISSUE TITLE
Commit and Push Fehler

### ISSUE THREAD

**Issue by Dirkmuthmann** [JirkaDellOro/EIA2#140]
Commit and Push sendet keinen commit an mein Repository

Im Push Window steht nur rejected - non-fast-forward.

Schon probiert:
- Pull
- fetsch
- pull merge

EDIT:
Möglicher Fehler: Ich habe meinen Anzeigename in Git geändert, probiert Eclipse deswegen vllt. noch auf den alten Namen zu pushen?

**Comment by JirkaDellOro** [comment]
Was bedeutet "Anzeigename in Git geändert"?
