### ISSUE TITLE
cardArray [ ]

### ISSUE THREAD

**Issue by alenamaria** [JirkaDellOro/EIA2#141]
Ich verstehe momentan noch nicht ganz, was der Inhalt vom cardArray [ ] ist. 
Ist das leer bevor man den cardContent zweimal mit push anfügt oder ist da bereits was drin?

**Comment by saenglert** [comment]
Hey Alena,
geht es um ein spezielles Beispiel, das Herr Dell'Oro euch zur Verfügung gestellt hast oder bist du gerade dabei deine eigene Lösung zu schreiben?

**Comment by JirkaDellOro** [comment]
das ist am Anfang leer.

**Comment by alenamaria** [comment]
Dankeschön.

**Comment by JirkaDellOro** [comment]
Noch ein kurzer Nachtrag: in unserem Aktivitätsdiagramm enthält cardContents die möglichen Zeichenketten (im einfachsten Fall nur jeweils ein Buchstabe), die auf den Karten erscheinen können. cardArray dagegen enthält, nachdem es besetzt wurde, die Zeichenketten die tatsächlich im Spiel genutzt werden, also in der richtigen Anzahl und jede doppelt.

**Comment by JirkaDellOro** [comment]
@Sascha: im Codebereich findest Du die Tafelbilder und die Mindmap zur Orientierung...
