### ISSUE TITLE
Prompt Abfrage

### ISSUE THREAD

**Issue by YannicHermann** [JirkaDellOro/EIA2#142]
Hallo zusammen, 

bei mir scheitert es gerade schon an der Prompt Abfrage zu Beginn.
Habe es auch schon mit Jascha versucht, der mir dann den Tipp mit der while Schleife gegeben hat, was aber leider auch nicht zum Erfolg geführt hat.
Vielleicht kann mal jemand reinschauen. Habe es schon mit gefühlt allen möglichen Vaarianten probiert..

Danke!
https://github.com/YannicHermann/EIA2/blob/master/SS18/Aufgabe_2/memory.ts

**Comment by YannicHermann** [comment]
Danke für deine Zeit, Sascha. 

Habe jetzt eine weitere halbe Stunde dran rumgewerkelt. Mir ist klar geworden das die Schleife unendlich lange läuft, weil sich 'numPairs' eben nicht ändert. Bezüglich 'askPairs' habe ich versucht es aufzubröseln, wobei ich nicht sicher bin, ob das so meintest. Zudem habe ich es mit einer do-while-Schleife probiert.. 
Nichtsdestotrotz komme ich nicht voran - I'm sorry

**Comment by JirkaDellOro** [comment]
Eigentlich ist das schon dicht dran
```
    let askPairs: string;
    let numPairs: number = parseInt(askPairs);
    do  {
    askPairs = prompt ("Wie viele Paare?");
    } while ( numPairs < 1 || numPairs > 20); 
```
Man müsste das nur etwas umarrangieren. Es sollte genügen  
```
numPairs = parseInt(askPairs);
```
unter die Zeile mit dem prompt einzubauen.

Außerdem sollte in der Laufbedingung der Schleife überprüft werden, ob numPairs vielleicht einen ungültigen Zahlenwert hat. Dafür gibt es die Funktion isNaN(...)

**Comment by YannicHermann** [comment]
Vielen Dank, es funtktioniert jetzt! 👍
