### ISSUE TITLE
Allgemeines Problem

### ISSUE THREAD

**Issue by FranziskaHeiss** [JirkaDellOro/EIA2#143]
Wir (10 Leute) sitzen jetzt seit zwei Stunden an der Aufgabe und kommen einfach zu keinem Ansatz. Unser Problem ist, dass uns gefühlt jegliche Grundlage fehlt, um die Aufgabe letzlich umzusetzen, unser Code besteht nur aus einzelnen Bruchstücken, die sich nicht wirklich zusammenführen lassen. 

https://github.com/FranziskaHeiss/EIA2/tree/master/Aufgabe2

**Comment by LisaJaehn** [comment]
Mittlerweile seit drei Stunden hier und noch keine Erleuchtung.

**Comment by kempfsas** [comment]
Die zusätzlichen 9 Arbeitsstunden pro Woche haben wir mittlerweile auch schon deutlich überschritten...

**Comment by JirkaDellOro** [comment]
Ich habe euren Code kommentiert und euch einen Pull-Request erstellt.

**Comment by JirkaDellOro** [comment]
Das Problem ist nicht (nur) das Kodieren, sondern ihr scheint noch nicht zu wissen, was ihr eigentlich machen wollt. Ich zeichne den mittleren Teil des Aktivitätsdiagramms noch einmal ordentlich, vielleicht hilft es. Derweil könnt ihr den Code aufräumen. Ihr habt leider auch die Aufgabenstellung nicht ordentlich gelesen. Da steht z.B. auch
"Die aufzurufende HTML-Datei enthält nur einen Header mit dem Verweis auf ihr Skript, sowie die beiden Bereiche für die Karten und die Spielerinformation. "
