### ISSUE TITLE
Undefinierte createCards-Funktion

### ISSUE THREAD

**Issue by al-mll** [JirkaDellOro/EIA2#144]
Hallo,
bei Überprüfung der Lauffähigkeit meines Codes taucht in der Konsole des Browsers leider der Fehler "undefined" bei Zeile 38 und 50 auf:
https://github.com/al-mll/EIA2/blob/master/Aufgabe2/DOM.ts
Definiert habe ich meine createCards-Funktion als ": void".
Vielleicht liegt es aber auch an den Parametern, die ich nicht korrekt angegeben habe und deswegen nicht übermittelt werden können.
Für Tipps zur Lösungsfindung wäre ich sehr dankbar.

**Comment by saenglert** [comment]
Hallo Alfred,
du hast die ungute Angewohnheit deine Variablen zu deklarieren, aber nicht zu initialisieren:
```
// DOM.ts Zeile 46
let cardArray: string[];
```
Das ist die Deklaration einer Variable vom Typ String Array. Einfach gesagt, gibst du hier an, dass sobald du `cardArray` aufrufst, das Programm einen Wert vom Typ String Array erwarten soll. Dabei wird allerdings noch keine Aussage über den Inhalt der Variable getroffen. Du definierst hier die sprichwörtliche Box, aber nicht den Inhalt und so bleibt die Variable leer.
```
// DOM.ts Zeile 47
console.log(cardArray);
```
Liefert dir dementsprechend als Wert `undefined````

// DOM.ts Zeile
cardArray.push(_cardContents[i]);
```
Der Wert `undefined` besitzt keine Eigenschaft push, also kommt es hier zu einem Type Error.

Die Lösung des Problems ist simpel. Du musst einfach deiner cardArray einen Startwert mitgeben:
`let cardArray: string[] = [];`
Das ist dann die Deklaration (linke Seite) und Initialisierung (rechte Seite) einer Variable in einem Aufwasch. Es kann durchaus legitime Gründe geben eine Variable nur zu deklarieren, aber nicht zu initialisieren, aber häufig handelt man sich als Anfänger mehr Probleme als Nutzen ein, wenn man keinen Anfangswert mitgibt.

**Comment by al-mll** [comment]
Alles klar, jetzt klappt es!
Manchmal zeigt es im eclipse einen Fehler an, wenn ich die Vaiable deklariere und direkt initiiere.
Deswegen habe ich sie erstmal nur deklariert.

**Comment by JirkaDellOro** [comment]
Was ist ein "PikeAss"? .... Ach, ich will es besser gar nicht wissen.

**Comment by saenglert** [comment]
Dasselbe wie ein Standart

**Comment by JirkaDellOro** [comment]
AUAAA!
