### ISSUE TITLE
Memory Setup: Nur 2 Karten werden erstellt

### ISSUE THREAD

**Issue by al-mll** [JirkaDellOro/EIA2#145]
Nochmals Hallo :),
ich hätte da nochmal ein kleines Problem. Und zwar werden bei mir nur zwei Karten erstellt:
https://al-mll.github.io/EIA2/Aufgabe2/DOM.html
Hier noch der Code:
https://github.com/al-mll/EIA2/blob/master/Aufgabe2/DOM.ts
Eigentlich ist mein cardArray mit genug Inhalt gefüllt um die Anzahl an Paaren zu erstellen, die der Spieler haben möchte. Es sieht aber so aus, als ob das cardArray nach zweimaliger Anwendung der splice-Funktion komplett leer ist, was aber nicht sein kann.
Für jeden Hinweis wäre ich dankbar.

**Comment by JirkaDellOro** [comment]
Was war das Problem?

**Comment by al-mll** [comment]
Ich habe der splice-Methode zusätzlich zur Indexzahl (Zufallszahl k) die Zahl 1 mitgegeben -> splice(k, 1), damit auch wirklich klar ist, wie viele Items aus dem Array genommen, bzw. dem Array hinzugefügt werden. Das hat aber erstmal auch nicht geholfen. Deswegen habe ich noch zwei cardArrays (cardArray1 und cardArray2) und zwei createCard-Funktionen (createCard1 und createCard2) erstellt. So hat es letztendlich geklappt.
