### ISSUE TITLE
Fragen zum Code aus der Vorlesung

### ISSUE THREAD

**Issue by LauraGiannotta** [JirkaDellOro/EIA2#146]
8. fieldset.addEventListener("click", clickHandler, true); **_//Wozu schreibt man hier "true"?_**

10. let button: HTMLButtonElement = <HTMLButtonElement>document.querySelector("button"); **_//Was bewirkt der query.Selector genau? Google hilft mir da leider nicht weiter._** 

33.-36.     function logEvent(_event: Event): void { _**Warum "void" trotz Rückgabe?**_
        if (_event == undefined) {
            console.log("No event object passed");
            return;  _**Warum keine Variabel? Was gibt das zurück?**_

Danke im Voraus :)

**Comment by JirkaDellOro** [comment]
**zu 9**
Eine gute deutsche Quelle, und bei Google in der Regel unter den ersten Suchergebnissen zu finden, ist SelfHTML, siehe https://wiki.selfhtml.org/wiki/JavaScript/DOM/Document/querySelector
Bitte nochmal melden, sofern die Erklärung dort nicht helfen sollte

**Comment by JirkaDellOro** [comment]
**zu 33.-36.**
Gute Frage! Die `return`-Anweisung bewirkt zweierlei
1. sie gibt einen Wert zurück, sofern einer der `return`-Anweisung folgt
2. sie beendet die Funktion sofort  

In dem vorliegenden Fall wird kein Wert zurück geliefert, wie dies auch schon durch das void im Funktionskopf deutlich wird, aber die Funktion soll sofort beendet werden, wenn _event nicht definiert ist. Dann würden nämlich die nachfolgenden Konsolenausgaben nicht funktionieren. Eine solche `return`-Anweisung mitten im Funktionskörper nennt man auch "early out".
