### ISSUE TITLE
Aufgabe 3

### ISSUE THREAD

**Issue by FranziskaHeiss** [JirkaDellOro/EIA2#147]
Soll der Score für die Aufgabe 3 schon mitzählen oder nicht? In der Aufgabenstellung selbst steht das noch nicht drin, aber bei dem Aktivitätsdiagramm von heute haben wir es schon mit reingeschrieben.

**Comment by JirkaDellOro** [comment]
Es ist im Aktivitätsdiagramm, weil es jemand hereingerufen hat. Da wir derzeit nur einen Spieler spielen lassen, ergibt Punktezählung eigentlich keinen Sinn und ist deshalb auch noch nicht Teil der Aufgabenstellung. Wer mag, kann es natürlich einbauen.
