### ISSUE TITLE
Compare Content

### ISSUE THREAD

**Issue by YannicHermann** [JirkaDellOro/EIA2#148]
Hallo zusammen, 

um vergleichen zu können, ob die umgedrehten Karten denselben Content haben, pushe ich diesen in einen neuen Array 'openCards' (die Funktion zum Vergleichen ist noch nicht vorhanden). Beim Ausgeben in der Konsole ist mir aber aufgefallen, dass die Werte entweder undefined sind oder immer denselben Wert haben (und zwar einen der gar nicht dem Angezeigten entspricht). 
Daher ist es mir nicht möglich die Contents zu vergleichen. Komme aber selbst nicht darauf wo es klemmt..

Der Code ist mittlerweile sehr unübersichtlich. Über eine Hilfestellung würde ich mich trotzdem sehr freuen!
https://github.com/YannicHermann/EIA2/blob/master/SS18/Aufgabe_2/Tests/memory2.ts

**Comment by R0bel** [comment]
In Zeile 124 übergibst du jeder erstellten Karte einen Eventlistener, was auch so stimmt. Aber du erstellst auch gleich die Funktion, die diesen Event abarbeitet.  Wenn du dir den Beispielscode aus der Vorlesung anschaust, sieht du das es folgende Form hat:  
`fieldset.addEventListener("mouseover", clickHandler);`
Was der Code bewirkt ist, dass wenn man über das filedset mit der Maus hovert, die Funktion clickHandler() ausgelöst wird. In deinem Code wird stattdessen die unbenannte function(), die du direkt an den Eventlistener angehängt hast aufgerufen. Ich empfehle dir den Code wie es in der Vorlesung gezeigt wurde zu schreiben:

`card.addEventListener("click", function(): void { ... }`
wird zu:
```
card.addEventListener("click", funktionName);
function funktionName(_event : MouseEvent): void {...}
```

Außerdem befinden sich sowohl diese Funktion als auch clickHandler() und logEvent() in deiner createCard()-Funktion. Du musst sie nach außen verlagern. Dann wirst du sehen, dass dein Code für den Event auf  Sachen aus der createCard()-Funktion zugegriffen hat (wenn du es richtig machst, kann auf `card `nicht zugegriffen werden). Du willst aber auf den Inhalt deiner angeklickten Karte zugreifen.
Für das weitere Vorgehen empfehle ich dir den Code aus der Vorlesung nochmal anzuschauen und zu verstehen was _event.target macht.
