### ISSUE TITLE
Gespeichertes Bild wird nicht eingefügt

### ISSUE THREAD

**Issue by JacquelineWagner** [JirkaDellOro/EIA2#15]
Hallo,

wir drei sitzen mal wieder seit längerer Zeit an einem Problem.🙈  Und zwar wird der gespeicherte Canvas nicht über die Bienen gelegt.
Das Problem befindet sich vermutlich zwischen den Zeilen 92 - 131.

Hier der Link:
https://jacquelinewagner.github.io/EIA2/aufgabe5/aufgabe5.htm

Danke im Voraus.

**Comment by saenglert** [comment]
Hallo Jacqueline,
geht bitte nochmal Schritt für Schritt durch was eure copy & paste Funktion jeweils machen, wann sie es machen und vorallem: Was machen sie mit der Information?

**Comment by JacquelineWagner** [comment]
okay danke, habe das Problem gefunden.

**Comment by saenglert** [comment]
Wo lag denn das Problem?Wäre sicher interessant für andere die auch noch nicht ganz sicher sind wie das funktioniert.

**Comment by JirkaDellOro** [comment]
... und habt ihr den Pull-Request von Moritz gefunden und verarbeiten können?

**Comment by moritzhfu** [comment]
Habe wohl vergessen auf commit zu drücken bevor ich den Laptop ausgeschaltet habe und mein Request ist verschwunden. Ich sende ihn nochmal.
