### ISSUE TITLE
Problem bei Aufgabe 3 (Event)

### ISSUE THREAD

**Issue by Lina-MariaStraub** [JirkaDellOro/EIA2#150]
Hallo zusammen,

leider komme ich alleine nicht mehr weiter. Ich habe eine neue Funktion für das Event erzeugt und eine Timerfunktion eingefügt. Doch das 'click' Event kann ich einfach in meinem Memory nicht anwenden. 

In Zeile 38 meines TS Codes weiss ich auch nicht so recht, ob ich eine bisher bestehende Variablenbezeichnung verwenden muss. 

[https://github.com/Lina-MariaStraub/EIA2/blob/master/aufgabe_3/memory3.ts](url)

Danke.

**Comment by JirkaDellOro** [comment]
Wir müssen erst einmal etwas aufräumen. Als Hilfestellung habe ich den Code kommentiert und einen Pull-Request erstellt. Bitte entsprechend korrigieren. Vielleicht klärt sich dabei schon das Problem...

Es ist außerdem zu überdenken, ob das window auf Klicks reagieren soll, oder ob es nicht geschickter ist, wenn das ein Objekt tiefer im DOM-Tree tut.
