### ISSUE TITLE
Karteninhalt in neues Array pushen 

### ISSUE THREAD

**Issue by JohannesHalla** [JirkaDellOro/EIA2#151]
Um die zwei umgedrehten Karten zu vergleichen habe ich einen neuen Array erstellt "cardShuffle". 
Hier möchte ich nur den Inhalt der geöffneten Karten "hineinpushen". 
Ich komme einfach nicht dahinter, wie ich nur auf die einzelnen Karten zurückgreifen kann. 

Vielen Dank! 

https://github.com/JohannesHalla/EIA2/blob/master/Aufgabe3/Memory1.1.ts

**Comment by R4Pi3R** [comment]
Schon sehr nah dran!
In changeStatus wird das Element, das das Event entgegennimmt (_event.target) als "t" gespeichert. 
Dieses t ist ein HTMLElement, das in das cardShuffle-Array (Codestyleguide beachten, der Name und die Funktion passen nicht zueinander) gepusht und dann mit einem weiteren Arrayeintrag verglichen werden kann.
Bei dieser Art die Aufgabe zu lösen muss allerdings der Unterschied zwischen Event.target und Event.currentTarget beachtet werden.

Eine kurze Erklärung zu diesem Unterschied und zu Bubbling gibt es hier: 
https://javascript.info/bubbling-and-capturing
