### ISSUE TITLE
Gratulation

### ISSUE THREAD

**Issue by LisaJaehn** [JirkaDellOro/EIA2#152]
Ich habe ein Problem bei der Erstellung der Gratulation am Ende des Spieles. Die Gratulation erscheint immer schon zu Beginn des Spieles. Ich weiß nicht, ob ich den Funktionsaufruf falsch platziert habe oder allgemein einen Fehler bei der Erstellung gemacht habe.

https://github.com/LisaJaehn/EIA2/blob/master/Aufgabe4/Game.ts

**Comment by R4Pi3R** [comment]
Was mir auffiel war, das q (Styleguide beachten!) zu Beginn des Skripts mit der Länge des leeren Arrays initialisiert wird und danach nur dekrementiert wird. (Startwert war 0, was der Grund gewesen sein kann, dass die Bedingung der Abfrage erfüllt und der Alert ausgelöst wurde)
Der Code wurde in der Zeit in der ich drüber geschaut habe bereits bearbeitet, daher werde ich zum restlichen Stand nichts kommentieren. Falls das Problem weiterhin besteht oder neue auftreten bitte bescheid geben :)
