### ISSUE TITLE
removeEventListener

### ISSUE THREAD

**Issue by al-mll** [JirkaDellOro/EIA2#153]
Hallo,

bei mir hängt es gerade an der Unterbrechung aller Interaktionen während des 2-Sekunden-Timeouts.
Ich dachte mir, dass ich bei den Karten, die mit einem EventListener ausgestattet wurden, die EventListener wieder entfernen könnte.
Nach w3schools ist dies auch möglich.
Dementsprechend habe ich diesen Code erstellt:
```
                if (openCards.length == 2) {
                    for (let i: number; i < listeners.length; i++) {
                        listeners[i].removeEventListener("click", clickHandler);
                    }
                    window.setTimeout(handleTimeout, 2000);
                    for (let i: number; i < listeners.length; i++) {
                        listeners[i].addEventListener("click", clickHandler);
                    }
                } 
```
https://github.com/al-mll/EIA2/blob/master/Aufgabe3/DOM.ts
Dieser Code ist Teil meiner clickHandler()-Funktion:
Damit möchte ich noch vor dem Timeout alle EventListener entfernen.
Nach dem Timeout die EventListener wieder den Karten hinzufügen.
Leider klappt dies aber nicht.
Für einen Hinweis wäre ich sehr dankbar.

**Comment by JirkaDellOro** [comment]
setTimeout installiert den TimeOut-Listener, was bewirkt, dass in diesem Fall 2000 Millisekunden später die Funktion `handleTimeout` aufgerufen wird. Der Programmfluss wird durch setTimeout aber nicht unterbrochen. Das heißt, dass sofort nach der Anweisung setTimeout die Listener wieder installiert werden.

PS: Sie sollten unbedingt die Gelegenheit jetzt nutzen und den gedoppelten Code für createCard entfernen und eine sinnvollere Lösung zu implementieren
