### ISSUE TITLE
Spielfeld wird zu Karte

### ISSUE THREAD

**Issue by kempfsas** [JirkaDellOro/EIA2#154]
Hallo, 
ich habe das Problem, dass es aus dem div, das um alle Karten ist, auch eine Karte gemacht hat, d.h. wenn ich neben die Karten klicke kann ich auch das Spielfeld als Karte "taken", "hidden" und "visible" machen. Deshalb erscheint bei mir die Gratulation auch nur dann erst, wenn ich zum Schluss ein paar mal auf das Spielfeld klicke und so das Spielfeld als Karte "taken" mache. Leider hab ich den Fehler nicht finden können.

https://github.com/kempfsas/EIA2/blob/master/Aufgabe3/Aufgabe3.ts

**Comment by JoschaB** [comment]
So wie ich das sehe, hast du den EventListener dem Window-Element angefügt. Somit reagiert er bei jedem Objekt, das angeklickt wird. Da nun aber nicht überprüft wird, ob das entsprechende Objekt auch eine Karte ist, wird der Status von jedem Objekt, das angeklickt wird, geändert.
Was die Gratulations-Nachricht angeht, liegt dies denke ich daran, dass die Funktion "graduation" nicht in der setTimeout function steht. Die Variable l wird erst nach der verzögerrung erhöht, da der normale Programmfluss aber nicht unterbrochen wird, wird die Funktion "graduation" direkt ausgefürht, l aber da noch nicht erhöht wurde. Dadurch muss erst ein weiteres Kartenpärchen verschwinden, das es aber nicht gibt. Da man jetzt bei dir aber auf den Hintergrund klicken kann, dient dies als dieses fehlende Paar und die Nachricht wird angezeit.

Was mir noch aufgeafllen ist, dass man bei dir mehr als zwei Karten gleichzeitig anklicken kann, was das Programm etwas durcheinander bringt.

**Comment by kempfsas** [comment]
Die Gratulation hab ich hinbekommen aber hast du mir einen Lösungsansatz, wie ich die anderen Probleme gelöst bekomme? Ich hab’s gestern versucht aber vor der Abgabe leider nicht lösen können und komme auch jetzt nicht auf den richtigen Weg.

**Comment by JoschaB** [comment]
Kleiner Denkanstoß:
Sorge dafür, dass alle Karten etwas gemeinsam haben, was sonst kein anderes Objekt hat. Genau diese Gemeinsamkeit kann man nun, nachdem auf etwas geklickt wurde abfragen.
