### ISSUE TITLE
clickHandler reagiert nicht

### ISSUE THREAD

**Issue by LeonSchweikert** [JirkaDellOro/EIA2#155]
Hallo,
Mein Problem ist das meine Karten zwar angezeigt werden wie sie sollen, jedoch sind sie nicht klickbar.Ich habe keine Errors in meinem Code und den Event Listener an der richtigen Stelle platziert.Finde den Fehler allerdings nicht.

https://github.com/LeonSchweikert/EIA2/blob/master/Aufgabe3/Aufgabe3.ts

**Comment by JoschaB** [comment]
Deine Karten haben standartmäßig den Tag "hidden", durch diesen lassen sie sich nicht anklicken. Sobald dieser entfernt wird, funktioniert es.

**Comment by LeonSchweikert** [comment]
Danke :)
