### ISSUE TITLE
Doppelclick auf die selbe Karte

### ISSUE THREAD

**Issue by muelle2k** [JirkaDellOro/EIA2#156]
Hi 
Bei mir und bei vielen Anderen wird der Spielverlauf gestört, wenn man ein zweites Mal auf die gleiche Karte "clicked". Wie kann ich angeben, dass die erste gedrückte Karte nicht mehr clickbar ist? 
https://github.com/muelle2k/EIA2/blob/master/Aufgabe3/js/game.ts

**Comment by muelle2k** [comment]
hab's schon hinbekommen :)

**Comment by armbrusf** [comment]
sehr gut :)
