### ISSUE TITLE
Frage zu Aufgabe 5

### ISSUE THREAD

**Issue by sofiagschwend** [JirkaDellOro/EIA2#157]
Die Antwort des Ergebnisses wird bereits im Terminal und im Browser angezeigt. Was genau ist dann mit Response gemeint?

_2.2 Passen Sie den Request-Handler so an, dass alle Query-Daten nicht nur im Terminal, sondern auch in der Response erscheinen. Prüfen Sie das Ergebnis._

**Comment by saenglert** [comment]
Wenn du sagst "im Terminal", wessen Termial ist das eigentlich? Das Terminal des Servers. Dem User bringt es aber herzlich wenig, wenn der Server eine Antwort hat, sie ihm aber nicht mitteilt. Dazu ist das Response Objekt da, welches das Gegenstück zur Request ist.

Wenn du diese Seite aufrufst um dir mein Kommentar anzusehen, sendet dein Browser eine Request an den http(s) Server von Github. Dieser stellt dir die benötigten Infos und schickt sie dir in Form einer Response, die du dann betrachtest.

**Comment by JirkaDellOro** [comment]
Ist es klar geworden, Sofia?

**Comment by sofiagschwend** [comment]
Ja, hat alles funktioniert. Danke.
