### ISSUE TITLE
Consts werden als Fehler ausgegeben

### ISSUE THREAD

**Issue by LisaJaehn** [JirkaDellOro/EIA2#158]
Hallo,

ich habe ein Problem mit dem Code, welchen Herr Dell Oro hochgeladen hat.

"use strict";
const Url = require("url");
const Http = require("http");

Diese consts in der .js Datei werden bei mir immer als Fehler angezeigt. Ich vermute mein Windows mag es nicht wenn ich const im Zusammenhang mit "use stric" verwende. Ich habe es getestet indem ich in der .js Datei die consts in vars umgewandelt habe. 

Ein Freund von mir hat es unter macOS High Sierra getestet, dort ging es ohne Probleme.

Hier ist die Fehlermeldung die ich bekomme
![Die Fehlermeldung von Windows](https://i.imgur.com/WXjFklS.png)

**Comment by saenglert** [comment]
Hallo Lisa,
Win 7 hier, keine Probleme.

Das Problem ist viel eher wie du versuchst das Script auszuführen.
```
Quelle: Kompilierungsfehler in **Microsoft JScript**
```
Microdoof hat nichts bei unserer Node Anwendung verloren. Um ehrlich zu sein, bin ich mir gerade garnicht sicher, wie du versuchsts, dein Script aufzurufen um diesen Error zu bekommen. Wenn du uns einen Error auftischt, bitte immer die letzten Schritte die du getan hast ebenfalls auflisten.

Der gedachte Weg zum laufende Programm sollte eigentlich folgender sein:

* Programm in TypeScript schreiben (.ts)
* Programm zu JavaScript compilieren (.js & .js.map)
* Programm mit node ausführen:
```
> node pfad/zu/meinProgramm.js
```

**Comment by JirkaDellOro** [comment]
Gibt es etwas Neues von hier?

**Comment by LisaJaehn** [comment]
Mittlerweile funktioniert es, aber woran es lag weiß ich nicht. 
Es ging aufeinmal, obwohl ich das Script nicht anders aufgerufen habe als davor auch.

**Comment by JirkaDellOro** [comment]
Dann müssen wir es wohl zunächst als Systemschluckauf belassen...
