### ISSUE TITLE
Fehlermeldung mit import * as Http from "http";

### ISSUE THREAD

**Issue by muelle2k** [JirkaDellOro/EIA2#159]
Hi, 

bei mir wird das angezeigt: 
<img width="891" alt="bildschirmfoto 2018-05-09 um 20 06 27" src="https://user-images.githubusercontent.com/37657825/39831477-ea95885e-53c4-11e8-8b25-e9e21fa3dd5e.png">

was kann ich tun? Ich hab die Dateien direkt vom Github Repository EIA2_S18_Code auf meinen Laptop gezogen und direkt wird diese Fehlermeldung angezeigt.

**Comment by saenglert** [comment]
Du hast deine TypeScript Installation in Eclipse nicht richtig konfiguriert.

Schau dir bitte die Mindmap unter `Installations > Typescript in Eclipse > Compiler` nochmal genau an.
