### ISSUE TITLE
Cleaning = gelöschte JS-Datein

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#16]
Eclipse wollte die JS-Datei nie neu schreiben("updaten"), also habe ich es gecleant. 
Das Problem ist nun, dass es mir die JS-Datein komplett gelöscht hat und ich diese nicht wieder erstellen lassen kann.
Ich hab probiert : 
die Plug-ins zu deaktivieren und aktivieren
in den Einstellungen des Compilers die Häkchen zu löschen und neu zu setzen
.

Wie bekomme ich meine JS-Datein wieder?

**Comment by saenglert** [comment]
Hast du aktuell Errors (Rot) im Code? Unsere Einstellungen verbieten dem Compiler den TS Code in JS zu compilieren, wenn es noch Errors gibt.

**Comment by NadiaCredidio** [comment]
Das könnte sein, diese müsste ich vllt. behoben haben. Doch gerade kann ich auch nichts Prüfen, weil mein Laptop sich nicht mit dem Wlan verbinden will. Aber wie sag ich Eclipse nachträglich, dass er die wieder erstellen soll? Durch eine Änderung im ts erscheint das js nicht mehr.

**Comment by saenglert** [comment]
Bevor wir jetzt anfangen mit den Compilerfunktionen rumzuspielen, behebe erstmal das Problem mit dem Wlan (oder benutze ein Kabel) und lade den aktuellsten Code hoch.

**Comment by RedImp1470** [comment]
Das Problem hattest du doch schon mal Nadia? Da hat es, soweit ich mich erinnern kann, tatsächlich geholfen alle (!) Errors zu beseitigen. Beim nächsten Speichern, bzw. beim nächsten Build-Vorgang sollte die js-Datei automatisch wieder erstellt werden.

**Comment by NadiaCredidio** [comment]
Das stimmt! Ich hab versucht alles zu entfernen, doch er zeigt mir das mit dem ImageData irgendwie als falsch an. Ich hab bei den anderen nachgesehen und bei denen sieht der Codeteil genau so aus. Ich weiß nicht warum es bei mir nicht funktioniert, aber ich hab den Code nochmal hochgepuscht.

**Comment by saenglert** [comment]
Ich kann dir auch sagen warum: Überlege mal wo du die Variable imgData definierst und wo du sie benutzt.

Und "irgendwie" als falsch ist auch eine echt blöde Aussage, wenn wir von hieraus helfen sollen. Eclipse gibt dir eine Fehlermeldung an, wenn du über das rote X am Rand oder den rot unterstrichenen Bereich mit der Maus fährst.

**Comment by NadiaCredidio** [comment]
Es hat nun funktioniert, dass die JS wieder erstellt wird. Danke, ich hatte das mit der Variable verpennt.
