### ISSUE TITLE
Heroku App Erzeugung funktioniert nicht

### ISSUE THREAD

**Issue by sinaseifert** [JirkaDellOro/EIA2#160]
Hi, 
bei mir kommt folgende Fehlermeldung wenn ich meine App mit github verbunden habe.:
![grafik](https://user-images.githubusercontent.com/37697857/39893575-79ba0e44-54a4-11e8-9b27-50fa2abd8614.png)

Wenn ich ganz zu anfangs auf die Sprachauswahl gehe, soll ich etwas installieren und Eingaben in dem DOS-Fenster machen. Ich habe aber Node.js auf meinem Laptop installiert.

**Comment by JirkaDellOro** [comment]
Welche Sprachauswahl, ganz zu Anfang von was? Die im Screenshot dargestellte Meldung kommt von Heroku, es ist dafür also unerheblich, was auf dem Laptop installiert ist. Ich vermute, dass die Datei package.json nicht existiert oder nicht angepasst wurde. Bitte mit meinem Code aus der Vorlesung vergleichen...

**Comment by JirkaDellOro** [comment]
Ich habe gerade in das Repository geschaut, von dem ich annehme, dass Heroku sich darauf bezieht. Das Problem dabei wäre dann, dass package.json in dem Unterordner liegt, Heroku aber auf der obersten Ebene danach sucht. Aus diesem Grund habe ich meinen Code nicht in einem Unterordner. Also entweder alles umräumen oder package.json auf die oberste Ebene legen und darin die Verweise auf Server.js um die Pfadangabe erweitern.

**Comment by sinaseifert** [comment]
vielen Dank für Ihre Antwort. Sie hatten Recht, es lag an der Ordnerstruktur. Jetzt funktioniert es.
Eine weitere Frage hätte ich noch, allerdings zur vorherigen Aufgabe. Was genau meinen Sie mit "Code reflektiert Decks"?
Vielen Dank für Ihre Hilfe

**Comment by JirkaDellOro** [comment]
Hierzu: https://github.com/JirkaDellOro/EIA2/issues/161
