### ISSUE TITLE
fehlermeldung

### ISSUE THREAD

**Issue by AnnikaKussberger** [JirkaDellOro/EIA2#162]
https://user-images.githubusercontent.com/37657458/39922116-e1ff0a6c-551d-11e8-9662-e54bb5a88e08.png
 Bei mir erscheint diese Fehlermeldung und ich bekomme sie nicht mehr weg :(

**Comment by moritzhfu** [comment]
Siehe hierzu: https://github.com/JirkaDellOro/EIA2/issues/159

Falls Fehler danach immer noch da, gerne erneut posten.

**Comment by JirkaDellOro** [comment]
Ist die Node-Definitionsdatei für TypeScript (node.d.ts) vorhanden?

**Comment by AnnikaKussberger** [comment]
Ja, ich hab alle Dateien aus Ihrem Code kopiert und zusammen hochgeladen. Habe gerade die Datei nochmal aufgerufen und die Fehlermeldung war einfach wieder weg.

**Comment by JirkaDellOro** [comment]
Also ist jetzt alles OK? Leider braucht Eclipse manchmal eine ganze Weile bis vermutete Fehler gelöscht werden. Im Fenster "Problems" kann man die auch von Hand löschen, was oft schneller Klarheit schafft.
