### ISSUE TITLE
Heroku aktualisiert code nicht?

### ISSUE THREAD

**Issue by Lina-MariaStraub** [JirkaDellOro/EIA2#163]
Hallo, ich habe einen neuen Code auf Github hochgeladen. Jedoch wird auf Heroku nur mein Alter angezeigt (Zeigt sich darin, dass meine a und b werte nicht angezeigt werden und "Das Ergebnis ist" (alte Formulierung) angezeigt wird) 

ich habe es schon mit dem Disconnect Button versucht aber dennoch wird die alte Version angezeigt.

Vielleicht weiss ja jemand wie ich das Problem behebe. Danke

**Comment by JirkaDellOro** [comment]
Wieso wird ihr Alter angezeigt?

Was ist die Adresse Ihrer App? Haben Sie nach einer Änderung erneut "Deploy" auf Heroku ausgelöst oder das automatische Deployment eingerichtet?

**Comment by Lina-MariaStraub** [comment]
https://eia2node257767.herokuapp.com/?a=10&b=20
das ist der Link zu der aktuellen Aufgabe

ebenfalls habe ich bei "Deployment method" Github ausgewählt und dann die Schritte von Deploy Branch über View ausgeführt.

Was genau meinen sie mit "alter"?

**Comment by Lina-MariaStraub** [comment]
das mit dem automatischen Deployment (enable automatic deploys) habe ich jetzt auch versucht. auch das aktualisiert es leider nicht

**Comment by JirkaDellOro** [comment]
Der manuelle Deploy hat Vorrang, der automatische erleichtert nur. Bitte kommen Sie in meine Sprechstunde, damit wir der Sache gemeinsam auf den Grund gehen können.
