### ISSUE TITLE
Response funktioniert nicht

### ISSUE THREAD

**Issue by kerndand** [JirkaDellOro/EIA2#165]
Hallo,

ich habe ein Problem und zwar bekomme ich keine response bei meiner Refresh Funktion. Auf dem Server läuft alles bis Zeile 93, also meine line Variable wird in der Konsole ausgegeben. Allerdings schickt es die Variable nicht zurück an den Client und ich weiß nicht woran das liegt. Das einzige was passiert wenn ich den Refresh Button drücke, ist, dass mit der Studi in der Browser-Konsole ausgegeben wird, was für mich keinen Sinn macht, da ich nirgends ein console.log in meiner Funktion stehen habe. 

Client: https://github.com/kerndand/EIA2/blob/master/Aufgabe6/ProcessForm.ts
Server: https://github.com/kerndand/EIA2_Node/blob/master/Server.ts

**Comment by kerndand** [comment]
Konnte das Problem lösen

**Comment by JirkaDellOro** [comment]
Bitte noch die Lösung kurz darstellen, damit alle etwas davon lernen können.
