### ISSUE TITLE
MongoDB Installation

### ISSUE THREAD

**Issue by alenamaria** [JirkaDellOro/EIA2#167]
![fehlermeldung mongodb](https://user-images.githubusercontent.com/37595721/40775378-35691a44-64c8-11e8-8468-2089bb4d9a97.PNG)

Wir haben MongoDB über den Link im Freemind Viewer versucht zu installieren. Haben alles durch geklickt und die Installation hat auch begonnen, aber dann kam diese Fehlermeldung. Im System ist nur die Download-Datei zu finden, nicht das installierte Programm auf dem C-Laufwerk. Wir haben es mehrfach probiert. Woran kann das liegen?

**Comment by alenamaria** [comment]
Es funktioniert nun - wir haben den Haken bei "Install MongoDB Compass" raus gemacht, dann hat die Installation geklappt.

**Comment by JirkaDellOro** [comment]
Super, dass Sie die Lösung hier posten                                                                                                                                                                        Von meinem BlackBerry gesendet – dem sichersten Mobilgerät                                                                                                                                                                            Von: notifications@github.comGesendet: 31. Mai 2018 12:09 nachm.An: EIA2@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: Re: [JirkaDellOro/EIA2] MongoDB Installation (#167)  Es funktioniert nun - wir haben den Haken bei "Install MongoDB Compass" raus gemacht, dann hat die Installation geklappt.

**Comment by LauraGiannotta** [comment]
habe das gleiche Problem, Alenas Lösung hat bei mir leider nicht geklappt :(
