### ISSUE TITLE
Unterstütztes Betriebssystem 

### ISSUE THREAD

**Issue by FranziskaHeiss** [JirkaDellOro/EIA2#168]
![unbenannt](https://user-images.githubusercontent.com/37657839/40775617-cbdbd084-64c8-11e8-88cf-866c9e7852db.JPG)

Heißt das, dass ich ein neues Betriebssystem brauche, um die neuste Version (3.6) installieren zu können. Ich hab nämlich noch Windows 7 als 32-Bit Version. Wenn ich eine ältere Version (3.2) auswähle steht da, dass es bestimmte Einschränkungen gibt. Könnte ich trotzdem eine ältere Version installieren?

![mongodb](https://user-images.githubusercontent.com/37657839/40776057-fb800a48-64c9-11e8-9813-69c5f4b97990.JPG)

**Comment by JirkaDellOro** [comment]
Es würde mich wundern, wenn uns die Einschränkungen tangieren. Bitte die 32-Bit -Version installieren                                                                                                                                                                         Von meinem BlackBerry gesendet – dem sichersten Mobilgerät                                                                                                                                                                            Von: notifications@github.comGesendet: 31. Mai 2018 11:59 vorm.An: EIA2@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: [JirkaDellOro/EIA2] Unterstütztes Betriebssystem (#168)  
Heißt das, dass ich ein neues Betriebssystem brauche, um die neuste Version (3.6) installieren zu können. Ich hab nämlich noch Windows 7 als 32-Bit Version. Wenn ich eine ältere Version (3.2) auswähle steht da, dass es bestimmte Einschränkungen gibt. Könnte ich trotzdem eine ältere Version installieren?

**Comment by FranziskaHeiss** [comment]
Mir ist gerade aufgefallen, dass es sich bei der 32-Bit Version nicht um den Community Server handelt. Bei dem Community Server steht zwar, dass es Windows 7 unterstützt, aber nicht welche Bit Version. Mit dem normalen Download Link funktioniert die Installation nicht. Es erscheint ein Fenster, dass dieses Paket auf der Plattform nicht unterstützt wird, also brauch ich doch ein neues Betriebssystem?

**Comment by NicoKlein97** [comment]
Wenn du auf der Download Seite im Reiter "Community Server " bist, gibt es über dem OSX-Button die Möglichkeit "Previous Releases" auszuwählen. Wenn du dann die Version 3.2.20 auswählst, kannst du eine 32 Bit Version runterladen. Die ist zwar ziemlich alt, aber vielleicht hilft es ja trotzdem.

**Comment by JirkaDellOro** [comment]
Googelt man nach "mongodb 32bit" findet man gleich viele Links unter denen ich hilfreiche vermute. Da würde ich die jüngsten anschauen.
