### ISSUE TITLE
MongoDB Terminal Fehler

### ISSUE THREAD

**Issue by sofiagschwend** [JirkaDellOro/EIA2#169]
Installation von MongoDB hat geklappt. In Eclipse MongoDB Server als externesTool einbinden hat funktioniert. Das starten im Terminal klappt auch.
Der Befehl npm install mongodb ruft folgende Fehler Meldung auf:
![mongodb_terminal_fehler](https://user-images.githubusercontent.com/37657968/40778182-99a3ac10-64d0-11e8-9c11-ff7846157fbe.JPG)

Im Json wird kein Json-Package erzeugt.
Wie kann ich den Fehler beheben?

**Comment by JirkaDellOro** [comment]
So weit gehen wir noch nicht, das werden wir etwas anders machen. Es genügt derzeit, wenn Sie mit der Mongo-Shell Befehle absetzen können und Ihre Datenbank auf  mLabs einrichten                                  Von meinem BlackBerry gesendet – dem sichersten Mobilgerät                                                                                                                                                                            Von: notifications@github.comGesendet: 31. Mai 2018 12:48 nachm.An: EIA2@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: [JirkaDellOro/EIA2] MongoDB Terminal Fehler (#169)  Installation von MongoDB hat geklappt. In Eclipse MongoDB Server als externesTool einbinden hat funktioniert. Das starten im Terminal klappt auch.
Der Befehl npm install mongodb ruft folgende Fehler Meldung auf:

Im Json wird kein Json-Package erzeugt.
Wie kann ich den Fehler beheben?
