### ISSUE TITLE
unendlich viele Bienen entstehen  aus einem mir unbekannten Grund

### ISSUE THREAD

**Issue by sailechr** [JirkaDellOro/EIA2#17]
Aufgabe liegt in meinem EIA2-Ordner.
https://github.com/sailechr/EIA2/blob/master/aufgabe6/canvas.ts

**Comment by saenglert** [comment]
Hallo Chris,
Ich kann das Problem gerade nicht reproduzieren. Viel eher hat die Version die aktuell online ist ein Problem mit zwei gleich benannten Variablen. Sobald ich das behoben hatte, wurden die Bienen korrekt dargestellt.

**Comment by sailechr** [comment]
okay liegt das dann an dieser variable für das abgespeicherte Bild imagedata ??

**Comment by saenglert** [comment]
Das ist korrekt.

**Comment by sailechr** [comment]
okay ich versuche es nochmal :) vielen lieben dank :)

**Comment by sailechr** [comment]
also ich habe es jetzt umgeändert und ich lade es sobald wie möglich hoch :) 
es funktioniert
