### ISSUE TITLE
MongoDB Connection Error

### ISSUE THREAD

**Issue by LeonSchweikert** [JirkaDellOro/EIA2#170]
Hallo,
wir haben dieses Problem und kommen nicht weiter.
![issue](https://user-images.githubusercontent.com/37657463/40785585-25b1f280-64e9-11e8-8ec2-d048d671cea6.PNG)

**Comment by JirkaDellOro** [comment]
Genau diesen Fall habe ich in der Vorlesung behandelt

**Comment by kerndand** [comment]
Ich hab nun schon mehrfach von Leuten in unserem Kurs gehört, dass sie dasselbe Problem haben. Daher wäre es sehr nett von Ihnen wenn Sie vielleicht nochmal schreiben könnten wie genau Sie das in der Vorlesung gemacht hatten.

**Comment by JirkaDellOro** [comment]
Ok, das Tafelbild habe ich auch noch nicht hochgelegen, fürchte ich. Beim Aufruf von MongoD muss der Pfad zum Ordner angegeben werden, der die Daten aufnehmen soll. Etwa so

MongoD - - dbpath Ordnername

**Comment by kerndand** [comment]
Ich habe --dbpath und dann den Pfad zu dem Database Ordner in meinem Workspace angegeben. Dann werden mir Dateien in dem Database Ordner erstellt und in dem Windows Terminal steht "waiting for port 27017". Ab diesem Punkt komme ich dann leider nicht mehr weiter.

**Comment by JirkaDellOro** [comment]
@kerndand : Somit läuft also der Datenbankserver und man kann die Shell starten, um damit zu interagieren

**Comment by kerndand** [comment]
Okay der Datenbankserver läuft dann soweit. Aber wie starte ich denn die Shell dann?

**Comment by kerndand** [comment]
Okay hat sich erledigt, ich musst nur die mongo.exe ausführen, eigentlich selbsterklärend.
