### ISSUE TITLE
Terminal funktioniert nicht und ich kann deswegen MongoDB nicht starten.

### ISSUE THREAD

**Issue by TimLieberherr** [JirkaDellOro/EIA2#171]
Ich habe das Problem das mein Terminal in Eclipse nicht startet. Auf meinem Mac läuft aktuell Mac OS High Sierra 10.13.2. Anscheinend haben auch andere das Problem. Wie auf dem Bild zu sehen startet das Terminal nicht und reagiert auch auf keine Eingaben. Es gibt nur bash-3.2$  aus. Ich habe schon versucht das Problem zu lösen, in dem ich  "StartExplorer"  über den Marketplace in Eclipse installiere, was aber nichts gebracht hat. Leider hat auch die Verknüpfung mit dem MongoDB Datenbank nicht funktioniert.  

![problem terminal](https://user-images.githubusercontent.com/37657870/40877276-2f0b8404-667e-11e8-9410-15cc10954cda.jpeg)

**Comment by TimLieberherr** [comment]
![console eclipse](https://user-images.githubusercontent.com/37657870/40877547-1de9c00a-6683-11e8-9268-7f50be925a96.jpeg)

**Comment by muelle2k** [comment]
Ich hab das leider genau das gleiche Problem.

**Comment by muelle2k** [comment]
Ich hab genau das gleiche Problem und im Internet steht auch nichts nützliches drin.

**Comment by JirkaDellOro** [comment]
Habt ihr das mal probiert: https://marketplace.eclipse.org/content/tm-terminal ?

**Comment by muelle2k** [comment]
Bei mir funktionieren leider beide Varianten nicht. Ich hab den richtigen Pfad drin, jedoch funktioniert das mit dem "npm install mongodb" nicht. 

<img width="510" alt="bildschirmfoto 2018-06-02 um 23 32 23" src="https://user-images.githubusercontent.com/37657825/40881043-39780130-66bd-11e8-9ca7-653428d0926a.png">

oder schreib ich hier was falsch?

**Comment by saenglert** [comment]
Ja, machst du tatsächlich. Shell (Kommandozeilen) Aufrufe sind in aller Regel nach folgender Syntax aufgebaut:
```
> [Befehl] [Optionen...]
```
Du gibst bei dir als erstes keinen Befehl sondern einen Ordner an. Du willst vermutlich mongodb in den von dir angegebenen Ordner installieren. Npm kennt zwei Installationsarten (`dev` mal außenvor): Lokal und global. Was wir hier versuchen ist eine lokale Installation und dazu müssen wir im entsprechenden Ordner sein, also zuerst:
```
> cd /Users/patrickmk/git/EIA2_Node
´´´
Und im Anschluss können npm und mongodb initialisiert und installiert werden:
```
> npm init
> npm install mongodb
```

**Comment by JirkaDellOro** [comment]
Die Node-Library für MongoDB zu installieren ist nicht Teil der aktuellen Aufgabe, hierfür nicht erforderlich und in der Folge problematisch. Bitte hier stoppen

**Comment by muelle2k** [comment]
Das funktioniert leider auch irgendwie nicht. Oder schreib ich hier wieder was falsch? 

<img width="336" alt="bildschirmfoto 2018-06-03 um 10 37 37" src="https://user-images.githubusercontent.com/37657825/40884777-3703262a-671a-11e8-9c87-a0ad71794fbb.png">

**Comment by JirkaDellOro** [comment]
Bitte meinen Post beachten!!!

**Comment by muelle2k** [comment]
Ok. Also machen wir den Schritt nicht von der Mindmap? 

<img width="415" alt="bildschirmfoto 2018-06-03 um 10 58 37" src="https://user-images.githubusercontent.com/37657825/40884929-2ad02ce2-671d-11e8-8a2c-f107e551d97b.png">

**Comment by JirkaDellOro** [comment]
??? Wo habt ihr das denn her? Es gab einmal zwischenzeitlich eine MindMap-Version, in der das drinstand. Stellt bitte sicher, dass ihr immer die aktuelle Version betrachtet!

**Comment by steflaur** [comment]
<img width="990" alt="screen" src="https://user-images.githubusercontent.com/32569591/40888515-95f9ccae-6758-11e8-99ea-d46dd95f5365.png">

also ich finde das auch so unter dem Link der EIA2 Seite

wenn ich aber versuche, den Punkt "Main" in meinem Mac Terminal abzuschicken, weil Eclipse ja nicht geht, kommt immer "Permission denied"

<img width="854" alt="terminal" src="https://user-images.githubusercontent.com/32569591/40888569-7aa8a690-6759-11e8-88e5-83f683000ca1.png">

**Comment by JirkaDellOro** [comment]
Danke, ich habe es gefunden. Das war eine Notiz für die Zukunft, ich habe es nun als solche markiert.

Beim Terminalbefehl wundert mich, dass "mongod" und "data" beide unter git/EIA2-Heroku/mongoDB liegen sollen.

**Comment by steflaur** [comment]
ja ok das war unlogisch, jetzt klappts
