### ISSUE TITLE
Pushen geht nicht

### ISSUE THREAD

**Issue by sofiagschwend** [JirkaDellOro/EIA2#172]
Ich  habe den weiteren Branch 'database' erstellt: Darauf hin wurde mir folgender Fehler angezeigt:
![eclipse-git upload-pack](https://user-images.githubusercontent.com/37657968/41050934-06e6d0fc-69b5-11e8-9720-7fc7991de7d7.JPG)

Nun funktioniert das Pushen auch nicht mehr
![fehler2](https://user-images.githubusercontent.com/37657968/41050864-de285b22-69b4-11e8-89c3-f1cf1bb735fa.JPG)

Ich habe keine Lösung im Internet gefunden.

**Comment by JirkaDellOro** [comment]
Das ist ungewöhnlich, daher kann ich keine schnelle Lösung bieten. Ich schaue es mir morgen im Praktikum an.

**Comment by saenglert** [comment]
Da klingeln ein paar Glocken bei mir ...
Bin mir nur nicht ganz sicher was die Lösungsstrategie war. 

Bitte mal installierte Java Version prüfen und alle alten Installationen von Java entfernen.
