### ISSUE TITLE
TypeScript Builder funktioniert nicht mehr

### ISSUE THREAD

**Issue by kerndand** [JirkaDellOro/EIA2#173]
Hallo, 

mein TypeScript Builder funktioniert irgendwie nicht mehr richtig. Allerdings ist das Porblem nur bei meiner Server.ts - Datei, bei allen anderen funktioniert es. Und zwar wenn ich meine Server.ts abspeichere, sollte ja eigentlich der Code in JavaScript umgesetzt werden. Leider funktioniert dies bei mir nicht, sodass in meiner Server.js - Datei nur "//# sourceMappingURL=Server.js.map" steht. Ich habe schon versucht meinen Code in einem neuen TS-Dokument zu speichern, allerdings kommt dort genau das gleiche Problem. Ich weis nicht wo das Problem liegt, denn bis vor ein paar Minuten hat es noch funktioniert.

**Comment by JirkaDellOro** [comment]
Hallo Daniel,

bitte einmal Project->Clean durchführen. Falls dann Fehler unter "Problems" auftauchen, diese beheben.

**Comment by kerndand** [comment]
Ich konnte das Problem lösen, vielen Dank.

**Comment by JirkaDellOro** [comment]
Mit Hilfe meines Tipps, oder wo lag der Fehler?

**Comment by kerndand** [comment]
Ja, ich konnte mit Hilfe ihres Tipps das Problem lösen.
