### ISSUE TITLE
Frage zu Callbackfunctions

### ISSUE THREAD

**Issue by kerndand** [JirkaDellOro/EIA2#174]
Hallo,
Ich habe mir ihren Code heruntergeladen und genau angeschaut. Leider bin ich nach einiger Zeit immer noch nicht wirklich dahinter gekommen wie die Callbackfunctions funktionieren. Es wäre sehr nett, wenn sie diese nochmal anhand ihres Codes erklären könnten. 

`Database.findAll(function(json: string): void` 
In dieser Zeile rufen wir die Funktion findAll in der Database.ts auf. Die Funktion in den Klammern muss folglich die Callbackfunction sein, doch was bewirkt der Paramater den wir ihr mit geben?

Dann in der Database.ts 

```
export function findAll(_callback: Function): void {
    var cursor: Mongo.Cursor = students.find();
    cursor.toArray(prepareAnswer);

    function prepareAnswer(_e: Mongo.MongoError, studentArray: StudentData[]): void {
        if (_e)
            _callback("Error" + _e);
        else
            _callback(JSON.stringify(studentArray));
    }
}
```

Hier verstehe ich nicht wirklich was passiert. Daher wäre es sehr nett, wenn Sie diese Funktion vielleicht nochmal Schritt für Schritt erklären könnten. Vielen Dank!

**Comment by saenglert** [comment]
Callbacks sind aus dem Problem "Wie warte ich auf das Ergebnis meines asynchronen Codes?" entstanden.

Am Beispiel MongoDB:
Wenn wir versuchen Daten zu lesen, kann das abhängig von Größe und Komplexität der DB schnell oder langsam von statten gehen. Schnell ist kein Problem, aber wenn es länger dauert ist es unschön, wenn unser Programm praktisch an dieser Stelle hängt bis der Aufruf irgendwann abgearbeitet ist. Z.B. soll während des Vorgangs ein Ladebalken angezeigt und aktualisiert werden oder der User soll gar nichts davon mitbekommen, dass Daten geladen werden und unser Programm ungestört weiter benutzen (Endloses Scrolling z.B.).

Der Ansatz von Callbacks ist dazu, den Aufruf (z.B. einen Read Vorgang in MongoDB) zu starten und gleichzeitig die Information mitzugeben, was passieren soll wenn der Vorgang abgeschlossen ist:

```
// Pseudocode
// Funktion zum Lesen von Daten von der Datenbank
function readDB( whatToRead: string, callback: function): void {
  connectToDB(function(connection) {
    connection.sendQuery(whatToRead, function (result) {
      callback(result);
    })
  });
}

// Funktion zum Anzeigen der geladenen Daten
function displayData(data: Result[]): void {
  console.log('Async finished')
  data.foreach(function(datum) { 
    console.log(datum) 
  };
}

console.log('Before async start')
readDB('users', displayData);
console.log('After async start')
```

Könnte man diesen Code jetzt ausführen würde folgendes in der Konsole auftauchen:
```
> Before async start
> After async start
// 10 Säcönds Lätör
> Async finished
> User 1
> User 2
> User ...
```
'After async start' wird vor 'Async finished' , da der Callback `displayData` erst ausgeführt wird wenn die `readDB` Funktion komplett ausgeführt wurde. Innerhalb der Funktion können wie man sieht auch weitere Callbacks erstellt und eingesetzt werden, was natürlich zu längeren Wartezeiten führen kann. Aber da wir ja durch die asynchrone Arbeitsweise unser Hauptprogramm frei ist, können wir diese Wartezeit sinnvoll überbrücken, bis unser Callback aufgerufen wird und das Ergebnis verarbeiten kann.

**Comment by JirkaDellOro** [comment]
Ok, fangen wir mit findAll in Database.ts an
```
1 export function findAll(_callback: Function): void {
2    var cursor: Mongo.Cursor = students.find();
3    cursor.toArray(prepareAnswer);
4
5    function prepareAnswer(_e: Mongo.MongoError, studentArray: StudentData[]): void {
6        if (_e)
7            _callback("Error" + _e);
8        else
9            _callback(JSON.stringify(studentArray));
10    }
11 }
```
Im Funktionskopf (1) sieht man, dass als Parameter ein Verweis auf eine Funktion erwartet wird, der im weitern Verlauf der Funktion als `_callback` bezeichnet wird. Dann geschieht über die Collection `students` der Zugriff auf die Datenbank (2) und das Ergebnis wird in ein Array umgewandelt (3). Nach erfolgter Umwandlung, soll die Funktion `prepareAnswer` aufgerufen werden, denn ein Verweis darauf wurde der Methode `toArray` mitgegeben. `prepareAnswer` erhält Information zu eventuellen Fehlern als `_e` und das fertige Array der gefundenen Daten als `studentArray` (5). Enthält `_e` Informationen, wird `_callback` mit einer Fehlerausgabe als Parameter aufgerufen (7). Ansonsten wird das Array weiter umgewandelt in einen JSON-String und damit `_callback` aufgerufen (8).

Vielleicht ist euch aufgefallen, dass `prepareAnswer` innerhalb von `findAll` definiert ist. Bislang haben wir darauf geachtet, keine Funktionen innerhalb von andere zu definieren, sondern sie ordentlich zu trennen. In JS/TS ist es aber möglich und in diesem Fall auch sinnvoll. Denn dadurch ist `_callback` auch in `prepareAnswer` bekannt und kann genutzt werden.

**Comment by JirkaDellOro** [comment]
Nun noch zum Aufruf:
```
1 Database.findAll(function(json: string): void {
2              respond(_response, json);
3 });
```

Dies ist eine etwas verwirrende Schreibweise, die aber in JS/TS relativ häufig zu finden ist. Wir sind es eher gewohnt, was gut ist, es so zu schreiben:

```
1 Database.findAll(receiveFoundData);
2 
3 function receiveFoundData(json: string): void {
4       respond(_response, json);
5 };
```
Hier wird klarer, das `findAll` ein Verweis auf die Funktion `receiveFoundData` als Callback mitgegeben wird. Die Funktion hat hier einen eigenen Namen und ist eigenständig.  

Oben dagegen wird die Funktion direkt bei der Parameterübergabe definiert und hat keinen Namen, sie ist "anonym". Ich wollte euch in diesem Zusammenhang damit konfrontieren, damit ihr das auch einmal gesehen und genutzt habt. Allerdings hattet ihr schon vorgegriffen, denn man kann das auch als Arrow-Funktion schreiben:
```
1 Database.findAll((json: string) => {
2      respond(_response, json);
3 });
```

**Comment by JirkaDellOro** [comment]
Gerne weiter fragen, falls noch etwas unklar sein sollte...
