### ISSUE TITLE
Problem bei Search Funktion

### ISSUE THREAD

**Issue by kerndand** [JirkaDellOro/EIA2#175]
Hallo,

leider muss ich mich nochmal melden, da ich ein neues Problem habe. Und zwar wird mir bei meiner Search-Funktion der Student den ich suche nicht angezeigt. Es kommt die ganze Zeit "No Match", da anscheinend mein Student nicht gefunden wird, obwohl ich nach der richtigen Matrikelnummer suche. Leider finde ich meinen Fehler nicht. Es wäre nett, wenn Sie sich meinen Code mal kurz anschauen könnten. Vielen Dank!

[Database.ts](https://github.com/kerndand/EIA2_Node/blob/Aufgabe8/Database.ts)
[Server.ts](https://github.com/kerndand/EIA2_Node/blob/Aufgabe8/Server.ts)

**Comment by JirkaDellOro** [comment]
In Database.ts wird offensichtlich das Ergebnis der Suche nicht gespeichert. Wo kommt der Wert von myCursor her?

**Comment by JirkaDellOro** [comment]
Übrigens nicht "leider" , sondern "zum Glück". Wir freuen uns doch über Fragen

**Comment by kerndand** [comment]
Das war ein Fehler meiner Müdigkeit gestern. Eigentlich hatte ich es abgespeichert, jedoch funktioniert es leider trotzdem nicht. Ich habe den aktualisierten Code hochgeladen.

**Comment by JirkaDellOro** [comment]
Nein, war auch mein Fehler. Ich habe gerade erst gesehen, dass Sie mit dem Callback der findOne arbeiten wollen. Das ist dann eine andere Vorgehensweise als die von mir gezeigte, sollte aber möglich sein. Allerdings müssen Sie sich nun ganz genau die Datentypen und -strukturen anschauen. Ich konnte darin allerdings keinen Fehler finden.

Dieser versteckt sich in der Benennung der Felder in der Query der Request. Sie schicken ein "searchFor", der Server erwartet ein "searchedFor"

**Comment by JirkaDellOro** [comment]
PS: der Parameter des Callbacks sollte nicht myCursor heißen, sonder studi oder doc, sonst ist das sehr irreführend

**Comment by kerndand** [comment]
Ich konnte das Problem lösen. Es lag tatsächlich nur daran, dass ich "searchedFor" anstatt "searchFor" geschrieben hatte. Ich habe den Parameter des Callbacks umbenannt, war wirklich ziemlich irreführend und hat mich teilweise auch selbst verwirrt :)

**Comment by kerndand** [comment]
Problem gelöst, es stellte sich heraus, dass ich bei meiner line-Variable nur noch 2 Anführungszeichen hinzufügen musste.
