### ISSUE TITLE
Diverse Fehlermeldungen

### ISSUE THREAD

**Issue by alenamaria** [JirkaDellOro/EIA2#176]
Wir haben versucht, die bereits in der Datenbank gespeicherten Daten über den refresh-Button auszugeben. Allerdings wird in der Konsole folgende Fehlermeldung angezeigt:
![fehlermeldung_konsole](https://user-images.githubusercontent.com/37595721/41189243-fe292510-6bca-11e8-8ab5-c5c4e32ed10c.PNG)
Wir haben aber in der Server.ts die Access-Zeile drin.

Zudem erhalte ich über Heroku beim Starten der App (nach dem Deploy) einen Application Error. Mit den Logs kann ich leider nicht so viel anfangen:
![logs](https://user-images.githubusercontent.com/37595721/41189274-6b75038c-6bcb-11e8-882c-e528039edb02.PNG)

**Comment by JirkaDellOro** [comment]
Das liegt an dem merkwürdigen Aufbau, der sich bei euch entgegen meiner Vorlage eingeschlichen hat. Ihr installiert zwei Listener für Requests mit unterschiedlichen Handlerfunktionen. Im ersten Handler baut ihr nun schon eine Antwort mit Hilfe des Parameters _text zusammen, wobei dieser höchstwahrscheinlich keinen für die Aufgabe sinnvollen Wert erhält. Dann schickt ihr die Antwort zurück. Danach wird der zweite Handler aufgerufen und versucht auch eine Antwort zu erstellen, der erste hat diese aber schon abgeschlossen....

**Comment by JirkaDellOro** [comment]
Ist sämtlicher aktueller Code auf Github zu finden?

**Comment by JirkaDellOro** [comment]
Und auch schon der Link auf dem Steckbrief, so dass ich leicht testen kann?

**Comment by JirkaDellOro** [comment]
Ich  habe mir jetzt jedenfalls einmal angeschaut. was ich finden konnte. Die Lösung mit den Handlern ist nun recht geschickt. Auch scheint insert und refresh gut zu funktionieren. search ist aber noch gar nicht implementiert...

**Comment by alenamaria** [comment]
Okay, dann werden wir uns nun noch mit der search-Funktion auseinander setzen.
