### ISSUE TITLE
Master und database branch

### ISSUE THREAD

**Issue by kempfsas** [JirkaDellOro/EIA2#177]
Hallo,

Mir ist aufgefallen, dass sich mein Masterbranch dem database-branch anpasst, d.h. wenn ich z.B. in eclipse im database-branch ein neues ts erstelle, dann wird das auch im masterbranch erstellt und das sollte ja eigentlich nicht passieren. Habe ich da etwas falsch eingestellt?

**Comment by JirkaDellOro** [comment]
Scheint sich erledigt zu haben. Was war das Problem?

**Comment by kempfsas** [comment]
Eclipse hat die Files aus irgendeinem Grund immer auf beide Branches gespeichert. Ich musste das Repository in Eclipse löschen und nochmal neu hinzufügen und dann hat es funktioniert.
