### ISSUE TITLE
Verbindungsproblem heroku mit neuen branch & Access-Zeile ?

### ISSUE THREAD

**Issue by muelle2k** [JirkaDellOro/EIA2#178]
Hallo,

ich habe folgendes Problem: 
<img width="1233" alt="1" src="https://user-images.githubusercontent.com/37657825/41201726-732f8b9a-6cbd-11e8-980e-fb8107a4efbf.png">
Wenn ich auf heroku den neuen branch "database" deploy, dann wird die Verbindung von heroku und mLab hergestellt. Wunderbar.
Jedoch funktioniert meine Suche nicht, obwohl ich die Access-Zeile drin hab. Wieso ist das so?

<img width="1229" alt="2" src="https://user-images.githubusercontent.com/37657825/41201762-46b41cce-6cbe-11e8-9a91-d937578f1232.png">
Und wenn ich dann die Seite neu lade, dann passiert garnichts mehr. Weil dann die Verbindung von heroku auf den neuen branch "database" nicht mehr vorhanden ist. Es funktioniert nur wenn ich kurz davor auf heroku es deployed habe. 
Was muss ich umstellen damit die Verbindung von heroku auf den neuen branch "database" bestehen bleibt? 

Vielen Dank im Voraus für eure Hilfe!

**Comment by muelle2k** [comment]
Ohh, schade. Leider zu spät gesehen. 

Ansonsten erstelle ich eine neue App auf heroku und lasse es darauf laufen.

**Comment by JirkaDellOro** [comment]
Klar. Und meine Sprechstunde kann man einfach besuchen, am Besten aber am Tag vorher anmelden...
