### ISSUE TITLE
Die Serverantwort woird nicht in die Textareaelemente übertragen

### ISSUE THREAD

**Issue by sinaseifert** [JirkaDellOro/EIA2#179]
Hallo, ich habe folgendes Problem:
Bei Aufgabe 6 laufen jetzt alles Anfragen auf dem Server. Allerdings werden die Serverantworten zwar einwandfrei in der Netzwerkkonsole auf Chrome angezeigt, aber der response vom Server wird nicht auf die Cientseite übertragen. Diese scheint leer zu sein, ich weiß aber nicht warum.

**Comment by JirkaDellOro** [comment]
Das liegt wahrscheinlich daran, dass respond(...) vom Listener aufgerufen wird. Das soll wohl eher nicht so sein, sondern erst wenn die entsprechenden Datenabfragen durchgeführt wurden. Bitte noch einmal mit dem Vorlesungscode vergleichen
