### ISSUE TITLE
Fehler bei Startposition der Bienen

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#18]
Hallo zusammen, 
eig müsste ich das Interface soweit programmiert haben, jedoch stoppt das Programm an der Stelle in der die Startposition für die Bienen am Bienenkorb festgelegt wird (Code Zeile 70). Warum?

https://github.com/fehrenbi/EIA2/blob/master/Aufgabe%206/blumenwiese6a.ts

**Comment by saenglert** [comment]
Das du uns die genaue Zeile sagen kannst, zeigt mir schonmal, dass du in die Konsole geschaut hast. Dort steht auch die Antwort deiner Frage:
`TypeError: allBees[i] is undefined`
Das Element auf im Array allBees am Index des Wertes von I ist undefiniert (-> nicht vorhanden).

**Comment by JirkaDellOro** [comment]
Das heißt, in der Schublade liegt noch nichts, auf dessen x- oder y-Eigentschaft man zugreifen könnte. Einfach nochmal den Code der Vorlesung studieren, dann sollte klar sein was zu tun ist.

**Comment by fehrenbi** [comment]
Alles klar Dankeschön ich werde schauen ob ich den Fehler behoben bekomme :)
