### ISSUE TITLE
Access-Control-Allow-Origin Fehlermeldung

### ISSUE THREAD

**Issue by muelle2k** [JirkaDellOro/EIA2#180]
Hallo, 

ich verstehe nicht wieso diese Fehlermeldung angezeigt wird, obwohl ich die 
Access-Control-Allow-Origin Zeile wie aus der Vorlesung drin hab. 
<img width="454" alt="default" src="https://user-images.githubusercontent.com/37657825/41307064-6df6208c-6e78-11e8-8fd7-36a14a673b62.png">

Hier mein Code vom Server: https://github.com/muelle2k/EIA2_Node/blob/database/Server.ts

**Comment by JirkaDellOro** [comment]
Fällt mir leider auch nicht gleich ins Auge. Schauen wir uns am besten im Praktikum an.

**Comment by muelle2k** [comment]
Ich habe den Fehler gefunden. Meine ts Datei wurde nicht in js und js.map umgewandelt. 

Jetzt läuft alles :)
