### ISSUE TITLE
Problem mit Timeout in der moveObjects-Funktion

### ISSUE THREAD

**Issue by AnnaLotz** [JirkaDellOro/EIA2#181]
Um in meiner Unterwasser-Welt einen Anker bewegen zu lassen, habe ich einen Boolean-Wert erzeugt, der angibt, ob der Anker sinken oder steigen soll (Zeile 21). 
Nachdem ich diesen Wert abfrage, soll mit einer Timeout nach einiger Zeit erst die Funktion ausgeführt werde, die die Objekte auch wirklich bewegt. Jedoch wird dieser Timeout nicht beachtet und auf meinem Canvas habe ich nun einen Anker, der durchgehend von oben nach Unten und zurück "springt". Ziel ist es jedoch, dass dieser ein paar Sekunden unten liegen bleibt, bevor er wieder hoch gezogen wird.
Ich nehme an das Problem liegt darin, dass die Function moveAnchorAndChain() bei jedem Frame neu aufgerufen wird und der Timeout dadurch nichts nutzt. Gibt es da eine bessere Lösung für oder habe ich etwas übersehen?

Hier der Link zu meinem Canvas: https://annalotz.github.io/EIA2/Aufgabe_10/Canvas.html
und zu dem Code auf GitHub: https://github.com/AnnaLotz/EIA2/blob/master/Aufgabe_10/Canvas.ts

![canvas_anker](https://user-images.githubusercontent.com/37657636/41820179-b62b7e02-77cd-11e8-963f-c2f31ed09385.PNG)

**Comment by JirkaDellOro** [comment]
Hallo Anna,

die geschickteste Lösung ist, statt einer boolschen Variablen namens sink dem Anker eine string-Variable namens status oder action zu spendieren. Damit können dann mehrere Zustände lesbar abgebildet werden wie "sinking" , "lifting" , "grounded" usw abgebildet werden. Gerne kannst Du das zurück stellen, denn ich plane solch komplexeres Verhalten noch für die Fische

**Comment by JirkaDellOro** [comment]
PS: außerdem sollten überlaufende Werte immer auf Überlauf und nicht auf Gleichheit geprüft werden
