### ISSUE TITLE
Fehlermeldung in der Konsole

### ISSUE THREAD

**Issue by alenamaria** [JirkaDellOro/EIA2#182]
Franzi und ich versuchen momentan die Luftblasen und Fische in einzelne Subklassen der Superklasse "MovingObjects" umzuwandeln. Leider funktioniert es bei uns nicht. Fische und Luftblasen werden nicht erzeugt.
Im Browser wird folgende Fehlermeldung angezeigt:
![fehlermeldung](https://user-images.githubusercontent.com/37595721/42048004-33835ee2-7b02-11e8-8509-41a85aeced3c.PNG)
Wir kommen einfach nicht weiter. Woran könnte das denn liegen?

**Comment by saenglert** [comment]
Ist die aktuellste Version der Aufgabe online?

**Comment by alenamaria** [comment]
Ja, die habe ich eben hochgeladen

**Comment by alenamaria** [comment]
https://github.com/alenamaria/EIA2/tree/master/Aufgabe%2011

**Comment by JirkaDellOro** [comment]
https://alenamaria.github.io/EIA2/Aufgabe%2011/Aufgabe11.html

**Comment by JirkaDellOro** [comment]
Vorsichtshalber: setzt MovingObject.js in der HTML-Page nach oben, so dass dieses Script zuerst geladen wird. Manche Browser brauchen das noch.

**Comment by JirkaDellOro** [comment]
Die Klassennamen sollten im Singular stehen, da sie den "Bauplan" für nur eine Instanz enthalten und nicht für eine Gruppe

**Comment by alenamaria** [comment]
Ah, okay, dann sind meine Fische wieder sichtbar, wenn ich MovingObjects.ts im HTML-Dokument nach oben setze. Die Luftblasen zeigt es mir allerdings nach wie vor nicht an.

**Comment by saenglert** [comment]
Das liegt an der Position der Bubbles. Schau mal nach was du mit der machst.

**Comment by alenamaria** [comment]
Ich finde den Fehler bei der Position leider nicht. Über die Konsole habe ich mir das Array "movingObjects" ausgeben lassen. Dort stand, dass die x- und y-Koordinaten der Bubbles "not a number" sind. Aber ich weiß nicht, warum es mir da keine Zahlen anzeigt.

**Comment by saenglert** [comment]
Dann überleg mal wo du die Bubbles erstellst und da mit den Koordinaten gemacht bzw. gerade nicht gemacht wird.

**Comment by alenamaria** [comment]
Ich habe nun die Function "setRandomPosition" im Constructor eingebunden und meine Luftblasen sind nun wieder sichtbar - meintest du das?

**Comment by saenglert** [comment]
Exakt. Du hast nie Werte für X und Y eingesetzt.
