### ISSUE TITLE
"click" auf der unteren gescrollten Hälfte funktioniert, aber nicht auf der geklickten Stelle

### ISSUE THREAD

**Issue by muelle2k** [JirkaDellOro/EIA2#183]
Hallo, 

da mein Smartphone ziemlich groß ist, habe ich <canvas width=965 height=1450> so gesetzt und das Aquarium wird so angezeigt: 
<img width="1600" alt="bildschirmfoto 2018-06-28 um 19 06 00" src="https://user-images.githubusercontent.com/37657825/42049563-a77e353e-7b06-11e8-9be3-3ee3e451a699.png">
Hier funktioniert das "clicken" für das Futter. Aber wenn man dann nach unten scrollt und auf der unteren Hälfte "clickt", dann wird das Futter nicht auf der geklickten Stelle angezeigt, sondern weiter oben. ?!?
<img width="1317" alt="bildschirmfoto 2018-06-28 um 19 06 24" src="https://user-images.githubusercontent.com/37657825/42049665-e663e50a-7b06-11e8-8751-ab7bae4adffe.png">

---------------------------------------------------

Es funktioniert nur überall, wenn man die Ansicht soweit verkleinert (50%) bis man das ganze Bild sieht. 
<img width="1366" alt="bildschirmfoto 2018-06-28 um 19 06 35" src="https://user-images.githubusercontent.com/37657825/42049760-3ed6f59c-7b07-11e8-969d-bebd909a5138.png">

Was kann ich machen, damit ich auch auf der unteren gescrollten Hälfte klicken kann? 

Vielen Dank im Voraus!

**Comment by muelle2k** [comment]
Hier der Link: 
https://muelle2k.github.io/EIA2/Aufgabe11/Canvas.html

**Comment by saenglert** [comment]
Das liegt daran, dass du zwischen Screen und Page Coordinaten unterscheiden musst.

Wenn du eine Seite scrolls. ändern sich die Page Coordinaten, aber der Screen bewegt sich nicht.

**Comment by muelle2k** [comment]
Vielen Dank!!
