### ISSUE TITLE
Abgabe funktioniert nicht, Konsolenausgabe auch nicht hilfreich

### ISSUE THREAD

**Issue by EvelynSchmidt** [JirkaDellOro/EIA2#184]
Meine Abgabe funktioniert nicht, der Hintergrund zeichnet sich aber weder Fische noch Bubbles werden angezeigt auch das Event onclick funktioniert nicht, finde den Fehler nicht. Die Konsolenausgabe ist auch nicht hilfreich. 
Abgabe bereits hochgeladen und im Steckbrief verlinkt, wäre super wenn jemand den Fehler findet :)

**Comment by R0bel** [comment]
Schau dir in deiner HTML-Datei an in welcher Reihenfolge du deine Scripte verlinkst. Außerdem sollst du Plant.ts umbenennen, da es die MovingObjects-Klasse enthält und keine Plant-Klasse.

**Comment by EvelynSchmidt** [comment]
Danke, jetzt gehts 😊
