### ISSUE TITLE
MovingObjects funktioniert nicht

### ISSUE THREAD

**Issue by katrindreier** [JirkaDellOro/EIA2#186]
Hallo, 
meine MovingObjects tauchen nicht auf dem Canvas auf. Habe keine Fehlermeldung etc. und finde den Fehler nicht, kann bitte jemand über meinen Code schauen? :) 

https://katrindreier.github.io/EIA_2/Aufgabe11/Start.html

**Comment by R0bel** [comment]
Schau dir nochmal die Scripte an, die du in deiner Start.html verlinkt hast und schau ob alle richtig verlinkt wurden.

**Comment by katrindreier** [comment]
Hab ich gemacht, allerdings funktioniert es trotzdem nicht...

**Comment by JirkaDellOro** [comment]
Habe kurz den Compiler angeworfen und konnte sofort feststellen, dass bei moveObjects der Schleifenkörper kein einziges mal ausgeführt wird, da movingObjects leer ist...

Bitte übrigens meinen Kommentar zum Konzept beachten und die Klassennamen im Singular schreiben!

**Comment by katrindreier** [comment]
Vielen Dank, jetzt hab ich die Lösung gefunden :)
