### ISSUE TITLE
Canvas Responsiveness

### ISSUE THREAD

**Issue by al-mll** [JirkaDellOro/EIA2#187]
Hallo,

meine Frage bezüglich der Abschlussaufgabe ist: muss die Anwendung responsive sein?
Es heißt ja lediglich: "Die Anwendung läuft im Browser auf Smartphones, Tablets und Desktopgeräten."
Eine Anwendung kann auch ohne responsives Design geräteübergreifend laufen.
Die Darstellung im Browser variiert dann aber natürlich.

Mein Problem ist nämlich, dass meine Anwendung auf einer Canvas gezeichnet werden soll.
Da eine Canvas aber nicht (so leicht) responsive dargestellt werden kann (und vor allem die gezeichneten Objekte in der Canvas nicht), frage ich mich, ob ich die width und height der Canvas entsprechend gering halten dürfte. Auf Desktopgeräten wäre die Darstellung zwar nicht der Knüller, die Anwendung aber immerhin noch lauffähig. Außerdem kann per Broswer-interner Zoomfunktion die Darstellung leicht vergrößert werden.

Grüße,
Alfred

**Comment by JirkaDellOro** [comment]
Hallo Alfred,

bevor Sie sich einschränken: der Canvas kann natürlich ebenso per CSS mitskaliert werden. Allerdings ändert sich dabei die Auflösung. Eine andere Variante ist, tatsächlich die Canvasgröße per Javascript anzupassen und dem RenderingContext mit der scale-Anweisung mitzuteilen, das Koordinatensystem anzupassen. So bleibt die Auflösung optimal
