### ISSUE TITLE
Fische schwimmen nicht wieder ins Bild

### ISSUE THREAD

**Issue by sofiagschwend** [JirkaDellOro/EIA2#189]
Meine Sharks hören nach 1-2 Duchrgängen auf weiter durch das Bild zu schwimmen. Sie hören vermutlich a) auf sich zu zeichnen, b) werden außerhalb des Sichtfeldes dargestellt, oder c) es ist ein anderes Problem.
[https://sofiagschwend.github.io/EIA2/AbschlussAufgabe12/Futter%20bei%20die%20Fische%20Das%20Spiel/Canvas.html](url)

Woran könnte das liegen?

**Comment by R0bel** [comment]
Es liegt daran, dass sie außerhalb des Sichtfeldes dargestellt werden. Ich empfehle dir zunächst einmal ein Aktivitätsdiagramm für dein Konzept zu erstellen. Dann siehst du vielleicht an welcher Stelle du arbeiten musst.
