### ISSUE TITLE
"Supplied parameters do not match any signature of call target."

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#19]
Hallöchen, ich wieder.

Ich versuche gerade die 6a zu machen, doch hab immer diesen Error, wenn ich versuche der Biene ihren x und y-Wert zu geben.
Ich weiß nicht woran das liegt, kann mir da jemand aushelfen?

Line 83, 167, 179, 195 ^^'

Danke im voraus, 
Nadia =)

**Comment by JirkaDellOro** [comment]
Ist es ein Laufzeitfehler, ein Entwicklungszeit- oder Kompilierzeitfehler?

**Comment by NadiaCredidio** [comment]
Es kann sein, dass ich die Frage gerade nicht verstehe ^^'

Es beklagt sich, während der Entwicklungszeit(?), sodass es nicht in die Laufzeit kommt, da die JS-Datei nicht erneuert wird.

**Comment by JirkaDellOro** [comment]
Also gibt es Fehleranzeigen in Eclipse (Entwicklungs-, bzw. Kompilierzeit), und nicht in der Browserkonsole (Laufzeit)
Welche Fehlermeldung wird den dabei ausgegeben?

**Comment by JirkaDellOro** [comment]
Ist klar, was mit "namespace" gemeint ist, und warum wir diese nutzen?

**Comment by NadiaCredidio** [comment]
Genau, die Fehler sind in Eclipse und bislang ist es in jeder genannten Zeile der Fehler "Supplied parameters do not match any signature of call target."

Ja, das verstehe ich. Die Variablen die im Namespace definiert werden sind in dem ganzen Namespace nutzbar. Es wäre praktisch deren Scope-Bereich sozusagen.

**Comment by moritzhfu** [comment]
Vorsicht: Namespace bedeutet nicht das alle Variablen im ganzen Namespace nutzbar sind. Es ist eher so, dass diese nur jeweils im Namespace bekannt sind. Zusätzlich besitzen sie (natürlich) ihren eigenen Scope.
D.h. wird eine Variable in einer Funktion definiert ist sie auch nur dort nutzbar. 
Wichtig ist der namespace u.a. zur Abgrenzung von globalen Variablen zueinander. D.h. zwei Variablen können in zwei unterschiedlichen Namespaces gleich heißen; diese werden durch den jeweils unterschiedlichen Namespace voneinander abgegrenzt und unterschieden.

Zu deiner Fehlermeldung:
Wenn man diese etwas übersetzt und ein wenig ergänzt sollte der Fehler vermutlich relativ klar sein.

Übergebene Parameter entsprechen keiner (Methoden)-Signatur einer/der aufgerufenen Ziel-(Methode).

**Comment by NadiaCredidio** [comment]
Das habe ich Verstanden. Ich hab es nur falsch ausgedrückt scheint es.

Ich versteh die Meldung halt an sich nicht ^^' 
Ich weiß nicht was da die Methode wäre.

Ich hab ja die Funktion " function biene(_b: Bee): void {"
wobei  b " let b: Bee = { x: 0, y: 0, g: 0, farbe: "#0000ff" }; " ist.
Dann gebe ich in z.B. der init funktion die funktion wie folgend über : "        biene(1250, 420, 10, "00FF00");" 
und das geht nicht, obwohl es ja so stimmen müsste, oder nicht? Es sind ja die Richtigen Pararmeter, aber das mit der Methode versteh ich hier eben nicht.

Weiter unten im Verlauf hab ich dann versucht der Funktion Biene die Pararmeter so :" biene(b.x, b.y);" zu übergeben, aber das funktioniert dann eben auch nicht. 

Ich versteh halt einfach komplett nicht was da falsch sein soll, tut mir leid.

**Comment by moritzhfu** [comment]
Überprüfe mal die Anzahl der Parameter die die Funktion Biene entgegennimmt und die Anzahl der Parameter, die du der Methode in init übergibst. 
Ebenso die Anzahl im weiteren Verlauf, also bei biene(b.x, b.y).

**Comment by NadiaCredidio** [comment]
Die Funktion übernimmt einen Pararmeter, der aber aus dem Arry Bee besteht, dass heißt doch eigentlich, dass er dennoch 4 annehmen müsste, oder nicht ?
Sodass _b:Bee = _b.x, _b.y, _b.g, _b.farbe ist, oder nicht ? 

Und unten würden demnach nur die anderen zwei Pararmeter fehlen, oder ?

**Comment by moritzhfu** [comment]
> Die Funktion übernimmt einen Parameter, der aber aus dem Array Bee besteht, dass heißt doch eigentlich, dass er dennoch 4 annehmen müsste, oder nicht ?

Nein. Die Funktion nimmt genau _einen_ Parameter entgegen; Datentyp Bee.

**Comment by JirkaDellOro** [comment]
Meine Frage nach dem namespace lag darin begründet, dass ich sehen konnte, dass in den letzten Aufgaben immer der gleiche Namespace verwendet wurde (Aufg4_Canvas). Damit sind Konflikte im wahrsten Sinne vorprogrammiert, auch wenn sie derzeit vielleicht noch nicht auftreten.

**Comment by NadiaCredidio** [comment]
Ich hatte nicht mehr daran gedacht es zu ändern, aber nachdem Sie es angesprochen haben, habe ich es umbenannt.
Hmm..ich bekomm es gerade einfach nicht hin. Ich frag einfach, ob mir morgen jemand helfen kann =)

**Comment by JirkaDellOro** [comment]
Ist der aktuelle Code im Repository?

**Comment by JirkaDellOro** [comment]
Ausgehend von der Annahme, dass er aktuell ist, habe ich eine Pull-Request mit meinen Kommentaren verfasst. Sollte per Mail kommen, hier der Link für die anderen Betreuer: https://github.com/NadiaCredidio/EIA2/pull/1

**Comment by NadiaCredidio** [comment]
Den Code hatte ich zwischenzeitlich etwas geändert. Nun ist er wieder so drin, wie er mehr oder minder war. Ich stell mich gerade vllt. etwas schwer verständlich an.
Ich bin Ihre Kommentare durchgegangen und habe diese dann meinerseits kommentiert. 

Ich versteh die Übergabe der Parameter mit dem Interface nicht, oder was ich da eben falsch mache.
