### ISSUE TITLE
Hintergrund nicht mehr sichtbar ?

### ISSUE THREAD

**Issue by LeonSchweikert** [JirkaDellOro/EIA2#190]
Hallo,

ich habe meinen Canvas Hintergrund fertiggestellt und wollte damit beginnen Animationen einzufügen. Nachdem ich die erste Animation eingefügt hatte war leider nichts mehr außer der Animation zu sehen, soll heißen der Hintergrund ist nicht mehr sichtbar. Leider finde ich den Fehler nicht.

https://leonschweikert.github.io/EIA2/Aufgabe9/tryout.html

**Comment by R0bel** [comment]
Schau dir an wann du deinen Hintergrund zeichnest. Auch dir empfehle ich erstmal ein Aktivitätsdiagramm zu erstellen. Dann findest du solche Fehler schneller oder vermeidest sie.
