### ISSUE TITLE
Koordinaten von bewegten Objekten verfolgen 

### ISSUE THREAD

**Issue by marcobohn** [JirkaDellOro/EIA2#191]
Ich hab für meine Abschlussaufgabe ein UFO, das auf Knopfdruck Laserstrahlen schießt. 
Wie kann ich die Bewegung von mehreren Strahlen verfolgen und anschließend die Koordinaten von Laserstrahl und Zielobjekt abgleichen?

**Comment by saenglert** [comment]
Hallo Marco,
mir wird aus den zwei Sätzen gerade nicht 100% klar, was du vor hast. 

Ich hab mir mal deinen bisherigen Stand angeschaut (bitte immer mit verlinken) und denke, dass es dir darum geht herauszufinden, ob der Laserstrahl das Auto trifft oder nicht (aka Collision Detection).

Der einfachste Weg ist natürlich einfach die Positionen der `car` und `rayTrack` Objekte zu vergleichen, ob sie innerhalb eines gewissen Rahmens gleich sind (z.B. +-3px, da sie aufgrund von Rundungsfehlern vermutlich nie ganz denkungsgleich sind).

Nun sind die beiden Objekte allerdings nicht punktförmig, sondern haben eine Fläche und um zu vermeiden, dass sie ineinander geraten, aber keine Kollision erkannt wird (sog. Clipping), muss auch diese Fläche berücksichtig werden.

Dazu die grundlegende Frage: Womit wird die Fläche eines Objekts auf dem Canvas definiert? Das passiert in dem wir den CanvasRenderingContext2d (crc2) verwenden und einen sog. Pfad anlegen, der zum Schluss mit Farbe gefüllt wird.

Wäre es nicht wirklich hilfreich, wenn dieser Context auch eine Funktio besitzt, die uns sagt ob ein Punkt innerhalb eines Pfads liegt ... ?

**Comment by saenglert** [comment]
PS: 
Fast vergessen: Falls du das ganze etwas fancy machen willst, schau dir mal das hier an:

https://www.embed.com/typescript-games/basic-collision-detection.html

**Comment by JirkaDellOro** [comment]
Sascha hilft gerne, das ist ein netter Zug. Ich habe auch mal in das Repository geschaut und konnte kein vernünftiges Konzept für die Abschlussarbeit finden. Es wäre ein netter Zug, den Betreuern ein solches zur Verfügung zu stellen. Unter Produktionsbedingungen ist es für einen Medienkonzepter mehr als das, nämlich sein Job.
