### ISSUE TITLE
Touch implementierung

### ISSUE THREAD

**Issue by MaximSchlegel** [JirkaDellOro/EIA2#192]
Für meine Abschlussaufgabe funktioniert die Interaktion mit der Maus wie sie soll. Jetzt ist die Frage wie genau implementiere ich die Interaktion mit dem Touchscreen.
Bei der Maus Interaktion Track ich die Koordinaten der Maus und vergleiche diese mit dem 
Interaktionsobjekt. Kann ich die gleiche Lösung auch in die Touch Interaktion integrieren und wenn ja wie bekomme ich die Koordinaten von der Fingerbewegung des Users? 
Hier noch der Link zu den Codes die für die bisherige Maus Interaktion verantwortlich sind.

Hauptprogramm ab Zeile 46:
https://github.com/MaximSchlegel/EIA2/blob/master/Abschlussaufgabe/Abschlussaufgabe.ts

Circle Klasse ab Zeile 53:
https://github.com/MaximSchlegel/EIA2/blob/master/Abschlussaufgabe/Circle.ts

**Comment by R0bel** [comment]
Der Aufbau des Events beim Touch sieht ein bisschen anders aus als beim Mausevent. Du kannst nicht direkt über `var touchX: number = event.screenX;` darauf zu greifen. Schau dir nochmal die Beispiele von Mozilla in dem zweiten Link an. Sie verwenden dort pageX und wenn du das verstehst, kannst du es auch für screenX und screenY machen.
