### ISSUE TITLE
Score funktioniert nicht

### ISSUE THREAD

**Issue by JaquelineSchnitzer** [JirkaDellOro/EIA2#193]
Hallo :)
Bei meinem Spiel soll das Kaninchen die Karotten fressen, wofür man einen Punkt bekommt. Beim Fressen der Schokolade gibt es einen Punkt Abzug. Hat man weniger als Null Punkte ist das Spiel vorbei. 

Ich habe eine Weile an dem Score herum probiert und es funktioniert nicht so richtig. Habt ihr ein paar Tipps? Oder andere Wege wie ich es versuchen kann?

Der Unterschied zwischen Karotte und Schokolade wird noch nicht sauber erkannt. Und wenn ich ins Minus komme, gibt er mir gefühlte 1000 mal einen "Game over" Hinweis.

https://github.com/JaquelineSchnitzer/EIA2/tree/master/Abschlussaufgabe/Code

**Comment by R0bel** [comment]
Hallo Jaqueline,
deine Kollisionen stimmen nicht ganz und deshalb funktioniert dein Score auch nicht. Schau dir den Link von Sascha zu Kollisionen an: https://www.embed.com/typescript-games/rectangle-rectangle-collision.html
Zu deiner Endlosschleife: Schau dir nochmal an was genau bei einem Gameover passieren sollte. Welche Vorgänge laufen noch, die gestopt werden müssen? Erweiter dafür dein Aktivitätsdiagramm mit genaueren Angaben. Das hilft sowohl dir als auch deinem Tutor leichter den Überblick zu behalten. Du hast z.B. deine Animation nicht in deinem Aktivitätsdiagramm dargestellt. 
Außerdem ist mir aufgefallen, dass deine Bild-Klasse sich nicht in einer eigener Datei befindet. Bitte das ändern und deinen Code dann nochmal anpassen. Schau dir an ob es notwendig ist, dass du z.B. 4 eigene Klassen für das Gras benötigst oder ob man es anders lösen kann. Ich hoffe das hilft dir weiter.

**Comment by JirkaDellOro** [comment]
Ohne den Code gesehen zu haben: der CanvasRenderingContext bietet eine sehr einfache Möglichkeit eine zumindest rudimentäre Kollisionsprüfung zu bewerkstelligen. Die Methode heißt isPointInPath oder so ähnlich.

**Comment by R4Pi3R** [comment]
Nein, das funktioniert so "einfach" leider nicht.
Wenn deine Bilder aber nicht zu Komplex sind (oder es nicht darauf ankommt, ob die Kollisionserkennung tatsächlich Pixelgenau ist) kannst du im Hintergrund des Bildes eine einfache Form zeichnen lassen und prüfen, ob eine Überschneidung mit dieser vorliegt.

**Comment by JirkaDellOro** [comment]
Tatsächlich muss keine Form gezeichnet sondern nur ein Pfad angelegt werden.

**Comment by JaquelineSchnitzer** [comment]
Ich hab die Abstände der Objekte nun mit dem Satz des Pythagoras ausgerechnet und diese Distanz nun als Orientierungswert genommen, wann was passieren soll. Er erkennt nun die Objekte. 
Das einzige was jetzt noch stören könnte, er zählt solange Punkte dazu bis diese wieder voneinander entfernt sind. 
Ich habe es nun so gelassen, weil ich dies ganz interessant im Spielverlauf finde.

Mich würde trotzdem interessieren wie man das noch lösen könnte :)
