### ISSUE TITLE
Blätter fallen nur einmal

### ISSUE THREAD

**Issue by AnnikaKussberger** [JirkaDellOro/EIA2#194]
Ich habe das Problem dass immer wieder Blätter vom Baum fallen sollen, sie Blätter fallen bisher nur einmal beim Neustart und danach nicht mehr. Ist das ähnlich zu lösen wie bei Sofia oder woran könnte das liegen?
https://github.com/AnnikaKussberger/EIA2/blob/master/Abschlussaufgabe/leaves.ts

**Comment by R0bel** [comment]
Hallo Annika,
ich konnte bei dir kein Aktivitätsdiagramm finden. Bitte das noch machen. Es hilft dir solche Fehler leichter zu finden. 
Zum Problem: Du hast es richtig erkannt. Schau dir dein move() nochmal an und versuche zu verstehen was dein Code macht und was du eigentlich machen willst.

**Comment by AnnikaKussberger** [comment]
Es funktioniert jetzt. Jetzt habe ich allerdings ein neues Problem. Ich möchte auf Klick objekte verschwinden lassen. Dazu rechnet die funktion den abstand zwischen position click und position objekt aus. Ich komme aber nicht auf die Lösung warum hier irgendwas nicht funktioniert.
https://github.com/AnnikaKussberger/EIA2/blob/master/Abschlussaufgabe/canvas.ts

**Comment by JirkaDellOro** [comment]
Wo finde ich den Link zur github.io-Seite, so dass ich dass einfach schnell laufen lassen kann?

**Comment by AnnikaKussberger** [comment]
https://annikakussberger.github.io/EIA2/Abschlussaufgabe/Abschlussaufgabe.html

**Comment by JirkaDellOro** [comment]
Dass die Objekte verschwinden, wenn man auf sie klickt, scheint zu funktionieren. Was funktioniert nicht?
