### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by nicoherrmann** [JirkaDellOro/EIA2#195]
Hallo,
in der Aufgabenstellung steht, wir sollen unsere Repositories folgendermaßen bennen:
"https://[username].github.io" (Userpage) und "https://[username].github.io/EIA2" (Projectpage)
![projekt](https://user-images.githubusercontent.com/43846525/46471980-f3fcdb00-c7db-11e8-87c3-08198b9cf7cd.png)
Allerdings kann man bei der Erstellung des Namens kein "/" verwenden.
![issue](https://user-images.githubusercontent.com/43846525/46471907-b5ffb700-c7db-11e8-88fd-a898036874cf.png)
Sollen wir dann bei dem Repository mit dem Namen "https://[username].github.io" einen Ordner erstellen mit dem Namen "EIA2" erstellen, sodass man über die URL darauf zugreifen kann oder gibt es da einen anderen Weg? Weil wenn man es als Unterordner macht wären es ja keine zwei verschiedenen Repositories, aber wenn man es mit dem Namen direkt erstellen möchte ist es kein "/" sondern ein "-".

Mfg
Nico Herrmann

**Comment by JirkaDellOro** [comment]
Es muss unterschieden werden zwischen der Organisation der Repositories unter github.com und der Publikation der Inhalte durch Pages unter github.io.

Auf github.com legt man einfach per "new" Repositories an und gibt ihnen dabei einen Namen ohne Schrägstriche, z.B. EIA2. Das Repository ist dann in meinem Fall einsehbar unter https://github.com/JirkaDellOro/EIA2. Die Pagespublikation, sofern diese veranlasst wird, findet man aber unter der URL https://jirkadelloro.github.io/EIA2

Die Userpage ist ein besonderes Repository, welches sich durch die Namensgebung auszeichnet (siehe Mindmap). Es wird automatisch publiziert unter dem Usernamen auf github.io, in meinem Fall z.B. https://jirkadelloro.github.io. Ansonsten ist es aber ein gewöhnliches Repository und einsehbar unter -in meinem Fall- https://github.com/JirkaDellOro/JirkaDellOro.github.io

Beantwortet das die Frage?

**Comment by nicoherrmann** [comment]
> Auf github.com legt man einfach per "new" Repositories an und gibt ihnen dabei einen Namen ohne Schrägstriche, z.B. EIA2. Das Repository ist dann in meinem Fall einsehbar unter https://github.com/JirkaDellOro/EIA2. Die Pagespublikation, sofern diese veranlasst wird, findet man aber unter der URL https://jirkadelloro.github.io/EIA2
> 
Beantwortet meine Frage soweit zwar, habe ich auch so gemacht, allerdings wird unter https://nicoherrmann.github.io/EIA2 dennoch nur ein Fehler angezeigt.

**Comment by nicoherrmann** [comment]
Ah nein das hab ich vergessen, funktioniert jetzt.
Danke sehr
