### ISSUE TITLE
Eclipse hat eine Fehlermeldung bei GitHub

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#196]
Hallo,
![20181004_162552 1](https://user-images.githubusercontent.com/43847187/46482696-61b60080-c7f6-11e8-8a0c-91abfbf46fbc.jpg)
 Eclipse zeigt folgende Fehlermeldung an. Kann mir da jemand helfen?

**Comment by JirkaDellOro** [comment]
Was wird denn unter "Details" angezeigt? Haben Sie Nutzername und Passwort korrekt angezeigt?

**Comment by saenglert** [comment]
Wenn es das ist was ich glaube, macht wieder das Git Plugin von Eclipse Zicken.

ALLE vorhanden Java Versionen auf dem Computer löschen und die neuste 64bit Version installieren. Auf jedenfall bitte noch den ganzen Inhalt der unter Details steht hier posten.

**Comment by AnnaLotz** [comment]
Hast du versucht, noch einmal zu pushen? Manchmal hat es bei mir erst beim zweiten mal geklappt.

**Comment by haasmanu** [comment]
Ich habe die neuste Java Version runtergeladen und mehrmals versucht zu pushen, leider mit keinem Erfolg...
![20181005_161840 1](https://user-images.githubusercontent.com/43847187/46541578-b623b380-c8bc-11e8-9d69-86597377648f.jpg)

Dies wird mir nun Angezeigt

**Comment by saenglert** [comment]
Das sieht doch schonmal sehr viel besser aus.

`non-fast-forward` bedeutet, dass im Git repository auf Github (Achtung: Git ist nicht gleich GitHub) Änderungen vorliegen, die in den lokalen Änderungen die gerade gepusht werden sollen noch garnicht vorhanden sind und durch den Push überschrieben werden würden.

Das Gegenstück zum `Push` mit dem man Änderungen an ein Remote Repository schickt ist der `Pull`.
Ich bin mit gerade nicht 100% sicher, wo der Button dafür in der Eclipse UI ist, sollte aber in der Nähe des Push Buttons sein.

Oder falls du dich in die wunderbare Welt der Kommandozeile wagen wills.

`git pull`

**Comment by JirkaDellOro** [comment]
Grundsätzlich zu Beginn der Arbeit immer pullen! Das erspart viel Ärger...

**Comment by haasmanu** [comment]
Vielen Dank dieses Problem konnte ich zum Glück beheben :)
