### ISSUE TITLE
Commit and Push, sowie Steckbrief

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/EIA2#197]
Hallo,
ich habe das Problem, dass die von mir gepushten Dateien nicht in meinem zweiten Repositorie angezeigt werden. Im ersten sind die Veränderungen immer direkt zu sehen.
Zusätzlich habe ich noch das Problem, dass die in meinem Steckbrief verlinkten Seiten nicht auf der Kursseite erscheinen.
So sehen die Links aus:
<a href="https://ahornzweig.github.io/" target="_blank">Github-Repository, 04.10.2018</a><br>
<a href="https://github.com/Ahornzweig/EIA2" target="_blank">Userpage, 04.10.2018</a>

**Comment by JirkaDellOro** [comment]
Sie hatten den Pfad mit http:// angegeben. Da die Kursseite aber eine gesicherte Seite ist, verlangt sie auch, dass eingebundene Subseiten per https:// angesprochen werden. Ich habe es korrigiert

**Comment by Ahornzweig** [comment]
Okay, vielen Dank für die Hilfe.
