### ISSUE TITLE
Steckbrief

### ISSUE THREAD

**Issue by yeniayeb** [JirkaDellOro/EIA2#198]
ich habe soeben versucht mein Steckbrief hoch zuladen ,jedoch hat es leider
wieder nicht funktioniert.
Node habe ich auch installiert. Eclipse habe ich auch neu installier nichts
desto trotz hat es nicht funktioniert.
Bei mir erscheint bei ''Team''  immer noch kein Commit. Woran kann das liegen?.

Ich bedanke mich im Voraus

**Comment by JirkaDellOro** [comment]
eGit ist installiert und ein Repository wurde von Github geclont?

**Comment by NicoKlein97** [comment]
Besteht denn eine Verbindung zwischen dem Ordner in Eclipse und Github ?
Normalerweise steht ja im Project Explorer in Eclipse neben dem Ordner in hellgrau der Name des verbundenen Repositories, ist das bei dir der Fall ?

**Comment by yeniayeb** [comment]
ich denk schon, im Anhang ist ein Screenshot.
Jetzt funktioniert das mit dem Comit jedoch erscheint nichts in meinem Github.


Nico Klein <notifications@github.com> hat am 5. Oktober 2018 um 11:49
geschrieben:

**Comment by yeniayeb** [comment]
leider bekomme ich die selbe Fehlermeldung.

**Comment by JirkaDellOro** [comment]
Dann sehen wir uns am Besten am Montagmorgen in meiner Sprechstunde

**Comment by AnnaLotz** [comment]
...Issue kann geschlossen werden
