### ISSUE TITLE
Aktivierungscode falsch

### ISSUE THREAD

**Issue by janamamedow** [JirkaDellOro/EIA2#199]
Ich habe ein Problem mit dem Aktivierungscode. Ich habe versucht mich mehrmals für den Steckbrief anzumelden, jedoch kam jedes mal die Meldung, dass der Code falsch sei.

**Comment by R4Pi3R** [comment]
Bei jedem Registrierungsversuch wird ein neuer Code versendet. Wurde der zuletzt erhaltene für die zuletzt durchgeführte Registrierung verwendet? 
Dieser Code kann auch Sonderzeichen (im Speziellen am Ende, wo man diese gerne ignoriert) enthalten. Zum Code gehören alle Zeichen bis zum Ende der Zeile in der dieser steht.

Schneller fix versuch:
Lösche bitte zuerst alle Mails die du vom Registrierungsserver erhalten hast.
Registriere dich dann erneut auf der Kursseite und warte auf die Mail.
Der Prompt in dem der Code einzugeben ist friert den Tab, ggf. aber auch das ganze Browserfenster oder alle Instanzen von diesem ein. 
Damit man den Code nicht via Handy o.Ä. abrufen und von Hand abtippen muss kann man in diesem Fall einen anderen Browser verwenden (bei Windows bspw. Edge) und die Mail darüber öffnen. So lässt sich der Code einfach kopieren und mittels STRG und V (auf Apple-Geräten CMD und V) im Prompt einfügen.

Bitte einmal auf diese Art versuchen und zurückmelden, ob es funktioniert hat oder nicht

**Comment by AnnaLotz** [comment]
Habe es mit Jana noch einmal gemeinsam versucht, es hat dann auch funktioniert!
