### ISSUE TITLE
Aufgabe6a Variable undefined

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#20]
In der Konsole wird mir ausgegeben, dass die Variable "b" undefinded ist. Ich finde aber den Fehler nicht, bzw. weiß nicht wie oder was ich anderst machen soll. Die Variable wird in der Zeile 381 deklariert.

https://michellefix.github.io/EIA2/Aufgabe6a/Aufgabe6a.html

**Comment by JirkaDellOro** [comment]
flyBees wird aufgerufen, bevor die Bienen erzeugt wurden. Daher sind die noch "undefined"

Bei dieser Gelegenheit bitte die Compilereinstellungen überprüfen, wir kompilieren nach Ecmasript6
