### ISSUE TITLE
Kompilierung von .ts Dateien funktioniert nicht.

### ISSUE THREAD

**Issue by basickri** [JirkaDellOro/EIA2#200]
Trozt der vorgenommenen Einstellungen (Compiler, Check) werden meine .ts Dateien nicht in .js Dateien kompiliert. Welches Problem könnte hier vorliegen?

**Comment by saenglert** [comment]
Sind die Dateien auch fehlerlos? Der Compiler ist so eingestellt, dass wenn es Fehler gibt, er keinen Output produziert.

**Comment by R4Pi3R** [comment]
Wurde der Typescript compiler auch "enabled"?

**Comment by baayzi** [comment]
ich habe das selbe problem und ich habe alles enabled und bin der anleitung aus eia1 für typescript schritt für schritt gefolgt

**Comment by JirkaDellOro** [comment]
... und Node ist auch installiert? Haben Sie auch mit der Anleitung in der EIA2-Mindmap verglichen?

**Comment by baayzi** [comment]
Also ich habe jetzt alles versucht, was ich kann. Ich habe auch schon das Project von Eclipse gelöscht und nochmal neu importiert.

**Comment by baayzi** [comment]
Ok nun nach langen neu installieren und konfigurieren habe ich das Problem gelöst. SOLVED!!!

**Comment by basickri** [comment]
Hey Sascha,

Nochmal zu meinem Problem, dass Eclipse die Dateien nicht kompiliert.
Der TypeScriptBuilder ist enabled. Und der Code müsste eig stimmen, ausser ich
übersehe was.
Woran könnte es sonst noch liegen bzw. was kann ich sonst noch machen?

Anbei findest  du noch ein Screenshot vom jetzigen Standpunkt (Eclipse).

Beste Grüße
Kristian Basic

Sascha <notifications@github.com> hat am 5. Oktober 2018 um 16:41 geschrieben:

**Comment by JirkaDellOro** [comment]
Ups, da hatte ich den Issue vorzeitig geschlossen, da Bato seine Erfolgsmeldung abgesetzt hatte.

Wo finden wir den Screenshot? In Ihrem EIA2-Repository liegt leider kein Code, sonst könnten wir da reinschauen. Das wäre besonders geschickt...

**Comment by basickri** [comment]
Den Screenshot schicke ich nochmal per Anlage in dieser Mail.

Habe jetzt nochmal alles neu eingerichtet & sobald ich alles wiederherstelle
lade ich es noch hoch!
Was mir jedoch aufgefallen ist, ist dass unter jedem File den ich in Eclipse
erstelle ein Fragezeichen auftaucht?


JirkaDellOro <notifications@github.com> hat am 7. Oktober 2018 um 13:18
geschrieben:

**Comment by basickri** [comment]
Endlich! Ich konnte nach der neuen Installation und erneuter Einstellung das
Problem lösen!

JirkaDellOro <notifications@github.com> hat am 7. Oktober 2018 um 13:18
geschrieben:
