### ISSUE TITLE
Mein Steckbrief wird nicht im Browser angezeigt??

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#201]
Hallo,

Ich habe alles so erstellt und auf GitHub gepusht wie in der Aufgabe beschrieben.
Doch wenn ich nun meine Steckbrief HTML Datei aufrufen möchte steht nur Error 404.

Bitte um Hilfe :/

**Comment by saenglert** [comment]
Da ist er doch:

https://haasmanu.github.io/Steckbrief/steckbrief.htm

Pfade (alles was nach der Domain github.io kommt) sind case-sensitive.

**Comment by JirkaDellOro** [comment]
Ist ja auch schon eine Weile auf der Kursseite, Sascha... :-)

**Comment by saenglert** [comment]
Ja, das hat mich schon etwas gewundert, aber hey ich richte nicht, ich beantworte nur Fragen. :P

**Comment by JirkaDellOro** [comment]
Des Pudels Kern: Manuel hätte den Issue schließen sollen. Das mach' ich jetzt
