### ISSUE TITLE
Steckbrief 

### ISSUE THREAD

**Issue by StfnMerdi** [JirkaDellOro/EIA2#202]
Mein Steckbrief wird auf der Kursseite nicht angezeigt bzw. anscheinend falsch verlinkt obwohl ich eigentlich es richtig habe.
404 File not found steht da
Habe jetzt ewig rum probiert aber kann keine Lösung finden

**Comment by JirkaDellOro** [comment]
Merdian, Stefan... korrekt?

Sind Sie ganz sicher, dass die Datei steckbrief.htm im Repository zu finden ist?

**Comment by StfnMerdi** [comment]
Ja sie ist drin aber ich weiß jetzt auch nicht mehr wie ich es verlinkt hab und jetzt wird auch nicht mal mein Bild angezeigt.

**Comment by JirkaDellOro** [comment]
Ja, jetzt ist sie drin, aber falsch geschrieben. Das s sollte kleingeschrieben sein.

**Comment by Lizzyfrmdblck** [comment]
Hey, ich hab fast das gleiche Problem - bei mir liegt es daran, dass sich zwei Steckbrief-Dateien im Rep befinden und die Verlinkung zum korrekten Steckbrief (beim Anlegen des Steckbriefs) leider nicht funktioniert hat. Weiß aber leider nicht, wieso die Verlinkung nicht gestimmt hat.

**Comment by JirkaDellOro** [comment]
@StfnMerdi : Das Userpage-Repository wurde nicht korrekt benannt, es muss den Usernamen integrieren.

**Comment by JirkaDellOro** [comment]
@Elyssia: das kann ich jetzt nicht nachvollziehen, bitte einfach in die Sprechstunde oder zu Anna ins Spiellabor kommen. Jedenfalls ist Portrait und Steckbrief auf der Kursseite zu sehen...

**Comment by StfnMerdi** [comment]
https://StfnMerdi.github.io/Steckbrief

MFG Stefan Merdian <https://github.com/StfnMerdi/StfnMerdi.github.io>
