### ISSUE TITLE
Verlinkungen werden nicht angezeigt 

### ISSUE THREAD

**Issue by chiasmox** [JirkaDellOro/EIA2#203]
Anastasia Geibel hier.

Ich habe alles auf github hochgeladen, jedoch werden die Verlinkungen auf meinem Steckbrief nicht angezeigt.

**Comment by AleaFlesch** [comment]
Ich habe das selbe Problem..
Es hat bis jetzt immer funktioniert mit dem hochladen. Gerade eben habe ich noch meine JS Datei für die Miniseite hochgeladen, diese wurde aber in Github nicht angezeigt und jetzt sind bei mir keine Links mehr auf der Kursseite.

**Comment by theresagut** [comment]
Ich hab das selbe Problem wie Alea. 
Meine Dateien werden auf Github nicht mehr angezeigt...

**Comment by R4Pi3R** [comment]
Habe gerade mal bei allen reingeschaut.
Dort wo Dateien fehlen, bitte einmal einen Pull durchführen und danach nochmals pushen. Vllt hat sich das git Plugin mal wieder irgendwo verschluckt.

Für die auf der Kursseite nicht aktualisierten Steckbriefe: Bei einigen wird angezeigt, dass GitHub Pages sich gerade in der Wartung befindet. Es kann sein, dass der Steckbrief deshalb nicht neu geladen wird. bitte etwas warten und später nochmal überprüfen und Rückmeldung geben.

**Comment by chiasmox** [comment]
chiasmox.github.io/Steckbrief/steckbrief.htm
Wie man hier sehen kann, funktioniert der Link, wird jedoch auf der Kursseite selber nicht angezeigt. Bei mir scheint es auch kein Fehler in github an sich zu sein.

**Comment by JirkaDellOro** [comment]
Als Protokoll muss https verwendet werden, im registrierten Pfad war http eingetragen. Ich habe es korrigiert.
