### ISSUE TITLE
Github: HTML Dokument kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by basickri** [JirkaDellOro/EIA2#204]
Ich habe das Problem, dass bei meine Html nicht angezeigt werden kann. Alles ist gepusht und der Pfad eigentlich auch richtig verlinkt. Wenn ich aber auf der Kursseite auf den Link klicke, kommt eine 404 Fehlermeldung.

**Comment by R4Pi3R** [comment]
Wurde GitHub Pages auch im EIA2 Repository aktiviert?
Zusätzlich: das Repository heißt EIA2, der Link verweist aber auf eia2.

**Comment by AnnaLotz** [comment]
...Issue kann geschlossen werden.
