### ISSUE TITLE
ts Datei macht keine js Datei

### ISSUE THREAD

**Issue by theresagut** [JirkaDellOro/EIA2#205]
Beim erstellen der ts Datei wird keine js Datei automatisch gemacht obwohl TS enabled hab.

**Comment by JirkaDellOro** [comment]
Ist in den Compileroptionen auch eingestellt, dass automatisch beim Speichern kompiliert wird?

**Comment by theresagut** [comment]
Wo finde ich diese Einstellung?

**Comment by R4Pi3R** [comment]
Anleitung in der Mindmap: Installations ->TypeScript in Eclipse -> Preferences Typescript Compiler

**Comment by AnnaLotz** [comment]
...TS-Datei im Repository vorhanden, Issue kann vermutlich geschlossen werden.
