### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Koelleka** [JirkaDellOro/EIA2#206]
Mein Repository und meine Userpage lassen sich nicht mehr mit der Seite verknüpfen, bzw lassen sich nicht mehr anzeigen und ich suche den Fehler, übers Wochenende. Im Moment meldet Eclipse (das Programm an sich) noch einen Fehler und ich werde mich damit mal außeinander setzen.

**Comment by NicoKlein97** [comment]
Kannst du den Fehler von Eclipse hier posten ? Vielleicht erleichtert das die Fehlersuche.
Zu dem anderen Problem, hast du deinen Link ändern lassen ?

**Comment by R4Pi3R** [comment]
Ist meines Wissens nach erledigt,
Bitte Issue schließen
