### ISSUE TITLE
i prompt wird zweimal ausgeführt + Fehlermeldung

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#209]
Ich habe das Problem, dass prompt bei mir zweimal ausgeführt wird. Ebenso bekomme ich die Fehlermeldung: 

Uncaught TypeError: Cannot read property 'appendChild' of null
    at placeDiv (Aufgabe2.ts:129)
    at Aufgabe2.ts:182
    at Aufgabe2.ts:212

Link zur ts Datei: https://github.com/dangscha/EIA2/blob/master/Aufgabe%202/Aufgabe2.ts

**Comment by R4Pi3R** [comment]
Beide Probleme sollten sich lösen, wenn die Abfrage und die Darstellung der Karten in eine Funktion gebündelt werden, die von einem DOMContentLoaded Eventlistener aufgerufen wird.
Das Script wird im Head der HTML referenziert und dort gestartet. zum Zeitpunkt des Durchlaufens gibt es noch keinen body, dem ein div als Kind hinzugefügt wird.

**Comment by JirkaDellOro** [comment]
Ist dann wohl exakt das, was ich in der Vorlesung beschrieben habe. Der Browser ist gerade noch dabei, den Head in seinem DOM zusammen zu bauen und es gibt noch keinen Body...

**Comment by dangscha** [comment]
Problem gelöst, danke
