### ISSUE TITLE
Übersetzung von ts auf js funktioniert nicht

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#21]
Eclipse übersetzt keine Typescript dokumente in Javascript und erstellt auch keine neuen, bei erstellung eines neuen Ts dokuments. Habe bereits neu En/Disabelt. Das gesamte Projekt cleanen geht leider nicht. Jemand ne Idee wie ich das wieder zum Laufen kriege?

**Comment by NadiaCredidio** [comment]
Ich hab das Problem total oft ^^' es kann sein, dass du einen Fehler in der TS hast und es damit nicht zu einer Erneuerung/Erstellung der JS kommt =)

**Comment by aliciaburger** [comment]
Ja das dachte ich auch aber das ist es nicht, wenn ich eine neue ts datei erstelle, wird die js datei garnicht erst erstellt.

**Comment by NadiaCredidio** [comment]
Hmm..ich stell dann immer die Map file aus und an, und meist klappt es dann =)

**Comment by aliciaburger** [comment]
okay und wie mache ich das?

**Comment by NadiaCredidio** [comment]
Unter dem compiler, einfach kurz haken raus und wieder rein, apply und müsste passen?

**Comment by aliciaburger** [comment]
Nein das wars leider auch nicht :/ 
Danke dir aber trotzdem für deine Hilfe!

**Comment by JirkaDellOro** [comment]
Der Fehler muss nicht unbedingt in der neuen Datei sein, sondern irgendwo anders im Projekt. Daher im Problems-View nachschauen und alle Fehler und Warnung ausräumen.

**Comment by aliciaburger** [comment]
In den anderen Projekten funktioniert es leider auch nicht , und dort sind weder Fehler noch Warnungen. 
Ich glaube auch dass der Linter nicht richtig arbeitet. er zeigt mir Fehler an, wo keine sind. (zb Missing Whitespace obwohl da platz ist.)

**Comment by JirkaDellOro** [comment]
Autoformat durchgeführt? Außerdem mal einen Clean durchführen, bitte. 

Project -> Clean -> Clean all projects

 

 

 

Von: aliciaburger [mailto:notifications@github.com] 
Gesendet: Sonntag, 7. Mai 2017 17:47
An: JirkaDellOro/EIA2
Cc: JirkaDellOro; Comment
Betreff: Re: [JirkaDellOro/EIA2] Übersetzung von ts auf js funktioniert nicht (#21)

 

In den anderen Projekten funktioniert es leider auch nicht , und dort sind weder Fehler noch Warnungen.
Ich glaube auch dass der Linter nicht richtig arbeitet. er zeigt mir Fehler an, wo keine sind. (zb Missing Whitespace obwohl da platz ist.)

**Comment by aliciaburger** [comment]
Ja Autoformat ist drin, einen clean kann ich nicht machen(grau hinterlegt)

**Comment by JirkaDellOro** [comment]
Haben Sie Skype? Dann könnten wir mal eine Bildschirmübertragung machen.

**Comment by JirkaDellOro** [comment]
Teamviewer geht auch

**Comment by aliciaburger** [comment]
ja mein skype name ist lissl.burger
