### ISSUE TITLE
EIA2 Tutorium?

### ISSUE THREAD

**Issue by AleaFlesch** [JirkaDellOro/EIA2#210]
Letztes Jahr gab es ein Tutorium, gibt es das dieses Jahr auch?
Und wenn ja wann & wo?

**Comment by JirkaDellOro** [comment]
Hallo Alea,

 

schön, das ihr beginnt danach zu fragen. Wenn ausreichend Bedarf besteht, werden wir versuchen ein Tutorium einzurichten. Dazu sollten Sie dann versuchen einen der studentischen Betreuer zu gewinnen. Wenn die zu sehr ausgelastet sind, gibt es noch ein paar Namen, die ich in die Runde werfen könnte…

 

Von: AleaFlesch [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Oktober 2018 19:46
An: JirkaDellOro/EIA2
Cc: Subscribed
Betreff: [JirkaDellOro/EIA2] EIA2 Tutorium? (#210)

 

Letztes Jahr gab es ein Tutorium, gibt es das dieses Jahr auch?
Und wenn ja wann & wo?

**Comment by AleaFlesch** [comment]
Hallo Herr Dell Oro,

alles klar vielen Dank! Dann gebe ich das mal weiter.
Es finden sich bestimmt ein paar.

Grüße und bis nächste Woche
Alea



Am 18.10.18 um 20:52 schrieb JirkaDellOro
