### ISSUE TITLE
UNO -Bato

### ISSUE THREAD

**Issue by BatoKotur** [JirkaDellOro/EIA2#211]
Hallo, 

ich habe bei der neusten Aufgabe keine Ahnung mit was ich anfangen soll und bin etwas überfordert. Ich hoffe mir kann jemand helfen den Anfang der Aufgabe zu programmieren.

**Comment by NicoKlein97** [comment]
Deinem Aktivitätsdiagramm zu folge planst du zu aller erst einige Arrays anzulegen. Bereitet dir das Probleme ?
Als zweites sieht es so aus, als würdest du einen zufälligen Zahlenwert erstellen zu wollen. Wie in der Aufgabenstellung angemerkt, ist Math.random() hierfür gut geeignet.
Gehe diese Parts einfach Schritt für Schritt durch und versuche vielleicht zuerst dein Aktivitätsdiagramm weiter auszubauen. Momentan erscheint mir dieses noch sehr grob, was ein Grund für deine Unsicherheit sein könnte.
