### ISSUE TITLE
UNO placeDiv Frage

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#213]
Hallo ich komme nicht weiter bei der placeDiv function der Rest vom Code sollte stimmen 

   function placeDiv(l: number): void {
        let div: HTMLDivElement = document.createElement("div");
        document.body.appendChild(div);
       div.setAttribute(allCards[l].name, allCards[l].color);                       // was kommt hie rein

        document.getElementById(allCards[l].name).innerHTML += allCards[l].name;  // was kommt hier rein
        let s: CSSStyleDeclaration = div.style;
        s.border = "thin solid black";
        s.textAlign = "center";
        s.position = "absolute";
        s.backgroundColor = allCards[l].color;
        s.width = 55 + "px";
        s.height = 120 + "px";
        s.left = (a + 0.5) * 100 + "px"; // a = zählt hoch in main um die div zu verschieben 
        s.bottom = 40 + "px";
        s.borderRadius = 5 + "px";

// l (klein L) ist die randomNumber die sich die Informationen, zur Hintergrundfarbe und Name der Karte, aus einem Array und dem dazu gehörigen Interface holt. 

mfg 
Tom

**Comment by JirkaDellOro** [comment]
Ich finde leider kein richtiges Konzept in Ihrem Repository und kann daher nicht nachvollziehen, was Sie vorhaben... :-(

Grundsätzlich würde ich nicht die placeDiv-Funktion aus der letzten Aufgabe nutzen. Die habe ich nur aus didaktischen Gründen gebastelt. Tatsächlich haben wir doch CSS zur Verfügung und die Formatierung ist besser mit Hilfe einer entsprechenden Stylesheet-Datei gemacht. Dort erwartet man so etwas. Außerdem sollte eine solche Funktion dann konkreter insertHandCardToDom oder so heißen.

Ganz konkret zum Code: getElementById sollte fehlschlagen, da dem neu erzeugten div keine id zugewiesen wurde. Der Aufruf ist zudem überflüssig, den div ist doch bekannt, da gerade erzeugt...

**Comment by NicoKlein97** [comment]
Zusätzlich: Ich sehe jetzt nicht was dieser Wert genau aussagt, aber vom Namen her schätze ich, dass bei der Verwendung von setAttribut ein Fehler vorliegt. Der erste Parameter in der Klammer sollte das zu ändernde Attribut sein (in deinem Fall würde ich mal schätzen, dass es sich um die Hintergrundfarbe handelt). Am besten mal schnell in die API von setAttribut reinschauen um die Syntax zu checken.

**Comment by JirkaDellOro** [comment]
Tatsächlich würde setAttribute auch so funktionieren, sofern `allCards[l].name` existiert und vom Typ String ist (sonst würde TypeScript bereits meckern). Es würde dann ein neues Attribut mit eben diesem Namen erschaffen. Es ist allerdings zweifelhaft, ob das beabsichtigt ist.

Ohne Konzept ist das nicht zu beurteilen und daher auch nur eingeschränkt Hilfe möglich!
