### ISSUE TITLE
Ich finde meinen Fehler nicht

### ISSUE THREAD

**Issue by LuisaCarmen** [JirkaDellOro/EIA2#215]
Hallo, ich sitze nun schon ewig an meinem Code und finde meinen Fehler nicht. Bei den Zeilen 229, 240, 254 265 und 274 zeigt es mir an "Argument of type string is not assignable to Parameter of type number". Ist sicher nur ein Leichtsinnsfehler doch ich finde es einfach nicht.

**Comment by LuisaCarmen** [comment]
danke!!

**Comment by JirkaDellOro** [comment]
Nachtrag: bitte unbedingt den CodingStyle (siehe Mindmap) beachten
