### ISSUE TITLE
Auslesen von mehrdimensionalem Array

### ISSUE THREAD

**Issue by JannisBackhaus** [JirkaDellOro/EIA2#216]
Hallo zusammen, 
ich habe ein kleines Problem beim Zugriff auf mein zweidimensionales Array.
Mein Array "deck" ist folgendermaßen deklariert:

let deck: number[][] = [];

Ich habe mithilfe mehrerer Schleifen Werte hinzugefügt, und möchte jetzt die zwei einzelnen Werte, jeweils pro Array-Platz auslesen und in eine Variable c einsetzen.
Nach langem Herumgooglen bin ich auf folgende Lösung gestoßen:

let c: number = (deck[a][0]);                 // a soll in diesem Fall die zufallsgenerierte Nummer sein

Das Problem ist allerdings, dass _console.log(c)_ bei dieser Schreibweise **nicht** den 0-ten Array-Wert des deck-Array-Platzes a auswirft, sondern jedes Mal einfach die 0.

Was wäre die richtige Schreibweise um mein Problem zu lösen? Ich komme bei Google auf keine anderen Lösungen...
Hier befindet sich mein vollständiger Code: https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2002/test2.ts
Danke im Vorraus für die Hilfe!

**Comment by JirkaDellOro** [comment]
Syntaktisch scheint das korrekt zu sein. Ich habe in den Code geschaut und fürchte, hier gibt es einige konzeptionelle Schwächen. Das größte Problem: es gibt kein Konzept. Bitte erst einmal das posten, dann können wir zielführend helfen.

**Comment by JannisBackhaus** [comment]
Hier der Link zum Konzept. Ich hoffe es hilft bei der Übersicht. Die Website und Ausgabe an sich funktioniert, nur werden eben immer die gleichen Karten ausgegeben, da der Array Zugriff nicht funktioniert. https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2002/konzept%20jannis.pdf

**Comment by JirkaDellOro** [comment]
Zunächst ist es schön zu sehen, dass bei der Konzeptarbeit aufgefallen ist, dass der switch ein unpassendes Konstrukt ist. Den hätten Sie wahrscheinlich nicht gebaut, wenn Sie zuerst konzipiert hätten. Ich schaue mir jetzt den Code genauer an.

**Comment by JannisBackhaus** [comment]
Vielen Dank für die Antwort, ich habe die if/else-Verzweigung durch einen switch ausgetauscht, und jetzt läuft der Code. Ich bin mir allerdings nicht sicher welchen switch Sie meinen. Mein Code ist durch mehrere switches aufgebaut und funktioniert jetzt.

> 
> 
> Zunächst ist es schön zu sehen, dass bei der Konzeptarbeit aufgefallen ist, dass der switch ein unpassendes Konstrukt ist. Den hätten Sie wahrscheinlich nicht gebaut, wenn Sie zuerst konzipiert hätten. Ich schaue mir jetzt den Code genauer an.

**Comment by JannisBackhaus** [comment]
Den eigentlich Fehler konnte ich beheben, ich habe auch meinen Code mit dem kürzeren Konzept verbessert. Dankeschön!

**Comment by JirkaDellOro** [comment]
Ähm... was war den nun der eigentliche Fehler und was die Lösung des Problems?

**Comment by JannisBackhaus** [comment]
Die ursprüngliche if/else-Verzweigung war fehlerhaft und außerdem für den Zweck den ich im Sinn hat nicht passend. Ich habe sie einfach durch einen funktionierenden switch ausgetauscht.
