### ISSUE TITLE
Uncaught TypeError 

### ISSUE THREAD

**Issue by Cryray** [JirkaDellOro/EIA2#217]
Uncaught TypeError: Cannot read property 'yellow' of undefined
    at HTMLDocument.main (uno.ts:121)
Das ist der Fehler den ich bekomme. Meine anderen Farbwerte nimmt er aber bei "yellow" gibt mir die Konsole den oben genannten Error aus.
Danke für die Hilfe

**Comment by JirkaDellOro** [comment]
Hallo Leon,

hier gibt es mehrere Probleme. Das Schlimmste ist, dass Sie verbotenerweise den Typ any eingesetzt haben. Ich vermute, um eine Compilerwarnung zu umgehen. Damit teilen Sie dem Compiler mit: "Sei still, ich weiß genau was ich tue". Damit haben Sie Ihre erste und wichtigste Hilfestellung abgeschaltet. Der andere Punkt ist, dass man aus Ihrem Konzept noch immer nicht herauslesen kann, was Sie vorhaben. Daher ist es auch uns kaum möglich eine zielführende Hilfestellung zu leisten.

Sie müssen die Hilfe auch möglich machen...

**Comment by Cryray** [comment]
Das Problem, dass ich habe ist folgendes:
Ich erstelle ein Array mit dem Typ Number und weise ihm alle grünen Karten zu.
Nun erstelle ich ein zweites übergeordnetes Array und will diesem das Array mit den grünen Karten zuweisen. Hier bekomme ich schon den Fehler da er mir sagt : Type Number[] is not assignable to Type Number
Ich weiß in der Theorie was das heißt, weiß aber nicht welchen Typ das übergeordnete Array besitzen soll.
Danke schonmal für die Schnelle Antwort.

**Comment by Cryray** [comment]
Problem konnte vorerst gelöst werden.

**Comment by JirkaDellOro** [comment]
Wie die Fehlermeldung es beschreibt: es wird versucht ein Array von Zahlen in ein Array von Zahlen zu stopfen. Solch ein Array erwartet aber, mit Zahlen gefüttert zu werden, nicht mit Arrays von Zahlen. Es ist, als wollten Sie eine ganze Kleiderkommode in Ihre Sockenschublade stopfen.

Bitte trotzdem zuerst das Konzept erstellen, dann umsetzen. Sie stehen jetzt auf der Baustelle mit Werkzeug und Material, es gibt aber keinen Plan was damit zu tun ist.
