### ISSUE TITLE
get elemnt by id 

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#218]
wenn ich meine div id mit document.getElementbyId aufrufen möchte sagt mir der linter Proberty 'getElementbyId' does not exist on type 'Document'. Was kann ich hier machen?

**Comment by lindschoki** [comment]
Habe es auch gerade gemerkt...

**Comment by JirkaDellOro** [comment]
Wenn’s gelöst ist, bitte Issue schließen

 

Von: lindschoki [mailto:notifications@github.com] 
Gesendet: Sonntag, 21. Oktober 2018 15:36
An: JirkaDellOro/EIA2
Cc: JirkaDellOro; Comment
Betreff: Re: [JirkaDellOro/EIA2] get elemnt by id (#218)

 

Habe es auch gerade gemerkt...

**Comment by R4Pi3R** [comment]
Da der Fehler erkannt und eleminiert würde,
Bitte den Issue schließen.
