### ISSUE TITLE
Karten Name im Div

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#219]
Hallo ich habe die Div-Elemente erstellt. Leider weiß nicht wie ich den Namen/Bezeichnung auf der Karte erscheinen lassen kann. Danke schon einmal vorab :)

**Comment by JirkaDellOro** [comment]
OK, das neue Konzept ergibt jetzt Sinn und erscheint zielführend. Da hilft man gern.

Ich würde div.innerText nehmen...

**Comment by R4Pi3R** [comment]
Einen Großteil hast du bereits erledigt.
Deine placeDiv Funktion werden Farbe und Wert der jeweiligen Karte übergeben.
Beim Erstellen veränderst du den Style des erstellten Div-Elements.
Im Selben Zug kannst du mit einem anderen Befehl den Inhalt verändern. Ich würde dir für das Element ".innerText" oder ".innerHTML" empfehlen.

**Comment by JirkaDellOro** [comment]
Ich war schneller, Jascha!

@haasmanu : Bezüglich des Aufbaus des Kartendecks bitte https://github.com/JirkaDellOro/EIA2/issues/214#issuecomment-431647374 beachten

**Comment by haasmanu** [comment]
Okay danke für den Hinweis :)

**Comment by haasmanu** [comment]
Ich habe es versucht aber kam Leider nicht auf die Lösung, dass die Werte mir auf der Karte angezeigt werden :(

**Comment by JirkaDellOro** [comment]
Das erstaunt mich, denn in Zeile 702 und 721 sind doch auch bereits Textinhalte definiert worden

**Comment by haasmanu** [comment]
Ja das stimmt es geht eher darum, dass ich keinen Weg gefunden hab das Array: STAPEL[i].wert an dieser Stelle richtig einzubinden. Ich versuche es weiter...auch wenn die Abgabefrist schon vorbei ist, diesen Fehler zu beheben.

**Comment by JirkaDellOro** [comment]
So wie Jascha es vorgeschlagen hat, sollte es gehen. Einfach mit
`element.innerText = _wert;`

Übrigens bereites es physischen Schmerz so etwas wie STAPEL zu lesen. Bitte den CodingStyle beachten!

**Comment by R4Pi3R** [comment]
> Übrigens bereitet es physischen Schmerz so etwas wie STAPEL zu lesen. Bitte den CodingStyle beachten!

Das liegt am Linter! Der hat im Praktikum eine Warnung geworfen "variable declaration should be in upper case" und hat keine Ruhe gegeben, bis nicht der gesamte Variablenname Großgeschrieben war

**Comment by JirkaDellOro** [comment]
Dann bitte die Installation und die tslint.json kontrollieren. Ich hatte die Konfiguration anders geschrieben.
