### ISSUE TITLE
Klickfunktion will nicht funktionieren=)

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#22]
Ich bekomme nun keinen einzigen Error, doch die Klickfunktion will nicht funktionieren.
Wenn ich sie umschreibe, löscht sie alle vorhandenen Bienen und ersetzt diese mit einer.

Was ist das Problem?

Danke für die Hilfe !

**Comment by moritzhfu** [comment]
In Zeile 175 rufst du die Funktion biene immer wieder mit der gleichen Biene (b aus Zeile 18) auf. Hier musst du das Array bees iterieren.

**Comment by moritzhfu** [comment]
Habe dir einen Pullrequest geschickt.
