### ISSUE TITLE
Hochladen nicht möglich

### ISSUE THREAD

**Issue by SinaSchwambach** [JirkaDellOro/EIA2#220]
Meine TypescriptDatei wird nicht automatisch in eine JavascriptDatei umgewandelt, woran könnte das liegen? 
Auch ist es mir nicht möglich meine Html-Datei, obwohl sie auf meinem Repository ist, aufzurufen um sie zu verlinken.

**Comment by R4Pi3R** [comment]
https://sinaschwambach.github.io/EIA2/Aufgabe%202/uno.html
unter diesem Link kann ich die Seite aufrufen. Für Datei und Ordnernamen gilt das selbe wie für Variablen und Funktionen: Keine Leerzeichen und keine Sonderzeichen verwenden!
Dass die Datei nicht übersetzt wird heißt, dass irgendwo noch ein Fehler drin steck, entweder in deinem Code, oder in den Typescripteinstellungen von Eclipse.
Schau nach, ob du noch Fehler und/oder Warnungen in deinem Code hast und beseitige diese.
Wenn Eclipse keine (mehr) anzeigt und es trotzdem nicht funktioniert, dann schau bitte ob der Typescript Builder aktiviert (enabled) ist.
Falls auch das der Fall ist, schau in der Mindmap wo die Compiler Einstellungen für den Typescript Builder zu finden sind und prüfe, ob die Einstellungen mit denen in der Anleitung übereinstimmen

**Comment by JirkaDellOro** [comment]
Was auch helfen kann: Project -> Clean

**Comment by SinaSchwambach** [comment]
Vielen Dank schonmal, habe noch Fehler in meiner Tyoescript Datei bei denen ich aber allein nicht auf die Lösung komme..

**Comment by JirkaDellOro** [comment]
Dann den Code hochladen und uns hier die Zeilennummer und die Fehlerbeschreibung von Eclipse posten

**Comment by SinaSchwambach** [comment]
[namespace UNO.pdf](https://github.com/JirkaDellOro/EIA2/files/2499378/namespace.UNO.pdf)

an den letzten beiden Zeilen hapert es, da kommt dann "Multiple markers at this line
- Declaration or statement expected.
- ',' expected.
- 1 changed line"
diese Fehlermeldung

**Comment by JirkaDellOro** [comment]
Einfacher ist es, wenn Sie den Code hochladen und die Zeilennummer angeben.

Die letzten beiden Zeilen enthalten nur Klammern. Wenn der Code im PDF zuvor autoformatiert war, scheint es so, dass eine geschweifte Klammer zuviel da ist.

**Comment by NicoKlein97** [comment]
Wenn ich mich nicht täusche, wird die Runde Klammer in Zeile 39 genau vor 'DOMContentLoaded' nicht geschlossen. Check das mal nach.

**Comment by SinaSchwambach** [comment]
ja das stimmt aber sobald ich die klammer schließen möchte zeigt es mir einen neuen fehler an

**Comment by JirkaDellOro** [comment]
@Sina: IMMER pushen, damit wir die aktuelle Version sehen können!

**Comment by SinaSchwambach** [comment]
habe ich nun

**Comment by JirkaDellOro** [comment]
Bitte IMMER autoformatieren vor dem Pushen (siehe meine Mail bezüglich der Aktualisierung der Gebote)

**Comment by JirkaDellOro** [comment]
Wenn ich den Code klone werden mir sofort die falschen Zeichen markiert. Ist das bei Ihnen nicht so?

![image](https://user-images.githubusercontent.com/6279994/47271454-eab09400-d579-11e8-82c1-34fd4b9d5d98.png)

**Comment by SinaSchwambach** [comment]
Doch, aber bei manchen kommen jedoch trotzdem noch fehlermeldungen oder die zeichen werden mir als falsch angestrichen aber sobald ich sie entferne heißt es ich solle sie wieder hinzufügen

**Comment by JirkaDellOro** [comment]
Ich gehe davon aus, dass Sie die gleiche Anzeige erhalten. Es sind syntaktische Fehler, die wir aber nicht besprechen müssen, da sie innerhalb von offensichtlichen logisch fehlerhaftem Code auftreten. Es wäre zunächst zu erforschen, was Sie mit folgendem mehrfach vorkommenden Konstrukt erreichen wollen
```
document.addEventListener('DOMContentLoaded', function() {
            document.body.appendChild(div);
```

**Comment by SinaSchwambach** [comment]
das div zu erzeugen, oder benötige ich das DOMContentLoaded nur einmal dafür?

**Comment by JirkaDellOro** [comment]
Eine ereignisgesteuerte Programmierung ist für diese Aufgabe noch nicht erforderlich, bestenfalls für den Aufruf der Hauptfunktion. Wenn es nur darum geht ein div-Element dem Body anzuheften genügt der Aufruf 
```
            document.body.appendChild(div);
````
Erzeugt haben Sie das div bereits mit createElement

**Comment by SinaSchwambach** [comment]
ah okay, vielen Dank!

**Comment by JirkaDellOro** [comment]
Gerne. Wenn man das aufräumt kommt noch weiteres interessantes zu Tage. Es bleibt spannend. Bitte weitere Issues posten wenn's klemmt.

**Comment by JirkaDellOro** [comment]
Und den Schließen, wenn die Frage zufriedenstellend beantwortet wurde
