### ISSUE TITLE
TSLint

### ISSUE THREAD

**Issue by nicoherrmann** [JirkaDellOro/EIA2#221]
Hallo,
ich bekomme es nicht ganz hin, meinen TSLint richtig einzurichten. Soweit ich das verstanden hab muss man die Datei in sein EIA2 Projekt importieren, und danach mit "Configure -> Enable TSLint " aktivieren. Allerdings wird diese Option bei mir nicht angezeigt und ich weiß nicht warum bzw ob ich es von Grund auf falsch angehe. 
![tslint](https://user-images.githubusercontent.com/43846525/47289952-63a4ff80-d5fd-11e8-917c-fa25d50ead9e.png)
Grüße

**Comment by JirkaDellOro** [comment]
ist den der Linter überhaupt installiert? Sieht man unter Help->About Eclipse->Installation Details. Zur Installation siehe Mindmap

**Comment by nicoherrmann** [comment]
Ah ja habe einen Punkt in der Mindmap übersehen, hat jetzt funktioniert.
Danke sehr
