### ISSUE TITLE
Aufgabe bis 25.10 bzw. 28.10.

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/EIA2#223]
Hallo EIA2s,

es gab Fragen bezüglich der aktuellen Aufgabe, es wurde keine formuliert. Ich habe mir lieber noch etwas Gedanken darum gemacht, wie wir weiter verfahren. Sofern ihr den Eindruck habt, die heutige Vorlesung hat euch bezüglich der Herangehensweise an die Problemlösung etwas gebracht, vom richtigen Lesen der Aufgabe, der Anfertigung von hilfreichen Notizen, über die Erstellung einer Screenskizze bis zum ersten groben Aktivitätsdiagramm, würde ich das im Praktikum weiter fortsetzen. Dort sprechen wir über weitere mögliche Strukturen um die Spielkarten zu kodieren und picken uns eine der heute definierten Aktivitäten heraus um sie weiter aufzugliedern. Dann könnt ihr in eure Gruppenräume gehen um mit den Betreuern die Konzepte weiter zu entwickeln.

Damit möchte ich euch die Möglichkeit geben, ein komplettes Redesign zu machen. Auch bei denen, die eine Lösung hinbekommen haben, liegt noch vieles im Argen und alle Lösungen waren noch recht weit weg von optimal. Im besten Falle können wir so auch die ganzen Ampelschaltungen umgehen und ihr entwickelt tatsächlich bis Sonntag eigene gute Lösungen.

Ergibt das für euch Sinn und scheint wünschenswert? Ich freue mich auf Rückmeldung in diesem Issue-Thread

**Comment by dennisbenz** [comment]
Gerne einmal so probieren... dann sieht man ob es etwas bringt.

**Comment by baayzi** [comment]
Ja das wäre Top.

**Comment by haasmanu** [comment]
Wäre ich dafür einfach um einen richtige Code zu haben :)
