### ISSUE TITLE
Karten anzeigen

### ISSUE THREAD

**Issue by SinaSchwambach** [JirkaDellOro/EIA2#224]
Ich habe meinen Code jetzt nocheinmal überarbeitet, jedoch wird mir auf meiner Html Seite immernoch nichts angezeigt. In Eclipse wird mir aber auch kein Fehler mehr angezeigt. Woran könnte das liegen?

**Comment by SinaSchwambach** [comment]
Und das geht nochmal wie? 
Tut mir leid, aber ich stehe gerade etwas auf dem Schlauch..

**Comment by R4Pi3R** [comment]
Das Script sollte einen Eventlistener implementieren der auf DOMContentLoaded wartet und dann eine Funktion aufruft, die den Ablauf des Programms handhabt.
Wie ein Aufruf funktioniert weißt du ja, wenn ich mir deinen Code anschaue, da sich die Funktionen teils gegenseitig aufrufen

**Comment by SinaSchwambach** [comment]
DOMContentLoaded habe ich jetzt hinzugefügt aber die Karten werden immernoch nicht angezeigt

**Comment by JirkaDellOro** [comment]
Hallo Sina,

der Eventlistener ruft die Main-Funktion auf. Aber was genau macht die? Geh' bitte mal Zeilenweise durch und beschreibe kurz, was passieren soll.

**Comment by JirkaDellOro** [comment]
... und lass' bitte unbedingt die Formatierung drüber laufen

**Comment by SinaSchwambach** [comment]
In Zeile 1 wird die namespace festgelegt
Zeile 3-7 legt das interface fest
Zeile 11-15 dient dazu das array zu gestalten
Zeile 19- 26 ist die main funktion, diese gibt mir meine, durch den Spieler eingegebene, Handkartenzahl als string an, wandelt diese in eine number um und ruft die Karteniehen funktion auf
    function main(): void {
        let numofcards: string = prompt("Wie viele Karten möchtest du?");

        let node: HTMLElement = document.getElementById("hand");
        let innerHTML: string;
        let numcards = +numofcards
        kartenziehen(numcards)
    }
Zeile 28-33 dient dazu das Kartendeck darzustellen solange i kleiner ist als das Kartenarry, jedoch muss ich zugeben, dass ich gerade slebst nicht genau weiß wie ich auf i gekommen bin 
   
 function Kartendeckerstellen(_card: Deck[]): void {

        for (let i: number = 0; i < _card.length; i++) {
            let deck: HTMLElement = document.getElementById("Ziehstapel")
        }
    }
Zeile 35-43 ist dafür zuständig eine zufällige Zahl auszuwählen und diese Zahl dann aus dem array zu ziehen und die zuständige arrayplatzierung zu löschen, anschließend ruft sie die funktion handkarten darstellen auf und gibt ihr die zufällig gezogene array platzierung aus 

 function kartenziehen(_numcards: number): void {
        for (let x: number = 0; x < _numcards; x++) {
            let random: number = Math.floor(Math.random() * cards.length);
            let getcard: Deck = cards.splice(random)[1];
            Handkartendarstellen(getcard);

        }

    }

Zeile 46-53 die funktion ist dafür zuständig die zufällig gezogene Karte am div hand anzuhängen, mit den jeweiligen vom array vorgegebenen eigenschaften 

  function Handkartendarstellen(_getcard: Deck): void {
        let hands: HTMLElement = document.getElementById("hand");
        let span: HTMLSpanElement = document.createElement("span");
        document.appendChild(span)
    }

Zeile 54 sorgt dafür, dass die funktion main ausgeführt wird sobald DOM geladen ist 
document.addEventListener('DOMContentLoaded', main);


Mich wundert jedoch, dass nichtmal die im Html festgelegten Divs mit zugehörigen CSS eigeneschaften dargestellt werden

**Comment by JirkaDellOro** [comment]
Zeile 25 war gestern noch nicht da. Du hast also schon erkannt, dass deine Main-Function keine der anderen Funktionen mehr aufgerufen hat und damit dein Programm fehlerfrei durchgelaufen ist und schlicht fertig war.

Hast Du jetzt einmal die Entwicklerkonsole geöffnet und geschaut, ob da eine Laufzeit-Fehlermeldung auf dich wartet? 

Tipp: document mag nicht so viele Kinder haben...

**Comment by SinaSchwambach** [comment]
ja, das ist mir beim erneuten durchgehen aufgefallen..

die Konsole zeigt mir die Fehlermeldung an:  HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy

Wie kann ich es denn umgehen, so oft document. ... zu benutzen? weil ich muss ja auf auf die Id der divs im Html dokument zugreifen, was doch nur mit document.getElementbyId geht oder? auch das anhängen der Handkarten an das div hand weiß ich nicht wie ich das anders regeln sollte..

**Comment by JirkaDellOro** [comment]
Du musst appendChild an dem Element aufrufen, an welches Du anhängen willst.
z.B. `document.body.appendChild(...)` oder `div.appendChild(...)`
in letzterem Fall musst Du das div natürlich erst kennen, also entweder erzeugt haben oder aus dem DOM herausgefischt haben (z.B. mit getElementBy...)

**Comment by JirkaDellOro** [comment]
Ich bin jetzt weg, jemand anderes übernimmt bitte.

**Comment by SinaSchwambach** [comment]
okay also ich bin jetzt soweit, dass mir meine gewünschte Anzahl an Karten als schwarze Striche in der oberen linken Ecke angezeigt werden. Obwohl ich schon eine Css-Datei hinzugefügt habe. Auch weis ich noch nicht wie ich den Karten den gewünschten Wert übergeben kann.

**Comment by JirkaDellOro** [comment]
https://sinaschwambach.github.io/EIA2/Aufgabe%202/uno.html

**Comment by SinaSchwambach** [comment]
hatte versucht, irgendwie auf eine lösung zu kommen und dabei sachen abgeändert aber vergessen sie zurück zu setzten als es nicht funktioniert hat. Jetzt müssten Sie die schwarzen striche sehen können.

**Comment by NicoKlein97** [comment]
Woran genau hängt es jetzt an der Stelle ? Das erstellen der Striche gelingt dir ja schonmal, jetzt kannst du beginnen anstelle von Span-Elementen Divs zu erzeugen und diese durch Zuweisung  einer Klasse danach mit CSS stylen. Gibt es bei diesem Schritt Probleme ?

**Comment by JirkaDellOro** [comment]
Striche sind da und Fehler ist weg. Man kann auch bei den spans bleiben, das sind standardmäßig inline-elemente und passen also prinzipiell besser. Stell' dafür in CSS einmal 
`display: inline-block`
ein

**Comment by JirkaDellOro** [comment]
Ansonsten müsstest Du im Code den spans einfach noch einen innerText und einen className spendieren (oder zwei, je nachdem wie die Kartenfarbe geregelt werden soll)

**Comment by SinaSchwambach** [comment]
ja aber genau da hängt es, da ich nicht weis wie ich das machen soll... habe schon mehrere verianten versucht wie ich das innerHtml einbinden soll aber irgendwie hat es nie funktioniert

**Comment by NicoKlein97** [comment]
Mit span.innerHTML und setAttribute solltest du diese zwei Probleme eigentlich lösen können. Habe es selbst mit deinem Code ausprobiert und es funktioniert.
Am besten nochmal die zwei Sachen nachschlagen und bei Problemen nochmal bescheid sagen.

**Comment by SinaSchwambach** [comment]
also warum css nicht funktioniert hat habe ich jetzt herausgefunden.. 
sobald ich innerText verwende erscheint nur noch eine Karte und die ist immernoch ohne jegliche beschriftung..

**Comment by JirkaDellOro** [comment]
Das liegt daran, wie Du splice verwendet hast. Schau dir dessen Parameter an. Im Augenblick, schneidest Du alle Karten ab random weg. Warum Du dir aus den rausgeschnittenen Karten dann die  1-te und nicht die 0-te merkst, ist ein weiterer Punkt den Du überdenken solltest. Wozu sollen außerdem die Parameter _getCard und _random deiner Funktion "Handkartendarstellen" gut sein? _getCard nutzt Du gar nicht und mit dem Zufall hast Du dir bereits Karten aus dem Deck gezogen. Daher schlägt auch Zeile 50 fehl, denn die Karte, auf die Du dort zugreifen willst, hast Du vorher weggeschnitten...

**Comment by SinaSchwambach** [comment]
und wie greife ich dann auf die zufällig ausgewählte karte zu?

**Comment by SinaSchwambach** [comment]
hat sich erledigt, hab es herausgefunden

**Comment by SinaSchwambach** [comment]
Die Console zeigt mir jetzt an, dass in Zeile 49 _getcard undefined wäre, aber ich habe sie doch oben in der funktionsklammer dem interface Deck zugeordnet..

**Comment by NicoKlein97** [comment]
Das erste Problem ist, dass du die splice-Funktion nicht richtig nutzt. Die erste Zahl (also random) kannst du so darin stehen lassen, die eckige Klammer dahinter muss jedoch weg, statdessen muss in die runde Klammer noch eine 1 reingepackt werden. Das sieht dann so aus cards.splice(random,1) . Momentan werden deinem Array, mit allen Karten, einfach zu viele Einträge gelöscht, bis am Ende keine mehr übrig sind. Dann versucht der Code nicht existente Karten zu ziehen ----> undefined.

Als zweites hast du dein getcard als Typ Deck deklariert, das ist allerdings nicht richtig.
Es muss der Typ Deck[]. Darauf musst du unbedingt achten, sowas passiert einem schnell mal. Wenn du diese Dinge geändert hast musst du noch ein paar Dinge inder Handkartendarstellung() verändern. Versuch mal ob du das hikriegst, ansonsten wieder melden.

**Comment by SinaSchwambach** [comment]
ich bekomme es nicht hin.. egal was ich schreibe es wird ein fehler angezeigt..

**Comment by JirkaDellOro** [comment]
Es gibt sicher eine Möglichkeit es zu schreiben, so dass es funktioniert. Nico hat sich etwas suboptimal ausgedrückt. Aber auch mit dem was Du jetzt hast müsstest Du schon ganz gut weiter kommen. Probier mal in Zeile 56 und 57 zu schreiben:
```
        span.innerText =  _getcard[0].value;
        span.style.backgroundColor =  _getcard[0].color;
```
Wahrscheinlich wirst Du dann noch immer nicht ganz am Ziel sein. Ich finde es super, wie Du dich bemühst die Aufgabe selbst zu knacken. Deswegen möchte ich dir ein Angebot machen, damit Du dir keinen Frust holst. Wir geben dir Aufschub, Du kommst am Montagmorgen in meine Sprechstunde und wir finalisieren das zusammen. Da gibt es noch ein paar Sachen, die ich dir gerne erklären möchte. Oder Du machst es während des Vormittags mit Anna, sofern die Zeit hat.

**Comment by SinaSchwambach** [comment]
dann komme ich morgen früh in ihre sprechstunde.. danke schonmal für die hilfe... 
soll ich das issue dann jetzt schließen?

**Comment by JirkaDellOro** [comment]
Nein, lass' offen. Schließe ihn, wenn alles klar ist.

**Comment by SinaSchwambach** [comment]
habe noch eine Frage zu der funktion die meine Karte in das neue array pushen soll, ich weiß nicht ganz wie ich das geregelt bekomme..

**Comment by R4Pi3R** [comment]
Hast du den Aktuellen Code hochgeladen?
Welche Funktion meinst du genau?

**Comment by SinaSchwambach** [comment]
ja der aktuelle Code ist hochgeladen, ich sollte eine Funktion erstellen, die meine gezogenen Karten in ein neues Array pusht jedoch weiß ich nicht genau an welcher stelle ich die platzieren soll, und was genau ich in die klammer hinter hand.push schreiben soll

**Comment by R4Pi3R** [comment]
So wie es gerade in deinem Code ist wird jedes mal eine einzelne Karte gezogen, in das Hand-Array gesteckt und dann gemalt, dann die nächste usw.
Wenn du den Vorgang nun trennen möchtest, was durchaus Sinn ergibt, dann ließe sich das am besten so lösen, dass du nicht immer "eine ziehst, eine malst, eine ziehst, eine malst, ..." , sondern zuerst alle karten ziehst und in das Hand-Array pushst und danach alle Karten aus dem Hand-Array malen lässt.
So wie machen wir das am geschicktesten?
Hast du eine Idee? (Als Tipp: Auch ein Array lässt sich als Parameter an eine Funktion übergeben ;) )

**Comment by SinaSchwambach** [comment]
habe jetzt mein hand array als parameter übergeben und eine for-schleife gebaut, die mir jeweils meine karten aus dem array hintereinander darstellen soll. jetzt zeigt es mir jedoch an, dass die zählvariable o nicht gefunden werden kann obwohl ich die doch in meiner for-schleife deglariert hab

**Comment by Plagiatus** [comment]
wenn du mal den autoformatierer anschmeißt, dann merkst du dass es nicht richtig eingerückt wird. das liegt daran, dass du hinter deinem schleifenkopf ein `;` und dann erst die `{` hast. dadurch wird die schleife direkt beendet und der rumpf hat nichts mehr mit der schleife zu tun. und darum kennt der rumpf dann natürlich o auch nicht mehr.

**Comment by R4Pi3R** [comment]
Wenn ich mir das grad anschaue sieht das doch jetzt richtig gut aus

**Comment by SinaSchwambach** [comment]
okay das funktioniert jetzt, aber warum macht es mir jetzt weiße Schrift bei grün und gelb obwohl ich doch eigentlich deklariert habe, dass die schriftfarbe nur bei blauen und schwarzen karten weiß sein soll?

**Comment by SinaSchwambach** [comment]
bzw bei den schwarzen karten wird keine schrift mehr angezeigt

**Comment by moritzhfu** [comment]
```
if (hand[o].color == "#000000") {
    span.style.color = "white";
}

if (hand[o].color == "#0000ff") {
    span.style.color = "white";
}
else {
    span.style.color = "black"; 
}
```

Bitte hier einmal den Ablauf nachvollziehen. Nimm mal an, dass in `hand[o].color` `"#000000"` steht.
Dann gehe Zeile für Zeile des obigen Codes durch und überlege dir was am Ende in span.style.color steht.

**Comment by SinaSchwambach** [comment]
heißt das, dadurch, dass ich die festlegung für die blaue karte nach der der schwarzen karte habe, dass erst geguckt wird, ob die karte schwarz ist, anschließend aber ob sie blau ist und dann der fall else greift? 
war jetzt bisschen wirr ausgedrückt aber ich hoffe es war trotzdem irgendwie verständlich

**Comment by AnnaLotz** [comment]
Schau' dir am besten nochmal genau an, wie eine if/else Abfrage syntaktisch geschrieben wird, vllt fällt dir dann dein Fehler auf

**Comment by SinaSchwambach** [comment]
hat funktioniert, danke!

**Comment by JirkaDellOro** [comment]
Lade es bitte nochmal hoch, ich möchte mir deine Lösung gerne anschauen

**Comment by SinaSchwambach** [comment]
habe es jetzt hochgeladen, ich glaube jetzt funktioniert es

**Comment by JirkaDellOro** [comment]
Gut so. Noch etwas simpler wäre

```
span.style.color = "black";
if (hand[o].color == "#000000" || hand[o].color == "#0000ff")
    span.style.color = "white";
```
Hier sieht man gleich, dass die Standardfarbe Schwarz ist und nur in den beiden Ausnahmefällen mit weiß überschrieben wird.

**Comment by SinaSchwambach** [comment]
habe es geändert
