### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by Eleonora2709** [JirkaDellOro/EIA2#226]
Ich verstehe nicht, woher die Fehlermeldungen in meinem Code kommen. 
Außerdem komme ich nicht mehr weiter:

namespace uno {
    
    function main(){
        let x : number;
        let y : string = prompt ("Wie viele Karten möchtest du haben?");
        x = Number(y);
    }    
    interface Card {
        color: string;
        value: string;
    }
    let deck: Card[];
    let handcards:Card[];    
    let colors : string []= ["red", "green", "blue", "yellow"];
    let values : string[]=["0","1","2","3","4","5","6","7","8","9","+2","X","<=>"];
    
    for (let i:number =0; i<colors.length;i++){
        for (let a : number=0; a<values.length; a++){
            for (let z : number =0; z<2; z++){
                let card : Card = {color=colors[i],value=values[a]};
                deck.push(card); 
                }
            }

        function random():void {
        var random=math.floor(math.random()*deck.length);
        for (var l=0; l<deck.length;l++)
        if (card[l].position==random)
}
    }

**Comment by Plagiatus** [comment]
was denn für Fehlermeldungen? so ganz ohne hinweis darauf WELCHE fehlermeldungen du hast ist es etwas schwer dir zu helfen.

das einzige was ich bis jetzt sehe ist, dass deine random funktion innerhalb der colors.length for schleife ist, dass hinter der deck.length for schleife keine geschweifte klammer ist und dass nach der if es nicht weitergeht.

**Comment by JirkaDellOro** [comment]
Sang- und klanglos geschlossen? Was war das Problem, was Lösung, Eleonora? Bitte kurz beschreiben
