### ISSUE TITLE
Canvas Probleme

### ISSUE THREAD

**Issue by obiwan1337** [JirkaDellOro/EIA2#227]
Die Karten als Canvas implementieren und dann als child von einem existierenden Div setzen ist nicht ganz klar.
Auch ein Bild in einem Canvas laden funktioniert noch nicht.

**Comment by moritzhfu** [comment]
> Die Karten als Canvas implementieren

> Bild in einem Canvas

Warum der Weg über den Canvas? Das ist in der Aufgabenstellung doch gar nicht gefordert und ist in diesem Falle unnötig schwer.

Da die Aufgabe DynHTML lautet würde ich es auch als dynamisches HTML implementieren.

Du kannst natürlich den Weg über den Canvas gehen, die Mindmap und der [Code](https://github.com/JirkaDellOro/EIA2_S18_Code/tree/master/L09_Canvas) aus den vorangehenden Semestern bietet hier einen Einstieg.

**Comment by Plagiatus** [comment]
nein, du solltest den Weg über den Canvas nicht gehen. Es geht derzeit um das DOM sowie um generierte Webseiten, da wäre es am Thema vorbei, das über den Canvas zu implementieren. das wird dir auch einiges schwieriger machen in der zukunft. deine Karten sollten div elemente sein.

**Comment by obiwan1337** [comment]
Danke für den Hinweis. :) 

> Warum der Weg über den Canvas?
Wollte einfach mal etwas rumprobieren.

> nein, du solltest den Weg über den Canvas nicht gehen.
hab schon mit den Divs angefangen. Dann warte ich mit den Canvas-asugaben. Vielen Dank und ein angenehmes WE.

**Comment by JirkaDellOro** [comment]
Ich hatte Andre ermutigt es auszuprobieren, wenn er das möchte, mit dem Hinweis, dass es deutlich mehr Aufwand ist.

off topic: Hallo @moritzhfu ! Das ist ja schön. dass Du hier reinschaust. Die Studis haben sich ein Tutorium gewünscht, hast Du Langeweile?
