### ISSUE TITLE
Fehler in Browserconsole aber nicht im compiler

### ISSUE THREAD

**Issue by sebifyy** [JirkaDellOro/EIA2#228]
Hallo,

habe ein Problem mit meinem Code, und zwar wird im Browser folgender Fehler Fehler angezeigt:
Uncaught TypeError: Cannot read property 'value' of undefined
In Eclipse wird kein Fehler angezeigt.

` namespace unogame2 {
    interface Card {
        color: string;
        value: string;
    }

    let colors: string[] = ["Red", "Blue", "Yellow", "Green"];
    let values: string[] = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "+2", "X", "RW"];
    var handCards: Card[] = [];
    var deck: Card[] = [];

    for (let i: number = 0; i < colors.length; i++) {
        for (let a: number = 0; a < values.length; a++) {
            for (let z: number = 0; z < 2; z++) {
                var card: Card = { color: colors[i], value: values[i] };
            }
            deck.push(card);
        }
    }

    var userInput: string = prompt("Wie viele Karten sollen ausgeteilt werden?");
    var counter: number = Number(userInput);

    function randomCards(amount: number = counter): void {
        for (let i: number = amount; i > 0; i--) {
            let rCard: number = Math.random() * (deck.length - 1);
            handCards.push(deck[rCard]);
            deck.splice(rCard, 1);
        }
    }

    function displayCards(): void {
        for (let i: number = 0; i < handCards.length; i++) {
            let x: HTMLElement = document.getElementById("HandCards");
            x.innerHTML = handCards[i].value;
        }
    }
    randomCards();
    displayCards();

    console.log(card);
} `

**Comment by Plagiatus** [comment]
in welcher Zeile tritt der Fehler denn auf?
außerdem habe ich mit dem Code den du hochgeladen hast, einen anderen TypeError bekommen.

du versuchst deck[rCard] in das Array zu pushen, aber rCard ist noch eine Kommazahl (z.B. 1.5423).
Schaue mal nach Math.Floor um die Kommas abzuschneiden.

**Comment by saenglert** [comment]
Der Fehler tritt bei folgender Zeile auf:

`x.innerHTML = handCards[i].value;`

Und zwar handelt es sich dabei um einen sog. `Runtime Error` oder Laufzeitfehler. Ein solcher Fehler tritt auf, wenn du während das Programm ausgeführt wird (Runtime) eine Operation durchführst, die während des Compilierens (Compiletime) noch sinnvoll war, es aber nicht mehr ist.

Am konkreten Beispiel:
Deine Variable `handcards` ist ein Array mit Karten. Alle deine Karten haben ein Attribute value, dass du in der betroffenen Zeile abfragst. Das ist eine völlig korrekte Operation zu diesem Zeitpunkt ... vorausgesetzt in dem Array ist, wenn es dann zur Laufzeit aufgerufen wird auch etwas drinn, das abgefragt werden kann. Und da liegt der Hund begraben.

Ich habe dir einen sog. Pull-Request mit ein paar kleineren Änderungen (keine Lösung ;) ) geschickt. Wenn du dein EIA2 Repository aufrufst, findest du bei den Tabs unter dem Namen des Repos den Reiter `Pullrequests`. Da sollte meiner mit dem Titel `Refactoring` auftauchen. Wenn du ihn anklickst kommst du zuerst in die Konversationsansicht. Du siehst dort bereits einige Kommentare die ich zu den Änderungen hinzugefügt habe. Wenn du in den `File Changes` wechselst kannst du dir das etwas übersichtlicher anschauen und mit dem Vergleichen, was ich hinzugefügt/geändert habe (grün = neu, rot = entfernt).

**Comment by sebifyy** [comment]
So ich hab den Fehler behoben mit Math.floor
Jetzt wollte ich schließlich die divs erstellen für die verschiedenen Karten aber es taucht nun ein neuer Runtime Error in Zeile 40 auf

`namespace unogame2 {
    interface Card {
        color: string;
        value: string;
    }

    let colors: string[] = ["Red", "Blue", "Yellow", "Green"];
    let values: string[] = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "+2", "X", "RW"];
    var handCards: Card[] = [];
    var deck: Card[] = [];


    for (let i: number = 0; i < colors.length; i++) {
        for (let a: number = 0; a < values.length; a++) {
            for (let z: number = 0; z < 2; z++) {
                var card: Card = { color: colors[i], value: values[i] };
                deck.push(card);
            }
        }
    }


    var userInput: string = prompt("Wie viele Karten sollen ausgeteilt werden?");
    var counter: number = Number(userInput);

    function randomCards(amount: number = counter): void {
        for (let i: number = amount; i > 0; i--) {
            let rCard: number = Math.floor(Math.random() * (deck.length - 1));
            handCards.push(deck[rCard]);
            deck.splice(rCard, 1);
        }
    }

    function displayCards(): void {
        for (let i: number = 0; i < handCards.length; i++) {
            let x: HTMLElement = document.createElement("div");
            x.innerText = handCards[i].value;
            x.classList.add("card");
            x.classList.add(handCards[i].color);
            document.getElementById("card").appendChild(x);
        }
    }
    randomCards();
    displayCards();

    console.log(card);
}`

**Comment by JirkaDellOro** [comment]
@sebifyy bitte den Issue schließen, wenn das Problem behoben ist. Und in Zukunft für neue Probleme auch neue Issues machen. Außerdem, wie Jascha schon bemerkte, Issues bitte richtig posten!
