### ISSUE TITLE
[Closed] Variable wird nicht von Funktion übernommen

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#229]
Hallo, 
ich habe folgendes Problem:
Die placeSpan function in der main function nutz den Farbwert nicht, laut console.log besitzt sie jedoch einen Farbwert. Gebe ich r, y, etc. anstatt von "color2" in die placeSpan funtion ein bekommen die span Elemente eine Farbe.

 function placeSpan(color3: string, name3: string): void {
        let r = "#ff0000";
        let y = "#ffff00";
        let g = "#00ff00";
        let b = "#0000ff";
        let n = "#000000";
        let span: HTMLSpanElement = document.createElement("span");
        document.body.appendChild(span);
        span.setAttribute("id", "a" + name3);
        document.getElementById("a" + name3).innerHTML += name3;
        let s: CSSStyleDeclaration = span.style;
        s.backgroundColor = color3;
        console.log(name3);

    }

    function main(): void {

        let j: number;
        let i: string = prompt("Wie viele Karten pro Spieler?");
        j = Number(i);

        for (let d: number = 0; j > d; d++) {
            let l: number = random(deck.length);
            let str: string = deck[l];
            let color2: string = str.substring(0, 1);
            console.log(str.substring(0, 1));
            let name2: string = str.substring(1, 6);
            console.log(str.substring(1, 6));

            placeSpan(color2, name2);

            let remove = deck.splice(l - 1, 1);
            let lenght: number = deck.length;
            console.log(lenght);
            continue;

        }

**Comment by R4Pi3R** [comment]
Was mir direkt auffällt ist, das du dich nicht an den Code Styleguide gehalten hast.
Bitte in der Mindmap nochmal nachlesen und nachbessern. Bis das erledigt ist sollte auch irgendwie eine Netzwerkverbindung verfügbar sein, damit der Code gepusht werden kann.
Das Zitat hier ist ungeschickt um Fehler auszumachen und Hilfestellung zu leisten.

**Comment by t0mmy93** [comment]
jo alles klar

**Comment by JirkaDellOro** [comment]
Aber schon mal als Tipp: mit "r", "g", "y" etc als Farbe kann der Browser nichts anfangen. "#ff0000" dagegen kennt er. Man muss aber ja die Farbwerte nicht im Code angeben, CSS ist dafür gemacht.

**Comment by moritzhfu** [comment]
Offtopic (ausnahmsweise hier, das andere Issue wurde inzwischen (vorbildlich) geschlossen):
@JirkaDellOro Leider (zum Glück?) habe ich keine Langeweile, Und absolut keine Zeit für ein Tutorium. 😢 Ich halte aber mal Augen und Ohren offen, vielleicht fällt mir noch eine Kandidatin oder Kandidat ein.

**Comment by t0mmy93** [comment]
Es hat sich erledigt ich habe eine Lösung gefunden. :)

**Comment by JirkaDellOro** [comment]
Was war das Problem, was die Lösung. Bitte kurz beschreiben

**Comment by t0mmy93** [comment]
ich habe die farbcodes in das array geschrieben anstatt r, g, b, y

**Comment by AnnaLotz** [comment]
Wenn das Problem gelöst wurde, bitte den Issue richtig schließen (auf close Issue klicken...) anstatt nur "[closed]" davor zu schreiben

**Comment by t0mmy93** [comment]
closed
