### ISSUE TITLE
Bienen bleiben einfach oben links hängen

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#23]
Seitdem ich 6.1 bearbeite, bleiben die Bienen einfach oben links hängen. Es scheint, wie als würden die da immer wieder neu spawnen ohne Bewegung. Dabei hab ich nichts geändert außer die Arrayverschachtelung zu machen.

https://github.com/MrMarans/EIA2/blob/master/Aufg6/Main.ts

**Comment by JirkaDellOro** [comment]
Was war geschehen?
