### ISSUE TITLE
Prompt funktioniert nicht

### ISSUE THREAD

**Issue by LuisaCarmen** [JirkaDellOro/EIA2#230]
Hallo,

ich habe meinen Code soweit fertig, jedoch funktioniert er nicht ganz...wenn ich die Seite öffne kommt nur das was ich in der HTML und CSS deklariert habe, es scheint so als würde die js/ts Datei nicht übernommen werden...

ich hoffe jemand kann mir helfen, danke schon mal im Voraus.

**Comment by moritzhfu** [comment]
Falls das hier:
https://luisacarmen.github.io/EIA2/Aufgabe%202/Aufgabe2.html
Deine Aufgabe ist, so funktioniert da doch was? 

Was mir jedoch auffällt: Du solltest einmal überprüfen wo dein Funktion "game" beginnt und wo sie aufhört. Funktionen in Funktionen oder Interfaces innerhalb von Funktionen zu erzeugen ist nicht gut!
Ebenfalls gib mal spaßeshalber 20-30 Karten zu Beginn ein und achte auf die Fehlermeldung in der Browserkonsole. Falls du damit nicht weiterkommst einfach nochmal hier nachfrage.

Ansonsten schaut das doch auf den ersten Blick ganz gut aus was hier als Ergebnis rauskommt.

**Comment by LuisaCarmen** [comment]
Das ist die alte Aufgabe, da wir es nochmal ändern mussten, ist das hier meine neue https://luisacarmen.github.io/EIA2/Aufgabe2neu/NeuAufgabe2.html

**Comment by moritzhfu** [comment]
> Uncaught TypeError: Failed to execute 'addEventListener' on 'EventTarget': The callback provided as parameter 2 is not an object.

Ist der Fehler in der Browserkonsole. Ursache (siehe oben):

> Du solltest einmal überprüfen wo dein Funktion "game" beginnt und wo sie aufhört. Funktionen in Funktionen oder Interfaces innerhalb von Funktionen zu erzeugen ist nicht gut!

>

**Comment by JirkaDellOro** [comment]
Möchte ich unterstreichen. Bitte einfach aufräumen. Beispielsweise wird auch erst innerhalb der Funktion game angegeben, dass diese Funktion aufgerufen werden soll, wenn der Dom-Content geladen ist.  Das heißt, game muss zuerst aufgerufen werden, damit der Browser mitbekommt, dass game aufgerufen werden soll. Das funktioniert natürlich nicht, game wird folglich nie aufgerufen.

**Comment by JirkaDellOro** [comment]
wobei... das ist in der js-Datei so, nicht in ts. Das wird wohl nicht mehr kompiliert?

**Comment by Plagiatus** [comment]
Überprüfe nochmal alle deine Einstellungen, kann sein dass es da irgendwo was verstellt hat. wenn da alles passt, lösche einfach Mal die js und die js.map Dateien und speichere die ts Datei nochmal ab, dann sollte es wieder gehen.

**Comment by JirkaDellOro** [comment]
Noch eleganter Project->Clean

**Comment by LuisaCarmen** [comment]
Ich habe nun eine Weile gebraucht um den Fehler zu finden und es hat mir bei dem Absturz wirklich einige Einstellungen geändert. Nun funktioniert wieder alles und die Website wird so angezeigt wie es sein soll. Vielen Dank für die Hilfe, ein schönes Wochenende noch.
