### ISSUE TITLE
Kartenwerte werden nicht angezeigt

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#231]
Hallo habe ein kleines Problem...
nachdem ich meine Einzelkarten nun mit einem CSSStylesheet gestylt habe und in meinem HTML-Dokument drei Spielbereiche definiert habe, bekomme ich es leider nicht hin, dass meine Karten auch Werte anzeigen, sondern nur die Farbe, wie kann ich das ändern?
Danke für die Hilfe :)

**Comment by JirkaDellOro** [comment]
Bitte meine Anweisung zum Posten beachten!

**Comment by JirkaDellOro** [comment]
Ich warte mal ein paar Minuten...

**Comment by lindschoki** [comment]
Fehlt das Konzept / Diagramm für die Funktion?

**Comment by JirkaDellOro** [comment]
Hast Du meine Mail "Richtig Issues posten" nicht erhalten?

**Comment by lindschoki** [comment]
Doch ich hatte nur noch nicht in mein Postfach geschaut.
Hier der Link zu meinem neuen Code:
[https://github.com/lindschoki/EIA2/blob/master/Aufgabe%202/UNO.ts](url) 

Entschuldigen Sie die Umstände

**Comment by JirkaDellOro** [comment]
Der Link zeigt in unser Issue-Verzeichnis. Korrigieren und auch den Link zu pages posten. Siehe meine Anweisungen

**Comment by lindschoki** [comment]
[https://github.com/lindschoki/EIA2](url)
ich weis leider nicht was Sie mit dem pages-link meinen

**Comment by JirkaDellOro** [comment]
Einen Link auf das ausführbare Programm, so wie Du es im Steckbrief postest

**Comment by lindschoki** [comment]
[https://lindschoki.github.io/EIA2/Aufgabe%202/UNO.html](url)

**Comment by lindschoki** [comment]
Aber der Link funktioniert auch nicht ich weis jetzt leider nicht weiter

**Comment by lindschoki** [comment]
mit den urls habe ich es eigentlich so gemacht wie Sie sagen, vielleicht ist hier einfach der Cursor verrutscht und ich habe es nicht mehr bemerkt...

Danke für den Tipp bei der Funktion ich werde es gleich mal versuchen 
und nochmals Entschuldigung für die Umstände

**Comment by JirkaDellOro** [comment]
Entschuldigung ist nicht erforderlich, wir machend das gerne. Und wenn ihr richtig postet, gibt es keine unnötigen Umstände
