### ISSUE TITLE
Frage zur Ampelschaltung

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#233]
Hi,
ich hab eine Ampelschaltung für  "lange Variablenliste zu Beginn auflösen" bekommen, verstehe aber nicht ganz den Grund dahinter. Im Praktikum haben wir ja verschiedene Lösungsansätze besprochen und ich habe mich an diesen orientiert. Andere Personen haben dafür keine Schaltung bekommen. 
Ebenso steht bei mir "Die CSS-Sylings sollten über eine eigene CSS-Datei eingebunden werden", was ich jedoch gemacht habe. Vielleicht könnt ihr mich darüber etwas aufklären.

Link zur HTML Version: https://dangscha.github.io/EIA2/Aufgabe%202b/Aufgabe2b.html
Link zum Repository: https://github.com/dangscha/EIA2/tree/master/Aufgabe%202b

**Comment by R4Pi3R** [comment]
Da der Kommentar zur Liste von Prof. Dell'Oro kommt maße ich mir mal nicht an für ihn zu antworten. Was ich sagen kann ist, dass die Einträge in das Array auch direkt gemacht werden können, ohne dass vorher jede Variable einzeln deklariert und dann aufgerufen werden muss.
Zum Rest:
Das Styling der Karten wird vollständig im Skript abgehandelt. In der CSS Datei werden nur Nachzieh- und Ablagestapel mit Styles versehen.
Und es stehen auch noch weitere Punkte auf der Liste, die nachgebessert werden sollten, von denen die Ampelschaltung abhängig sein kann.
Die Ampel ist nicht als Strafe gedacht, sondern ist ein Hinweis darauf, dass die Abgabe nicht den gesamten Anforderungen der Aufgabenstellung und/oder den Geboten entspricht.

**Comment by JirkaDellOro** [comment]
Jascha sieht das richtig, mein Beitrag war nur ein Zusatz, daher das + am Anfang. Ergänzen möchte ich noch, dass es bei der Ampelschaltung auch um die Einberufung eines Beratungsgespräches geht. Da geht es um individuelle Förderung, der Vergleich mit anderen funktioniert nur bedingt.
