### ISSUE TITLE
Handkarten sortieren funktioniert nicht

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#235]
Hi,
ich habe aktuell ein Problem mit dem Sortieren der Handkarten. In der Variante, die ich versucht habe, kann die Sortieren-Funktion nicht auf die Farben zugreifen, da diese vorher als Strings deklariert wurden, sondern nur auf Numbers. Ich weiß nicht wie ich das Problem lösen soll.

Github-Typescript: https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe3.ts
HTML Version: https://dangscha.github.io/EIA2/Aufgabe%203/Aufgabe3.html

**Comment by Plagiatus** [comment]
Du versuchst da zwei strings voneinander mit einem minus abzuziehen, das geht natürlich nicht.
weißt du was diese sortierfunktion zurückgeben soll? lies das doch bitte einmal nach, z.B. hier
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by JirkaDellOro** [comment]
... und bitte macht das nicht als "anonyme" Funktion, so etwas machen wir nur in Ausnahmefällen, auch wenn es für viele Javascript-Programmierer Standard ist. Solche Ausnahmen zeige ich euch noch und wie man damit umgeht. Also bitte statt

````ts
            ....sort(function(a, b) { return wasAuchImmerDerCodeTunMussUmZweiKartenZuVergleichen });
````
bitte eine richtige Vergleichsfunktion schreiben und diese der Sort-Methode mitteilen, also folgende Struktur
````ts
            ....sort(compareCards);

// und an anderer Stelle
function compareCards(card1: Card, card2: Card): number {
   let result: number = wasAuchImmerDerCodeTunMussUmZweiKartenZuVergleichen;
   return result
}
````
So bleibt ihr ganz in den euch bisher bekannten Strukturen.  Glücklicherweise kehren übrigens auch die Javascript-Programmierer langsam wieder zu diesen klassischen übersichtlichen Strukturen zurück.

**Comment by dangscha** [comment]
Erstmal danke für die Hilfe
Ich habe nun eine andere Variante probiert. Habe aber jetzt das Problem, dass mir der Text in den Karten nicht mehr angezeigt wird und ich weiß nicht wie ich das Problem lösen soll.

https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe3.ts
https://dangscha.github.io/EIA2/Aufgabe%203/Aufgabe3.html

**Comment by Plagiatus** [comment]
schau mal in den Inspektor rein und schaue was mit deiner Seite passiert wenn du auf sortieren klickst.

**Comment by JirkaDellOro** [comment]
Ich habe das mal gemacht, ist interessant. Bei jedem Sortieren kommen neue Karten dazu. Die decken visuell die schon vorhandenen Handkarten ab, kriegen aber keine Texte. Dafür werden die Texte der ursprünglichen Karten immer länger. Kann man halt nicht sehen, weil die anderen drauf liegen. :sunglasses:

**Comment by dangscha** [comment]
Erneut danke für die Antworten :)
Habe jetzt eine extra Funktion geschrieben, damit die Karten gelöscht werden. Nun habe ich das Problem, dass mein PlaceDiv mir die Fehlermeldung
"Aufgabe3.ts:79 Uncaught TypeError: Cannot read property 'appendChild' of null at placeDiv (Aufgabe3.ts:79) "
ausgibt. Ich weiß nicht woran das liegt.

https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe3.ts
https://dangscha.github.io/EIA2/Aufgabe%203/Aufgabe3.html

**Comment by R4Pi3R** [comment]
Schau mal in den Inspektor und sieh dir an was passiert, wenn du sortieren drückst.

Das passiert wegen der Zuweisung und dem Aufruf in deiner delete Funktion.
Die Variable "node" bekommt das "content" element zugewiesen.
In der Abfrage überprüfst du dann aber ob dieses Element ein Elternobjekt hat.
"if(node.parentnode)" gibt immer true zurück, wenn für das Objekt ein Elternknoten existiert. 
Also fragst du: Hat "content" ein Elternteil? - Antwort; Ja
Und mit dieser Antwort veranlasst du in der folgenden Zeile, dass das Kind des Elternteils gelöscht wird.
Und das Kind des Elternteils ist das "content"Element selbst.
Deswegen wird dieses in der Folge dann nicht mehr gefunden, was den besagten Fehler auslöst

**Comment by dangscha** [comment]
Aber das ist doch Sinn der Sache. Ich will ja mein main löschen und in der nächsten Zeile meiner Delete-Funktion dieses wieder neu erstellen, daher halt auch die Zeile:  
let main: HTMLElement = document.createElement("main");
main.setAttribute("id", "content");

**Comment by R4Pi3R** [comment]
Ah, entschuldige bitte! Mir ist die Zeile entgangen und daher hatte ich angenommen, dass du etwas anderes vorhast.
In dem Fall ist das Problem, dass du im Skript zwar ein "main" Element erzeugst, dieses aber nicht an das DOM übergibst. (Das Komplette Main zu löschen ist aber auch nicht zwingend die schönste Variante)

**Comment by JirkaDellOro** [comment]
Zudem, Jascha, Jans Konzept kann ich die Funktionalität nicht entnehmen! Von daher seit ihr gerade im Blindflug unterwegs und Du bist Copilot. Hätte man so nicht freigeben müssen, da steht weder etwas von Löschen noch überhaupt von darstellen. 

Er soll erstmal aufzeichnen, was er vor hat. Dieser Satz von dir trifft genau um was es geht: "... daher hatte ich angenommen, dass du etwas anderes vorhast.". Annahmen auf der Basis von fehlerhaftem Code zu treffen ist Zeitverschwendung.

Also: Schleudersitz betätigen und warten, bis der Flugplan steht

**Comment by R4Pi3R** [comment]
*Ejecting*

**Comment by dangscha** [comment]
Der Adler ist gelandet :D 
Sortieren funktioniert jetzt. Konzept hatte ich zwar überarbeitet, aber vergessen im Steckbrief neu zu verlinken: https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe%203%20Konzept%20%C3%BCberarbeitet.pdf

Insgesamt fiel mir jetzt bei der Implementation auf, dass selbst das überarbeitete Konzept so nicht funktionieren kann. Wird nun erstmal erneut überarbeitet.
