### ISSUE TITLE
Fehlermeldung type null

### ISSUE THREAD

**Issue by SinaSchwambach** [JirkaDellOro/EIA2#236]
HTML: https://sinaschwambach.github.io/EIA2/Aufgabe3/uno3.html
Js-Datei: https://github.com/SinaSchwambach/EIA2/blob/master/Aufgabe3/uno3.ts

Ich habe das Problem, dass mir in der Console angezeigt wird, dass mein Button mit der Id Button vom Type null ist. Das bedeutet doch, dass irgendwie nicht darauf zugegriffen werden kann aber wie kann ich das umgehen?

**Comment by Plagiatus** [comment]
Du versuchst den button zu finden, bevor er im DOM geladen ist.

Erinnere dich daran was Prof Dell'Oro ein zwei Vorlesungen vorher gesagt hat, an der Stelle wo das Skript steht wird es auch abgearbeitet. Da dein Skript im head ist (wo es auch sein soll), ist an dieser Stelle noch nichts vom body geladen.

**Comment by SinaSchwambach** [comment]
ja das weis ich, ich weis jedoch nicht wie ich das umgehen kann..

**Comment by AnnaLotz** [comment]
Schau dir mal an, wo genau du im Code auf den Button zugreifen willst

**Comment by SinaSchwambach** [comment]
aber ich habe gedacht, dass dadurch dass DOMContentLoaded direkt oben steht wird alles erst ausgeführt wenn das DOM geladen ist?

**Comment by Plagiatus** [comment]
document.addEventListener("DOMContentLoaded", main);
das ist, wie du inzwischen weißt, ein Eventlistener. Und wie ist ein Eventlistener aufgebaut?
zuerst das worauf gehört werden soll, dann das was ausgeführt werden soll.

Das Programm hört nicht an dieser Stelle auf zu laufen, sondern merkt sich nur, dass es die funktion `main` ausführen soll, wenn das DOMContentLoaded Event aufgerufen wird.

**Comment by JirkaDellOro** [comment]
Das heißt, was danach kommt wird auch noch ausgeführt, sofern es nicht in einer Funktion steht, die noch nicht aufgerufen wird. Auf das DOM sollte man aber erst zugreifen, wenn es fertig aufgebaut ist. Vielleicht also aus einer Funktion heraus, die erst dann ausgeführt wird?

Irgendwie süß hier... vier Ärzte und ein Patient :smile:

**Comment by SinaSchwambach** [comment]
okay, das Problem ist jetzt gelöst aber jetzt werden die Karten nicht sortiert..

ja, ein Patient der sich trotz der vielen Hilfe ziemlich dumm anstellt..

**Comment by JirkaDellOro** [comment]
Im Gegenteil, Du stellst dich sehr schlau an, Du gehst zum Arzt. Andere sterben einfach...

In sortCards ist die Installation des Listeners schlecht, da bei jedem Aufruf der Funktion ein weiterer Listener installiert ist. Beim zweiten Sortieren wird dein Button also schon zwei Ohren haben, dann vier, dann acht... du weißt wie es weiter geht.

Ich muss weg, die anderen Ärzte übernehmen bitte wieder.

**Comment by Plagiatus** [comment]
wenn du dir mal dein Handkartenarray anschaust (Debugger oder Konsolenausgaben), dann siehst du dass es auch sortiert wird. Das Ergebnis wird bloß noch nicht auf dem Bildschirm ausgegeben.

**Comment by SinaSchwambach** [comment]
so kann man es natürlich auch sehen.. 

bedeutet das, dass ich meinen Listener in eine eigene Funktion packen muss, die dann meine sortCards Funktion aufruft? 
und danach dann nochmal meine displayCards funktion aufrufen muss, damit meine sortierten Karten auf dem Bildschirm dargestellt werden?

**Comment by Plagiatus** [comment]
probiers aus ;)

**Comment by SinaSchwambach** [comment]
habe ich, dann sortiert es mir einen Wisch neu gezogener Karten..

**Comment by SinaSchwambach** [comment]
bzw nicht neue Karten sondern mehrfach die gleiche Karte wird dargestellt

**Comment by Plagiatus** [comment]
es gehört von vorneherein nicht in die vergleichsfunktion. du solltest es in sortCards und nicht in compareCards schreiben.

**Comment by SinaSchwambach** [comment]
das habe ich jetzt aber meine Karten werden trotzdem nicht sortiert sondern es werden zwei neue Karten dargestellt

**Comment by Plagiatus** [comment]
schau mal in den debugger rein und gehe mal schritweise durch die display Hand durch, dann siehst du was los ist.

**Comment by SinaSchwambach** [comment]
habe ich versucht, komme aber nicht wirklich damit klar wie der funktioniert..

**Comment by R4Pi3R** [comment]
Was macht deine Display Funktion denn eigentlich? Sie geht durch das Handarray, erzeugt spans und hängt diese als Kinder an das Hand div. Aber was passiert, wenn das schon Kinder hat?
Und um dir etwas Verwirrung wegen der neuen Karte zu nehmen:
Der EventListener für das Ziehen einer Karte liegt einfach auf dem Dokument. Also egal wo ich in das Dokument klicke (z.B. auch auf dem Button zum Sortieren) ich ziehe eine neue Karte.

**Comment by JirkaDellOro** [comment]
Die Verwirrung wird noch größer. In der displayHand-Funktion steht folgendes:
````ts
        let span: HTMLSpanElement = document.createElement("span");
        for (let o: number = 0; o < hand.length; o++) {
````
Es wird also ein span-Element erzeugt und dann geht es in die Schleife. In der kriegt dasselbe span-Element immer munter neue Attribute und wird immer wieder dem DOM untergeschoben. Da ist es aber nach dem ersten Schleifendurchlauf schon drin. Also erzeugst Du nur eine Karte, stellst die dar und veränderst dann nur ihr Aussehen immer wieder. Wenn es mehrere Karten sein sollen, eben so viele wie im Hand-Array sind, musst Du bei jedem Schleifendurchlauf ein span-Element neu erzeugen.

Es wäre klasse, wenn du lernst mit dem Debugger umzugehen. Du erzeugst interessante Probleme, die nicht mehr ganz leicht zu finden sind. Komm' gerne ins Spiellabor, dann zeigen wir dir das. :wrench: :bulb:

**Comment by SinaSchwambach** [comment]
habe jetzt eine extra Funktion für die Darstellung der neuen Karten aber irgendwie wird jetzt automatisch sortierte Karten gezogen...

**Comment by Plagiatus** [comment]
ich sehe in der HTML mehrere Probleme, was genau ist das Problem auf das du hinaus willst?

**Comment by SinaSchwambach** [comment]
dass die karten sortiert gezogen werden, bei nachziehen zwei karten von der gleichen farbe gezogen werden und beim sortieren werden neue Karten gezogen..

**Comment by Plagiatus** [comment]
ich weiß immernoch nicht, was du mit "sie werden sortiert gezogen" meinst.

also, wenn du auf den Ablagestapel klickst, wird nicht nur drawNewCard() aufgerufen, sondern auch das allgemeine document click event: handleEventClickOnCard(). 

beim Nachtziehen wird immer zweimal die gleiche Karte angezeigt, aber nicht in die handkarten gezogen. schau dir mal genau an (im Debugger z.B.) wann was in welche Variable geschrieben wird und was wann mit der Ausgabe passiert.
