### ISSUE TITLE
array push

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#237]
Hallo hab ein kleines Problem, 

wenn ich die zufällig generierten Karten aus meinem deck array in mein handkarten array pushen möchte habe ich das Problem das der typ des Parameters im Push-Befehl in der Schleife nicht kompatibel mit dem Typ des Parameters aus dem Interface ist. was kann ich hier machen ? 

Danke für die Hilfe 

[](https://github.com/lindschoki/EIA2/blob/master/Aufgabe%203/UNOneu.ts)

**Comment by lindschoki** [comment]
[](urlhttps://github.com/lindschoki/EIA2/blob/master/Aufgabe%203/UNOneu.ts)

**Comment by lindschoki** [comment]
[link](https://github.com/lindschoki/EIA2/blob/master/Aufgabe%203/UNOneu.ts)

**Comment by JirkaDellOro** [comment]
Bitte immer auch einen Link zur App posten

**Comment by R4Pi3R** [comment]
Den richtigen Typ übergeben ;)

handcards ist ein Array vom Typ Card[]
_cards ist eine Variable vom Typ Number

Was du hier in das handcards Array übergeben willst ist aber keine einzelne Variable, sondern ein Interface vom Typ Card. 
Mit "deck[index]" greifst du darauf ein paar Zeilen weiter oben schon zu

**Comment by JirkaDellOro** [comment]
Genauer: ein Object vom Interfacetyp Card

**Comment by lindschoki** [comment]
Ah ich wuuste nicht welchen Parameter ich übergeben muss, jetzt klappts allerdings werden mir in der Konsole nicht nur ein array angezeigt das die Werte enthält sondern soviele arrays wie ich in prompt eingebe.

**Comment by JirkaDellOro** [comment]
Wo ist der Link zur App?

**Comment by lindschoki** [comment]
[link](https://lindschoki.github.io/EIA2/Aufgabe%203/UNOneu.html)

**Comment by lindschoki** [comment]
Ok hat funktioniert vorher kam nur die ganze Zeit ne Fehlermeldung wenn ich den console.log Aufruf unter die Schleife gesetzt habe. 

Danke für die Hilfe

**Comment by JirkaDellOro** [comment]
Gerne :+1: 

Und nicht vergessen hier dicht zu machen, wenn das Problem gelöst ist.
