### ISSUE TITLE
randomCards in neues Array pushen

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#238]
In der Function in Zeile 42 versuche ich die Kartenwerte, welche in der Main Function an die Function in Zeile 42 übergeben werden, in das Handkarten Array zu pushen.

Ich finde den Fehler nicht und kann mit dem Fehler in der Console auch nichts anfangen.
Die main Function wird auch nur noch einmal ausgeführt und gibt nur eine Karte aus. 

[link](https://github.com/t0mmy93/EIA2_Git/tree/master/Aufagabe3)
[Aufgabe3](https://t0mmy93.github.io/EIA2_Git/Aufgabe_3/Aufgabe3.html)

**Comment by JirkaDellOro** [comment]
Immer auch den Link zur App posten

**Comment by JirkaDellOro** [comment]
... dann könnten wir auch die Fehlerausgabe in der Console sehen dürfen.

Aus der Hüfte: es werden zwei Strings gepusht, die unterschiedliche Bedeutung haben. Ich schätze, es sollte nur ein String sein, der beide Bedeutungen vereint.

**Comment by t0mmy93** [comment]
ist verlinkt

**Comment by NicoKlein97** [comment]
Das Problem hier ist, dass das Array in Zeile 28 noch nicht richtig initialisiert ist. Deshalb bekommst du den undefined-Fehler. Du musst TypeScript nur sagen, dass das ein leeres Array sein soll. Also ` let handCards: string[] = [];`
Damit sagst du, dass du ein leeres Array erstellst. Dann ist der fehler verschwunden und es werden mehrere Karten erzeugt.

**Comment by JirkaDellOro** [comment]
Zum Hintergrund
````ts
let handCards: string[];
````
ist lediglich eine Deklaration und bedeutet, dass die Variable handCards vom Typ String-Array sein soll. Es ist aber noch kein Speicher reserviert worden und auch noch kein Array konstruiert. Das geschieht erst durch die Definition mit einem Wert, hier mit der Zuweisung des durch `[ ]` erschaffenen leeren Array.

**Comment by t0mmy93** [comment]
Vielen Dank 👍

**Comment by JirkaDellOro** [comment]
Gerne 👍

Und nicht vergessen hier dicht zu machen, wenn das Problem gelöst ist.
