### ISSUE TITLE
Auf generierte Id zugreifen

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#239]
Ich stehe aktuell vor dem Problem, dass ich durch meine Ablegen-Funktion eine Karte in ein anderes Array pushen möchte. Die erstellten Karten haben alle eine variable Id zugewiesen bekommen, ich weiß nun nicht wie ich auf diese Id zugreifen kann

Github: https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe3.ts
HTML: https://dangscha.github.io/EIA2/Aufgabe%203/Aufgabe3.html
Überarbeitetes Konzept: https://dangscha.github.io/EIA2/Aufgabe%203/Konzept%202.0.pdf

**Comment by JirkaDellOro** [comment]
Sorry, Jan, aber wir müssen uns zunächst noch ein wenig mit Formalitäten beschäftigen. Sonst ist es unnötig schwierig zu helfen.

Anhand des neuen Konzeptes kann ich schon sehr gut erkennen, was Du vorhast. Wenn Du nun deinen Code noch vernünftig strukturierst, kann ich dir sicher in ein paar Sekunden sagen, wie Du vorgehen musst.

Also: 
- bitte unbedingt den CodingStyle beachten und die Variablen und Funktionen richtig benennen. Nutze hierzu das Rename-Tool (Alt+Shift+R)
- keine Funktionen innerhalb von Funktionen definieren
- die Funktionen immer unten im Code ansiedeln, die Aufrufe derselben oben. So wie wir es auch mit der Konzeption machen. Zuerst kommt das Grobe, dann werden die Aktivitäten ausdefiniert.
- Eventlistener möglichst weit oben im Code installieren

**Comment by Plagiatus** [comment]
Umbenennen kann auch mit F2 gemacht werden glaube ich.

Schonmal ein Hinweis zu deinem Problem: ein EventListener kann der aufgerufenen Funktion automatisch das empfangene Event übergeben. dieses Event hat mehrere Eigenschaften, welche du nutzen kannst. 

MouseEvent:
https://developer.mozilla.org/de/docs/Web/API/MouseEvent
GenerischesEvent:
https://developer.mozilla.org/de/docs/Web/API/Event

**Comment by JirkaDellOro** [comment]
Auf F2 hört VSCode

**Comment by dangscha** [comment]
Hab einmal meinen Code überarbeitet und mich am Coding-Style orientiert. Hab versucht auf alles zu achten, ist es so nun besser? :)

https://github.com/dangscha/EIA2/blob/master/Aufgabe%203/Aufgabe3.ts

**Comment by JirkaDellOro** [comment]
Ja, deutlich besser. 
- Allerdings sind die ganzen Funktionen immer noch in der Funktion uno definiert, die müssen da raus
- Funktionsnamen sollen Aktivitäten beschreiben, sollen also nicht mit "event..." anfangen, sondern eher mit "install..."
- Du setzt Funktionen noch nicht sehr geschickt ein. Du hast drei kleine Funktionen, die dir Listener installieren, aber keine, die dir die Handkarten darstellt. Mach' mal aus den drei Installationsfunktionen eine und bau eine displayHand-Funktion.
- content aus dem DOM rauszulöschen und dann wieder reinzubasteln ist zu viel Aufwand. Der Einzeiler node.innerHTML = "" macht dir den gleichen Effekt.

Zu deiner eigentlichen Frage kann ich zurückverweisen auf Ja, deutlich besser. 
- Allerdings sind die ganzen Funktionen immer noch in der Funktion uno definiert, die müssen da raus
- Funktionsnamen sollen Aktivitäten beschreiben, sollen also nicht mit "event..." anfangen, sondern eher mit "install..."
- Du setzt Funktionen noch nicht sehr geschickt ein. Du hast drei kleine Funktionen, die dir Listener installieren, aber keine, die dir die Handkarten darstellt. Mach' mal aus den drei Installationsfunktionen eine und bau eine displayHand-Funktion.
- content aus dem DOM rauszulöschen und dann wieder reinzubasteln ist zu viel Aufwand. Der Einzeiler node.innerHTML = "" macht dir den gleichen Effekt.

Zu deiner eigentlichen Frage kann ich zurückverweisen auf Ja, deutlich besser. 
- Allerdings sind die ganzen Funktionen immer noch in der Funktion uno definiert, die müssen da raus
- Funktionsnamen sollen Aktivitäten beschreiben, sollen also nicht mit "event..." anfangen, sondern eher mit "install..."
- Du setzt Funktionen noch nicht sehr geschickt ein. Du hast drei kleine Funktionen, die dir Listener installieren, aber keine, die dir die Handkarten darstellt. Mach' mal aus den drei Installationsfunktionen eine und bau eine displayHand-Funktion.
- content aus dem DOM rauszulöschen und dann wieder reinzubasteln ist zu viel Aufwand. Der Einzeiler node.innerHTML = "" macht dir den gleichen Effekt.

Zu deiner eigentlichen Frage kann ich zurückverweisen auf Ja, deutlich besser. 
- Allerdings sind die ganzen Funktionen immer noch in der Funktion uno definiert, die müssen da raus
- Funktionsnamen sollen Aktivitäten beschreiben, sollen also nicht mit "event..." anfangen, sondern eher mit "install..."
- Du setzt Funktionen noch nicht sehr geschickt ein. Du hast drei kleine Funktionen, die dir Listener installieren, aber keine, die dir die Handkarten darstellt. Mach' mal aus den drei Installationsfunktionen eine und bau eine displayHand-Funktion.
- content aus dem DOM rauszulöschen und dann wieder reinzubasteln ist zu viel Aufwand. Der Einzeiler node.innerHTML = "" macht dir den gleichen Effekt.

Zu deiner eigentlichen Frage kann ich zurückverweisen auf Lukas' vorangegangene Antwort. Schau' dir bitte nochmal den Code aus der Vorlesung an, da wird das angeklickte Target weiter untersucht, so kommst Du an dessen Eigenschaften ran.

**Comment by dangscha** [comment]
Hab mein Code nochmal überarbeitet
Jetzt hab ich leider ein Problem mit meiner Ablagefunktion. Wenn ich auf eine Karte klicke, wird immer die erste Karte aus meiner Hand auf dem Ablagestapel getan. Weiß nicht woran es liegt.

**Comment by Plagiatus** [comment]
deine ID ist z.B. "card3", also steht nach dem substring operator noch "ard3" darin, was natürlich nicht in eine Zahl geparst werden kann. splice nimmt bei einem NaN scheinbar einfach immer das allererste, darum wird das erste herausgenommen egal auf was eigentlich geklickt wurde.

und dein KeyboardEvent wird wahrscheinlich nicht aufgerufen weil du es auf dem Nachzeihstapel eingefügt hast, statt auf dem gesamten Dokument. das scheint nicht anzukommen.

**Comment by Plagiatus** [comment]
ersteres kann man übrigens ganz toll mit dem Debugger herausfinden ;)

**Comment by R4Pi3R** [comment]
WAAAAGGGGHHH!
Lukas schreibt Antworten einfach schneller als ich die Issues lesen kann xD
Anbei immerhin eine Adresse unter der du nachschauen kannst was die Parameter in substr() auslösen =>https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/substr

**Comment by R4Pi3R** [comment]
Und @Lukas, wenn der Parameter nicht zugewiesen werden kann wird default 0 eingesetzt

**Comment by dangscha** [comment]
Super, danke. Funktioniert soweit alles. Gibt nur noch eine Kleinigkeit die mich stört: Wenn ich eine Karte nachziehe, taucht neben dem Nachziehstapel ein content auf. Weiß nicht wo das herkommt

**Comment by Plagiatus** [comment]
soweit ich das sehe, taucht das "content" bei jeder aktion auf, egal welche der drei aktionen man durchführt. 

wenn du nach sowas einfachem suchst, ist es wahrscheinlich am einfachsten, die Suche zu benutzen (CTRL+F) und nach dem wild gewordenen Wort zu suchen. So habe ich schnell herausgefunden, wo das Problem liegt, und du findest das auch.

**Comment by dangscha** [comment]
Gefunden! Dankeschön :)
