### ISSUE TITLE
Bienen werden nicht angezeigt

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#24]
Hallo zusammen, 
meine Bienen werden nicht angezeigt. Warum?

https://github.com/fehrenbi/EIA2/blob/master/Aufgabe%207/Aufgabe/blumenwiese7.ts

Danke schon im Voraus

**Comment by saenglert** [comment]
Heyhey,
blöder kleiner Fehler in blumenwiese7.ts Zeile 50:
`for (let i: number; i < amountBees; i++)`

Deine Zählvariable i bekommt keine Zahl zugewiesen.

D.h. wenn im nächsten Schritt i < amountBees überprüft wird, steht da effektiv "Ist eine undefinierte Zahl kleiner als eine Zahl?", was Java-/Typescript mit falsch beantwortet und deine Schleife wird nicht einmal ausgeführt.

Wie findet man solche Fehler, die keine Fehlermeldung erzeugen, weil sie mögliche Operationen sind? Über den Debugger z.B. im Browser! Beim ersten Überfliegen sah dein Code für mich soweit ganz korrekt aus. Dann habe ich mir einen Breakpoint in Zeile 51 gesetzt um herauszufinden, was passiert wenn die Bienen erstellt werden sollen. Beim Ausführen habe ich festgestellt mein Breakpoint wird nie erreicht, also die Schleife wird nie ausgeführt. Daraufhin habe ich mir natürlich die Schleife nochmal genauer angeschaut und bin über den Fehler gestolpert.
