### ISSUE TITLE
ids für erzeugte karten divs

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#240]
Ich bekomme es nicht hin, dass alle meine erzeugten Handkarten divs eine eigene id bekommen. Für die Funktion habe ich bereits einen neuen Parameter vergeben der durch die Schleife für jede div eine id zuweisen sollte, habe aber beim Funktionsaufrauf eine Fehlermeldung (ganz unten im code bei "createCards(allCards)"

[Aufgabe 3 link](https://github.com/lindschoki/EIA2/blob/master/Aufgabe%203/UNOneu.ts)

**Comment by Plagiatus** [comment]
bitte auch immer die ausführbare Seite mit verlinken

**Comment by lindschoki** [comment]
[Seite](https://lindschoki.github.io/EIA2/Aufgabe%203/UNOneu.html)

**Comment by Plagiatus** [comment]
dein `createCards` erwartet zwei Übergabeparameter, du gibst ihm nur einen (Fehlermeldung lesen hilft).
worfür wird denn `cardNumber` überhaupt genutzt?
es scheint nicht übersetzt zu werden, da der js code nicht zum ts code passt (wenn Fehlermeldungen existieren wird die ts nicht in eine js übersetzt)

**Comment by lindschoki** [comment]
Du hast recht aber ich hab bemerkt das der zusätzliche Parameter in createCards überflüssig ist und ich bei der id übergabe bei setAttribute durch Angabe vom Parameter "i" schon erreiche das jede Karte eine andere id bekommt

**Comment by Plagiatus** [comment]
das ist richtig. aber offensichtlich so noch nicht im code umgesetzt.

**Comment by lindschoki** [comment]
ja den neuen kann ich noch schnell hochladen
