### ISSUE TITLE
Funktionen werden nicht ausgeführt

### ISSUE THREAD

**Issue by emilymelzer** [JirkaDellOro/EIA2#241]
Ich habe das Problem, das meine „DrawCard“ Funktion nicht mehr funktioniert Bzw. Ausgeführt wird, seit dem ich die anderen, neuen Funktionen im Code habe. Davor hat alles funktioniert. Weiß jemand an was das liegt?

**Comment by emilymelzer** [comment]
https://github.com/emilymelzer/EIA2/tree/master/A3 Link zu meiner aufgabe

**Comment by Plagiatus** [comment]
und zur ausführbaren Seite? aka github pages?
