### ISSUE TITLE
Gesamtpreis funktioniert nicht richtig

### ISSUE THREAD

**Issue by nicoherrmann** [JirkaDellOro/EIA2#242]
Hallo,
habe jetzt soweit den Aufbau dynamisch und er schreibt es auch in die aktuelle Übersicht.
Der Gesamtpreis funktioniert gewissermaßen, allerdings verstehe ich nicht ganz, warum er bei einer Änderung der Daten der Wert so drastisch erhöht und warum die Reihenfolge beim Auswählen eine Rolle spielt (ob zuerst Artikel und dann Anzahl oder erst Anzahl und dann Artikel).

Die Funktion für den Preis beginnt ab Zeile 154

Website: https://nicoherrmann.github.io/EIA2/Aufgabe4/WBKonfigurator.html
Typescript: https://github.com/nicoherrmann/EIA2/blob/master/Aufgabe4/js/Script.ts

Aufgabe4 im Repository: https://github.com/nicoherrmann/EIA2/tree/master/Aufgabe4

Mfg

**Comment by NicoKlein97** [comment]
Die Erhöhung des Preises kommt da her, dass in den Zeilen 156 bis 158 die Werte welche multipliziert werden nie zurückgesetzt werden. Also jedes mal wenn calcPrice aufgerufen wird, werden die zuvor bereits eingetragenen und multiplizierten Preise nochmal und nochmal multipliziert.

Die Reihenfolge ist wichtig, weil du wenn du zuerst das Produkt eingibst dennoch in die calcPrice() reinspringst. Hier wird der Preis für das Produkt dann mit der nicht angegeben Menge (undefined) multipliziert-----> Der Preis der daraus hervor geht ist dann keine number sondern NaN und kann deshalb nicht mehr verwendet werden für die Kalkulation wenn du danach die menge angibst.

Ich hoffe das ist verständlich.

**Comment by nicoherrmann** [comment]
Oh ja Dankeschön sollte jetzt funktionieren
