### ISSUE TITLE
Lokale JSON-Datei in TypeScript importieren

### ISSUE THREAD

**Issue by JannisBackhaus** [JirkaDellOro/EIA2#243]
Ich habe eine JSON-Datei deco.json mit den nötigen Daten in Array-Form erstellt und möchte sie jetzt in TypeScript einbinden. Nach 2 Stunden vergeblichem herumgooglen habe ich immer noch keine Möglichkeit gefunden die funktioniert... HILFE!

Jannis

JSON: https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2005/deco.json

**Comment by Plagiatus** [comment]
Hier drin ist ein Beispiel wie man das machen kann:
https://github.com/hs-furtwangen/cowau-2018/blob/master/cowau/src/pages/load/load.ts

**Comment by JirkaDellOro** [comment]
Aua, aua........ viel zu kompliziert!!!

Mach' es bitte einfach so wie bei Uno, und beachte die Hinweise im vierten Punkt bei "Produktion" in der Aufgabenstellung. Aber... du bist bei Uno  einen Sonderweg gegangen. Mach' es diesmal so, wie die meisten anderen, und beachte dann den Punkt.

**Comment by JirkaDellOro** [comment]
Ich schreibe hier mal schnell einen kleinen Stub

Hauptprogramm
````ts
namespace Test{
  console.log(data[1]);
}
````   

Daten
````ts
namespace Test{
  export interface Stuff {
    what: string;
    ever: number;
  }

  export let data: Stuff[] = [
    { what: "idk", ever: 10 },
    { what: "google it", ever: 42 }
  ]
}

Klebe das mal in ein paar Files und schau ob es läuft. Vielleicht habe ich mich irgendwo vertippt.

**Comment by JirkaDellOro** [comment]
Ganze interessant, Sascha. Geht das so auch im Browser, ohne Node? Wenn nicht: Aua, aua, auaaah.... !

**Comment by saenglert** [comment]
Die "resolveJsonModule" Flag für den Compiler ist an eine Node basierte Modulesyntax gekoppelt. Also offensichtlich erstmal nein.

Aber wie das so bei JavaScript ist, gibt es für jedes Problem mind. 10 Lösungen. In diesem Fall empfehle ich das Projekt mit [webpack](https://webpack.js.org/) zu bundeln. Webpack lädt und parst JSON Dateien während des Build Prozesses und exportiert das Ergebnis wiederum per browserkompatiblen ES6 Syntax (nein wir fangen jetzt nicht mit IE6 Support an).

**Comment by JannisBackhaus** [comment]
@saenglert : Danke dir für die ausführliche Erklärung! Ich werde das zusätzlich mal ausprobieren, werde mich aber diesmal für die Abgabe dem Willen meines Profs beugen. 😄 
@JirkaDellOro : Zu Befehl 😁
