### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by LuisaCarmen** [JirkaDellOro/EIA2#244]
Hallo,

ich habe ein Problem und zwar hat mein Code gestern noch super funktioniert und heute zeigt es mir an "undefined" "Type Error: node is null" in Zeile 439... .  Ich muss da wohl irgendetwas falsch umgeändert haben und finde meinen Fehler einfach nicht und mir rechnet es mein Gesamtpreis nicht mehr aus. Bin am verzweifeln. Ich hoffe mir kann jemand weiter helfen. Danke schon mal im Voraus.
Luisa

https://luisacarmen.github.io/EIA2/Aufgabe4/Aufgabe4.html

**Comment by saenglert** [comment]
Hallo Luisa,
dann würde ich mal sagen, dass wir uns am Besten die betroffene Zeile anschauen:

`node.innerHTML = HTML;`

`node is null` bedeutet in diesem Kontext, dass der Wert `innerHTML` nicht aufgerufen werden kann, da die Variable `node` nichts enthält, also `null` ist. Im nächsten Schritt sollten wir uns anschauen, wann du die Variable `node` initialisierst (also zum ersten Mal mit einem Wert befüllst) und das passiert in Zeile 431:

`let node: HTMLElement = document.getElementById("endpricehtml");`

`getElementById()` liefert uns ein HTMLElement mit der Bedingung, dass es dieselbe Id hat, die wir als String der Funktion übergeben. Aber was passiert eigentlich, wenn es kein solches Element gibt? [Nachschlagwerk](https://developer.mozilla.org/de/).

Ein letzter Hinweis: Das Problem ist wirklich nur ein kleiner Buchstabendreher. Wenn du es in 5min nicht gefunden hast, löse ich es dir gerne auf.

**Comment by LuisaCarmen** [comment]
Habe es endlich gefunden. Habe mir schon gedacht, dass es bestimmt nur so ein kleiner Fehler ist. Vielen vielen Dank und einen schönen Sonntag noch.
