### ISSUE TITLE
Karten verschwinden

### ISSUE THREAD

**Issue by Leah1995** [JirkaDellOro/EIA2#245]
Bei mir hat sich das Problem ergeben, dass immer Karten verschwinden, wenn man zuerst auf den Ablagestapel und dann auf Sortieren drückt. 

Aufgabe: https://leah1995.github.io/EIA2WS/Aufgabe-3/Aufgabe3.html
TypeScript: https://github.com/Leah1995/EIA2WS/blob/master/Aufgabe-3/script.ts

Bin für jede Hilfe offen!

**Comment by Leah1995** [comment]
Anmerkung: Mir ist aufgefallen, dass das nur passiert, wenn schon Karten auf dem Ablagestapel liegen

**Comment by JirkaDellOro** [comment]
Setz' mal  im Debugger einen Breakpoint in der Funktion playCard uns schaue, unter welchen Bedingungen sie ausgeführt wird.
