### ISSUE TITLE
Ansteuern von assoziativen Arrays

### ISSUE THREAD

**Issue by JannisBackhaus** [JirkaDellOro/EIA2#246]
Hallo zusammen,

Ich habe meine Datenstruktur in meiner "data.js" Datei so umgeändert, dass ich auch neue Kategorien dynamisch im HTML darstellen lassen kann. 

Jetzt habe ich schon wieder das Problem, dass ich nicht auf meine Datenstruktur zugreifen kann. 
Die Skript-Datei "test.js" und "data.js" sind innerhalb eines Namespaces, meine Variable "data" wird exportiert, und ich kann über eclipse ohne Probleme mit meiner Datenstruktur arbeiten. 

Erst wenn ich im Browser versuche einen Test console.log auszuwerfen, kriege ich immer einen Uncaught TypeError. 

Habe ich irgendwas vergessen oder ist mein Browser einfach bockig? 

HTML-Link: https://jannisbackhaus.github.io/EIA2/Aufgabe%2006/config.html
HTML-Code: https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2006/config.html
data.ts-Code: https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2006/data.ts
test.ts-Code: https://github.com/JannisBackhaus/EIA2/blob/master/Aufgabe%2006/test2.ts

Danke im Vorraus für die Hilfe!
Jannis

**Comment by Plagiatus** [comment]
deine Variable heißt in der data.ts "data" aber du versuchst sie in der test.ts über "categories" anzusprechen

**Comment by Plagiatus** [comment]
die namespaces heißen auch unterschiedlich ;)

**Comment by JannisBackhaus** [comment]
Omg... danke 😆 jetzt klappts mit dem data sheet, aber jetzt hab ich ein neues Problem. Wenn ich mein "data"-Array ansteuere `data[i].form_type` und dann per Zähler auf die Variablen des jeweiligen Array-Objekts zugreifen will, schmeißt mir das Programm immer undefined als Wert rein. Ich hab dann gecheckt dass ich ja mit `data[i]["tree"].form_type` drauf zugreifen muss, was aber meine Dynamik zerhaut, weil ich ja nicht nur die Kategorie "tree" habe. `data[i][0]["tree"].form_type` klappt auch nicht. 
Gibt's da einen Trick ?

**Comment by JirkaDellOro** [comment]
Hallo Jannis,

deine Datenstruktur erscheint nicht 100% sinnvoll aufgebaut, wenn Sie auch schon sehr durchdacht wirkt und recht komplex ist. 

data verweist auf ein Array mit 6 Elementen, jedes davon ist vom Typ Categories. Hier fällt schon auf, dass da eine Dimension zuviel drin ist. Denn willst Du wirklich 6 Sammlungen unterschiedlicher Kategorien haben, oder würden dir nicht 6 Kategorien genügen? Zumal Du innerhalb dieser 6 Elemente eigentlich nur eine Kategorie anlegst. Dummerweise kannst Du dann aber auch nicht mehr darauf zugreifen, da ein assoziatives Array in JS/TS konsequent mit Hilfe von Schlüsseln angesprochen wird, nicht mit ganzzahligen Indizes. Die `[0]` in `data[i][0]` geht daher in die Hose.

Tipp: Ändere den Typ von data von `Categories[]` einfach auf `Categories` und lösche die äußeren eckigen Klammern in der JSON-Struktur. Das entspricht wahrscheinlich dem, was Du eigentlich beabsichtigst (und auch meinem Beispielcode). Dann iterierst Du darüber mit `for...in`

**Comment by JirkaDellOro** [comment]
PS: echt schön gemacht mit dem form_type! Du baust schon fast ein kleines CMS :+1:

**Comment by JannisBackhaus** [comment]
Perfekt! Jetzt klappt alles 😅 
Dankeschön!
