### ISSUE TITLE
Zählvariablen in assoziativem Array

### ISSUE THREAD

**Issue by SinaSchwambach** [JirkaDellOro/EIA2#247]
Ich möchte meine Funktion zum erstellen meiner Fieldsets allgemein schreiben, sodass ich nicht für jede einzelne Warenkategorie eine neue Funktion schreiben muss. Allerdings verstehe ich nicht ganz wie ich das anstelle durch das neue Array.
Wenn ich ein ganz normales Array hätte müsste ich ja schreiben:
for (let o: number = 0; o < item.length; o++) und dann würde die schleife ja solange durchlaufen wie Objecte im Array enthalten sind. 

Aber durch das neue Array habe ich jetzt ja quasi zwei Dinge wo ich eine Zählvariable einsetzten müsste:
einmal um durch die länge des data Arrays durchzulaufen und einmal um dann innerhalb der einzelnen Kategorien auf den preis oder Namen zuzugreifen.. aber wie mach ich das? 

TS-Datei: https://github.com/SinaSchwambach/EIA2/blob/master/Aufgabe5/wbkneu.ts
HTML: https://sinaschwambach.github.io/EIA2/Aufgabe5/wbkneu.html

**Comment by NicoKlein97** [comment]
Ich bin mir nicht ganz sicher ob ich deine Frage genau verstanden habe, ich glaube, dass das was du machen willst das ist, was Prof. Dell Oro in seinem Code hier: https://github.com/JirkaDellOro/EIA2_W18_Code/blob/master/L05_AssocArraysAndExport/Main.ts#L21
von Zeile 21 bis 33 gemacht hat. Am besten gehst du diesen Part mal ganz in ruhe mit dem Debugger durch.

**Comment by SinaSchwambach** [comment]
ich glaube das habe ich soweit dann vertsanden aber warum zeigt es mir bei _fieldset[_i].appendChild(input); eine "Index signature of object type implicitly has an 'any' type." Fehlermeldung an?

**Comment by Plagiatus** [comment]
_fieldset ist vom Typ HTMLFieldSetElement, auf was genau willst du da mithilfe von [_i] zugreifen?

**Comment by SinaSchwambach** [comment]
auf das zuvor ausgewählte fieldset

**Comment by Plagiatus** [comment]
und wofür brauchst du dann das i? du übergibst das (einzelne) fieldset doch schon an die funktion "createFormat" nachdem du es davor in Zeile 14 schon als einzelnes Fieldset aus dem Array (bzw der NodeListOf) geholt hast.

**Comment by SinaSchwambach** [comment]
achso, bedeutet das, dass ich das i gar nichtmehr brauch?

**Comment by SinaSchwambach** [comment]
achso okay,
wir haben jetzt das Problem, dass alles in ein Fieldset gepackt wird. Wir wollten fragen wie wir es hinkriegen, dass beim Value Change auch das nächste Fieldset benutzt wird.

**Comment by JirkaDellOro** [comment]
Kann ich im Konzept erkennen, was ihr vorhabt? Dann könnte ich gut helfen...

**Comment by SinaSchwambach** [comment]
ich glaube nicht wirklich dass man das erkennt aber das kann ich noch nachliefern

**Comment by JirkaDellOro** [comment]
Ja, bitte, das wäre klasse!

**Comment by JirkaDellOro** [comment]
... und es ist nicht unwahrscheinlich, dass ihr dabei selbst auf bessere Strukturen und Algorithmen kommt.
