### ISSUE TITLE
hilfe bei überprüfung der geklickten inputs

### ISSUE THREAD

**Issue by jstnez** [JirkaDellOro/EIA2#248]
https://github.com/jstnez/EIA2/blob/master/Aufgabe5/Aufgabe4code.ts

Guten Abend,

ich weiß leider nicht wie ich auf den Input von der Funktion oben zugreifen kann, so dass ich überprüfen kann welche Felder geklickt worden sind.

**Comment by nicoherrmann** [comment]
bin mir zwar nicht ganz sicher aber bei mir ging das mit target.getAttribute(z.B. "price" oder "name);
target ist in dem Fall "let target: HTMLInputElement = <HTMLInputElement>_event.target;"

Also in der handleChange Funktion denke ich mal

**Comment by Plagiatus** [comment]
ich sehe in dem Codeschnipsel "da oben" 4 funktionen plus eine auskommentierte Funktion. Von welcher sprichst du? was für ein Input? 
bitte klarifiziere deine Frage, weil sonst muss ich raten was genau dein Problem ist.

**Comment by Plagiatus** [comment]
wann wird das denn wovon aufgerufen? bei dir im code aktuell zwei mal: erstens von einem Event das auf "change" hört und später dann während der "createInput" Funktion. letzteres macht so keinen Sinn, sondern du willst ja den Warenkorb neu aufbauen/berechnen, wenn sich etwas geändert hat nehme ich an?
so, damit wird das ganze nur von dem change Event aufgerufen. Ein Eventhandler übergibt immer ein Eventobjekt dazu, siehe das Code Beispiel aus der Vorlesung (https://github.com/JirkaDellOro/EIA2_W18_Code/blob/master/L04_FormElements/FormElements.ts#L15). 
Und dann kannst du das machen was @nicoherrmann hier anspricht und auch im Beispielcode in Zeile 18 gemacht wird, du kannst das Ziel des change Events (`target`) abfragen und weiterverwenden (und eben in diesem Fall casten damit es wieder typsicher ist).

**Comment by Plagiatus** [comment]
dieses Target ist dann eben u.U. dein inputfeld, aus dem du dann die von dir gesetzten werte (bisher z.B. `name`, `value` oder `id`) wieder auslesen und verwenden kannst, um zu identifizieren was denn nun geändert wurde.

**Comment by JirkaDellOro** [comment]
@nicoherrmann :+1:

**Comment by jstnez** [comment]
Also lieg ich mit meinen Ansatz diese Sachen mir über das Input zu holen falsch?
Leider dringe ich durch deine Erklärung, Lukas, nicht ganz durch. Kannst du mir das bitte nochmal "für dumme" erklären, oder konketisieren was denn mein nächster Schritt sein sollte. 

Also ich weiß, dass ich eine Schleife brauche um durch meine Produkte durchzulaufen, um im Durchlauf zu checken welche Felder denn geklickt worden sind um diese in das Array von meinem Warenkorb zu pushen. Wenn der Warenkorb aufgebaut ist, sich was verändert, sich der Warenkorb wieder neu aufbaut. Um die Gesamtsumme zu bekommen: den Preis des jeweiligen Produketes mit der ausgewählten Menge zu multipizieren. 

Das ist grade mein Stand, bzw mein Ansatz für den Warenkorb.

**Comment by JirkaDellOro** [comment]
Hallo Justine,
der Ansatz klingt einfach und logisch. Du willst also, wie es bereits in der Aufgabenstellung empfohlen ist, die Zusammenfassung bei jeder Interaktion komplett neu aufbauen. Das macht die Sache einfach. Es wäre nun toll, wenn man dies in deinem Konzept sehen könnte, dann könnten wir dir wunderbar helfen. 

Leider finde ich mich in deinem Repository nicht mehr zurecht. Da gibt es einen Ordner für Aufgabe 5, darin liegen aber Dateien, die mit "Aufgabe 4" bezeichnet sind. Zudem ist der jüngste Push im Ordner für Aufgabe 4 gewesen. Was ist also aktuell?

Bitte räume auf und verweise auf ein aktuelles Konzept.
