### ISSUE TITLE
Warenkorb

### ISSUE THREAD

**Issue by Ruhlnell** [JirkaDellOro/EIA2#249]
https://ruhlnell.github.io/EIA2/Aufgabe 4/Aufgabe4.html

Kann mir bitte jemand beim Warenkorb helfen. Ich will meinen Code so beibehalten, finde jedoch keinen Ansatz für den Warenkorb.

Danke im Voraus:)

**Comment by Plagiatus** [comment]
und das liebe Kinder ist der Grund warum wir keine Leerzeichen in namen verwenden. 😄 

Also "Code so beibehalten" funktioniert grundsätzlich nicht, man braucht wahrscheinlich immer Änderungen, auch wenn es nur kleine sind (und das ist auch das woher die meisten Altschulden kommen beim Programmieren, die es einem später schwieriger machen als es sein müsste).

und was meinst du du findest keinen Ansatz für einen Warenkorb? Du weißt nicht was für eine Datenstruktur du benutzen kannst? Du weißt nicht wie du auf das geänderte zugreifen kannst? du weißt nicht wie du das alles zusammenrechnen kannst? du weißt nicht wie du das darstellen kannst? was genau ist dein Problem, dann helfen wir dir natürlich gerne weiter 👍

**Comment by Ruhlnell** [comment]
Ich weiß nicht wie ich auf das geänderte zugreife.:)

**Comment by Plagiatus** [comment]
hast du dir mal den Lösungsansatz + meine Kommentare in #248 angeschaut? Wenn nicht, hilft dir das? 😃
