### ISSUE TITLE
Mein colorArray wird nicht gefunden und weder Blumen noch Bienen werden angezeigt

### ISSUE THREAD

**Issue by sailechr** [JirkaDellOro/EIA2#25]
Hallo,
mein Problem ist, dass meine Blumen und Bienen nicht angezeigt werden, weil mein ColorArray nicht gefunden wird.
Beste Grüße 
Christias
PS: Link zur Datei: https://github.com/sailechr/EIA2/tree/master/aufgabe7

**Comment by JirkaDellOro** [comment]
1. Code autoformatieren vor dem Commit, sonst sind Fehler viel schwerer zu erkennen
2. Einen Link für die Ausführung des Codes bereit stellen
3. wo soll denn das ColorArray genutzt werden?

**Comment by sailechr** [comment]
Hallo,
danke für die schnelle Antwort und okay erledige ich sofort:).
Es gehört ja zu den Blumen und ich wollte es auslagern, und zwar in die separate TS-Datei für die Blumen.

**Comment by JirkaDellOro** [comment]
Sofort ist vorbei, ich kann nicht erkennen, dass die drei Punkte erledigt worden wären...

**Comment by saenglert** [comment]
Hey Chris,
habs mir gerade mal durchgelesen und das Problem mit dem Code ist, a) dass `colorArray` nicht mit dem Schlüsselwort `export` versehen ist und b) das es Teil der Klasse `Flowers` ist, weshalb `export` an dieser Stelle auch garnicht möglich ist.

Dein Problem ist also erstmal logischer Natur: Wohin gehört das `colorArray` eigentlich? So wie ich das in deinem Code sehe, wird dein `colorArray` lediglich dazu genutzt, eine einzelne Farbe für eine Blume auszuwählen, die dann in `color` gespeichert wird. 

`colorArray` gehört also logisch betrachtet nicht zu der einzelnen Blume, die unsere Klasse und seine Objekte abbilden sollen und haben damit nichts innerhalb der Klasse verloren. Aus meiner Sicht wäre es logischer das Array mit den Farben im Hauptprogramm zu belassen und jedesmal, wenn eine Blume erstellt wird, eine zufällige Farbe aus `colorArray` zu bestimmen und diesen einzelnen String dann an den Konstruktor weiterzureichen.

**Comment by sailechr** [comment]
okay danke :)ich habe es mir schon fast gedacht, aber die Blumen und die Bienen werden immer noch nicht angezeigt, und zwar auf Grund dessen, da´es für mich nicht verständlich ist, was ich in Zeile 183 in meiner canvas.ts Datei bei new Flowers( ) in die Klammer eintragen muss.  Muss ich das auch wie bei den Bienen mit einer Startposition machen ??zum Beispiel über den Constructor ?
Also ich komme da leider nicht weitergerade :(

**Comment by sailechr** [comment]
kleine Korrektur die Bienen werden jetzt zumindest angezeigt:)

**Comment by sailechr** [comment]
https://sailechr.github.io/EIA2/aufgabe7/canvas2.html

**Comment by JirkaDellOro** [comment]
Ich habe Pull-Requests gebastelt: https://github.com/sailechr/EIA2/pulls

**Comment by sailechr** [comment]
vielen Dank :)ich habe es berücksichtigt, aber die Blumen werden immer noch nicht angezeigt und ich habe, aber noch ein anderes Problem, und zwar wie kann man nach einer Pull-request von jemanden seine Dateien auf Github pushen ?
Das geht bei mir momentan leider nicht.

Vielen dank schon im Voraus und schönen Sonntag :)

**Comment by RedImp1470** [comment]
Der richtige Begriff ist bei der Verarbeitung von Pull-Requests ist "mergen". D.h. du bekommst von jemandem ein Pull-Request und möchtest die Änderungen in dein Repository übernehmen.
Dabei gibt es zwei Fälle:

1. Bei einem Merge entstehen Konflikte. Das ist der Fall, wenn du seit dem Pull-Request nochmals Änderungen an Dokumenten vorgenommen hast, die auch von jemand anderem im Request verändert worden sind.
2. Es entstehen keine Konflikte.

Im ersten Fall müssen diese Konflikte vor dem Merge gelöst werden. Dies kann man meistens direkt auf github.com erledigen.

Bitte lies dir dazu die folgenden beiden Artikel durch:
"Merging a pull request" - https://help.github.com/articles/merging-a-pull-request/
"Resolving a merge conflict on GitHub" - https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by JirkaDellOro** [comment]
Ich habe allerdings nur Kommentare eingefügt. Wenn die zur Kenntnis genommen werden und der ursprüngliche Code entsprechend überarbeitet wird, kann man den Request danach auch ignorieren.

**Comment by sailechr** [comment]
dankeschön für die Tipps :) ich versuche es mal mit Ihrem Tipp Herr DellOro.

**Comment by sailechr** [comment]
also irgendwie bekomme ich das alleine nicht hin und die Methode mit dem ignorieren finde ich nicht mehr.
Ich habe jetzt mal alles versucht. 
Trotzdem vielen dank für die Tipps.

**Comment by JirkaDellOro** [comment]
Das Repository ist unabhängig von den Pull-Request. Wenn Du also einfach deine Daten bei dir lokal änderst kannst Du sie ganz normal hochpushen. Ich nutze die Requests für euch nur als Notizzettel.

**Comment by JirkaDellOro** [comment]
PS: wenn Du über die Github-Website etwas verändert hast, musst Du erst einmal lokal einen Pull ausführen, sonst funktioniert der nächste Push nicht.
