### ISSUE TITLE
Produktkategorien?

### ISSUE THREAD

**Issue by GarberoV** [JirkaDellOro/EIA2#250]
https://github.com/GarberoV/EIA2_WS1819/tree/master/Aufgabe4_FormElements

Guten Morgen, 
ich bräuchte Hilfe bei der Bonusaufgabe. Ehrlich gesagt verstehe ich nicht ganz wie das aussehen soll, dass die Händlerin Produktkategorien hinzufügen und löschen kann? 

Danke im Voraus :)

**Comment by JirkaDellOro** [comment]
Klasse, dass Du dich mit der Bonusaufgabe beschäftigst! :+1: 

In meinem Beispielcode habe ich die Struktur schon vorweg genommen. Was bei dir Kategorien wären, ist bei mir der als key bezeichnete Schlüssel, in dem Fall "normal" und "reverse".

In deinem Code weiß derzeit jeder Artikel, zu welcher Kategorie er gehört, da es in seine Eigenschaft "art" geschrieben wurde. Mit meiner Struktur wäre das nicht mehr nötig, da unter der Kategorie als Schlüssel ein Array zu finden ist, welches alle Artikel enthält, die zu der Kategorie gehören.

Hilft das schon? Ansonsten gerne weiter fragen.

**Comment by GarberoV** [comment]
Vielen Dank für die schnelle Antwort :). Ja das hilft mir aufjedenfall schonmal, danke. Ich melde mich nochmal, sobald ich nicht mehr weiter komme. :)
