### ISSUE TITLE
Ausgabe Warenkorb wird überschrieben

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#251]
Moin Moin,

ich habe aktuell dass Problem, dass bei meinem Warenkorb immer die Weihnachtskugeln überschrieben werden. Wenn ich also eine Rote Weihnachtskugel ausgewählt habe und danach eine goldene hinzufügen will, wird diese immer überschrieben und ich weiß nicht warum.

Ebenso scheint mein Code Probleme beim zählen zu haben. Wenn ich den Zähler erhöhe, wird die Zahl nicht immer übernommen und erst wenn ich die Anzahl noch weiter erhöhe, übernimmt er diese wieder oder ich muss sehr lange warten
**(Alles gilt aktuell nur für die Weihnachtskugeln, die restlichen Stepper funktionieren noch nicht)**
HTML: https://dangscha.github.io/EIA2/Aufgabe%205/Aufgabe5.html
Github: https://github.com/dangscha/EIA2/blob/master/Aufgabe%205/Aufgabe5.ts

**Comment by JirkaDellOro** [comment]
Wegen der Kugeln kann ich gerade nicht schauen, aber die Stepper scheinen unter Chrome manchmal Probleme zu haben, da scheinen Event verschluckt zu werden. Könnte sein, dass dies das beobachtete Phänomen darstellt.

**Comment by Plagiatus** [comment]
Also, in Firefox habe ich das oben erwähnte Problem mit den verschluckten Events nicht, sobald ich was ändere, ändert sich auch sofort der Warenkorb.

Und soweit ich das beurteilen kann ist das Problem mit den Kugeln in Z105: du prüfst nur das gerade geklickte ab (`target.id`) und nicht alle anderen. dann wird in Z114 der `ballprice` auf den Wert des aktuell ausgewählten gesetzt und damit bist du fertig. Der Ansatz wie bei `node.innerHTML` += statt = zu verwenden ist gut, kommt bloß leider nicht zum tragen da die if-abfrage nie ein zweites Mal erfüllt ist. 

Außerdem ist mir aufgefallen, dass die forschleife in Z102 durch jedes input element durchiteriert, also durch alle 16 durch geht, und du dann aber in der if nur fragst ob die id stimmt. da wirst du spätestens bei den Kerzen auf Probleme stoßen, da die target.id numberCandles + 0 ist, aber articles[0] ist numberBalls0. Du siehst also, die IF Abfrage ist der Hauptquell des Problems, da müsstest du dir nochmal etwas anderes überlegen.
Du bist schon sehr nah dran.

**Comment by dangscha** [comment]
Super danke, das Problem wäre erstmal gelöst
Nun direkt zum nächsten: In meiner Preisfunktion wird das Attribute price nicht richtig aufgerufen zu werden und er berechnet daher nicht dem Gesamtpreis. Ich finde den Fehler nicht

**Comment by Ahornzweig** [comment]
Hi, ich habe das Gleiche Problem.
Zeile 180:
let articlePrice: number = Number(document.getElementsByTagName("p")[i].getAttribute("price")); 
liest nicht alle Preise korrekt aus (manche bleiben einfach 0).  
HTML: https://ahornzweig.github.io/EIA2/A5/A5.html
Github: https://github.com/Ahornzweig/EIA2/blob/master/A5/A5Kunde.ts

**Comment by Plagiatus** [comment]
@dangscha in Z204 versuchst du über `document.getElementsByTagName("a")[i]` auf das zweite a Element zuzugreifen, was dir ganz brav `<a id="baum">` zurückliefert, was aber natürlich den Preis nicht hat. stattdessen willst du wahrscheinlich auf `checkout.ChildNodes[i]` zugreifen, welches dann wieder den Preis hat.

**Comment by Plagiatus** [comment]
@Ahornzweig bei dir scheint es tatsächlich das genau gleiche Problem zu sein, bloß dass ei dir manche funktionieren weil sie zu den passenden p elementen gehören.

Du hast aber noch ein anderes Problem, schau dir mal das div mit der id "div" an, nachdem du ein paar Sachen ausgewählt hast.

**Comment by Ahornzweig** [comment]
Vielen Dank, es funktioniert jetzt. :)
Nur musste ich dafür ein any benutzen, kann man das irgendwie umgehen?

let article: any = checkout.childNodes[i]
let articlePrice: number = Number(article.getAttribute("price"));

(let articlePrice: number = Number(checkout.childNodes[i].getAttribute("price")); zeigt mir einen Fehler an)

**Comment by JirkaDellOro** [comment]
Was wird angezeigt, wenn Du mit der Maus über childNodes fährst?

**Comment by Ahornzweig** [comment]
Bei. getAttribute wird mir der Fehler angezeigt. 
Property 'getAttribute' does not exist on type 'Node'.

**Comment by Ahornzweig** [comment]
So sieht es jetzt aus:
let article: any = checkout.childNodes[i]
let articlePrice: number = Number(article.getAttribute("price"));

Und angezeigt wurde mir nur die eine Fehlermeldung

**Comment by JirkaDellOro** [comment]
Ok. In unserem Diagramm zur Klassenhierarchie, und vor allem bei MouseOver im Code, siehst Du, dass childNodes eine Liste vpn Nodes ist. Nodes können getAttribute nicht. Da Du weißt, dass es sich nicht um einfache Nodes handelt, sondern um Spezialisierungen (z.B. HTMLDivElement) könntest Du dem Compiler das mit spitzen Klammern mitteilen.

Aber Du könntest auch versuchen, über die children-Liste von checkout zu gehen. Das ist eigentlich die gleiche Liste, aber der Typ ist HTMLElement. Dann könnte es sofort klappen
