### ISSUE TITLE
Anzeigen von Produktkategorien

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#252]
Ich habe Produktkategorien-div's erstellt welche immer der Menge der Kategorien entspricht.
Nun will ich das die Produkte auch in die jeweilige Kategorie angezeigt werden.(so wie in meinem Konzept beschrieben)
Es muss jedoch ein Fehler vorliegen da es nicht alle rein schreibt, sondern nur 2 und dann stoppt die Schleife. 

https://sftp.hs-furtwangen.de/~bommerto/EIA2/Aufagbe_5/Homepage.html  
(github zeigt die html Datei nicht an deswegen der andere Link)

danke im voraus

**Comment by JirkaDellOro** [comment]
Wird angezeigt, wenn Du den Buchstabendreher auch in der URL angibst. Ist aber eklig, daher das bitte korrigieren

https://t0mmy93.github.io/EIA2_Git/Aufagbe_5/Homepage.html

**Comment by JirkaDellOro** [comment]
Die Konsole zeigt gleich einen Fehler an
```
Uncaught TypeError: Cannot set property 'innerText' of null
    at displayProdctsCategories (algorythm.ts:38)
    at HTMLDocument.init (algorythm.ts:7)
```
Geht es darum? Und kriegst Du das selbst hin? Oder geht's um etwas anderes und ich schaue mir den falschen Code an?

**Comment by t0mmy93** [comment]
Ich denke mal das es sich um den Fehler handelt da die schleife dort stoppt und ich auf den ersten Blick nicht weis warum.

**Comment by JirkaDellOro** [comment]
Sorry, war gerade in der :bath:

Also, wenn da steht, dass die Eigenschaft innerText von null nicht definieren kann, wurde das Element nicht gefunden, dessen Eigenschaft angesprochen werden soll. Und da direkt auf Zeile 38 verwiesen wird, ist div2 die Variable, die eigentlich dieses Element referenzieren soll, aber eben lediglich den Wert null aufweist. Dieser wurde offensichtlich in der Zeile darüber zugewiesen, also durch
`let div2: HTMLElement = document.getElementById("div[" + i + "]");`
Kurzer Blick in den Debugger offenbart, dass dies beim dritten Durchlauf geschieht und der Vergleich mit dem bis dahin aufgebauten DOM zeigt, dass nur die div-elemente mit den ids `div[0]` und `div[1]` existieren. Das ist also korrekt so.

**Comment by JirkaDellOro** [comment]
Kann es sein, dass Du an der Stelle eigentlich nicht ein Element aus dem body heraussuchen willst um es ihm wieder anzufügen, sondern ein neues erzeugen möchtest?

Ich bin mir ziemlich sicher, dass dir diese Fehler nicht passieren würden, wenn du dich an die CodingStyles halten würdest. Die Dinge haben keine sprechenden Namen. Welche Bedeutung hat "div2"? Warum heißt die Funktion placeDiv, und nicht displayCategorySelection oder so etwas?

**Comment by JirkaDellOro** [comment]
Die Produktkategorien sind ja da, nur versuchst Du in Zeile 37 diese divs wieder im DOM zu finden. Warum?

**Comment by t0mmy93** [comment]
Aso ok jetzt habe ich es verstanden. 
Ich versuche es zu beheben, bei weiteren Fragen melde ich mich.

**Comment by t0mmy93** [comment]
Ich versuche den legend Elementen ein label und ein input Element zuzuordnen, welches 1. Checkboxen/Radiobutton abbilden soll dem Type entsprechend, welchen ich im Array zugewiesen habe und 2. Die Farben oder Produkteigenschaften, welche als "color" im Array gespeichert sind.
komme jedoch nicht weiter.

https://t0mmy93.github.io/EIA2_Git/Aufgabe_5/Homepage.html

**Comment by JirkaDellOro** [comment]
Erkläre mir bitte, warum die Schleife in Zeile 61 so definiert ist, dass sie so oft laufen soll, wie der Kategoriename Buchstaben hat. Der Zusammenhang erschließt sich mir nicht.

**Comment by t0mmy93** [comment]
Die länge gibt die anzahl der Produkte an in den Kategorien (var Name ungünstig gewählt)

Sie soll solange laufen wie viele Produkte in der Kategorie gespeichert sind und dann sollte sie alle Produkteigenschaften in labels wieder geben (die schleife funktioniert so nicht dies ist mir bewusst ich finde nur keine Lösung dafür auf die schnelle  )

**Comment by JirkaDellOro** [comment]
Das war kein Witz, Du zählst die Buchstaben durch. Schau' doch mal, von welchem Typ _categoryName ist...

**Comment by t0mmy93** [comment]
ohh
