### ISSUE TITLE
key strings

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#254]
ich habe noch mal ne Frage zu den key strings, 

die Fieldset-Erzeugung klappt super, jedoch bekomme ich es nur hin zu allen einzelnen Objekten ein eigenes Fieldset zu erzeugen, jedoch möchte ich nur drei übergeordnete Fieldsets zu den im Array enthaltenen keys erstellen. Ich weiß nicht obs an meiner Konzentration liegt aber ich komme nicht mehr weiter.

[ts-code](https://github.com/lindschoki/EIA2/blob/master/Aufgabe%205/Aufgabe5.ts)

[seitenlink](https://lindschoki.github.io/EIA2/Aufgabe%205/Aufgabe5.html)

**Comment by JirkaDellOro** [comment]
Nimm die Fieldseterzeugung aus den Funktionen raus und setze sie vor die Schleifen. Lass dir von den create-Funktionen die dort erzeugten Inputfelder zurück geben und hänge sie in der aufrufenden Schleife an das Fieldset dran.

**Comment by lindschoki** [comment]
Ich bekomme es leider nicht hin es im Code so umzusetzen, mir machen die typen und der Funktionsaufruf Probleme

**Comment by Plagiatus** [comment]
jetzt wollte ich es mir gerade anschauen? schreibst du ein neues Issue oder hat sich das Problem erledigt?
