### ISSUE TITLE
Zugriff auf ein Array im assoziativen Array

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#255]
Bsp. Code
export let data: HomoVar
        = {
            "normal": [
                { text: "Some text here", value: 101, truth: true, words: ["what", "ever"] },
                { text: "More text here", value: 42, truth: false, words: ["idk", "google it"] }
            ],
            "reverse": [
                { text: "No text here", value: -101, truth: true, words: ["tahw", "reve"] },
                { text: "Less text here", value: -42, truth: false, words: ["kdi", "ti elgoog"] }
            ]
        };

Ich versuche auf words[] zu zugreifen sodass ich die enthaltenen strings getrennt ansteuern kann.
Egal was ich versuche ich bekomme immer nur beide werte am Stück oder einzelne Buchstaben.
Darum wollte ich fragen wie man gezielt auf die einzelnen werte zufreifen kann (mit words[0] z.b. bekomme ich nur den ersten Buchstaben, ich brauche jedoch den ganzen string) 

danke im voraus

**Comment by JirkaDellOro** [comment]
`data["normal"][0].words[1]` sollte dir "ever" liefern. Klappt das nicht?

**Comment by t0mmy93** [comment]
Ok diesen weg habe ich noch nicht probiert, ich habe immer die falsche Syntax genutzt.

Vielen Danke :)

**Comment by JirkaDellOro** [comment]
Vielen Bitte. 

Das hat natürlich schon eine gewisse Komplexität, deshalb habe ich nochmal das Sätzchen dazu geschrieben. Wenn man sich das Schritt für Schritt vor Augen führt steigt man durch
