### ISSUE TITLE
Github Pages werden nicht aktualisiert

### ISSUE THREAD

**Issue by Koelleka** [JirkaDellOro/EIA2#257]
Ich habe die Aufgabe und den Steckbrief hochgeladen, aber die Github Pages werden nicht aktualisiert.

In den Repositories sind alle Codeänderungen drin.
https://github.com/Koelleka/eia2_userpages/blob/master/steckbrief.htm
https://github.com/Koelleka/eia2/tree/master/Aufgabe5

Aber auf den Pages kommt immer ein 404 Fehler bzw. die Seite wird nicht aktualisiert.
https://koelleka.github.io/eia2_userpages/steckbrief.htm
https://koelleka.github.io/eia2/Aufgabe5/Aufgabe5.html

**Comment by Koelleka** [comment]
In Github steht noch diese Fehlernachricht.

Your site is having problems building: Page build timed out. Please try again later.

**Comment by Plagiatus** [comment]
dann liegt es an github, nicht an dir. lass ihm etwas zeit, das fängt sich hoffentlich von alleine wieder.
