### ISSUE TITLE
Value type number aktualisieren

### ISSUE THREAD

**Issue by YannicHermann** [JirkaDellOro/EIA2#258]
https://github.com/YannicHermann/EIA2/tree/master/WS18/Aufgabe_5

Hallo zusammen, 

ich bin dabei meinen Warenkorb aufzubauen. Für die Radio Buttons funktioniert das bereits. Wenn ich aber inputs vom type: number hinzufügen will, muss ich den Preis ja mit der eingebenen Value multiplizieren. Diese ändert sich aber nicht im HTML und bleibt immer der bei Erzeugung definierte Wert. Ich weiß einfach nicht, wie ich diesen Wert "variabel" machen kann, damit ich den Preis richtig ausrechnen kann. 

Über einen kleinen Denkanstoß wäre ich dankbar.

**Comment by Plagiatus** [comment]
Sehr seltsam. versuche mal den Standardwert auf "0" statt auf "" zu setzen und schaue ob es dann geht, weil eigentlich ist das der richtige Ansatz.

ansonsten schau dir mal das von @ruhlnell an, da geht es zum Beispiel und es ist auch über value gelöst.
https://ruhlnell.github.io/EIA2/Aufgabe5/Aufgabe5.html

**Comment by saenglert** [comment]
Der Bezeichner `value` den du im HTML angibst ist nicht dersselbe, den du in JS abfragst.

Stell es dir so vor:
```
class NumberInput {
  value: number;
  constructor(value: number) {
    this.value = value;
  }

  up() {
    this.value += 1;
  }
} 
```

Was du im HTML machst ist ein neues "Object" vom Typ Input zu erzeugen und übergibst im als Parameter den Typ "Number" und den Value "1". Anschließend kann dieser Wert intern geändert werden, z.B. wenn du einen neuen Wert eintrippst oder die Pfeile benutzt.

Was jetzt in JS passiert, wenn du
```
myInput.value
```
aufrufst, ist dass du auf den aktuellen internen Wert von Value zugreifst. Nicht den ursprünglichen Parameter. Solltest du diesen brauchen bekommst du den über:
```
myInput.getAttribute("value")
```

**Comment by Plagiatus** [comment]
@saenglert er macht es doch über `getAttribute` bzw `setAttribute`. Du hast aber auch recht, dass er "value" zweimal als Variablenname verwendet, evtl etwas ungünstig.

**Comment by saenglert** [comment]
Ich hab mich nicht in den Code reingewühlt (bin grade auf der Arbeit).

Was ich allerdings empfehlen würde, ist die `get/setAttribute` zu vermeiden, da die HTML Attribute wie beschrieben eher als Ausgangsparameter funktionieren und von den Objekten intern geändert werden.

Das bedeutet, dass z.B. der User eine Änderung am Input vornimmt, wird diese nicht berücksichtig, wenn `getAttribute("value")` aufgerufen wird (es nur der "Startwert" abgefragt), während `input.value` immer die aktuell ausgewählte Zahl beinhaltet.

Und das ist ja genau das Problem das Yannick gerade beschrieben hat. Er bekommt nur den anfänglichen Wert und möchte allerdings den aktuellen Wert haben.

**Comment by JirkaDellOro** [comment]
Es ist so, dass `input.getAttribute("value")` etwas anders ergibt/ergeben kann, als `input.value`

Dein Klassenbeispiel, Sascha, ist für manche wahrscheinlich verwirrend, da wir noch nicht bei Klassen waren.

**Comment by saenglert** [comment]
Oh wups, my bad (^.^)*

**Comment by YannicHermann** [comment]
Okay, danke für die Antworten! 
Probiere nochmal rum. Das mit dem Standardwert = "0" funktioniert leider schon mal nicht ..

**Comment by YannicHermann** [comment]
https://github.com/YannicHermann/EIA2/blob/master/WS18/Aufgabe_5/Aufgabe_5.ts#L90

Code läuft jetzt. Habe mir den Value jetzt über TypeScript geholt. Im HTML-Attribut aber bleibt alles beim Gleichen irgendwie..
