### ISSUE TITLE
Stepper Value lässt sich nicht multiplizieren

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#259]
Ich schaffe es nicht den Wert zu multiplizieren, welcher im Stepper steht.
https://t0mmy93.github.io/EIA2_Git/Aufgabe_5/Homepage.html

Ich habe auch schon diesen issue angeschaut aber hat nichts geholfen.

https://github.com/JirkaDellOro/EIA2/issues/258

**Comment by JirkaDellOro** [comment]
Wenn ich in die Konsole schaue, sehe ich viel null und NaN. Hast Du da mal geschaut? Konvertierst Du die Strings aus den HTML-Attributen auch brav in numbers?

**Comment by t0mmy93** [comment]
ja ist alles in Numbers umgewandelt.

in der console stimmen die werte auch, wenn ich sie mir ausgeben lass deswegen wundere ich mich.

**Comment by JirkaDellOro** [comment]
Gib' mir mal bitte einen Hinweis auf die Zeile, in der Du das Problem vermutest.

**Comment by JirkaDellOro** [comment]
Jedenfalls sieht man schon in der Domstruktur, dass die Stepper keine price-info tragen

**Comment by t0mmy93** [comment]
Es muss sich um die function in Zeile 147 ff. handeln, da die Übergabewerte alle stimmen laut console.log.

**Comment by t0mmy93** [comment]
Ich habe den Steppern den Price zugewiesen nun geht es.

Danke :)

**Comment by JirkaDellOro** [comment]
Ich habe aber Zweifel an der Konzeption, wenn ich den Code so anschaue. Der Aufbau das Warenkorbs scheint um das jeweils angeklickte Element zentriert zu sein, das wäre der harte Weg...
