### ISSUE TITLE
Fehler beim Erkennen von crc2

### ISSUE THREAD

**Issue by JanaBurger** [JirkaDellOro/EIA2#26]
Hallo,
bei mir erscheint in Zeile 13 ein Fehler ("Cannot redeclare block-scoped variable crc2"), der auch schon angezeigt wird wenn ich den Code aus der Vorlesung bei mir reinkopiere. Deshalb kann ich weder den Vorlesungscode noch meinen eigenen zum Laufen bringen. 
Ich weiß leider nicht woran das liegen könnte.
Wenn mir jemand helfen könnte wäre ich sehr dankbar:)
Hier der Link:

https://janaburger.github.io/EIA2/aufgabe7/aufgabe7.html
bzw.
https://github.com/JanaBurger/EIA2/blob/master/aufgabe7/js/aufgabe7.ts

Danke schonmal,
Jana

**Comment by JirkaDellOro** [comment]
Mein erster Tipp wäre die namespace-Bezeichnung. Da steht noch "L7-Classes". Das würde auch dazu passen, dass es sich mit meinem Vorlesungscode beißt, der nutzt die gleiche Bezeichnung...

**Comment by JanaBurger** [comment]
Okay danke, dieses Problem wäre gelöst.:)
Allerdings wird mein Canvas immer noch nicht angezeigt und ich weiß nicht warum. Die Konsole hilft mir irgendwie auch nicht weiter. Über einen weiteren Tipp würde ich mich sehr freuen.

**Comment by JanaBurger** [comment]
Okay, so ein doofer Fehler. Hatte die Dateien im HTML falsch verlinkt...

**Comment by JirkaDellOro** [comment]
Klassiker, passiert mir auch dauernd...
