### ISSUE TITLE
Heroku App Implementierung

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#262]
Hallo,
ich verstehe den Teil 3 der neuen Aufgabe nicht so genau. Sprich wie ich genau die neu erstellte App richtig zum laufen bringe. Genauso wenig verstehe ich den Teil mit dem Beispiel Query.
Wäre super wenn mir da jemand weiter helfen kann :)

**Comment by NicoKlein97** [comment]
Heyho,
hast du dir den Heroku-Teil in der Mind Map angesehen ? Wenn nicht, versuche mal dich daran zu halten und schau ob es dann funktioniert.

Mind Map: https://jirkadelloro.github.io/FreeMindViewer/?map=EIA2.mm&path=https://jirkadelloro.github.io/EIA2

Ihr habt ja gelernt, wie ihr Daten über die URL im Browser verschicken könnt. Jetzt sollen die Daten, welche du in der URL übergibst, beim ausführen der App in einem neuen Tab ausgegeben werden. Zum Beispiel als einfacher text im Browser-Fenster.

Ich hoffe das hilft.

**Comment by haasmanu** [comment]
Die Mindmap habe ich mir angeschaut und genauso befolgt. Dennoch bin ich sehr verunsichert was die nächsten Schritte betrifft :/

**Comment by NicoKlein97** [comment]
An welchem genauen Punkt bist du denn jetzt ? Hast du schonmal versucht die App zu starten ?

**Comment by haasmanu** [comment]
Das weiß ich nicht so ganz wie das gehen soll.

**Comment by NicoKlein97** [comment]
Wenn du in deiner Heroku App-Übersicht bist, klick auf die angelegte App, gehe dann auf den Reiter Deploy, checke hier nochmal ob bei "Deployment Method" Github ausgewählt ist, scrolle ganz nach unten und drücke "Deploy Branch".

Dann müsste das ganze starten.

**Comment by MonettaMarchiano** [comment]
Ich hab das soweit befolgt. "Deploy Branch" -> view  kommt nur ein Application Error.

https://eia-2-marchian.herokuapp.com

<img width="378" alt="bildschirmfoto 2018-12-01 um 21 13 25" src="https://user-images.githubusercontent.com/32566125/49332494-07df7600-f5ae-11e8-9e57-370ff8c72c0e.png">

Was mach ich jetzt?

**Comment by haasmanu** [comment]
Super es hat geklappt danke :)

**Comment by Plagiatus** [comment]
@MonettaMarchiano hat das mit dem Deploy geklappt? gab es da eine Fehlermeldung oder so? was wird dir angezeigt, wenn du hier klickst (oben rechts)?
![grafik](https://user-images.githubusercontent.com/7681159/49332781-973b5800-f5b3-11e8-84bd-5a988b19e276.png)

**Comment by Plagiatus** [comment]
@MonettaMarchiano bzw ich habe das Problem schon gefunden. Überprüfe den "scripts" Pfad in deiner package.json, das muss auf die Datei zeigen, ausgehend von da wo die package datei liegt.

**Comment by haasmanu** [comment]
Hallo ich nochmal, hab einen Error angezeigt bekommen...was soll ich tun?
![error](https://user-images.githubusercontent.com/43847187/49332928-64df2a00-f5b6-11e8-90a9-385c923c5a6c.JPG)

https://eia2-manu.herokuapp.com

**Comment by Plagiatus** [comment]
Deine Server.js Datei ist leer, da kann ja nichts funktionieren.

**Comment by haasmanu** [comment]
Okay sorry da hat was mit Server.js.map nicht so ganz geklappt...hat jetzt geklappt vielen dank

**Comment by MonettaMarchiano** [comment]
Jetzt hat es geklappt, vielen Dank!

**Comment by girrbacv** [comment]
Bei mir wird das bei View Logs angezeigt...
<img width="1213" alt="bildschirmfoto 2018-12-02 um 16 46 21" src="https://user-images.githubusercontent.com/43846396/49341733-e89a2480-f651-11e8-83fe-ab4fcbe4466f.png">

**Comment by Ljubaska** [comment]
Habe gleiches Problem wie Verena ..

**Comment by JirkaDellOro** [comment]
Vergleicht einmal die Datei package.json mit meiner. Ihr teilt dem Heroku-Rechner nicht mit, dass er überhaupt node starten soll...

**Comment by Ljubaska** [comment]
![bildschirmfoto 2018-12-02 um 17 13 12](https://user-images.githubusercontent.com/43846372/49342030-a70b7880-f655-11e8-9c78-21c2f5983fd0.png)

Jetzt wird nur noch das hier angezeigt..
