### ISSUE TITLE
Server.js lässt sich mit node nicht starten

### ISSUE THREAD

**Issue by Koelleka** [JirkaDellOro/EIA2#263]
Die Server.ts kann mit jslint erfolgreich kompiliert werden.
Wenn ich die Server.js mit node starten will kommt:

`SyntaxError: Unexpected token import`
Startbefehl: `node Server.js`

Wenn ich die Server.js mit experimental-mode starte dann kommt der Fehler:
`SyntaxError: Unexpected token *`
Startbefehl: `node --experimental-modules Server.js`

Die installierte Node Version ist `v10.14.1` (Hab ein Update installiert, davor war die `v8.12.0` installiert)
Befehl: `node --version`
Aber wieder genau der gleiche Fehler:
`SyntaxError: Unexpected token *`

Sieht nicht nach einem Eclipse Fehler aus. Die ts-Dateien konnten auch alle kompiliert werden und ich nutze node ja nicht mit der Eclipse Konsole, sondern mit der Mac Konsole (terminal).

Vielleicht ist es auch nur ein Konfigurationsfehler. In meinem Eclipse ist nicht die interne node Version eingestellt (`v6.9.4`), sondern ich hab das auf die eigene Installation geändert `v10.14.1`.
[Vielleicht hilft das?](https://stackoverflow.com/a/35728427)

**Comment by Plagiatus** [comment]
Dein Link ist schon sehr nah dran (gute Arbeit bei der Fehlersuche übrigens! 👍 ). Bist du sicher, dass du die Übersetzungseinstellungen in Eclipse für das Typescript richtig eingestellt hast? Weil aus dem `import * as Http from "http";` sollte in der js Datei eigentlich `const Http = require("http");` werden.
Node unterstützt import aus ES6 noch nicht wirklich, darum sollte die ES5 version genutzt werden. 

_Auch die Sache mit der experimental-modules option is machbar, dann musst du deine .js Datei aber in eine .mjs Datei wandeln glaube ich._

**Comment by Koelleka** [comment]
Okay danke hat funktioniert :)
es5 Kann ich bei mir in der Konfiguration nicht auswählen, aber commonjs.

Das war die ursprüngliche Konfiguration:
<img width="469" alt="falsche_config" src="https://user-images.githubusercontent.com/28564632/49333543-fb184d80-f5c0-11e8-8f1f-1bac7a511d50.png">

Und das ist die neue und mit der geht es jetzt (`commonjs`):
<img width="454" alt="richtige_config" src="https://user-images.githubusercontent.com/28564632/49333545-03708880-f5c1-11e8-8ec2-ae0f79dab421.png">

Und für das er die richtige Node Version noch nimmt diese Einstellung:
<img width="619" alt="nodejs_config" src="https://user-images.githubusercontent.com/28564632/49333551-0f5c4a80-f5c1-11e8-9fe7-440a85315101.png">
