### ISSUE TITLE
node.d.ts und server.ts fehlerhaft

### ISSUE THREAD

**Issue by Cryray** [JirkaDellOro/EIA2#265]
Die Node.d.ts Datei wird bei mir mit vielen kopiert, die Fehler beziehen sich alle auf die Fehlerausgabe : "Duplicate Identifier ". Zudem werden bei meiner Server.ts Datei Modul http und name process nicht gefunden.
Danke schon mal im vorraus

**Comment by Cryray** [comment]
Hab ich gemacht und das Problem existiert leider immernoch.

**Comment by Plagiatus** [comment]
Dann überprüfe bitte deine Typescript Build Einstellungen, kann ja fast nur noch daran liegen. Wenn die auch alle Stimmen bin ich überfragt.al Eclipse neu gestartet? 🤔

**Comment by Cryray** [comment]
Die stimmen auch alle und neu gestartet hatte ich es auch schon mehrmals.. Gibt es noch ne alternativ Lösung damit ich die Aufgabe wenigstens bearbeiten kann?

**Comment by Cryray** [comment]
Also ich arbeite auf jeden Fall mit Eclipse, ich hab die Einstellungen in der Mindmap auch. Node Version hab ich gerade nochmal die aktuellste runtergeladen. Und node.d.ts liegt auf der obersten Ebene. Hab auch schon probiert sie im Server Ordner zu platzieren hat aber auch nicht geholfen.

**Comment by Cryray** [comment]
Ok nvm ich hab den Fehler glaube ich gefunden 
Danke trotzdem für die Hilfe

**Comment by JirkaDellOro** [comment]
Und Du glaubst, Du kommst so leicht davon ohne uns aufzuklären? Was war der Fehler?

**Comment by Cryray** [comment]
Ich habe den Fehle jz erst gefunden. Und zwar hatte ich noch eine andere TypeScript Version drauf die sich über die andere installierte geschoben hat. Somit hab ich immer mit der falschen Version von TS gearbeitet. Einmal deinstalliert und neugestartet und jz funktionierts 👍
