### ISSUE TITLE
GitHub Push Fehler

### ISSUE THREAD

**Issue by JannisBackhaus** [JirkaDellOro/EIA2#266]
Hallo, 
ich habe meinen Server lokal getestet und will jetzt Heroku verlinken und stelle fest, dass Eclipse die Daten nicht pushen kann. Ich kriege als Meldung immer nur `master -> master [rejected -  non-fast-forward]`.
Was könnte das Problem sein? 

Danke! 
Jannis

**Comment by Plagiatus** [comment]
Führe zuerst über den Menüpunkt Team einen pull aus, eventuell reicht das schon und du musst nicht die ganze Sache neu synchronisieren.

**Comment by t0mmy93** [comment]
Bei mir auch, hab auch gepullt.

Geh einfach auf dein Repository und klick upload file und zieh den Ordner rein.

**Comment by JannisBackhaus** [comment]
@Plagiatus Das hatte ich schon mehrfach versucht, hab auch Eclipse beendet und wieder gestartet aber es hat einfach nichts getan.
Habs so wie Nico gemacht und funktioniert wieder alles 👍  
Danke für die Hilfe !

**Comment by JirkaDellOro** [comment]
Beachtet bei der Arbeit immer die vorgeschriebene Reihenfolge (siehe MindMap) um solche Desyncs zu vermeiden. Also IMMER erst pullen bevor ihr irgendetwas anderes macht. Spätestens, wenn ihr im Team arbeitet, geht ihr sonst durch das Tal der Tränen.
