### ISSUE TITLE
_response.write und Heroku

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/EIA2#267]
Hallo,
bei der Bearbeitung der Aufgabe, bin ich auf zwei größere Probleme gestoßen.

1. mein neues _response.write() tut nicht was es soll. 
_response.write(Url.parse(url, true).toString()) ist mein aktueller Code 
"[object Object]" ist jetzt im browser zu sehen. 

Davor habe ich es mit:  _response.write(Url.parse(url, true).query); 
und:  _response.write(Url.parse(url, true).query.toString());
probiert. 

Über: console.log(Url.parse(url, true).query);
wird mir in meinem Terminal jedoch das Richtige angezeigt.
url ist hierbei eine von mir deklarierte Variable, die aus _request.url besteht.
Die Frage, ist also, wie ich _response.write() richtig umsetzen kann.

2. Das ganze funktioniert nur mit meinem localhost8100. Muss ich irgendwas bei Heroku verändern, damit das wieder für den Konfigurator funktioniert?

Github: https://github.com/Ahornzweig/EIA2/blob/master/L06_SendData/Server/Server.ts

**Comment by JirkaDellOro** [comment]
So extrem trivial ist die Aufgabe nun auch wieder nicht, dass es ein Einzeiler wäre. Schau noch einmal in die Aufgabenstellung. Die Ausgabe im Browser soll schließlich bewusst formatiert und mit Zeilenumbrüchen etc. formatiert sein.

**Comment by Ahornzweig** [comment]
Okay, danke.

**Comment by Ahornzweig** [comment]
Nochmals danke. Da muss ich dann auch noch mal nachschauen 😅
