### ISSUE TITLE
Aufgabe 7.1 Umbruch

### ISSUE THREAD

**Issue by nicoherrmann** [JirkaDellOro/EIA2#268]
Guten Abend,
hab es soweit hinbekommen, dass er den search-String bei "&" trennt und in ein Array packt (aktuell noch kein assoziatives Array.
Der angezeigt Text wird dann auch in Abhängigkeit des Arrays generiert.
Da es allerdings keine richtige HTML Seite ist (glaube ich?) gibt es auch keinen Body auf den ich zugreifen kann zumindest hat mir da der Terminal nur fehler angezeigt
![body](https://user-images.githubusercontent.com/43846525/49469877-eaf2af00-f808-11e8-808d-a228dcb839de.png)
Bemerkung: Der Teil mit dem body ist nicht gepusht da es sonst garnicht funktioniert

Zurück zu meiner Frage:
Da ich nicht auf den Body zugreifen kann und auch anderweitig nicht weiß wie ich einen Umbruch machen soll, damit das strukturiert ausgegeben wird weiß ich nicht weiter.
Server.ts: https://github.com/nicoherrmann/EIA2/blob/master/L06_SendData/Server/Server.ts
(Umbruch bräuchte in ab Zeile 53)

Mein WBK: https://nicoherrmann.github.io/EIA2/Aufgabe5v2/Konfigurator.html
zum testen der Übertragung

Mfg
Nico

**Comment by nicoherrmann** [comment]
> Das ist schon ziemlich gut. Aber die Zerlegung in ein Array ist viel zu kompliziert. Der parse-Befehl kann noch einen zweiten Parameter schlucken, schau dir das mal an.

Hab ich eigentlich gemacht sogar in der Mindmap aber iwie bekomm ichs nicht ganz gebacken aber das mit dem Umbruch funktioniert jetzt danke!
Hatte das sogar auch schon im Kopf gehobt aber habs verworfen weil ich dachte, dass das nur bei innerHTML funktioniert

**Comment by JirkaDellOro** [comment]
Es ist eigentlich auch ähnlich, nur das zwischen der Zeichenkette und der Interpretation derselben die Übertragung vom Server zum Client geschieht.
