### ISSUE TITLE
Komme nicht weiter

### ISSUE THREAD

**Issue by LuisaCarmen** [JirkaDellOro/EIA2#269]
Hallo,

ich kann einfach nichts zu der neuen Aufgabe finden und weiß auch nicht wie ich es umsetzen soll...es sieht so aus, als wäre ich nicht alleine damit, weil in unserer MKB Gruppe anscheinend alle auf dem Schlauch stehen und nicht weiter kommen bzw. nicht wissen wie sie anfangen sollen oder wo man recherchieren kann... .

Ich wäre sehr dankbar für einen Anhaltspunkt.
Grüße, Luisa

**Comment by caddarndt** [comment]
Dem kann ich mich nur anschließen

**Comment by saenglert** [comment]
Ok, wenn ihr allerdings auch nicht formulieren könnt wo es klemmt oder welchen Teil der Aufgabe man nochmal genauer besprechen sollte, dann kann ich euch auch nicht helfen, ohne eine Schritt für Schritt Lösung zu schreiben. Dafür würde ich allerdings einen Klapps auf den Hinterkopf von oben bekommen, weswegen ich das lieber sein lasse.

**Comment by JirkaDellOro** [comment]
Wir hatten in der Vorlesung sogar zwei Lösungen aufgezeigt und waren auf den Seiten mit den entsprechenden Dokumentationen der Module bzw Klassen queryString und Url von Node.js. Ich empfehle Url.
