### ISSUE TITLE
Objekte werden nicht in das Array gespeichert

### ISSUE THREAD

**Issue by JacquelineWagner** [JirkaDellOro/EIA2#27]
Hallo,

irgendwie werden die neuen Blumen nicht in das Array gespeichert.
In der Konsole wird zwar angezeigt, dass das Array vorhanden ist, jedoch eine Länge von Null hat.

Hier der Link:
https://jacquelinewagner.github.io/EIA2/aufgabe7/aufgabe7.htm

Danke im Voraus

**Comment by JirkaDellOro** [comment]
Wo soll denn das Speichern geschehen? Für die Bienen sehe ich ein beeData,push im Hauptprogramm, aber ich konnte nicht erkennen, wo das flower-Array neue Elemente erhalten soll...
