### ISSUE TITLE
Probleme mit Eclipse, GitHub & Heroku und Kursseite nicht erreichbar

### ISSUE THREAD

**Issue by MonettaMarchiano** [JirkaDellOro/EIA2#270]
Hallo,

ich habe folgende Probleme: Ich kann auf Eclipse zwar meine Sachen committen, aber die landen nicht auf GitHub, also muss ich sie manuell selbst verändern. Das sehe ich daran, dass es keine Updates gibt. 
Zudem habe ich auf Heroku einen Application Error und die URL der Kursseite wurde auf dem Server nicht gefunden. 

Also die Aufgabe für morgen ist online, aber wäre super wenn mir jemand helfen könnte das Commit Problem und den Application Error zu lösen. Vielen Dank schon mal :)
<img width="527" alt="bildschirmfoto 2018-12-05 um 21 57 18" src="https://user-images.githubusercontent.com/32566125/49543591-ed243e80-f8d8-11e8-85fa-351f29141acd.png">
<img width="527" alt="bildschirmfoto 2018-12-05 um 21 56 53" src="https://user-images.githubusercontent.com/32566125/49543586-eb5a7b00-f8d8-11e8-897b-11241523cdf4.png">

**Comment by JirkaDellOro** [comment]
gepullt hattest Du?

**Comment by JirkaDellOro** [comment]
... und was heißt: "also muss ich sie manuell selbst verändern"?

**Comment by saenglert** [comment]
> zwar meine Sachen committen, aber die landen nicht auf GitHub

Du erwähnst den Zwischenschritt `pushen` nicht. Vergisst du den Schritt vielleicht?

**Comment by MonettaMarchiano** [comment]
> Du erwähnst den Zwischenschritt `pushen` nicht. Vergisst du den Schritt vielleicht?

Nein, den habe ich nicht vergessen, hab ihn nur nicht erwähnt, war aber mit Commiten gemeint.



> gepullt hattest Du?
Soweit schon. 



> ... und was heißt: "also muss ich sie manuell selbst verändern"?

Mann kann doch direkt Dateien ändern ohne dafür Eclipse aufmachen zu müssen und das habe ich bei den jeweiligen Dateien gemacht.

**Comment by Plagiatus** [comment]
> Du erwähnst den Zwischenschritt pushen nicht. Vergisst du den Schritt vielleicht?

Unwahrscheinlich. In Eclipse ist das normalerweise automatisch beides ("commit and push").

Dein letzter Commit auf GitHub war vor 40 Minuten (also ca. 15 Minuten bevor du hier gepostet hast), kommt das hin? 

Ich kann bestätigen, dass die Kursseite (und auch alles andere was mit dem Webuser zu tun hat) aktuell defekt sind, ich komme auch nicht drauf. 

Wenn Heroku einen Application Error hat, dann brauchen wir die Logs (s. #262 wie man die findet) um einen eventuellen Fehler finden zu können.

**Comment by MonettaMarchiano** [comment]
> > Du erwähnst den Zwischenschritt pushen nicht. Vergisst du den Schritt vielleicht?
> 
> Unwahrscheinlich. In Eclipse ist das normalerweise automatisch beides ("commit and push").
> 
> Dein letzter Commit auf GitHub war vor 40 Minuten (also ca. 15 Minuten bevor du hier gepostet hast), kommt das hin?
> 
> Ich kann bestätigen, dass die Kursseite (und auch alles andere was mit dem Webuser zu tun hat) aktuell defekt sind, ich komme auch nicht drauf.
> 
> Wenn Heroku einen Application Error hat, dann brauchen wir die Logs (s. #262 wie man die findet) um einen eventuellen Fehler finden zu können.

Eben, ich klicke direkt immer auf commit and push.
Ja genau, das kommt ca. hin. Ich bin auf #262 gegangen und hab auf Heroku in View Logs geklickt, verstehe aber nicht so viel davon. Was muss ich denn tun?


<img width="1228" alt="bildschirmfoto 2018-12-05 um 23 09 17" src="https://user-images.githubusercontent.com/32566125/49547375-ce2aaa00-f8e2-11e8-82a8-dae67ad41483.png">

**Comment by Plagiatus** [comment]
Mhhh, die .js Datei scheint Typescript und nicht Javascript zu sein. Dann stürzt es natürlich ab. Stelle sicher, dass der kompilierte js Code in der Server.js Datei ist, und nicht der Code aus der Server.ts. ich vermute da ist etwas beim manuellen editieren schief gegangen?

Außerdem, Versuche einen Team > Pull in eclipse durchzuführen, evtl löst das das Push Problem.

**Comment by MonettaMarchiano** [comment]
Das wars tatsächlich! Vielen Dank :)

**Comment by JirkaDellOro** [comment]
Daher meine Frage:  ... und was heißt: "also muss ich sie manuell selbst verändern"?

Und die Antwort: "Mann kann doch direkt Dateien ändern ohne dafür Eclipse aufmachen zu müssen und das habe ich bei den jeweiligen Dateien gemacht."

Und nun meine Empfehlung: NICHT MACHEN!
