### ISSUE TITLE
Eclipse spinnt

### ISSUE THREAD

**Issue by MonettaMarchiano** [JirkaDellOro/EIA2#272]
Hallo,

mein Eclipse spinnt mal wieder: es sagt mir, dass bei der ts-Datei bei der letzten Klammer, also die vom Namespace: "Declaration or statement expected." Dadurch kann ich natürllich meine Datei nicht kompilieren lassen um zu sehen ob der Code funktioniert. 

<img width="728" alt="bildschirmfoto 2018-12-09 um 15 08 11" src="https://user-images.githubusercontent.com/32566125/49698510-2f919800-fbc5-11e8-978d-b5e61163646d.png">
Die Datei selbst ist hochgeladen! 
[https://github.com/MonettaMarchiano/EIA2/blob/master/Baumgenerator_99/scripts/main.ts]

Meine data.ts - Datei möchte allerdings auch nicht aktualisiert werden, obwohl keine Fehler angezeigt werden. Ich hab bereits mehrmals schon das Projekt gecleart, Eclipse neu gestartet usw. 

Kann mir jemand helfen?

**Comment by NicoKlein97** [comment]
Könnte ein Klammer-Fehler sein. Hast du mal alle Klammern in deinem Code gecheckt um zu sehen wann sie wo schließen ? Vielleicht ist irgendwo eine nicht korrekt geschlossen.

**Comment by MonettaMarchiano** [comment]
Wenn ich eine weitere Klammer einfüge, dann kommt genau die selbe Fehlermeldung. Entferne ich sie, kommen 12 Fehlermeldungen, dass gewisse Dinge nicht gefunden werden, also weil der Namespace dann ja nicht funktioniert..

**Comment by nicoherrmann** [comment]
![monetta](https://user-images.githubusercontent.com/43846525/49698865-17704780-fbca-11e8-9c50-8ff96332effb.png)
Du hast den namespace direkt am Anfang wieder geschlossen

**Comment by Plagiatus** [comment]
Wenn du dir mal deinen Code formatieren lässt, dann siehst du besser, wo was zu oder auf geht. Die Tatsache dass die Z28 wieder ganz vorne ist ist ein Zeichen, dass der Namespace bereits beendet wurde.

**Comment by MonettaMarchiano** [comment]
Ich hab noch mal was umgeändert und jetzt kommt die Meldung: } expected. Wenn ich die Klammer aber dazu packe, dann kommen folgende Fehlermeldungen: 

<img width="908" alt="bildschirmfoto 2018-12-09 um 16 11 02" src="https://user-images.githubusercontent.com/32566125/49699090-1987d580-fbcd-11e8-9e91-4d7196c9bb01.png">

**Comment by MonettaMarchiano** [comment]
hab die Klammer in Zeile 28 entfernt und es kommen in Zeile 29-49 und 495-508 die Meldung: statements are not aligned. 

und wenn ich ganz unten die Klammer hinzufüge, dann kommen in Zeile 286 und 392 die Fehlermeldung "Cannot find name "createPragraph".

**Comment by MonettaMarchiano** [comment]
[https://github.com/MonettaMarchiano/EIA2/blob/master/Baumgenerator_99/scripts/main.ts](url) Entschuldigung, hab nicht dran gedacht

**Comment by JirkaDellOro** [comment]
Der Link führt ins Nichts...

**Comment by Plagiatus** [comment]
der obige Link funktioniert nicht, weil er relativ verlinkt, aber in der ersten Nachricht ist einer der passt, bloß nicht klickbar. 
https://github.com/MonettaMarchiano/EIA2/blob/master/Baumgenerator_99/scripts/main.ts

soweit ich das sehe schließt du die Funktion init nicht, außerdem ist nach "write Basket" soweit ich das sehen kann eine Klammer zu viel. nach writePersonsData fehlen einige Klammern und dementsprechend sind nach createParagraph einige zu viel.

**Comment by JirkaDellOro** [comment]
Die letzte Klammer lässt mich zweifeln, dass hier letztlich eine Autoformatierung durchgeführt wurde.

**Comment by JirkaDellOro** [comment]
erneut: Du solltest uns bei der Fehlersuche helfen...!

**Comment by MonettaMarchiano** [comment]
> der obige Link funktioniert nicht, weil er relativ verlinkt, aber in der ersten Nachricht ist einer der passt, bloß nicht klickbar.
> https://github.com/MonettaMarchiano/EIA2/blob/master/Baumgenerator_99/scripts/main.ts
> 
> soweit ich das sehe schließt du die Funktion init nicht, außerdem ist nach "write Basket" soweit ich das sehen kann eine Klammer zu viel. nach writePersonsData fehlen einige Klammern und dementsprechend sind nach createParagraph einige zu viel.

Also die Init habe ich jetzt geschlossen, die Meldungen von Zeile 29-49 ist nun weg. Bei writeBasket passt alles soweit, das hab ich gerade noch mal nach geprüft. ich habe bei writePersonsData eine hinzugefügt, zwei bei createParagraph entfernt, jedoch bleibt bei den Zeilen 497-510, also createParagraph, die Meldung: statements are not aligned und dazu werden in der Zeile 288 und 394 "Cannot find name createPragraph".

**Comment by JirkaDellOro** [comment]
... was nicht wirklich gut ist, den er verhindert, dass Du lernst dir selbst zu helfen

**Comment by MonettaMarchiano** [comment]
Die Autoformatierung habe ich vorhin schon mehrmals gemacht und es wurde mir keine Klammer zu viel oder zu wenig angezeigt. Das Problem ist immer noch das selbe wie vorhin..

**Comment by MonettaMarchiano** [comment]
Hab das Problem gefunden: es war die vorletzte Klammer die zu viel war und bei der writePersonData fehlte die Klammer zum Schließen.

**Comment by JirkaDellOro** [comment]
Es wird dir nicht angezeigt, welche Klammer fehlt oder zuviel ist. Aber Du siehst sofort, ob 
- zwei folgende Klammern in der gleichen Einrückungstiefe sind
- die letzte Klammer auf die erste Einrückungseben kommt oder nicht mehr
- deine Funktionen alle die gleiche Einrückungstiefe besitzen und so weiter
Du musst also nach solchen Merkmalen schauen. Der Compiler kann nicht erkennen, ob das so sein soll oder ein Fehler ist. Das kannst Du selbst viel besser.

Und wenn Du es nicht sehen solltest, die Betreuer sehen es und freuen sich, wenn Du Ihnen damit hilfst dir zu helfen. Also, wie schon mehrfach gefordert,
## vor dem Commit IMMER Autoformat! ##
Ich werde in Zukunft die Unterstützung ablehnen, wenn diese einfache Regel nicht befolgt wird.
