### ISSUE TITLE
Heroku: Kann nicht deployen

### ISSUE THREAD

**Issue by Lizzyfrmdblck** [JirkaDellOro/EIA2#273]
Hey Leute,

Ich habe ein neues Heroku-Profil angemeldet, weil die neue Aufgabe mit dem alten heroku-Link nicht funktioniert hat und ich dachte, es liegt vllt an falschen Einstellungen - jetzt kommt, sobald ich auf "Deploy branch" klicke, leider folgende Fehlermeldung:

!     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

Jetzt bin ich etwas ratlos, denn ohne den Heroku-Link kann ich die neue Aufgabe nicht machen. 

Hat jemand ne Idee?

**Comment by JirkaDellOro** [comment]
Hört sich nach fehlender oder falscher Datei "package.json" an. Wenn Du Links posten würdest, könnte man dir besser helfen
