### ISSUE TITLE
Heroku App Error

### ISSUE THREAD

**Issue by grandalf94** [JirkaDellOro/EIA2#274]
Ich habe die Aufgabe 7_2 fertig bearbeitet, wobei allerdings die Bestellung nicht formartiert angezeigt wurde. Durch einen Tipp habe ich bei Heroku nochmal "Deployed", jetzt geht die App verlinkung leider gar nicht mehr. Woran kann das liegen?

https://herokueia2.herokuapp.com/
https://github.com/grandalf94/EIA2

grüße

**Comment by Plagiatus** [comment]
gehts doch wieder oder was?

**Comment by JirkaDellOro** [comment]
Also hier kommt etwas raus...
https://herokueia2.herokuapp.com/?asdv=asvd
