### ISSUE TITLE
Kein Response wird ausgegeben.

### ISSUE THREAD

**Issue by obiwan1337** [JirkaDellOro/EIA2#275]
Die Response bliebt auf localhost und auf Heruko ohne ein Ergebnis.
https://github.com/obiwan1337/EIA2/blob/master/Aufg7/aufg7.html
https://github.com/obiwan1337/EIA2/blob/master/Aufg7/js/aufg7.ts
https://github.com/obiwan1337/EIA2/blob/master/Aufg7/Server/Server.ts

**Comment by JirkaDellOro** [comment]
Ich wünsche mir Links zu den Runtimes.

**Comment by obiwan1337** [comment]
Problem gelöst. Die Localhost xhr Kanäle waren geblockt. Entblocken hat die Funktionalität hergestellt.
