### ISSUE TITLE
unknown command: find

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#277]
Hallo zusammen,
bei mir wird unknown command: find angezeigt obwohl ich in allen ts-Dateien eine find-Funktion definiert/exportiert habe.

https://haasmanu.github.io/EIA2/L08_Database/Client/DatabaseClient.html

Danke :)

**Comment by Plagiatus** [comment]
`find()` wird bei mir ohne Probleme ausgeführt. Es tritt dann später ein Problem in der `handleFindResponse()` auf, weil die Antowort scheinbar kein wohlformatiertes JSON Objekt ist.

**Comment by haasmanu** [comment]
Okay ich hab mir das angeschaut aber wüsste jetzt nicht so genau was ich wo ändern sollte....

**Comment by Plagiatus** [comment]
Der Server scheint eine fehlerhafte Antwort zu schicken, bzw wird die Antwort schon direkt blockiert und der Server stürzt ab. Scheint also ein Problem auf der Serverseite zu sein. Sicher dass es richtig deployed ist? gibt Heroku irgendwelche Fehler aus?

**Comment by haasmanu** [comment]
Ich denke dass es richtig deployed ist...wo schaue ich genau auf heroku nach um die Fehler zu sehen?

**Comment by Plagiatus** [comment]
siehe meinen Kommentar in https://github.com/JirkaDellOro/EIA2/issues/262#issuecomment-443457720.

**Comment by haasmanu** [comment]
![error3](https://user-images.githubusercontent.com/43847187/50053828-9b32b280-013b-11e9-8016-bbbd59a79ec2.JPG)

**Comment by Plagiatus** [comment]
schade, die eigentliche Fehlermeldung ist abgeschnitten. klick mal auf deploy und wechsle sofort in the logs, damit du die Fehlermeldung auch mitbekommst wenn sie passiert.

**Comment by haasmanu** [comment]
![error4](https://user-images.githubusercontent.com/43847187/50053989-4e4fdb80-013d-11e9-9c1f-f1fab59a29eb.JPG)
hoffentlich ist es das Richtige

**Comment by Plagiatus** [comment]
das.... ist genau die gleiche Ausgabe wie oben. 100% die gleiche plus eine extra Zeile. sogar mit den gleichen Zeitstempeln. Klick nochmal auf "deploy branch" im "Deploy" Reiter und wechsel dann rüber.

**Comment by haasmanu** [comment]
![error5](https://user-images.githubusercontent.com/43847187/50054128-39744780-013f-11e9-8d2a-f023e01c01e3.JPG)

**Comment by haasmanu** [comment]
Hoffe das ist das Richtige was du meinst

**Comment by Plagiatus** [comment]
das ist schonmal sehr interessant, aber erste Fehlereintrag wäre erstmal wichtiger. das was nach "Connected to Database" steht, weil das was du da hast scheint nicht der erste Fehler in der Reihe zu sein.

**Comment by haasmanu** [comment]
![error6 1](https://user-images.githubusercontent.com/43847187/50054268-7856cd00-0140-11e9-9b31-99ad4bbf25a9.JPG)

**Comment by haasmanu** [comment]
![error6 2](https://user-images.githubusercontent.com/43847187/50054278-8e648d80-0140-11e9-9d5f-e0de6ca1442d.JPG)

**Comment by haasmanu** [comment]
Das ist alles was davor steht

**Comment by Plagiatus** [comment]
also, finde ich sehr seltsam, ich starre jetzt seit einer weile auf den Code und die Logs aber ich komme auf keinen grünen Zweig. Es scheint als wäre die Antwort schon weggeschickt worden bevor die eigentliche Antwort kommt..

**Comment by Plagiatus** [comment]
Okay, ich habs gefunden. 
Wie ich gesagt habe, wird `respond()` zweimal aufgerufen, dadurch stürzt der Server ab.
Das kommt daher, dass du nach dem `case: "find"` kein break hast, dadurch wird der default case auch aufgerufen und somit wird natürlich "unknown command" zurückgegeben. und wenn dann die Datenbank anwortet und versucht noch eine antwort zu schicken kommt es zu oben genanntem Fehler .

**Comment by JirkaDellOro** [comment]
Wenn man ein vollständigen Log vom Start der App an haben will: unter "more <>" auf "Restart all dynos" klicken!

**Comment by haasmanu** [comment]
Super jetzt geht die find-Funktion, vielen Dank :)

**Comment by Plagiatus** [comment]
alles klar, wenn dann alles funktioniert bitte das Issue schließen 😃
