### ISSUE TITLE
unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by YannicHermann** [JirkaDellOro/EIA2#278]
Ich trete etwas auf der Stelle.. 

Ich bin mir nicht einmal sicher, ob meine Datenbank richtig eingebunden ist, weil bei einem "Refresh-Click" der im Titel genannte Syntax-Error in der Konsole erscheint und deshalb nichts dargestellt wird. Ich denke ich verstehe den Error insofern, dass die Syntax der ankommenden JSON-Daten nicht stimmt. Aber wie kann ich denn einsehen, wie diese aussehen, sodass ich den Fehler beheben kann? Oder liegt der Fehler woanders? 

https://yannichermann.github.io/EIA2/WS18/Aufgabe_8.2/Client/DatabaseClient.html

Freue mich über Antworten.

**Comment by YannicHermann** [comment]
Okay, da die response: "" ist, kommt also gar nichts von der Datenbank an. In der Database.ts https://github.com/YannicHermann/EIA2/blob/ac4cd2adeb198837d42b96a1d4a8b8d5b6fb350c/WS18/Aufgabe_8.2/Server/Database.ts#L18 verweise ich aber doch auf meine Datenbank. Was bin ich am übersehen?

**Comment by Plagiatus** [comment]
was für eine Anfrage schickt der Client denn an den Server? Wie sieht die query aus? Und verarbeitet der Server all diese Dinge korrekt?

**Comment by YannicHermann** [comment]
Eine XMLHttp Anfrage.  
Die Query  ist glaube ich leer. 
Und der Server verarbeitet die Dinge leider nicht korrekt.

**Comment by Plagiatus** [comment]
okay, wenn die query leer ist dann hat der Server ja auch nichts zu verarbeiten oder?

_Der Code sollte übrigens ohne Änderungen deinerseits so funktionieren, und du musst nur hinzufügen um die Aufgabe zu lösen. In der Datei von Prof. Dell'Oro ist die query nicht leer._

**Comment by YannicHermann** [comment]
Oh, dann habe ich wohl schon die ganze Zeit auf falscher Grundlage gearbeitet. 
Setze mich nochmal neu damit auseinander.
Danke !

**Comment by Plagiatus** [comment]
naja, nicht ohne Änderung, du musst natürlich deinen Heroku Server und deine Datenbank eintragen, klar.
