### ISSUE TITLE
Kann keine Studenten hinzufügen 

### ISSUE THREAD

**Issue by baayzi** [JirkaDellOro/EIA2#279]
Hallo,

ich habe das Problem das wenn ich Studenten hinzufügen will die Seite anstelle von storing data nur das was ich grade eingegeben habe ausgibt.

**Comment by Plagiatus** [comment]
Gibt es auch einen Link zu deinem Problem?

**Comment by baayzi** [comment]
https://baayzi.github.io/EIA2/L08_Database/Client/DatabaseClient.html

**Comment by Plagiatus** [comment]
keine der Antworten vom Server sehen aus wie sie aussehen sollten.

Die Antwort vom Server erinnert stark an den Weihnachtsbaumkonfigurator...
