### ISSUE TITLE
Klickfunktion funktioniert nicht mehr

### ISSUE THREAD

**Issue by MichelleZei** [JirkaDellOro/EIA2#28]
Hallo,

nachdem ich den Code refaktoriert habe, funktioniert die Klickfunktion der Bienen nicht mehr. Anstatt dass eine neue Biene erscheint, wird das Bild eingefroren. Die Bienen bewegen sich dann nicht mehr.

Hier der Link:
https://michellezei.github.io/EIA2/aufgabe7/aufgabe7.html

Vielen Dank im Voraus

**Comment by JirkaDellOro** [comment]
Was sagt denn die Konsole?

**Comment by MichelleZei** [comment]
Wenn ich klicke kommt:
TypeError: s is undefined

**Comment by JirkaDellOro** [comment]
In welcher Zeile? Es müsste eine Info auf die Datei und die Zeile an der der Fehler auftritt gegeben sein. Wenn man da drauf klickt, kann man direkt sehen wo es klemmt

**Comment by MichelleZei** [comment]
Es klemmt im main.ts in Zeile 62. Bei "s.animate();", aber ich habe doch durch die Zeile vorher "let s: Bienen = bees[i];" das s definiert. Warum bekomme ich dann trotzdem gesagt, dass s noch nicht definiert ist?

**Comment by JirkaDellOro** [comment]
Hmm... das heißt, dass die Bienen sich zunächst bewegen, das Programm also funktioniert und die Bienen aus dem Array ihren animate-Aufruf erhalten. Erst wenn geklickt wird, gibt es Probleme. Werden denn neue Bienen korrekt dem Array hinzugefügt?

**Comment by MichelleZei** [comment]
Nein, dem Array werden keine neuen Bienen hinzugefügt.

**Comment by JirkaDellOro** [comment]
Sollte das aber nicht so sein?

**Comment by JirkaDellOro** [comment]
Wie ich das gesehen habe, wird die Bienenanzahl n hochgezählt. Die animate-Schleife zählt also eine Biene mehr, greift dann aber in eine leere Schublade -> undefined...

**Comment by MichelleZei** [comment]
Jetzt werden die neuen Bienen zwar in den Array hinzugefügt, aber sie werden noch nicht gemalt

**Comment by JirkaDellOro** [comment]
Ja, jetzt wird ja auch n nicht mehr verändert. Nun haben wir das Problem auf den Kopf gestellt. Jetzt gibt es tatsächlich mehr Bienen im Array, aber es wird nur in die ersten 10 Schubladen geschaut...

Statt n hochzuzählen ist es jetzt aber viel geschickter, die Schleife bis zur Länge des Arrays laufen zu lassen!

**Comment by MichelleZei** [comment]
Alles klar, jetzt funktioniert es, danke!

**Comment by JirkaDellOro** [comment]
Gerne!
