### ISSUE TITLE
Kinder fahren Berg nicht runter

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#281]
Hallo zusammen,
Ich versuche die Kinder den Berg runterfahren zu lassen doch sie bleiben auf der Stelle stehen und vibrieren. Wenn jemand weiß woran das liegen könnte wäre ich sehr dankbar :)

https://haasmanu.github.io/EIA2/Aufgabe10/Aufgabe10.html

**Comment by saenglert** [comment]
Erstelle dir mal zur Veranschaulichung eine Tracetable für die `move` Funktion deiner `Timmy` Klasse.

**Comment by haasmanu** [comment]
okay bin drauf gekommen danke :)
