### ISSUE TITLE
Kollision von Kind und Baum(Bonus Aufgabe Gruppe rot)

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#282]
Hallo,
ich habe Fragen zu der Bonus Aufgabe für die ich zwei Ansätze habe:

1. Ich rechne den Vektor zwischen 0x0px und dem Kind und dem Baum aus und sobald sie gleich sind gibt es die erwünschte Animation. 
Die Collision detection funktioniert hier jedoch nur auf einen bestimmten Baum und nicht bei allen erzeugten. Wie kann ich das Problem beheben?  

2. Ich habe Kreise um die Kinder und Baumstämme gemalt um eine Hitbox zu simulieren und dadurch mit der isPointInPath() Methode die Kollision zu erzeugen. 

Jedoch finde eich keine Lösung die Methode auf die Kreise anzuwenden, nur auf die x Koordinaten der Objekte und dort ist die Chance auf eine Kollision wieder sehr gering..    

vielen Danke im voraus.

https://t0mmy93.github.io/EIA2_Git/Aufgabe_10/Aufgabe10.html

**Comment by saenglert** [comment]
Irgendwie bin ich grade zu blöd den Aufgabentext für die Bonusaufgabe zu finden, aber ich schließe mal sehr stark aus deiner Frage und deinem aktuellen Stand, dass es um eine Kollisionsabfrage geht.

Dazu eine grundlegende Frage: Wann kollidieren zwei Objekte? Wenn der Abstand zwischen ihnen Null oder kleiner Null wird. Der logische nächste Schritt ist dann natürlich zu Fragen: Wie bestimme ich den Abstand zweier Objekte auf meinem Canvas? 

Du hast schon völlig richtig erkannt, dass man diese Frage etwas eingrenzen und nur einfach Formen wie Kreise oder Rechtecke betrachten sollte. Komplexe Formen erfordern komplexere Berechnungen, aber hier gehts ja "nur" ums Prinzip. Eine weitere Einschränkung die dir aufgefallen ist: Exakt werden wir das ganze nicht bestimmen können. Überall schleichen sich kleine Rundungsfehler ein, weswegen es sinnvoll ist einen Bereich zu definieren der "gut genug" ist als Kollision erkannt zu werden. Zum Beispiel würde es keinem Menschenauge auffalllen, wenn als Bedingung für eine Kollision `distance < 1` angebenwird statt Null um eben Rundungsfehler auszugleichen.

So viel zur grauen Theorie, kommen wir zur Mathematik dahinter. Dein Ansatz mit Vektoren erscheint für mich grundsätzlich machbar, deine Herangehensweise allerdings nicht so ganz. Wenn man sich das ganze visualisiert mit einem Dreieck aus den drei Punkten U (Ursprung des Koordinatensystems), C (Child) und T(Tree), so hat dieses Dreieck zwei bekannte Seiten (UC und UT) und die gesuchte unbekannte Distanz (CT). Nun kann man sicherlich in dieser Konstelation die Seite CT aus den beiden anderen errechnen, aber das ist nicht wirklich spaßig, da sich die Zusammensetzung des Dreiecks (welche Seite ist die Hypothenuse etc.) bei jedem Fall ändert. Wäre es nicht schöner eine kurze und prägnante Formel zu haben? 

Wir bleiben weiterhin in der Geometrie und Dreiecken. Für Nerds: Die namensgebende Person trifft man in Assassins Creed Odysee. Zeichne dir ein einfaches Koordinatensystem, setzte zwei zufällige Punkte ein (einer für das Kind einer für den Baum). Verbinde die beiden Punkte mit einer direkten Linie. Das ist der Abstand den wir suchen. Zu guter letzt, zeichne jeweils zwei Linien durch die beiden Punkte, eine Linie parallel zur X Achse. die andere zur Y Achse.

Jetzt sollten dir in deiner Skizze zwei Dreiecke auffallen, die für die Geometrie eine sehr wichtige Eingenschaft haben. und deren fehlende Seite (die Distanz zwischen Kind und Baum) du einfach berechnen kannst.

**Comment by Plagiatus** [comment]
Vllt kurz zur Erklärung der sogenannten "Bonusaufgabe":

@R4Pi3R hat seiner Gruppe ein Sternchen versprochen, wenn sie es so machen, dass wenn die Kinder beim herunterfahren gegen einen Baum fahren sie permanent entfernt werden und durch einen roten Fleck auf dem Baum ersetzt werden. 😂

**Comment by saenglert** [comment]
Also mir ja schon immer klar, dass was mit Jascha nicht stimme kann, aber naja...

**Comment by t0mmy93** [comment]
haha 

Ok das klingt alles sehr viel komplexer als ich es erhofft habe.
Ich glaube ich lasse es dann lieber ^^ 

trotzdem danke für die Infos.
