### ISSUE TITLE
Bäume werden in der Sonne dargestellt

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#283]
Moin Moin,

habe aktuell das Problem, das einige meiner Bäume in meiner Sonne dargestellt werden. Finde den Fehler nicht, vielleicht kann mir jemand von euch helfen :)

HTML: https://dangscha.github.io/EIA2/Aufgabe10/A10.html
TypeScript Main: https://github.com/dangscha/EIA2/blob/master/Aufgabe10/Main.ts
TypeScript Class Tree: https://github.com/dangscha/EIA2/blob/master/Aufgabe10/Classes/Tree.ts

**Comment by saenglert** [comment]
Grüzi,
kannst du bitte mal in deiner `main.ts:39` den Pfad mit `crc2.closePath()` schließen?

**Comment by dangscha** [comment]
Hab ich gemacht, Problem bleibt bestehen

**Comment by saenglert** [comment]
Moment, dann ziehe ich mir erstmal dein Repository

**Comment by Plagiatus** [comment]
Ich sehe hier mehrere Probleme:

1) beginPath() ist eine Funktion, an einigen Stellen fehlen dir die Klammern für den Funktionsaufruf.

2) isPointInPath() so wie du es aufrufst schaut, ob der Punkt auf einem beliebigen Pfad im canvas liegt, nicht nur auf dem zuletzt hinzugefügten. Damit checkt er auch nach alles Pfaden die vorher schon dazugekommen sind, u.a. auch eben die Sonne.

3) hat nichts mit deinem Problem zu tun, aber warum malst du die Bäume jedes Update neu?
