### ISSUE TITLE
Kinder verschwinden

### ISSUE THREAD

**Issue by haasmanu** [JirkaDellOro/EIA2#284]
Hallo ich bin es nochmal,
ich versuche grade bei den Kinder die den Berg hoch gehen, sobald sie aus dem Bild sind wider auftauchen zu lassen weiß aber nicht woran das liegen könnte.
Bitte um Hilfe :)

https://haasmanu.github.io/EIA2/Aufgabe10/Aufgabe10.html

**Comment by haasmanu** [comment]
Die Klasse heißt Jimmy...hab ich vergessen zu erwähnen

**Comment by R4Pi3R** [comment]
Ein Link zu der entsprechenden Klasse wäre im nächsten Issue super ;)

Zu deinem Issue (bei dem ich hoffen muss, dass ich es richtig verstanden habe) hier ein paar Gegenfragen, die dich hoffentlich auf den Ursprung des Fehlverhaltens und die Lösung hinweisen:

Wo im Canvas ist die y-Koordinate 0?
Wo ist die y-Koordinate 800?
Wann wird die y-Koordinate größer als 800?
Wenn die Kinder zur Seite aus dem Bild fahren, warum fragst du nach der y-Koordinate?
Momentan kämen alle Kinder an der selben Stelle wieder ins Bild. Wäre es nicht besser, wenn ein Bereich auf der y-Achse angegeben wird innerhalb dessen sie zufällig wieder erscheinen?
Gleiches gilt auch für die Kinder, die den Berg hinab fahren!

**Comment by Plagiatus** [comment]
In deiner move Funktion von Jimmy fragst du ab, ob seine y Position größer ist als 800. Aber Jimmy bewegt sich ja von unten nach oben, also Richtung 0.

Außerdem, selbst wenn diese Bedingung erfüllt ist, wird Jimmy auf die linke obere Ecke gesetzt und bewegt sich dann außerhalb des Sichtfeldes weiter nach oben rechts.

**Comment by Plagiatus** [comment]
Mist, zu langsam

**Comment by haasmanu** [comment]
Okay cool das klingt logisch da hab ich nicht richtig nachgedacht, Dankeschön :)

Aber ich verstehe noch nicht so ganz ob ich diesen Bereich der y-Achse auch in der move() function angeben muss oder in der main?
