### ISSUE TITLE
for Schleife in for Schleife

### ISSUE THREAD

**Issue by nicoherrmann** [JirkaDellOro/EIA2#285]
Moin,
habe in meiner Update Funktion eine Vorschleife in der alle geworfenen Schneebälle abgefragt werden und wenn der Timer bei 0 ist wird geprüft, ob Sie mit einem Pfad eines Kindes kollidieren.
Das ganze sieht folgendermaßen aus:
![snowball](https://user-images.githubusercontent.com/43846525/52535787-df64bc80-2d52-11e9-9fe5-2af421cb9de2.png)
wenn die Methode "checkIfHit" aufgerufen wird gibt sie ein "bum" in der Console aus. Innerhalb der zweiten for Schleife ist das allerdings nicht der Fall, es wird aber auch kein "else" ausgegeben, wie es anderweitig der Fall sein sollte. In der ersten If-Abfrage kann man die checkIfHit Methode einkommentieren, dann gibt er auch "bum" aus, nur nicht in der zweiten.

Spiel: https://nicoherrmann.github.io/EIA2/RodelhangTerminator/RodelhangTerminator.html
Repository: https://github.com/nicoherrmann/EIA2/tree/master/RodelhangTerminator

Grüße
Nico

**Comment by Plagiatus** [comment]
soweit der Debugger mir das sagt, ist children.length = 0. ist children nicht die Klasse und childrenArray das array auf das du eigentlich zugreifen willst?

**Comment by nicoherrmann** [comment]
Ups ja hast recht dankeschön
