### ISSUE TITLE
Endabgabe

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#286]
Ich wollte mal wissen ob ich mit meinen Gedanken in die richtige Richtung gehe
bis jetzt ist das nur ein grobes vor konzept
[Konzept](https://lindschoki.github.io/EIA2/Endabgabe/Endabgabe%20Vor-Konzept.pdf)

**Comment by JirkaDellOro** [comment]
Prinzipiell geht das in eine sehr gute Richtung. Folgendes sei angemerkt:
- der Signalempfang sollte außerhalb der Aktivität "Schneeballwurf" stehen und diese aktivieren.
- die if-Abfrage zu Beginn der Aktivität createSnowball ist unnötig, sofern sie ohnehin nur bei Klick auf Screen aufgerufen wird.
- Animation-updates in diesen Aktivitäten ist unsinnig, da diese Updates an anderer Stelle zeitgesteuert passieren. Der Schneeball muss sich hier nur einklinken

**Comment by lindschoki** [comment]
ok vielen dank werde versuchen das umzusetzen
