### ISSUE TITLE
Schneeball Wurf

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#289]
Macht das Konzept so Sinn? Wenn ich in der Schneeballklasse eine move() Funktion einbaue und diese dann außerhalb der update Funktion in der getClickedPosition Funktion aufrufe, wie bekomme ich es dann hin, dass der Schneeball trotzdem durch "update" animiert wird.

Habe zum animieren auch die Möglichkeit mit CSS transform: translate3d gefunden, wäre dies möglich oder ist das umständlich ?

[Wurf Konzept](https://lindschoki.github.io/EIA2/Endabgabe/Wurf%20Konzept.pdf)

**Comment by lindschoki** [comment]
?

**Comment by JirkaDellOro** [comment]
Ich denke nicht, dass CSS unsere Pfade auf dem Canvas manipulieren kann

**Comment by JirkaDellOro** [comment]
Den Schneeball einfach in das Object-Array einklinken, dann wird er automatisch mit animiert, wenn alles ordentlich objektorientiert und polymorph gebaut wurde
