### ISSUE TITLE
Funktion in eine Methode umwandeln

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#29]
Meine Blumen werden mit einem switch-Case plaziert und farblich verändert, indem ich nur die Parameter einer drawFlower-Funktion verändert habe. Ist das auch irgendwie möglich, wenn drawFlower jetzt eine Methode ist?
Bei mir speziell geht es um case 0 ( Zeile 28) und case 1 (Zeile 32). 

https://github.com/MichelleFix/EIA2/blob/master/Aufgabe7/flowers.ts

**Comment by JirkaDellOro** [comment]
Nun, in den genannten Zeilen passen die Parameter nicht zur Methodendefinition. Wenn der Aufruf zu bleiben soll, muss die Methode auch die entsprechenden Parameter entgegen nehmen, analog zu drawFlower2. Zuvor sollte aber überlegt werden, ob die Parameterübergabe überhaupt gewünscht bzw. erforderlich ist. Wenn ohnehin mit den Eigenschaften des Blumenobjektes gemalt werden soll (x,y,fillcolor etc.) kann die Methode doch direkt darauf zugreifen und die Übergabe ist überflüssig und irritierend.
