### ISSUE TITLE
Datenbank geht nicht

### ISSUE THREAD

**Issue by dangscha** [JirkaDellOro/EIA2#290]
Habe versucht eine Datenbank für das Spiel zu machen, jedoch gibt es Probleme bei der Funktion refresh. Das Inserten von Daten funktioniert, das Anzeigen durch Refresh wirft dann jedoch Fehlermeldungen auf. Danach funktioniert auch nicht Insert und es muss neu Deployed werden

HTML: https://dangscha.github.io/EIA2/Endabgabe/A11.html
TS: https://github.com/dangscha/EIA2/blob/master/Endabgabe/Server/Server.ts

**Comment by JirkaDellOro** [comment]
Das neu deployed werden muss bezweifle ich. Schau dir die Heroku-Logs an, da wird wahrscheinlich ein Fehler gemeldet. Zum erneuten Start nach einem Crash genügt "Restart Dynos"

Schlau wäre es auch, zunächst lokal zu entwickeln und zu testen und erst den fertigen Code auf Heroku zu hieven.
