### ISSUE TITLE
Schneebälle werden nicht gezeichnet

### ISSUE THREAD

**Issue by t0mmy93** [JirkaDellOro/EIA2#292]
Hallo, 
 ich habe die Schneebälle erzeugt und ich habe ihnen zu Testzwecken die Position 50 50 gegeben jedoch werden diese dort nicht angezeigt. 
In der Console wird auch gesagt das new SnowBall kein contructor sei. 
Es gibt einen Failed to load resource Error, lokal geht es. Im html müsste es jedoch richtig verlinkt sein. 

https://t0mmy93.github.io/EIA2_Git/Endabgabe/Aufgabe10.html
https://github.com/t0mmy93/EIA2_Git/blob/master/Konzept2.jpg

**Comment by Plagiatus** [comment]
in deiner Konsole ist eine Warning:

    Laden fehlgeschlagen für das <script> mit der Quelle "https://t0mmy93.github.io/EIA2_Git/Endabgabe/class/SnowBall.js".

könnte es eventuell daran liegen? 😉

**Comment by t0mmy93** [comment]
Das ist mir bewusst das es nicht ladet aber ich weis ja nicht warum die namen stimmen, die main ts wird am  Ende aufgerufen. 

Lokal funktioniert es normale jedoch werden lokal auch keine Schneebälle erzeugt obwohl sie laut Konsole da sein müssten.

**Comment by Plagiatus** [comment]
die namen stimmen nicht.
`SnowBall.js` vs `snowBall.js`

**Comment by t0mmy93** [comment]
ok lol   🤦‍♂️ 

danke
