### ISSUE TITLE
objekte erscheinen nicht 

### ISSUE THREAD

**Issue by lindschoki** [JirkaDellOro/EIA2#293]
die konsole wirft keine fehler aus, rotzdem werden mir die Objekte von drei Klassen nicht angezeigt, woran liegt das ? 

[Klassen](https://github.com/lindschoki/EIA2/tree/master/Endabgabe/Klassen)
[HTML Datei](https://github.com/lindschoki/EIA2/blob/master/Endabgabe/Rodelhang%20Terminator.html)
[](https://lindschoki.github.io/EIA2/Endabgabe/Rodelhang%20Terminator.html)

**Comment by lindschoki** [comment]
[rodelhang](https://lindschoki.github.io/EIA2/Endabgabe/Rodelhang%20Terminator.html)

**Comment by JirkaDellOro** [comment]
Starte doch einmal den Debugger in der update-Funktion und guck dir die Objekte genauer an, die dort bewegt und gezeichnet werden...

**Comment by lindschoki** [comment]
komme hier leider auch nicht weiter kenne mich mit dem debugger nicht sehr gut aus

**Comment by JirkaDellOro** [comment]
Das ist natürlich doof. Klicke in der Entwicklerkonsole auf Sources und lasse dir dann dein Hauptprogramm anzeigen. In der Updatemethode klickst Du links auf eine Zeilennummer um die Ausführung zu pausieren (Breakpoint). Dann kannst Du Schritt für Schritt mit F10 den Programmablauf verfolgen.

**Comment by lindschoki** [comment]
also alle schleifen verhalten sich gleich wie die snowflake schleife mehr kann  ich da halt nicht rausfinden

**Comment by lindschoki** [comment]
bräuchte hier echt hilfe

**Comment by JirkaDellOro** [comment]
Und über welche Indizes wird iteriert?

**Comment by lindschoki** [comment]
ich weis leider nicht was indizes sind

**Comment by lindschoki** [comment]
das können ja nur die objekte im objects array sein

**Comment by JirkaDellOro** [comment]
Die Nummer des Eintrags im Array

**Comment by lindschoki** [comment]
ok ach so ich habe jetzt in die einzelnen schleifen die werte eingegeben ab denen die die neuen objekte anfangen beispielsweise nach 50 schneeflocken  den wert 56 in die schleife für die 6 bäume. Jetzt funktioniert es 
Vielen Dank

**Comment by JirkaDellOro** [comment]
Eigentlich solltest Du das alles mit einer Schleife erschlagen! Deswegen hast Du doch die Vererbung gebaut!!!

**Comment by lindschoki** [comment]
achso ja stimmt das änder ich schnell ab
