### ISSUE TITLE
HTMLCollection macht Probleme 

### ISSUE THREAD

**Issue by JannisBackhaus** [JirkaDellOro/EIA2#294]
Hallo liebe Betreuer, 
ich habe ein furchtbar penetrantes Problem mit einem Array. In meiner createEventListener-Funktion will ich basierend auf der Menge der Kategorien (ergo der Länge des Arrays `divs`), über eine Schleife die EventListener hinzufügen. Die Schleife wird aber jedes Mal vom Programm übersprungen, da die Länge des Arrays trotz enthaltener Elemente, gleich 0 bleibt. Selbst in der Browser-Konsole werden die Elemente korrekt und vollständig als Array mit Länge 6 ausgegeben. Erst wenn ich direkt `divs.length` anspreche wird die Länge plötzlich gleich 0. 

`    function createEventListener(): void {
   
        let divs: NodeListOf<Element> = document.getElementsByClassName("divtop");
        console.log("HIER")
        console.log(divs)
        console.log(divs.length)
        for (let i: number = 0; i < divs.length; i++) {
            let div: Element = <Element>divs[i];
            div.addEventListener("input", generateCart);
            console.log("div" + i + " got Eventlistener")
        }
        document.getElementById("orderbutton").addEventListener("click", checkOrderAndSendData);

        console.log("createEventListener done");
    }`
![issue](https://user-images.githubusercontent.com/43847206/52821937-a14bfd80-30b0-11e9-82b5-5abf04a4cf99.PNG)

HILFE!! 

Link zur HTML-File: https://jannisbackhaus.github.io/EIA2/Abschlussabgabe/Client%20User/config.html
Link zur TS-File: https://github.com/JannisBackhaus/EIA2/blob/master/Abschlussabgabe/Client%20User/config.ts

**Comment by saenglert** [comment]
Hallo Jannis,
ich kann das Problem gerade nicht sehen, da du in `config.ts` Zeile 4 auskommentiert hast und Zeile 5 nicht auskommentiert ist.

**Comment by JannisBackhaus** [comment]
Oh mist.. Habs geändert, sollte jetzt klappen.

**Comment by saenglert** [comment]
Kann es sein, dass du TypeScript nicht richtig konfiguriert hast? Wenn ich versuche den Rückgabewert von `getElementsByClassName` in einer Variable vom Typ `NodeList` zu speichern, gibt mir der Compiler die Rückmeldung, dass die Typen nicht kompatibel sind.

Du hast ja schon völlig richtig gesagt, dass wir hier mit einer `HTMLCollection` arbeiten, die von `getElementsByClassName` kommt. Dann speichere die Collection auch in einer solchen Variable ab:

```
let divs: HTMLCollection = document.getElementsByClassName("divtop");
// oder wenn du ganz genau sein willst
// let divs  = document.getElementsByClassName("divtop") as HTMLCollectionOf<HTMLDivElement>;
```

**Comment by Plagiatus** [comment]
@saenglert das ist erst mit der neusten TS version der Fall, mit der vor einem halben Jahr gibt es noch eine NodeListOf<HTMLElement> zurück, von dem her stimmt das schon.

Und bei mir funktioniert das Problemlos, besteht das Problem noch? 

![grafik](https://user-images.githubusercontent.com/7681159/52854071-a7c48e80-311d-11e9-83f8-51ada8b5ad52.png)

![grafik](https://user-images.githubusercontent.com/7681159/52854084-b317ba00-311d-11e9-83af-2f5f1a4473e4.png)

**Comment by saenglert** [comment]
@Plagiatus Kaum ist man IE und Edge los, muss man jetzt veraltete TS Versionen versorgen, ahrg 🤦‍♂️

**Comment by JannisBackhaus** [comment]
Also bei mir hat es weder mit NodeList noch mit NodeListOf<Element> oder HTMLCollection geklappt... bei allen hat er mir alle Elemente ausgegeben, aber eben doppelt so wie im Screenshot zu sehen. divs.length gibt mir immer nur 0 zurück und stoppt damit eben den Funktionsfluss von createEventListener. @Plagiatus funktioniert bei dir die Bestellübersicht denn? Also wenn du was anklickst wird das rechts angezeigt direkt?

**Comment by JirkaDellOro** [comment]
Mit dem Debugger auf Zeile 74 gestoppt sehe ich sofort, dass die divs zu dem Zeitpunkt noch nicht existieren...

**Comment by Plagiatus** [comment]
Bei mir funktioniert es nachdem ich 1-2 mal geladen habe, liegt es evtl daran, adss heroku eingeschlafen ist?

Außerdem werden bei mir die eventlistener installiert auf die div boxen 

![grafik](https://user-images.githubusercontent.com/7681159/52879964-f8111000-3160-11e9-8473-1b1d1ae6b760.png)

und in der Konsole gibt es eine "change registered" ausgabe in der Konsole (direkt gefolgt von einem Error aber hey... xD).

![grafik](https://user-images.githubusercontent.com/7681159/52880351-027fd980-3162-11e9-9c67-dfa13e1dbd20.png)

**Comment by JirkaDellOro** [comment]
@Lukas: Breakpoint auf 74 mal gesetzt? Ich kann das Problem stabil reproduzieren

**Comment by Plagiatus** [comment]
ja selbstverständlich. Meine neue Beobachtung ist jetzt: ich kann das Problem immer dann reproduzieren, wenn ich eben NICHT den breakpoint setze. wenn der Breakpoint gesetzt ist, funktioniert es wunderbar. Da kommen dann auch die Konsolenausgaben in einer andere Reihenfolge. 

Es kommt mir ganz spontan ein Timing Problem in den Sinn, dass die Eventlistener eingefügt werden bevor die divs angelegt wurden. Ich vermute es liegt daran, dass in der main direkt nach dem absenden der Anfrage die dynamicHTML() Funktion sowie die createEventListener() funktion aufgerufen werden, ohne die Rückgabe der Server daten abzuwarten. Außerdem wird dynamicHTML() am Ende der handleStateChangeGetData() nochmal aufgerufen (L64), wodurch es dann so aussieht, als wären die divs ja bereits da gewesen aber die Eventlistener nicht hinzugefügt worden. Macht da mal einen Breakpoint rein.

Hier zeigt sich auch schön ein Problem mit der (firefox?) Konsole, die sich leider nachträglich noch updaten kann. Wenn man nämlich den breakpoint bei 64 setzt und da das ausgegebene Array anschaut, dann hat es die Länge 0. schaut man es sich nach dem Breakpoint erst an, steht zwar in der übersicht immernoch "length: 0", wenn man dieses Objekt dann allerdings aufklappt stehen alle 6 Einträge drin als könnte sie kein Wässerchen trüben.

Also, Ablauf in der richtigen Reihenfolge machen (erst nach der Serverantwort dann auch die Eventlistener hinzufügen) und dann sollte das klappen.

(PS mein tag ist nicht Lukas 😉)

**Comment by JannisBackhaus** [comment]
Okay Lukas hat das Problem erkannt. Die dynamicHTML und createEventListener Funktionen wurden doppelt getriggert, einmal in der Main Funktion und einmal in der RequestHandler Funktion für die Datenabfrage... Ich steuere jetzt beide nur in der Handler Funktion an um besagtes Timing Problem zu umgehen, und es funktioniert wieder! Dankeschön!
P.S.: Der Error hat sich eingeschlichen durch die anderen keys die mein Interface jetzt verwendet.

**Comment by JirkaDellOro** [comment]
@Plagiatus: da habe ich gar nicht drauf geachtet, wer beim Tag rauskommt...
@JannisBackhaus: selbstverständlich hat Lukas das erkannt. Ich hatte gehofft, Du würdest es nach meiner Empfehlung, den Debugger zu benutzen und einen Breakpoint zu setzen, selbst erkennen...
