### ISSUE TITLE
Kinder lassen sich nicht abwerfen 

### ISSUE THREAD

**Issue by SinaSchwambach** [JirkaDellOro/EIA2#295]
Hallo, ich habe Probleme damit den Pfad der Kinder mit dem der Schneebälle zu vergleichen. Habe bereits schon mehrere Möglichkeiten ausprobiert um herauszufinden, woran es liegen könnte, dass in meine if abfrage nie zutrifft, aber keine war die Richtige. 

main-ts
https://github.com/SinaSchwambach/EIA2/blob/master/Endabgabe/main.ts

snowball-ts 
https://github.com/SinaSchwambach/EIA2/blob/master/Endabgabe/snowball.ts

child-ts
https://github.com/SinaSchwambach/EIA2/blob/master/Endabgabe/child.ts

**Comment by Plagiatus** [comment]
immer auch den Link zur ausführbaren HTML dazu bitte.

**Comment by Plagiatus** [comment]
außerdem, was genau macht denn das "isPointInPath"?

**Comment by SinaSchwambach** [comment]
https://sinaschwambach.github.io/EIA2/Endabgabe/Endabgabe.html

so wie ich es verstanden habe guckt "isPointInPath" ob der in der Klammer angegebene Punkt auf dem gezeichneten Pfad liegt

**Comment by Plagiatus** [comment]
soweit so richtig, allerdings ist es so dass es den Punkt auf jeden gezeichneten Pfad überprüft, nicht nur der zuletzt gezeichnete. Wenn du es gegen einen bestimmten Pfad prüfen willst, musst du den mit übergeben. Siehe https://developer.mozilla.org/de/docs/Web/API/CanvasRenderingContext2D/isPointInPath

**Comment by SinaSchwambach** [comment]
okay, aber wie übergebe ich den pfad? weil sobald ich etwas in die klammer dazu schreibe, wie bei der internetseite gezeigt, zeigt mir eclipse einen fehler an

**Comment by JirkaDellOro** [comment]
isPointInPath, ohne Pfad-Parameter, prüft gegen den aktuellen Pfad, also den, der zu dieser Zeit gezeichnet würde. Im einfachsten Fall legt man einfach einen Rechteck oder Kreispfad um das zu prüfende Objekt und ruft dann die Funktion auf.

TypeScript und CanvasRenderingContext haben sich seit der letzten Version des Palantir-Plugins für Eclipse weiter entwickelt. In Eclipse sind die neuen Funktionen daher wahrscheinlich nicht verfügbar.

@Plagiatus : es gibt (oder gab) auch isPointInStroke, habe ich gerade gesehen. Ist vielleicht interessant für FUDGE

**Comment by SinaSchwambach** [comment]
okay, das funktioniert jetzt, danke!
aber jetzt habe ich noch eine andere Frage: 
Wenn ich das Array meiner Datenbank sortieren möchte in welcher Datei muss ich das machen?

**Comment by Plagiatus** [comment]
das ist relativ egal. du solltest dir grundsätzlich überlegen ob das Sortieren vor oder nach dem verschicken an den Client passieren soll.

**Comment by SinaSchwambach** [comment]
okay und warum werden meine kinder beim erneuten starten des Spiels viel schneller als davor?

**Comment by Plagiatus** [comment]
ganz spontan klingt das für mich danach, dass die update zweimal aufgerufen wird, bzw vom vorherigen spiel noch läuft. überprüfe das mal.

**Comment by SinaSchwambach** [comment]
habe der update funktion eigentlich mitgegeben, dass sie nach einer minute nichtmehr ausgeführt werden soll und wüsste nicht wo ich sie zweimal aufgerufen haben sollte

**Comment by NicoKlein97** [comment]
Ich kann mir das ganze gerade zwar nur auf meinem Handy ansehen, aber du rufst die update-Funktion einmal in der Init auf, und einmal in der update-Funktion selbst mithilfe des Timers. Schau hier mal mit dem Debugger nach ob sich die Werte bei einem neustart so verhalten wie erwartet.

**Comment by SinaSchwambach** [comment]
ich habe es versucht aber irgendwie werde ich aus dem debugger nicht wirklich schlau.. ich muss doch die update funktion in der init aufrufen, da sie sonst bei start des spieles nicht gestartet wird und um sie weiterhin am laufen zu halten muss sie doch auch in sich selbst erneut aufgerufen werden, oder sehe ich das falsch? weil in der ersten runde funktioniert es ja noch

**Comment by NicoKlein97** [comment]
Hast du schonmal versucht dir die Geschwindigkeitswerte der Kinder direkt sobald eines erstellt wird einmal ausgeben zu lassen ? Wenn du das zweimal hintereinander machst sollte sich ja zeigen, ob diese größer werden. Das kannst du ja mit einem Console.log machen.

**Comment by Plagiatus** [comment]
das ist richtig. Du benutzt `clearTimeout` allerdings falsch. schau nochmal in das Beispiel von [W3](https://www.w3schools.com/jsref/met_win_cleartimeout.asp) oder [diese Stackoverflow Frage & Antwort](https://stackoverflow.com/questions/5397117/cleartimeout-not-working) an.

das hilft vorallem bei setInterval, bzw wenn du ein timeout event vorher abbrechen willst.
Ich würde dir vorschlagen, den Timeout um sich selbst aufzurufen in der update methode hinter eine konditionelle Abfrage zu packen, die nur dann update nochmal aufruft wenn das spiel noch läuft.

**Comment by SinaSchwambach** [comment]
so hat es funktioniert, danke 
jedoch habe ich jetzt das Problem, dass ich es nicht hinbekomme mir die sortierte datenbank ausgeben zu lassen

**Comment by SinaSchwambach** [comment]
habe es hinbekommen, trotzdem danke

**Comment by Plagiatus** [comment]
umso besser wenn du es selbst hinbekommst 👍
