### ISSUE TITLE
Fehler 503 Service unavailable

### ISSUE THREAD

**Issue by baayzi** [JirkaDellOro/EIA2#296]
Hi,
bin grade verzweifelt und der Lukas weiß auch nicht woran es liegt.
Hab mal einen Screenshot von dem Fehler gemacht.
![503](https://user-images.githubusercontent.com/39768730/52870517-58478800-3148-11e9-9570-7a53c6a92ac8.PNG)

**Comment by baayzi** [comment]
Hier noch der Link zu meinem Repository und die ausführbare HTML-Seite.
https://github.com/baayzi/EIA2/tree/master/Endabgabe
https://baayzi.github.io/EIA2/Endabgabe/Endabgabe.html

**Comment by JirkaDellOro** [comment]
Ihr habt sicher auf Heroku frisch deployed und Dyno neu gestartet? Gibt es Meldungen beim Build oder beim Dyno-Start?

**Comment by baayzi** [comment]
Hallo Herr Dell'Oro, 
problem gefunden. In der package.json hat das node vor der verlinkung gefehlt.
Waren verwirrt weil Heroku uns Permission Denied zurückgab.

**Comment by JirkaDellOro** [comment]
Bitte bei gelösten Probleme gleich posten und schließen. Ich hatte mich nämlich gewundert, dass es nicht funktioniert, obwohl "node" angegeben war...
