### ISSUE TITLE
Uno macht viele Probleme

### ISSUE THREAD

**Issue by caddarndt** [JirkaDellOro/EIA2#297]
Hallo zusammen!

Vorweg: Ja, ich weiß. Ich hab mir da einen ziemlichen Müll zusammengecodet. Ich habe an zu vielen Baustellen gleichzeitig gearbeitet und weiß mittlerweile nicht mehr wo oben und unten ist.

Aber meine größten Probleme mal grob zusammengefasst: Mein Rundensystem funktioniert nicht richtig, mein grundlegendes Regelsystem (nur Farbe und Wert beachtet) funktioniert nicht richtig und das Ablegen der Karten des Computers funktioniert nicht richtig. Mir wird auch leider nie ein Error angezeigt, den ich als Anhaltspunkt benutzen könnte.
Ich denke wenn die drei Punkte erstmal funktionieren kann ich auch mit weniger Verzweiflung weitermachen. 

Ausführbare HTML:
https://caddarndt.github.io/EIA2/Endabgabe/Endabgabe.html 

TypeScript Datei:
https://github.com/caddarndt/EIA2/blob/master/Endabgabe/Endabgabe.ts

Ich weiß das ist ziemlich wirr, wenn gebraucht kann ich morgen früh dafür noch Aktivitätsdiagramme hochladen, die liegen gerade nur leider warm und trocken woanders.

Wenn mir jemand helfen (oder erklären, als wäre ich 12) könnte, dann wäre ich sehr dankbar. 

Freundliche Grüße und ein schöner Abend

**Comment by Plagiatus** [comment]
Ich... bin etwas verloren. Kannst du evtl die Probleme etwas genauer darstellen? Was genau funktioniert denn daran nicht? wie sollte der eigentlich ablauf sein? Die ADs wären erstmal sehr hilfreich.

**Comment by caddarndt** [comment]
Okay ich versuchs mal ein bisschen genauer!

Rundensystem:
- Am Anfang wird automatisch zufällig der Spieler oder der Computer für den ersten Zug ausgesucht
- Die Runden werden ausgeführt (Erkennbar an alert Du bist am Zug/Gegner ist am Zug)
- es sieht so aus als ob der alert jedoch nur beim ersten Zug des Spielers kommt und dann bei den folgenden Zügen des Spielers nicht mehr, daher bin ich mir auch nicht sicher ob diese Züge praktisch als Runde erkannt werden

Regelsystem:
- Ich habe erstmal nur ein System in dem geprüft wird, ob die karten auf der hand des spielers/computers auf die letzte karte im Stapel der abgelegten Karten spielbar ist. Es bezieht sich nur auf die Farbe und den Wert, besondere Karten und deren Effekte werden noch nicht berücksichtigt
- Diese Möglichkeit wird in einem array response[] gespeichert, entweder als "true" oder "false", sodass man die Schlussfolgerung ziehen kann hand[i] == response [i]. Wenn der korrespondierende wert in response[] des geklickten index in hand[] "true" entspricht soll in der put() funktion die karte gespielt werden, entspricht der wert "false" wird ein alert ausgegeben, dass die Karte nicht spielbar ist
- Heute morgen hat das noch funktioniert, jetzt wird jedoch nur noch der alert ausgegeben obwohl eine Karte spielbar ist und auch als solches gespeichert, ich kann jedoch nicht finden warum

Ablegen vom Computer:
- Das macht mir ehrlich gesagt am meisten Schwierigkeiten, weil ich nicht mehr übertragen bzw nachvollziehen kann, wie ich die originale Ablegefunktion damals in Aufgabe 3 gemacht habe.
- Außerdem hängt das mit dem Regelwerk für den Computer zusammen
- Der Computer soll automatisch während seines Zuges prüfen, welche seiner Karten spielbar sind 
- Es wird wieder der vergleich wie oben beschrieben durchgeführt, jedoch mit dem kartenarray des computer computer[] und responseComputer[]
- alle karten die ein 'true' zurück geben, werden in ein array possibleCards[] gespeichert, daraus soll random eine ausgewählt werden die gespielt und aus possibleCards[] gelöscht wird, während die übrig gebliebenen Karten zurück in computer[] gegeben werden und danach auch aus possibleCards[] gelöscht, sodass possibleCards[] wieder leer ist.
- die möglichen karten werden auch gefunden und in dem array gespeichert, jedoch wird die dazugehörige put() funktion nicht ausgeführt
- wenn die karten ins das computer[] array zurück gegeben werden, sind die 'originale' auch noch da, sodass der Zug mit mehr Karten beendet wird als er begonnen hat, obwohl eine abgelegt wurde
(- so jetzt beim schreiben merke ich, dass ich da wahrscheinlich einen Denkfehler habe, und die karten die zuerst von computer[] in possibleCards[] geschoben werden auch aus computer[] gelöscht werden müssen. Oder ich habe einen doppelten Denkfehler, wer weiß)

Ich hoffe das hilft wenigstens ein bisschen weiter? AD's kommen wie gesagt leider erst morgen früh

**Comment by caddarndt** [comment]
Hier sind die ADs die ich mir geschrieben hatte

https://caddarndt.github.io/EIA2/Endabgabe/ADs.pdf

**Comment by NicoKlein97** [comment]
Zum Regelsystem:

Gehe deinen Code mal Schritt für Schritt mit dem Debugger durch, hier zeigt sich, dass die if-Bedingung, welche die put-Funktion aufruft niemals erfüllt wird.
Zuerstmal vergleichst du hier das Div in dem alle Handkarten sind mit dem Div was eine Karte repräsentiert, das wird nie true geben. Zum anderen siehst du in Response nach, ob sich dort der Wert true befindet, allerdings befindet sich in Response zu dem Zeitpunkt gar nichts. Wenn ich was falsch verstanden habe sag bescheid, aber so wie ich das sehe kannst du in diese if-Bedingung so nie reinkommen. Nutze den Debugger um solche Sachen zu sehen. 
Wäre es auserdem nicht besser anstelle true und fals als string zu nutzen einen boolean zu nehmen ?

**Comment by JirkaDellOro** [comment]
Kompliment zu den Diagrammen, das sieht recht zielführend aus. Der Zugwechsel sollte aber besser direkt vom Spieler ausgelöst werden, indem er eine Karte ausspielt oder passt. Die Veränderung der Anzahl seiner Handkarten ist kein gut nachvollziehbares Kriterium hierfür.

**Comment by Plagiatus** [comment]
Aaaaaaalso...

Erstmal muss ich dich bitten deinen Code einmal auto-zu-formatieren, da sind noch einige Dinge nicht ganz sauber eingerückt, was es an manchen stellen besonders schwer zu lesen macht. 

Und hier die Dinge die mir beim durchschauen aufgefallen sind, zusätzlich zu was schon gesagt wurde:

* Es ist sehr unschön dass alle deine Funktionen innerhalb der `uno` funktion deklariert sind.  
* `turnComputer` ruft nie `turnPlayer` auf. dadurch kann der neue alert ja gar nie kommen. Bzw nur wenn der Computer eine Karte nachziehen muss wird im Anschluss der Spieler wieder aufgerufen.   
* was tut `discard`? und warum wird es vom `takeEvent` aufgerufen?   
* Das ausgegebene Array (response) ist deutlich länger als das eigentliche Spielerhandarray.  (27 vs 20 bei mir)
* Nachdem die Handkarten sortiert wurden, stimmt `response` nicht mehr mit ihnen überein.
