### ISSUE TITLE
Spiel im Canvas wird zu klein angezeigt

### ISSUE THREAD

**Issue by MonettaMarchiano** [JirkaDellOro/EIA2#298]
Ich hab das Problem, dass das Spiel selbst zu klein angezeigt wird. Ich hab bisher immer wieder die Größe des Canvas abgeändert (im CSS) aber es passiert einfach nichts.
Im Browser wird es vernünftig angezeigt aber auf dem Handy ( in meinem Fall ein Iphone 6S) nicht wirklich. 

Könnte sich das jemand mal kurz angucken?

Das Spiel: 
https://monettamarchiano.github.io/EIA2/Abschlussaufgabe/index.html

Meine Dateien: 
https://github.com/MonettaMarchiano/EIA2/tree/master/Abschlussaufgabe

P.S. dadurch, dass ich es nur für Touch programmiert habe, funktioniert es auf dem Handy nur für Mozilla und Chrome.

**Comment by JirkaDellOro** [comment]
ich bin kein großer CSS-Crack, aber die Syntax
```
	width: max. screen-width;
	height: max. screen-height;
```
erscheint mir sonderbar. Müsste es nicht eher einfach
`width: max-width`
heißen?

**Comment by Plagiatus** [comment]
width: max. screen-width;
    height: max. screen-height;

macht gar keinen Sinn, das stimmt. wird so auch vom Browser ignoriert.

es gibt die eigenschaften width & height sowie max-width und max-height. Allerdings beides Eigenschaften und nicht werte für Eigenschaften. [Beispiel hier](https://www.w3schools.com/css/css_max-width.asp).

screen-width und screen-height gibt es dagegen gar nicht. man kann die Breite & Höhe des Bildschirms mit [Media queries](https://www.w3schools.com/cssref/css3_pr_mediaquery.asp) herausfinden, aber das ist wieder was anderes. Will man diese als Wert nutzen, dann sollte man immernoch prozent oder vh/vw als Einheit nutzen.
