### ISSUE TITLE
Import Problem auf der Serverseite

### ISSUE THREAD

**Issue by Koelleka** [JirkaDellOro/EIA2#299]
Ich hab ein Problem beim importieren von "http" und "url".

Meine Klassen für den Server sind alle in einzelnen Dateien.
In der Datei server.ts läuft dann alles zusammen. Alles ist auch in einem Namespace (UnoServer).

Wenn ich in meiner server.ts `import * as Http from "http";` verwenden will, dann findet er alle anderen Klassen nicht mehr, die ich selber definiert habe...

**Comment by JirkaDellOro** [comment]
Bitte Links zur Verfügung stellen!

**Comment by Koelleka** [comment]
Das ist meine [Server.ts](https://github.com/Koelleka/eia2/blob/master/Abschlussaufgabe/server/Server.ts)
Und das hier zum Beispiel die [Command.ts](https://github.com/Koelleka/eia2/blob/master/Abschlussaufgabe/server/Command.ts)

Generell liegen dann alle Server Klassen in einem verzeichnis, mit dem gleichen Namespace. [Klassen](https://github.com/Koelleka/eia2/tree/master/Abschlussaufgabe/server)

**Comment by JirkaDellOro** [comment]
- Wer ist er? 
- Werden zur Designzeit Fehler angezeigt oder zur Laufzeit? 
- Weitere Klassen/Module musst Du unter Node explizit ebenso importieren, siehe unsere Arbeit im Semester: `import * as Database from "./Database";`
- Ich schaue nochmal ob es wegen der Namespaces noch etwas zu beachten gibt

**Comment by Koelleka** [comment]
"Er" bezieht sich in diesem Fall auf die Datei Server.ts (Er = Eclipse)

Hier steht als Fehler "Cannot find name 'Command'". Das steht bei allen Klassen.
<img width="675" alt="bildschirmfoto 2019-02-16 um 17 22 34" src="https://user-images.githubusercontent.com/28564632/52902358-cefb8880-320f-11e9-9623-cc412673191a.png">

Das habe ich schin probiert mit dem import. Dort steht als Fehler dann:
"Command.ts is not a module"
<img width="339" alt="bildschirmfoto 2019-02-16 um 17 23 37" src="https://user-images.githubusercontent.com/28564632/52902360-d9b61d80-320f-11e9-8b2c-ae0022e83316.png">

Danke

**Comment by Plagiatus** [comment]
das zeigt nur WO der Fehler ist, nicht was er als Fehler anzeigt.

und mit einem gemeinsamen Namespace musst du eigentlich nichts importieren.

**Comment by Koelleka** [comment]
@Plagiatus Ja das dachte ich auch. Es funktioniert auch in allen anderen Klassen so.

Sobald ich `import * as Http from "http";` oder `import * as Url from "url";` hinzufüge, gehen meine eigenen Klassen nicht mehr

**Comment by JirkaDellOro** [comment]
Da gibt es wegen des Namespaces noch Sachen zu beachten. Deswegen habe ich in der Vorlesung bei Node keine Namespaces verwendet. Du kannst:
- auf die Namespaces verzichten und dich am Code der Vorlesung orientieren (einfach, aber Du musst halt aufpassen, dass es keine Konflikte mit anderen Aufgaben gibt)
- oder...

**Comment by Koelleka** [comment]
Okay dann lasse ich den namespace weg und importiere die einzelnen Klassen

`import { Command } from "./Command"; `
usw

**Comment by JirkaDellOro** [comment]
... export vor den namespace schreiben und diesen noch in den Klassenpfad einfügen.

Deine Nachricht kam dazwischen. Ok, mach' es so. Sonst wird es knifflig und Eclipse kann wahrscheinlich auch nicht die modernen Varianten richtig...

**Comment by Koelleka** [comment]
Ja das mit dem Namespace exportieren hab ich schon einmal ausprobiert.
Allerdings muss man den ja dann immer mitführen so wie ich das verstanden habe.

`export namespace A { export class B { ... } } `

Und wenn ich das dann importiere kann ich Klasse B ja nur mit `new A.B()` referenzieren... Oder gibt es dort noch andere Möglichkeiten beim Import, dass man den Namespace nicht extra noch einmal angeben muss?

Ohne Namespace geht es :)

**Comment by Koelleka** [comment]
Im Browser funktioniert das nach diesem Schema jetzt einwandfrei.

Jetzt gibt es allerdings auf dem Node Server ein anderes Problem.
Der In Eclipse kommen keine Fehler mehr, aber ich kann die Klassen in Node nicht verwenden. 

```
Request received
/Users/katharinakolle/git/eia2/Abschlussaufgabe/server/CommandManager.js:7
        this.addCommand(new Command_1.CreatePlayerCommand());
                        ^

TypeError: Command_1.CreatePlayerCommand is not a constructor
    at new CommandManager (/Users/katharinakolle/git/eia2/Abschlussaufgabe/server/CommandManager.js:7:25)
    at Function.get Instance [as Instance] (/Users/katharinakolle/git/eia2/Abschlussaufgabe/server/CommandManager.js:25:52)
    at Server.handleRequest (/Users/katharinakolle/git/eia2/Abschlussaufgabe/server/server.js:25:51)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:672:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by Koelleka** [comment]
NVM ich muss die ganzen ts Dateien alle noch einmal neu kompilieren...

Funktioniert jetzt alles :)
Danke!!

**Comment by JirkaDellOro** [comment]
:+1:
