### ISSUE TITLE
Ordner aus Eclipse hochladen

### ISSUE THREAD

**Issue by RomanBayer** [JirkaDellOro/EIA2#3]
Hallo,

    ich habe in Eclipse einen neuen Order "Aufgabe 0" angelegt. Dieser befindet 
    sich dort im Repositorie EIA2 (wie der Ordner mit meinem Steckbrief).
    Den Ordner "Aufgabe 0" lässt sich einfach nicht mit GitHub synchronisieren bzw.
    hochladen.

Gruß Roman

**Comment by JirkaDellOro** [comment]
Hallo Roman,

Rechtsklich auf Projekt -> Team -> Push to upstream

was passiert, wenn Sie das tun?

**Comment by RomanBayer** [comment]
Dann geht ein Fenster mit folgendem Inhalt auf:
Push Results: EIA2-origin
Pushed to EIA2-origin
master -> master [rejected-non-fast-forward]

Wenn ich das dann mit OK bestätige, geht es zu und es ist scheinbar nichts passiert. Außerdem hätte ich da die Möglichkeit "Configure push for remote "origin".

**Comment by JirkaDellOro** [comment]
Hallo Sie nach Strg+# auch den Ordner mit der Aufgabe "gestaged", so dass er überhaupt ins Repository aufgenommen wird?

**Comment by JirkaDellOro** [comment]
Ach, und non-fast-forward könnte darauf hindeuten, dass am remote-repo etwas verändert wurde. Führen Sie zunächst einen Pull aus, um die Daten zu ziehen.

**Comment by RomanBayer** [comment]
Super, vielen Dank. Nach dem Pull hat es funktioniert :-)

**Comment by JirkaDellOro** [comment]
Erinneren Sie mich bitte daran, dies in der Vorlesung anzusprechen.
