### ISSUE TITLE
Keine Bienen erscheinen

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#30]
Bei mir erscheinen keine Bienen mehr. Ich hab die Vermutung, dass es an Zeile 40, 41 oder/und 50, allerdings habe ich keinen Plan was ich da ändern muss, dass das funktioniert. Eclipse zeigt mir auch keinen Fehler an.

https://github.com/MrMarans/EIA2/blob/master/Aufg8/Bienen.ts

**Comment by MrMarans** [comment]
Und mein Blumen.ts erkennt keine Infos und überträgt auch nichts auf main.ts
https://github.com/MrMarans/EIA2/blob/master/Aufg8/Blumen.ts
Im Prinzip ist jede Zeile markiert

**Comment by MrMarans** [comment]
Main.ts findet jetzt auch nichts mehr aus Bienen.ts. Überall den Fehler "Cannot find name 'FunktionX'

**Comment by JirkaDellOro** [comment]
In dem Zustand, in dem der Code derzeit ist, möchte ich darin nicht auf Fehlersuche gehen. Folgende Unstimmigkeiten springen mir sofort ins Auge, die zuvor bereinigt werden müssen.
- warum heißt die Startdatei aufg6.html?
- warum heißt der Namespace L4_Classes?
- warum entsprechen die Methodennamen  und Klassennamen nicht dem vorgeschriebenen Stil?
- warum findet sich TS-Code in der Blumen.js-Datei?

**Comment by MrMarans** [comment]
Nun gut, ich hab mal von neu angefangen und konnte dazu die Bienen funktionierend übertragen (bis auf auf die function newBee, die jetzt gerade noch nicht tut und nicht übertragen ist, mach ich aber zum Schluss.)

Dazu hab ich die Startdatei nun umgeändert, den Namespace "hive_Classes" genannt und zudem sollte auch in den JS Dateien kein TS mehr sein.

Ich bekomme allerdings bei dem Constructor bei Blumen.ts sofort nen Fehler, dass "," fehlen, was mich daran hindert, an den Blumen zu arbeiten. Warum ist das so?

**Comment by braundominik** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/26409265/26035045/548f019c-38c6-11e7-805b-fbfc84268a4f.png)
Die Klammer auf die der rote Pfeil zeigt muss glaube ich dahin wo der grüne Pfeil zeigt.

**Comment by MrMarans** [comment]
Oh mein gott, wieso hab ich das nicht gesehen. Danke.

**Comment by MrMarans** [comment]
Mal abgesehen, dass mir Online nichts angezeigt wird und die Konsole nur Namen von Serien und Filmen aus Netflix angezeigt werden (https://gyazo.com/12a4df811a453f1f2920a19424aae143), fehlt es beim Thema Blumen zum anzeigen nurnoch um einen Wert in der Klammer bei Zeile 61 in Main.ts, und ich komm nicht drauf, was da rein soll. "Supplied Parametersd do not match any signature of call target" sagt der Fehler

**Comment by JirkaDellOro** [comment]
* warum heißt die Startdatei nun aufg7.html, wo wir doch bei Aufgabe 8 (laut Ordner) sind?
* warum ist darin der Verweis auf Main.js klein geschrieben?

**Comment by braundominik** [comment]
Der Fehler: "Supplied Parameters do not match any signature of call target" beschreibt ziemlich genau das Problem und wo weißt du ja auch schon Zeile 61.
Das new flowerSettings(); erwartet nun halt auch die entsprechenden Werte die du in der Klasse im Konstruktor forderst. Auch wenn du danach die Position zufällig setzt musst du der neuen Blume erstmal feste Werte mitgeben welche dann natürlich direkt danach durch deine Methode geändert werden.
