### ISSUE TITLE
Heroku Probleme!

### ISSUE THREAD

**Issue by Cryray** [JirkaDellOro/EIA2#301]
Ich habe Probleme mit dem Senden meiner Scores:
//////////////////////////////////////////////////////////////////
GET https://githubcryray.herokuapp.com/?name:Leon&score:-2378 503 (Service Unavailable)
sendRequestWithCustomData @ endabgabe.js:233
endabgabe.html:1 Access to XMLHttpRequest at 'https://githubcryray.herokuapp.com/?name:Leon&score:-2378' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
//////////////////////////////////////////////////////////////////
Das steht nach dem drücken des "Send" Knopfes in der Konsole.
Zudem lässt sich die URL : "githubcryray.herokuapp.com" nicht öffnen, obwohl Heroku mir sagt das alles erfolgreich deployt wurde.
Danke schonmal für die Antwort!

**Comment by Plagiatus** [comment]
bloß weil es erfolgreich deployed wurde, heißt das noch nicht, dass der Server nicht während der Laufzeit abstürzt wenn da irgendwo ein Fehler geworfen wird. schau mal in die Heroku Logs rein,

**Comment by Cryray** [comment]
Wie schau ich nochmal in die Heroku Logs? ^^

**Comment by Cryray** [comment]
Der Befehl "heroku logs" funktioniert in meiner Konsole nicht.

**Comment by JirkaDellOro** [comment]
im Heroku-Dashboard oben rechts More->View Logs

**Comment by Cryray** [comment]
Ok jetzt habe ich ein Problem gelöst.
Jedoch wird es in meiner Highscore Liste immer noch nicht angezeigt...

**Comment by Plagiatus** [comment]
Bitte einen Links zur ausführbaren HTML und zur Datei in der du deine Probleme vermutest.
Sowie weitere Info dazu, was denn genau wann nicht funktioniert, welche Errors es gibt etc..

**Comment by Cryray** [comment]
https://cryray.github.io/EIA2/Endabgabe/endabgabe.html

Datei in der ich Problem vermute: endabgabe.ts
Problem: Meine Dateien werden anscheinend auf Heroku hochgeladen aber ich kann sie auf meiner Highscore Liste nicht einsehen
Error gibt es keine mehr

**Comment by Plagiatus** [comment]
Wann sollte denn der Highscore angezeigt werden?

**Comment by Cryray** [comment]
document.getElementById("refresh").addEventListener("click", highscores); zeile 25 endabgabe.ts
<button id="refresh">Highscores</button> zeile 24 endabgabe.html
Wenn der Knopf Highscores im Menü gedrückt wird

**Comment by Plagiatus** [comment]
wie soll denn in deiner Highscore liste etwas angezeigt werden, wenn du nie eine anfrage an den server schickst?

**Comment by Cryray** [comment]
function sendRequestWithCustomData(): void {
        console.log("requestcustom");
        let xhr: XMLHttpRequest = new XMLHttpRequest();
        let sendString: string = "";
        sendString += "name:" + document.getElementById("textInput").getAttribute("value") + "&" + "score:" + score;
Zeile 304 in der endabgabe.ts
ist das keine anfrage an den server?

**Comment by Cryray** [comment]
Heroku sagt auch :"Request received"

**Comment by Plagiatus** [comment]
du bekommst auch eine Antwort zurück: 

    unknown command: undefined

überprüfe nochmal deinen Servercode, ob dieser die Daten richtig entgegennimmt, weitergibt und richtig antwortet.

**Comment by Cryray** [comment]
Ich bin nach langem rumprobieren immer noch nicht auf den Fehler gekommen...
Er sagt mir jetzt zudem nen Error den ich nicht behoben kriege..
Uncaught TypeError: Cannot read property 'name' of undefined
    at XMLHttpRequest.handleFindResponse (DatabaseClient.js:65)

**Comment by Cryray** [comment]
Jetzt lädt er die Heroku Logs nicht mehr..
Ich habe keine Ahnung wo der Fehler liegt

**Comment by Cryray** [comment]
Er zeigt mir jetzt die Daten in der Datenbank in den Heroku Logs an aber die Highscore Liste lädt er immernoch nicht..

**Comment by Cryray** [comment]
Also das genaue Problem ist in dem Fall, dass ich die Daten : "Score" und "Name" nicht aus der Datenbank bekomme, bzw vllt aus der Datenbank bekomme, sie aber auf jeden Fall nicht angezeigt werden in der High Score Liste

**Comment by NicoKlein97** [comment]
Hast du dir mal die Länge von deinem Data Array ausgeben lassen ?
Du gehst das dataArray 10 mal durch, bist du denn sicher, dass auch so viele Einträge in diesem Array drinnen sind ?

**Comment by Cryray** [comment]
Ich habe insgesamt 67 Einträge in diesem Array..

**Comment by Cryray** [comment]
Zumindest nach console.log(dataArray.length);

**Comment by Plagiatus** [comment]
Die Antwort die vom Server zum Client kommt ist immernoch `unknown command: undefined`. Da kann ja nichts interessantes drin stehen. Was erwartet denn dein Server für eine Anfrage und wie sieht die Anfrage tatsächlich aus?

**Comment by Cryray** [comment]
Naja wahrscheinlich gibt er mir die Default Ausgabe mit der CodeZeile aus:
default:
            respond(_response, "unknown command: " + command);
            break;
aber er sollte eigentlich diese ausführen:
case "insert":
            let student: playerData = {
                name: query["name"],
                
                score: parseInt(query["score"]) };
            
            Database.insert(student);
            respond(_response, "Please refresh your window and click on Highscore-List to see how good you are.");
            break;
        case "refresh":
            Database.findAll(findCallback);
            break;
Aber meiner Meinung nach sind die cases "refresh" und "insert" doch gegeben ode rnicht?
Danke für die schnelle Antwort

**Comment by R4Pi3R** [comment]
Die request wird in "function sendRequestWithCustomData()" generiert und gesendet, korrekt?

**Comment by Cryray** [comment]
Ja korrekt

**Comment by Cryray** [comment]
Die führt er auch aus zumindest macht er mir den console.log(requestcustom);

**Comment by Plagiatus** [comment]
also, ich habe jetzt erst gesehen dass mit dem ausführen der Highscore zwei verschiedene Funktionen aufgerufen werden, die eine zum Einfügen ist noch fehlerhaft, die zum Abrufen dagegen stimmt soweit.

Deine Daten werden nur in das falsche Element geschrieben. 
![grafik](https://user-images.githubusercontent.com/7681159/52912430-cbb8d900-32b1-11e9-943d-14fe8c112719.png)

![grafik](https://user-images.githubusercontent.com/7681159/52912448-fd31a480-32b1-11e9-9744-c8c50d382894.png)

**Comment by Cryray** [comment]
Also wird meine Liste in den Highscores Button gespeichert??
Wie hast du es jetzt geschrieben damit sie dir im "Menu" angezeigt werden??

**Comment by R4Pi3R** [comment]
Da wird dem String aber kein command angefügt. Wenn das nirgends anders passiert führt das dazu, dass bei dieser request immer die default response ausgeführt wird.

**Comment by Plagiatus** [comment]
Ich habe nichts geändert. lediglich das Highscore Overlay aus- und die Buttons eingeblendet.
Das hier ist dein Code. 
![grafik](https://user-images.githubusercontent.com/7681159/52912524-cb6d0d80-32b2-11e9-973e-347e31697f08.png)

**Comment by Cryray** [comment]
Es funktioniert jetzt! Danke fürs helfen
