### ISSUE TITLE
Firefox Debugger zeigt keine Quellen an

### ISSUE THREAD

**Issue by maz0o** [JirkaDellOro/EIA2#302]
Hallo zusammen,

Es geht um **Aufgabe 2.4**: 

> Verfolgen Sie den Verlauf im Debugger. Bestimmen Sie Abweichungen zu Ihrer Erwartung und erklären Sie diese.

Firefox zeigt mir hierzu keine auswählbaren Dateien bei "Quellen" an
[https://sftp.hs-furtwangen.de/~zaretzke/EIA2/Screenshots/screenshot_issue.PNG](url)

Gibt es hierzu was bestimmtes zu beachten, um die Codeabfolge sachgemäß zu prüfen?

Firefox Version: 66.0.2 (64-Bit)

Besten Dank im Voraus

**Comment by Plagiatus** [comment]
Der Link führt ins Leere, bitte beim Einfügen darauf achten, das er auch wirklich dahin führt, wo er hin soll.

https://sftp.hs-furtwangen.de/~zaretzke/EIA2/Screenshots/screenshot_issue.PNG

Das ist allerdings sehr seltsam. Vorallem da der Code ja ausgeführt wird. Hast du es Mal online versucht? (https://plagiatus.github.io/EIA2_S19_Code/L01_Tracetable/Boxes/) macht es einen Unterschied? Funktioniert es auch bei anderen Dateien nicht oder nur bei dieser?

**Comment by maz0o** [comment]
Danke für die schnelle Antwort,

Wenn ich den Code online ausführe, besteht das Problem leider weiterhin

https://sftp.hs-furtwangen.de/~zaretzke/EIA2/Screenshots/Screenshot_issue_2.PNG
(Hoffe der Link ist jetzt richtig angegeben)

Bei anderen Websites werden mir die verschiedenen Quellen im Debugger angezeigt

**Comment by Plagiatus** [comment]
Bei anderen Webseiten geht es? Wird ja immer komischer. Hast du irgendwelche Erweiterungen im Firefox die das blockieren können?  
Eigentlich sollte es auch nicht an irgendwelchen Cache Problemen liegen, aber versuche mal einen Harten Reload zu machen (Ctrl/Cmd + Shift + R), mit und ohne dass du die Dev Tools offen hast.

Versuche es auch mal in einem anderen Browser (wenn du einen hast) und prüfe ob es an Firefox oder an der Seite liegt.

Ansonsten schaue mal hier rein: https://stackoverflow.com/questions/34701061/why-is-the-firefox-debugger-not-showing-full-source-code evtl ist da noch etwas dabei das hilft.

**Comment by maz0o** [comment]
Erweiterungen sind keine installiert, der Hardreload hat jedoch funktioniert top, danke!
Aber Firefox scheint trotzdem Probleme zu haben, da er meine Haltepunkte quasi ignoriert und bei "ausdruck beobachten" bekomme ich das:

https://sftp.hs-furtwangen.de/~zaretzke/EIA2/Screenshots/issue_screenshot_3.PNG

Weißt du vlt. an was das liegen könnte bzw. was ich falsch gemacht habe?

**Comment by Plagiatus** [comment]
in dem screenshot ist weder die .ts Datei ausgewählt noch sind Haltepunkte gesetzt?

**Comment by maz0o** [comment]
Ich habe das Problem glaube falsch beschrieben, wenn ich den debugger laufen lassen will (auch mit gesetzten Haltepunkten) öffnet sich immer dieser Reiter mit "sourceSource..."

**Comment by Plagiatus** [comment]
Sehr seltsam, das habe ich noch nie gesehen.  
Wenn du es nicht herausbekommst, müssen wir wohl im Praktikum mal drüber schauen.

**Comment by maz0o** [comment]
Danke für deine schnelle Hilfe! Ich setz mich später nochmal dran, und im Zweifel zeig ich dir mein Problem wie du schon angesprochen im nächsten Praktikum.
