### ISSUE TITLE
Gabel wann?

### ISSUE THREAD

**Issue by Ninjanna** [JirkaDellOro/EIA2#303]
Wird die Gabel nur bei Funktionen verwendet oder wenn man generell mehr platz braucht um was zu beschreiben (zB sowas wie das switch case beim box code)?

**Comment by R4Pi3R** [comment]
Die Gabel kennzeichnet im Diagramm den Aufruf einer Funktion. Da diese in der Regel außerhalb des Blocks definiert wird (und ggf. mehrmals, an unterschiedlichen Stellen aufgerufen wird), wird das Diagramm für diese nicht in das aufrufende Diagramm übernommen. Das dient mehr der Übersichtlichkeit als dem Platzsparen.
Einfaches Beispiel: 
Die selbe Funktion wird im Hauptprogramm 3 Mal mit unterschiedlichen Parametern aufgerufen. Ohne sie auszulagern müsste 3 Mal der selbe Diagrammteil mit unterschiedlichen Werten erstellt werden. 
Durch das auslagern muss nur der Aufruf der Funktion 3 Mal im Hauptdiagramm stehen, die Handhabung der Parameter wird im ausgelagerten Diagramm der Funktion dargestellt.

**Comment by Plagiatus** [comment]
Zusätzlich dazu: wenn man mehr Platz braucht oder einen Pfeil nicht quer über das ganze Blatt ziehen möchte, kann man Verbindungsknoten nutzen. Dazu einfach einen Kreis mit einem Buchstaben malen:  

![grafik](https://user-images.githubusercontent.com/7681159/55401267-80e8dd00-5550-11e9-99cd-f1ed3bcbde8a.png)
  
Hierbei wichtig: Der Übersichtlichkeit halber sollte immer nur ein Pfeil in den Knoten hinein oder heraus gehen. Außerdem sollte es keine zwei gleiche Verbindungsknoten geben, aus denen der Pfeil herauskommt (sonst wäre das wieder eine Nebenläufigkeit und das dürfen wir nicht).

**Comment by Ninjanna** [comment]
Okay also keine Schleifen auslagern, verstehe, danke :) 
Dann direkt mal die nächste Frage: wenn in dem switch dem c ein farb-string zugeordnet wird, ist das dann ein akitiväts oder oder ein object node? Ich würde sagen Aktivität da das c ja schon vorher erstellt wurde. Auf der anderen Seite ist es nur eine einfache zuordnung, es wird nich wirklich was berechnet oder so. Ist Activity also falsch? Soll ich dafür ein neues issue aufmachen? ^^
Dann noch ne Randfrage: wo is die Gabel bei draw IO? Ich kann die nirgends finden...

**Comment by Plagiatus** [comment]
Aktivitätsknoten is hier richtig. Die Aktivität ist, dass du deinem c einen Wert zuweist.

die Gabel ist leider das einzige was ich tatsächlich noch nicht in draw.io gefunden habe. wirst du dir selbst basteln müssen. 😉 Aber man kann bei draw.io ja auch eigene Objekte speichern, darum musst du es nur einmal selbst bauen und kannst es dann immer wieder nutzen.

**Comment by JirkaDellOro** [comment]
Hier komme ich mal mit rein. Ich hatte vor einiger Zeit ein Symbol-Set für Draw.io gemacht, findet ihr hier:
https://github.com/JirkaDellOro/JirkaDellOro.github.io

Einfach importieren, dann solltet ihr alles haben, was ihr in EIA2 braucht und noch etwas mehr.

**Comment by JirkaDellOro** [comment]
Noch ein Wort hierzu: mit einer Gabel wird eine größere Aktivität markiert, die an anderer Stelle weiter definiert wird. Häufig übersetzt sich das später beim Coden in eine Funktion oder Methode, dass ist auch meist genau richtig so. Es kann aber auch z.B. eine Schleife damit umschrieben sein die im Code später einfach in einer Folge eingebaut wird.

Wenn alle Fragen beantwortet sind, bitte den Issue schließen...

**Comment by JirkaDellOro** [comment]
@Ninjanna: bitte schließen wenn geklärt, offen Issues verstopfen mein Dashboard. Vielen Dank.

**Comment by Ninjanna** [comment]
Sorry!

**Comment by JirkaDellOro** [comment]
Kein Problem, wir lernen alle ständig...
