### ISSUE TITLE
Einzelne Karten anwählen

### ISSUE THREAD

**Issue by julianSchubert** [JirkaDellOro/EIA2#304]
Hallo, komme nicht weiter.
Wie lassen sich einzelne Karten anwählen in der Funktion Karteablegen.
Also Testweise sollte Hallo bei einer einzelnen Karte angelegt werden.
Geb ich allen im Interface eine ID?
Was bringt mir das dann?

Kann man das auch machen wenn die Karten mit Arrays generiert werden odergibt es da keine Möglichkeit?

Im Internet findet man viele Lösungen mit any oder anonymer Funktion aber das sollen wir ja nicht machen.
Hier der Link zum Code:

https://github.com/julianSchubert/EIA2/tree/master/Aufgabe3

Hier die Seite:
https://julianschubert.github.io/EIA2/Aufgabe3/index.html

Danke schonmal
 Julian

**Comment by R4Pi3R** [comment]
Zunächst mal eine Stil Sache: Das Script sollte im head-Tag eingebunden werden, nicht im body.
Das wird im Code wie er jetzt ist zu Laufzeitfehlern führen, da nicht garantiert werden kann, dass die HTML-Elemente bereits existieren, wenn das Script versucht darauf einen Listener zu installieren.

Im weiteren solltest du dir vielleicht erst das "Karte ziehen" realisieren. Denn im Moment wirst du auch da auf ein Problem stoßen, da deine Handkarten in der selben Funktion dargestellt werden, in der sie auch aufgenommen werden. Wie wird eine neu gezogene Handkarte dargestellt? 
Oder allgemeiner: Wie sieht es mit der Darstellung der Hand aus, wenn an dieser durch ziehen oder spielen einer oder mehrerer Karten eine Veränderung stattfindet?

Zur eigentlichen Fragestellung:
Wenn du die Einträge des Handarrays für die Darstellung kreierst und mit appendchild() an das DOM übergibst, kannst du ihnen in diesem Schritt auch eine einzigartige Eigenschaft (hust...id...hust) mitgeben, die sich dann im Script wiederum abfragen lässt um das geklickte Element zu identifizieren.

**Comment by julianSchubert** [comment]
Danke, ich melde mich wieder falls es noch was gibt.
