### ISSUE TITLE
Problem mit getAttribute

### ISSUE THREAD

**Issue by KatharinaSchmitt** [JirkaDellOro/EIA2#305]
Hallo,

in meiner Funktion zum Karten auf den Ablagestapel legen, möchte ich auf die einzelnen Karten im meinem Handkarten-Array über die ID ansprechen.
Die ID der einzelnen Karten wird im Insprektor angezeigt, allerdings in meiner Funktion über getAttribute ("id") nicht gefunden.
Kann mir jemand helfen oder findet in meinem Code einen Fehler?

Hier mein Code:
https://github.com/KatharinaSchmitt/EIA2/blob/master/Aufgabe3/js/main.ts

Hier meine index:
https://katharinaschmitt.github.io/EIA2/Aufgabe3/index.html

Danke schonmal im Voraus!
Katharina

**Comment by Plagiatus** [comment]
die ID liegt auf dem P element, nicht auf dem Div Element, was du wahrscheinlich anklickst, korrekt?

**Comment by Plagiatus** [comment]
die ID liegt auf dem P element, nicht auf dem Div Element, was du wahrscheinlich anklickst, korrekt?
Wenn du auf den Text klickst, dann kommt auch die richtige ID in der Konsole.

**Comment by KatharinaSchmitt** [comment]
Ja stimmt.
Danke!!!
