### ISSUE TITLE
Keine einzelnen Ids

### ISSUE THREAD

**Issue by julianSchubert** [JirkaDellOro/EIA2#306]
Hallo,
ich komme nicht weiter habe die Funktion zum ablegen der Handkarten soweit geschrieben aber sie funktioniert nicht. Er erkennt die Ids auf denen die ganze Funktion basiert nicht.
Aber beim untersuchen der Elemente werden diese angezeigt.
Ich vermute es ist nicht der gleiche Fehler wie bei Katharina eine Überprüfung fand statt.

Hier der Link zum Code:

https://github.com/julianSchubert/EIA2/tree/master/Aufgabe3

Hier die Seite:
https://julianschubert.github.io/EIA2/Aufgabe3/index.html

Danke schonmal
Julian

**Comment by Plagiatus** [comment]
warum heißt das Kartenobjekt "neueReihenfolge"?

Schau mal deine Karten über den Inspektor genau an.

außerdem, denke bitte an die Coding Guidelines.

**Comment by julianSchubert** [comment]
Das ist eine gute Frage hab es mal umbenannt. 
Guidelines werde ich noch beachten, danke.

Habe jetzt die Karten im Inspektor angeschaut und die ID ist nicht auf dem div der einzelnen Handkarten. Wie bekomme ich die da aber hin? Nach meinem Verständnis sollte die aber da sein um die Funktion zu gewährleisten.

**Comment by Plagiatus** [comment]
Richtig. zum einen landen deine Attribute auf dem p element und nicht dem div, zum anderen landen sie auch da nicht richtig. z.B. als Klasse `class="Pik id="` sieht für mich etwas komisch aus. 

Und die sind auf dem P Element, weil du sie in Z296 dem P Element hinzufügst.

**Comment by julianSchubert** [comment]
Danke ein "" zu wenig und alles fürn Arsch.

Schönen Abend noch. Und nochmals Danke
