### ISSUE TITLE
event.target funktioniert nicht richtig

### ISSUE THREAD

**Issue by Gosselbe** [JirkaDellOro/EIA2#307]
Hallo,

ich komm bei meinem Code im Moment nicht weiter.
Bei meiner Funktion zum Ablegen der Handkarten wird irgendwie das Target nicht übertragen. Manchmal wird an einer zufälligen Stellen eine zufällige Karte in den Ablage-Array gepush, aber auch hier immer nur eine. 

Hier der Code:
https://github.com/Gosselbe/EIA2/blob/master/task3/main.ts

Hier die Index:
https://gosselbe.github.io/EIA2/task3/index.html

Danke schonmal für die Hilfe!
Bente

**Comment by R4Pi3R** [comment]
Ich vermute zwar, dass der Code noch in Arbeit ist, aber er ist definitiv zu unübersichtlich. Es werden überall zwischen Funktionen globale Variablen deklariert, die nicht global sein müssten und selbst wenn sie es müssten definitiv am falschen Ort sind.
Warum gibt es 2 fast gleiche writeHTML Funktionen?

In einer davon steckt auch der Fehler.
Das Event funktioniert wunderbar, die Abfrage trifft aber nie zu, da die zugeteilte ID und der Wert, der im Interface der jeweiligen Karte hinterlegt ist, nicht übereinstimmen.
Schau mal welchen Wert du in der Funktion als ID zuweist.

**Comment by Gosselbe** [comment]
In der Konsole wird jetzt korrekt angezeigt, welche Karten in das Ablagestapel-Array gepusht wurden, aber im User Interface wird nur die erste, angeklickte Karte gepusht und die nächsten generieren einen Absatzt wenn sie angeklickt werden.

**Comment by Plagiatus** [comment]
Bei mir funktioniert da gar nichts so richtig. Wenn ich auf eine Karte klicke kommt nur manchmal überhaupt eine Karte auf dem Stapel an, oftmals ist es nicht einmal die richtige Karte.

Überprüfe doch mal, welche Werte die HTML Karten tatsächlich bekommen. Lies nochmal @R4Pi3R's Kommentar.

**Comment by LucasRohrberg** [comment]
Sieht für mich beim ausprobieren & durch Debugger laufen eher danach aus, dass die Karten falsch positioniert werden. Es werden schon die richtigen Karten ins Ablage-Div gepusht und aus dem Handkarten-Div entfernt, nur sind die Karten des Ablage-Divs in der Darstellung alle untereinander ^^Also entweder über CSS lösen oder nur die neueste Karte des Ablagestapels darstellen lassen.

**Comment by Gosselbe** [comment]
Habs jetzt über CSS hinbekommen, war wirklich nur die Ansicht, die rumgesponnen hat. 
Vielen Dank an euch für die Hilfe und noch einen schönen Sonntag.
