### ISSUE TITLE
Läuft alles, aber...

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2#308]
Moin moin,
das Gute vorweg: Alle geforderten Aufgaben werden richtig ausgeführt.

Problem: Wenn man die Aktionen "mischt", also z.B. eine Karte zieht, ablegt, sortiert, nachzieht usw. macht mein Code Faxen. Vermutlich befindet sich der Fehler in einer Schleife und vermutlich in der Funktion removeCard (Zeile 51). Da ich den Fehler nicht finden kann, hoffe ich auf eure Unterstützung.

LG Jonas 

https://jonas915.github.io/EIA2/Aufgabe3/Aufgabe3.html

https://github.com/Jonas915/EIA2/blob/master/Aufgabe3/Aufgabe3.ts

**Comment by R4Pi3R** [comment]
Das Problem ist die Zuweisung der IDs und wird beim Spielen der Karten hervorgerufen. Führ das Spiel mal aus, spiel ein paar Karten und schau dir dann im Inspektor die HTML Seite an.

**Comment by Jonas915** [comment]
Danke für den Hinweis, habe ich gemacht. Ich verstehe auch, was er macht, weiß aber immer noch nicht warum... Habe diverse Sachen ausprobiert, aber die konnten das Problem nicht lösen. Wenn ich es bis Donnerstag nicht herausgefunden habe wäre es super, wenn du mir zeigen könntest, wie man es umschreiben müsste, aber ich mach erst mal noch weiter.

**Comment by Plagiatus** [comment]
Speziell, schau auch in den Ablagestapel mit rein.

**Comment by AnnaLotz** [comment]
Und, magst du uns verraten woran es gelegen hat?
