### ISSUE TITLE
Probleme beim Sortieren und Karten legen

### ISSUE THREAD

**Issue by MichelOrlik** [JirkaDellOro/EIA2#309]
Wie schon im Betreff steht, klappt es bei mir einfach nicht die Karten aus der Hand auf den Ablegestapel zu legen. Ich sitze seit Stunden dran und finde einfach den Fehler nicht. Evtl. ist der Code an sich das Problem...(Zeile 276-301)
Zudem finde ich den Fehler beim Sortieren nicht. Wenn ich sortiere dann generiert es kein neues Array mit Handkarten. Aber genau da habe ich das Problem, dass ich nicht genau weiß was ich einfügen muss damit es klappt, da egal was ich eingebe er das nicht annimmt.
https://michelorlik.github.io/EIA2/Aufgaben/Aufgabe%203/index.html
https://github.com/MichelOrlik/EIA2/blob/master/Aufgaben/Aufgabe%203/js/main.ts

**Comment by JirkaDellOro** [comment]
In der Console steht
main.ts:303 Uncaught ReferenceError: handCards is not defined
    at HTMLButtonElement.sortieren (main.ts:303)

Wo wird handCards denn definiert?
