### ISSUE TITLE
Bienen und Blumen erscheinen nicht mehr

### ISSUE THREAD

**Issue by hejSalome** [JirkaDellOro/EIA2#31]
Hallo! 

Plötzlich waren meine Bienen weg als ich etwas am Code der Blumen verändert habe. Und meine Blumen zeigt es auch nicht an. Liegt der Fehler möglicherweise in Zeile 79? 
https://github.com/hejSalome/EIA2/blob/master/aufgabe7/classes.ts

Gruß und danke schonmal, 
Salome

**Comment by JirkaDellOro** [comment]
Folgendes fällt mir auf:
* setRandomFlower denkt sich eine Position aus, diese wird aber nicht genutzt. Die Blumen werden offensichtlich auf 0,0 gezeichnet. Das sieht man auch in der Konsole.
* es ist sicher nicht erforderlich, in der Blumenmalschleife bei jeder Blume den Hintergrund zu speichern.
* ein Debugger-Breakpoint in animate zeigt, dass die Funktion wohl nie aufgerufen wird. Dann können die Bienen auch nicht fliegen.
* ... was ein Glück ist, denn es würde für jede Biene ein Timeout installiert!!

**Comment by hejSalome** [comment]
Vielen Dank für die schnelle Rückmeldung und Hilfe.
