### ISSUE TITLE
Sortieren klappt nur in Firefox, nicht in Safari

### ISSUE THREAD

**Issue by Ninjanna** [JirkaDellOro/EIA2#310]
Ich habe diese Woche irgendwie ständig Probleme mit dem Hochladen. Der Link zur Skizze funktioniert zwar endlich, aber der Code läuft nur in Firefox korrekt.
Genauer: meine handSortieren funktion die aufgerufen wird, wenn man den Sortieren button klickt, funktioniert einwandfrei in Firefox (sogar mit sortierung nach zahlen :), aber leider nicht in Safari. Der Rest (Karten nachziehen, ablegen) klatt überall. 
Habe ich irgendwas vergessen? Muss man auf etwas bestimmtes achten damit der Code überall läuft? 

Ich bin total ratlos und bedanke mich jetzt schon für jegliche Hilfe. 

https://github.com/Ninjanna/EIA2/blob/master/Aufgabe3/Maumau3.html
https://github.com/Ninjanna/EIA2/blob/master/Aufgabe3/maumau3.ts

**Comment by Ninjanna** [comment]
Alles klar, hier ist der Link: 
https://ninjanna.github.io/EIA2/Aufgabe3/Maumau3.html

**Comment by Plagiatus** [comment]
Mir fällt in deinem Code auf, dass du niemals -1 zurück gibst. Immer nur 1 oder 0, was für den sortieralgorithmus bedeutet, dass immer entweder a größer ist oder a und b gleichwertig sind.

Ich bin mir nicht ganz sicher warum das in verschiedenen Browsern zu verschiedenen Ergebnissen führt, vermute aber dass diese eine unterschiedliche Implementation der eingebauten Sortierfunktion nutzen, welche dann zu diesen unterschiedlichen Ergebnissen führen. Von [MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/sort):
> Die Zeit- und Speicherkomplexität des Sortierens kann nicht garantiert werden, weil sie implementierungsabhängig ist.

Ich würde vermuten wenn dein Code die richtigen Werte zurück gibt, dann sortieren auch die anderen Browser richtig.

**Comment by Plagiatus** [comment]
Und, woran lag es jetzt?
