### ISSUE TITLE
Eissorten werden nicht übertragen und berechnet

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2#312]
Mahlzeit,
bei meinem Code geklingt es mir nicht, dass die einzelnen Sorten 1-4 in der Übersicht angezeigt und berechnet werden. Wie krieg ich das gefixt?

Beste Grüße
Jonas

https://jonas915.github.io/EIA2/Aufgabe4/Index.html

https://github.com/Jonas915/EIA2/blob/master/Aufgabe4/css_ts_js/Funktionen.ts

**Comment by Plagiatus** [comment]
Wie versuchst du es denn bisher? Was ist dein Ansatz? Das kann ich deinem Konzept leider nicht so richtig entnehmen.

**Comment by Jonas915** [comment]
Hab ich doch tatsächlich nur vergessen den compiler anzuschmeißen..
