### ISSUE TITLE
Preis der Kugelanzahl falsch gerechnet

### ISSUE THREAD

**Issue by KatharinaSchmitt** [JirkaDellOro/EIA2#313]
Hallöchen,

ich rechnen meinen Preis für alle Eiskugel zur Zeit falsch aus und weiß nicht, was ich ändern muss damit das richtig klappt.

Mit einem Stepper kann man bei mir Kugelanzahl der einzelnen Sorten festlegen. Um den Gesamtpreis zu berechnen, rechne ich die target.value * Preis einer Kugel.
Wenn ich die Kugelanzahl änderen, müsste ich doch das vorherige value * Kugelpreis abziehen, bevor ich das neue value * Kugelpreis addieren?
Bzw. ich müsste die values der Kugelanzahlen pro Sorte * Kugelpreis rechen (nicht nur *target.value)?
Ich weiß jedoch nicht, wie ich die values anspreche (ohne target.value zu verwenden).

Hier mein ts:
https://github.com/KatharinaSchmitt/EIA2/blob/master/Aufgabe4/js/main.ts

und die index:
https://katharinaschmitt.github.io/EIA2/Aufgabe4/index.html

Danke schonmal!
Katharina Schmitt

**Comment by JirkaDellOro** [comment]
Ich erlaube mir hier einen Tipp zu geben, der im letzten Semester bereits in der Aufgabenstellung angeführt wurde:

Tipp: Lassen Sie bei jeder Interaktion mit dem Formular die Berechnung und Darstellung der Zusammenfassung komplett neu durchführen! (Dies können Sie bereits im Anwendungsfalldiagramm als Inklusion angeben)
