### ISSUE TITLE
label wird nicht angezeigt

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2#315]
in meiner Konsole sehe ich das meinen checkboxen ein Label hinzugefügt wird aber es wird nicht angezeigt

**Comment by Plagiatus** [comment]
bitte die Links dazu posten

**Comment by reginafaller** [comment]
https://reginafaller.github.io/EIA2/task6/HTML/test.html

**Comment by Plagiatus** [comment]
das scheint mir daran zu liegen, dass du deine labels _in_ den input feldern sind statt danach hast.

**Comment by Plagiatus** [comment]
außerdem hast du kein Konzept sondern bist direkt am programmieren?

**Comment by reginafaller** [comment]
Gibt es einen Weg, es nicht als child der Checkbox anzuhängen? ich kann es ja nicht dem fieldset anhängen in dem alle boxen sind. Es müsste als sibling angehängt werden...

Ich muss das Konzept noch hochladen

**Comment by Plagiatus** [comment]
du kannst auch dem Label das input element hinzufügen. Siehe https://wiki.selfhtml.org/wiki/HTML/Formulare/label
