### ISSUE TITLE
Preis nicht über Value?

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#316]
Hey, ist eher eine Frage als ein Problem, aber ich wollte wissen, ob man den Preis immer noch mit "value" anzeigen lassen kann, oder ob es sich um einen im Array definierten Preis handeln muss. Genau so die Frage bei der Darstellung im Checkout. Ich habe die ausgewählten Sorten usw. mit classname anzeigen lassen. Geht das noch, oder soll ich es besser ändern?

**Comment by Plagiatus** [comment]
von was für einem Value sprichst du hier?  

Grundsätzlich sollte der value genutzt werden, um z.B. die Anzahl der Kugeln zu speichern oder welcher Radiobutton in einer Gruppe ausgewählt ist und nicht um irgendwelche eigenen Werte zwischen zu speichern. Wenn ihr etwas eigenes speichern wollt, dann nutzt eigene Attribute (s. Hinweise in der Aufgabe).  
wie sich das genau auswirkt wenn man value dafür missbraucht, machen wir voraussichtlich nächste Woche in der Vorlesung.

Außerdem braucht ihr ja eigentlich den Preis gar nicht mehr im HTML hinterlegen, da ihr die Preise ja bereits im Händler-Objekt Festgelegt habt.

**Comment by mtmatern** [comment]
Ja, hast es richtig verstanden. Dann missbrauche ich die value mal nicht ;)
