### ISSUE TITLE
Eissorten werden richtig hinzugefügt jedoch falsch entfernt 

### ISSUE THREAD

**Issue by SinaHaas** [JirkaDellOro/EIA2#317]
Hallo,

Ich habe ein Problem mit meinem Code. Die Eissorten werden im User Interface beim Anklicken richtig angezeigt, beim entfernen werden jedoch nicht die richtigen entfernt.
Ich glaube es liegt an meinem Vergleich, kann jedoch kein System dahinter erkennen.

Ich hoffe ihr könnt mir helfen und vielen Dank im voraus.

Hier meine main.ts Zeile 85: https://github.com/SinaHaas/EIA2/blob/master/aufgabe5/js/main.ts
Hier meine data.ts: https://github.com/SinaHaas/EIA2/blob/master/aufgabe5/js/data.ts

Index: https://sinahaas.github.io/EIA2/aufgabe5/index.html

**Comment by Plagiatus** [comment]
der Fehler wird ja von einer Error Meldung in der Konsole begleitet.

```
Argument 1 of Node.removeChild is not an object.
main.ts:88:20
```

Das Problem scheint mir zu sein, dass du alle input Felder durch gehst, und dann versuchst das Kind mit dem gleichen index das Input Feldes zu entfernen. Das geht natürlich nur dann, wenn die Inputs in genau der richtigen Reihenfolge angeklickt werden und als Kind hinzugefügt/entfernt werden.

Ich möchte dich, um dir zukünftige Kopfschmerzen zu ersparen, an Hinweis Nr. 2 erinnern.

**Comment by SinaHaas** [comment]
Okay funktioniert jetzt, vielen Dank!
