### ISSUE TITLE
Gesamtpreis falsch gerechnet

### ISSUE THREAD

**Issue by KatharinaSchmitt** [JirkaDellOro/EIA2#318]
Hallöchen,
ich hab mal wieder ein Problem bei meiner Berechnung des Gesamtpreises.
Solange ich nur Eissorten oder nur Toppings auswähle, klappt alles. Sobald ich beides auswähle nicht mehr.
Wenn ich z.B. schon eine Eissorte gewählt habe und danach ein Topping auswähle, rechnet es mir mit dem gleichen Preis für Eissorte und Topping, obwohl der Preis für die Toppings eigentlich geringer ist.

Hier meine ts:
https://github.com/KatharinaSchmitt/EIA2/blob/master/Aufgabe5/js/data.ts
https://github.com/KatharinaSchmitt/EIA2/blob/master/Aufgabe5/js/main.ts
(Funktion für Gesamtpreis beginnt ab Zeile 88)

und html:
https://katharinaschmitt.github.io/EIA2/Aufgabe5/index.html

Danke schonmal!
Katharina

**Comment by obiwan1337** [comment]
Guten Mittag,

du liest den Preis des angeklickten Elements aus und rechnest nur mit dem. 
Die Berechnung mit dem Preis an Stelle i ist die Lösung.

**Comment by KatharinaSchmitt** [comment]
Danke!!! Klappt jetzt :)
