### ISSUE TITLE
"class extends value undefined ist not a constructor"

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#32]
Hallo zusammen, 
kann mir vielleicht jemand diese Fehlermeldung der Console erklären? Ich verstehe nicht was ich ändern muss, der Code zeigt in Eclipse keine Fehler an...

Danke schon mal im Voraus

https://fehrenbi.github.io/EIA2/Aufgabe%208/aufgabe8.html

**Comment by RedImp1470** [comment]
Versuch mal deine Superklasse(n) in der HTML-Datei vor, also über, den Subklassen einzubinden. Hilft das?

**Comment by fehrenbi** [comment]
Ja danke da war der Fehler :) Hatte auch die draw Methode noch nicht aufgerufen, aber jetzt funktioniert es. Danke!
