### ISSUE TITLE
Fehler Meldung "main.ts:130 Uncaught TypeError: Cannot read property..." bei Stepper

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#320]
Ich versuche gerade den Preis meiner einzelnen Eissorten (Stepper) anzeigen zu lassen. Ich habe es genau so gemacht, wie beim radiobutton für die Auswahl von Waffel oder Becher. Da funktioniert es einwandfrei. Leider komme ich nicht darauf, warum der Browser mir dann bei der ersten Sorte Schokolade sagt : "Uncaught TypeError: Cannot read property 'preis' of undefined at HTMLFieldSetElement.handleChange (main.ts:130)". Was muss ich bei den Steppern anders machen? https://github.com/mtmatern/EIA2/tree/master/Aufgabe5

**Comment by Plagiatus** [comment]
bitte den link zur ausführbaren Datei dazu posten, damit wir das nachvollziehen können (und im debugger nachschauen können, was ich hoffe du auch schon gemacht hast).

**Comment by Plagiatus** [comment]
Vorallem sehe ich gerade, dass du ja pro Eissorte ein Array mit jeweils einem Eintrag hast?? Und dann doch wieder jede einzelne Sorte hart codiert hast? Das geht komplett gegen die Aufgabe!

**Comment by mtmatern** [comment]
https://mtmatern.github.io/EIA2/Aufgabe5/index.html

Jo, bin schon durch mit dem Debugger. Ja, die sind jeweils in einem Array. Ich packe die sofort in eins. Ah, ich weiß was du meinst. Ja das macht mit Blick auf die Aufgabe in der Tat keinen Sinn . Ich überarbeite nochmal und melde mich dann wieder. Vielleicht ist ja dann der Fehler eh gefixt.

**Comment by mtmatern** [comment]
Guten Morgen, ich habe jetzt meinen Code überarbeitet und glaube so den richtigen Ansatz gefunden zu haben. Jetzt wird aber schon bei der HTML-Generierung der ersten zwei Radiobuttons, kein label angezeigt. Ich bin mit dem Debugger durch und habe versucht darauf hin den Code anzupassen, jedoch ohne Erfolg. Kann mir da jemand weiterhelfen? https://mtmatern.github.io/EIA2/Aufgabe5/index.html

**Comment by Plagiatus** [comment]
schau mal in den Inspektor wo deine Labels sind. Die sind nämlich da, aber am falschen Ort wenn du die mit "for" verlinken möchtest

**Comment by Plagiatus** [comment]
Dazu: siehe https://wiki.selfhtml.org/wiki/HTML/Formulare/label für die verschiedenen Möglichkeiten ein label einzubinden.

_Der Ansatz ist übrigens tatsächlich deutlich besser. Und wie du bestimmt gemerkt hast, auch Codemäßig deutlich schlanker_

**Comment by mtmatern** [comment]
Danke, habs gefixt bekommen.
