### ISSUE TITLE
Error bei Heroku

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2#322]
Hallo,
ich kann die Testseite bei Heroku erstellen (Aufgabe 3.2), allerdings bekomme ich den Error im Angang angezeigt. Mit dem Link, auf den ich verwiesen werde, komme ich leider nicht weiter.

Pls help, ohne das geht´s nicht weiter..

![Screenshot (45)](https://user-images.githubusercontent.com/44026431/57079416-94729980-6cf0-11e9-8256-5a37f6d78605.png)

Link Repository:  https://github.com/Jonas915/EIA2/tree/master/Aufgabe6

**Comment by Jonas915** [comment]
Done. Diese 3 Screenshots helfen vielleicht weiter:

![Screenshot (48)](https://user-images.githubusercontent.com/44026431/57080560-0ba92d00-6cf3-11e9-84dc-3f80e6e46193.png)

![Screenshot (49)](https://user-images.githubusercontent.com/44026431/57080575-119f0e00-6cf3-11e9-9634-d4833f124791.png)

![Screenshot (51)](https://user-images.githubusercontent.com/44026431/57080591-1663c200-6cf3-11e9-8b38-ddb254a146cd.png)

**Comment by Jonas915** [comment]
Deployed wurde die App aber.

![Screenshot (53)](https://user-images.githubusercontent.com/44026431/57080804-9db13580-6cf3-11e9-83ab-814d6fedd94d.png)

**Comment by Plagiatus** [comment]
hast du die app neu gestartet während die logs offen waren? weil in denen logs steht nicht die eigentliche Fehlermeldung drin sondern "schau mal weiter oben in den logs, da steht wahrscheinlich der eigentliche Fehler".

**Comment by Plagiatus** [comment]
und wenn das alles ist, dann ist wohl der Pfad falsch. prüfe nochmal deine package.json datei mit meiner.

**Comment by Jonas915** [comment]
Ich danke dir! Es war tatsächlich "nur" ein falscher Pfad. Dummer Fehler, sorry...

**Comment by Plagiatus** [comment]
Es gibt keine dummen Fragen. Wer nicht fragt und sich stattdessen mehr arbeit macht ist dumm. 😉
