### ISSUE TITLE
Heroku Error (Deploy Branch)

### ISSUE THREAD

**Issue by RueJohannes** [JirkaDellOro/EIA2#323]
Hallo, wenn ich auf "Deploy Branch" klicke kommt folgende Fehlermeldung:

![heroku_issue](https://user-images.githubusercontent.com/44100365/57081344-cdad0880-6cf4-11e9-8443-81501edb1fb0.PNG)

**Comment by Plagiatus** [comment]
liegt deine package.json am richtigen Ort?

**Comment by RueJohannes** [comment]
"start" Dateipfad war nicht korrekt. Jetzt funktionierts.
