### ISSUE TITLE
Heroku Application error

### ISSUE THREAD

**Issue by MarcelMielcarek** [JirkaDellOro/EIA2#324]
Nachdem ich die App Deployed habe, erscheint die Fehlermeldung "Application Error". Im Viewlog kriege ich dann folgende Errors. Die Dynos habe ich auch schon neu gestartet, behebt den Fehler aber nicht. 

![issue1](https://user-images.githubusercontent.com/37657719/57141866-8dfd2400-6dbb-11e9-8998-1430a5c78d7f.png)

**Comment by Plagiatus** [comment]
stimmt der Pfad? Auf groß-kleinschreibung achten

**Comment by MarcelMielcarek** [comment]
...das wars, Danke.
