### ISSUE TITLE
Heroku Fehler

### ISSUE THREAD

**Issue by Annsophie100** [JirkaDellOro/EIA2#325]
Hello :)
Also bei mir stimmt irgendwas gar nicht und ich versteh nicht was das Problem ist. Mir wird ein Fehler beim Öffnen der App angezeigt. Ich schätze es findet irgendwelche Dateien nicht aber ich weiß nicht wieso, denn sie liegen eigentlich auf der richtigen Ebene. Wenn ich den Log in Heroku öffne und den angegebenen Fehler eingebe tut sich leider auch nichts.
Lokal funktioniert alles.

Please Help ich bin langsam echt verzweifelt.

<img width="587" alt="heroku Problem" src="https://user-images.githubusercontent.com/48793597/57184048-b406ef00-6eb5-11e9-8ad0-386aebaf35e6.png">
<img width="1224" alt="Fehlermeldung" src="https://user-images.githubusercontent.com/48793597/57184058-e7497e00-6eb5-11e9-97c2-320799e07b13.png">

**Comment by Plagiatus** [comment]
das Bild ist vom Ende des Fehlers. Starte mal die dynos neu (s. #322 ) während du die logs offen hast.

Ich vermute aber mal stark, dass der Pfad den du in der package.json angibst nicht stimmt.

**Comment by Ninjanna** [comment]
Danke für die Antwort. Den Pfad haben wir mehrfach überprüft, Anna gefragt, das Repository neu verbunden hilft alles nix und nerven liegen blank. Hast du noch eine andere Idee woran es liegen könnte?

**Comment by Annsophie100** [comment]
😢😢😢😢😢😢

**Comment by Ninjanna** [comment]
wie man in den logs sieht scheint der Fehler etwas mit "node_modules missing" zu tun zu haben, vielleicht hilft das?

**Comment by Plagiatus** [comment]
Ich habe jetzt nochmal in eure package.json rein geschaut und meine Vermutung hat sich bestätigt: ihr gebt bei `scripts start` den falschen Pfad an.
Der Pfad muss relativ zum Repository sein, d.h. EIA2/ darf da nicht drin stehen. Sondern es geht z.B. bei Janna mit `Aufgabe06/test/...` los

**Comment by Annsophie100** [comment]
Danke Lukas 💙 ES TUUUUUUUT 🎉🎉🎉

**Comment by Plagiatus** [comment]
bitte schließen wenn das Problem gelöst wurde. 😉
