### ISSUE TITLE
wechseln auf server verhindern

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2#327]
wenn ich meine Bestellung abschicke, wechselt es automatisch auf die Server Seite. Ich dachte _response.write schickt meine Url an mein HTML zurück. wie bekomme ich es hin, dass mein Server etwas zurück schickt? https://reginafaller.github.io/EIA2/task8/HTML/test.html

**Comment by Plagiatus** [comment]
war wechselt es denn automatisch auf die Serverseite? Der Server sagt nicht "los komm zu mir", wenn dann muss irgendwas im Client sagen "ich will da jetzt hin". Was hat denn letzte Woche dem Client gesagt dass er wechseln soll?
