### ISSUE TITLE
Preisberechnung geht nicht mehr seit update

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2#329]
So, die magische 30-Minuten-Grenze ist überschritten, deshalb hier mein Problem:

Seitdem ich die Seite angepasst habe, funktioniert die Preisberechnung nicht mehr. Wenn ich die // bei  "preisForm =... " etc. weg lasse, werden die Elemente nicht mehr im HTML generiert.

https://jonas915.github.io/EIA2/Aufgabe6/Index.html

**Comment by Plagiatus** [comment]
was hast du denn angepasst? und von welcher Zeile sprichst du, die nicht mehr funktioniert?

**Comment by Plagiatus** [comment]
Gibt es einen Error in der Konsole wenn du das einkommentierst und deine Elemente nicht mehr generiert werden? 
Schau mal mit dem Debugger rein, was genau du da für einen Wert rein gibst und wo der her kommt, das hilft dir hoffentlich.
