### ISSUE TITLE
Probleme bei der Animation der Honigbienen

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#33]
Hallo,
Meine Honigbienen werden zwar erstellt, jedoch nicht mehr gezeichnet. Werden die Informationen aus der update bzw. move Methode nicht an die Subklasse weitergegeben, weil ich sie mit den neuen Angaben in der nectarBee.ts überschreibe? 
Ich glaube das hängt auch mit der Übergabe der Target-Koordinaten zusammen. Ich komme aber leider nicht weiter. 

Danke im Voraus!
https://lisamei.github.io/EIA2/Aufgabe07/start.html

**Comment by RedImp1470** [comment]
Das erste was mir auffällt ist, dass du in deinem Konstruktor für die Nektarbienen die Target-Koordinaten übergibst aber nie setzt. Evtl. hilft dir das ja schon weiter.
Wenn ich das richtig sehen werden die Nektarbienen sehr wohl gezeichnet - das sind die, welche am Bienenstock kleben und sich nicht bewegen. Das kannst du prüfen, indem du die Zeile, in der die Nektarbienen erzeugt werden mal auskommentierst, wenn die klebenden Bienen dann weg sind hatte ich Recht :).

**Comment by LisaMei** [comment]
Wie blöd, danke! Das bringt mich schon mal viel weiter!
