### ISSUE TITLE
server response verschieden wenn auf Heroku server oder lokal

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2#330]
wenn ich meinen Server lokal starte und etwas bestelle bekomme ich meine server Antwort wie gewollt formatiert  in mein HTML geschrieben. Aber wenn ich meine Adresse in meiner SendData.ts auf meine Heroku app umstelle, gibt es mir meine Server response in einem umformatierten string aus. Theoretisch müsste ja das selbe passieren, wie das was passiert wenn ich den server lokal starte oder? Ich habe meine Heroku app neu deployed, muss ich sonst noch etwas ändern?

https://reginafaller.github.io/EIA2/task8/HTML/test.html

**Comment by Plagiatus** [comment]
Wurde sie tatsächlich neu deployed? Weil deine package.json referenziert auf eine Datei, die nicht existiert.

**Comment by reginafaller** [comment]
stimmt, Problem gelöst Danke!
