### ISSUE TITLE
Bei richtigen Angaben wird kein HTML geschrieben

### ISSUE THREAD

**Issue by RittEvA** [JirkaDellOro/EIA2#331]
Hallo zusammen,
meine handleStateChange() wird nur dann aufgerufen, wenn ich bei meiner Postleitzahl weniger als 5 Zahlen eingebe und es wird mir in mein HTML alles richtig geschrieben. Ansonsten wird sie nicht aufgerufen und somit auch nicht in mein HTML geschrieben. Es werden alle Eisorten mit Value, so wie die Adresse in die url geschrieben und alles was ich vorher erstellen lasse wird ignoriert.
Vielleicht habt ihr eine Idee an welcher Stelle der Fehler liegt.
Vielen Danke schon mal im Voraus.

Server.ts: https://github.com/RittEvA/EIA2-Aufgaben/blob/master/Aufgabe7/js/Server.ts

main.ts: https://github.com/RittEvA/EIA2-Aufgaben/blob/master/Aufgabe7/js/main.ts

Link zum Dealer: https://ritteva.github.io/EIA2-Aufgaben/Aufgabe7/index.html

**Comment by Plagiatus** [comment]
deine Seite lädt sich selbst neu in dem Moment wo der Button erfolgreich abgeschickt wird. Darum wird dann auch der Antwortlistener verworfen und nie aufgerufen, da er ja auf die eben verlassene Seite angesetzt wurde.
Du musst also verhindern, dass die Seite neu geladen wird.

**Comment by RittEvA** [comment]
Leider kann ich den Befehl zum Neuladen der Seite nicht finden. Oder wie kann ich verhindern das die Seite neu geladen wird?

**Comment by Plagiatus** [comment]
Ich muss zugeben, dass ich dabei gerade auch etwas überfragt bin. der Button ist nicht `type="submit"` und auch sonst finde ich nichts, was mir direkt entgegenspringt als "ich bin der Fehler".

Versuche doch mal, das `<form>` aus dem HTML zu entfernen. oder zumindest einmal die method raus zu nehmen, evtl hilft das ja.

**Comment by RittEvA** [comment]
Ich habe beides ausprobiert und es hat sich nichts verändert

**Comment by JirkaDellOro** [comment]
Ich will mir das Projekt jetzt nicht ziehen, aber wenn ich mir die Main.ts so anschaue, fällt mir auf, dass sie nicht richtig formatiert ist. Einmal Autoformat laufen lassen, dann sieht man leichter Klammerfehler. Gleiches auch für die HTML-Datei.

Des Rätsels Lösung findet ihr aber wahrscheinlich hier https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button unter Attribute "type"

**Comment by Plagiatus** [comment]
stimmt, das klingt nach dem Problem 👍 
ich hätte nicht erwartet, dass submit der default case ist.

**Comment by JirkaDellOro** [comment]
Da bin ich schon x-mal dran hängen geblieben... :slightly_frowning_face:

**Comment by RittEvA** [comment]
Ich habe jetzt den Type des Buttons geändert und bekomme jetzt die URL in mein HTML geschrieben jedoch nicht aufgeteilt wie erwartet als eigene Elemente sondern einfach den string.

**Comment by Plagiatus** [comment]
joa, das ist ja auch das was dein Heroku Server dir zurück gibt.

**Comment by RittEvA** [comment]
.. aber eigentlich sollte der Server den String aufbereiten, was er aber nicht tut. Warum nicht?

**Comment by Plagiatus** [comment]
in deiner verlinkten Server.ts scheint er das zu tun. ist das aber auch die Server.ts die auf Heroku läuft? (offensichtlich nicht, sonst würde ich nicht so blöd fragen)

**Comment by RittEvA** [comment]
Vielen lieben Dank. Ich habe den Link geändert aber in der falschen Datei. Jetzt habe ich es korrigiert.
