### ISSUE TITLE
Acess Control Problem 

### ISSUE THREAD

**Issue by Annsophie100** [JirkaDellOro/EIA2#332]
Es gibt ja in der Server Ts die Zeile "Acess Control lign origin"
Aber wenn ich versuch zu tun was ich tun muss dann kommt die Fehlermeldung

<img width="1261" alt="Bildschirmfoto 2019-05-10 um 17 02 34" src="https://user-images.githubusercontent.com/48793597/57538679-3aee1880-7349-11e9-8997-906beaae5edc.png">
<img width="723" alt="Bildschirmfoto 2019-05-10 um 17 02 52" src="https://user-images.githubusercontent.com/48793597/57538687-3de90900-7349-11e9-9c5a-f2a640485602.png">

muss ich das irgendwo anders schrieben oder warum versteht das nicht das es da schon steht?
Liegt es eventuell daran das ich meinen Form Tag im HTML durch einen DIv ersetzt habe?

<img width="889" alt="Bildschirmfoto 2019-05-10 um 17 06 34" src="https://user-images.githubusercontent.com/48793597/57538783-696bf380-7349-11e9-8c81-acaeb2f216f0.png">

Die Aktuellste Version von meinem Code ist Online. Irgendwas mit der Server Anbindung tut einfach nicht. 

Könnte es auch ander Package Jason Liegen? Hab die zwar angepasst aber ich bin nicht sicher ob das so richtig ist 😅

Please help #missongrüneampel

**Comment by Plagiatus** [comment]
wie immer gilt: bitte die relevanten Links (zur ts Datei in der du den Fehler vermutest, zur ausführbaren HTML Datei) dazu posten, dann können wir viel einfacher prüfen was nicht nicht stimmt. Deine Screenshots sehen ok aus.

**Comment by Annsophie100** [comment]
zur index.html für den Eisdealer >>
https://github.com/Annsophie100/EIA2/blob/master/Aufgabe07/Client/index.html

zur main.ts für den Eisdealer >>
(funtkionen für serververhalten ganz unten)
https://github.com/Annsophie100/EIA2/blob/master/Aufgabe07/Client/scripts/main.ts

zur server.ts >>
https://github.com/Annsophie100/EIA2/blob/master/Aufgabe07/Server/server.ts

**Comment by Plagiatus** [comment]
> zur ausführbaren HTML Datei
Der fehlt noch

**Comment by Plagiatus** [comment]
Außerdem scheint dein Heroku ein Problem zu haben. Wahrscheinlich ist das Problem gar das AccessControlAllowOrigin sondern was auch immer dazu führt dass der Server abstürzt.
![grafik](https://user-images.githubusercontent.com/7681159/57583501-410f0100-74d1-11e9-9464-8ed1d92cc3a0.png)

**Comment by Annsophie100** [comment]
(Die html-Datei)
zur index.html für den Eisdealer >>
https://github.com/Annsophie100/EIA2/blob/master/Aufgabe07/Client/index.html

also ich hab jetzt nochmal die package.json angepasst, mein Repository komplett getrennt, wieder neu verbunden und deployed. Und es tut nicht.

**Comment by Annsophie100** [comment]
ok stopp es geht jetzt 🎉🎉
