### ISSUE TITLE
Bestellbestätigung wird bei jeder Aktion generiert

### ISSUE THREAD

**Issue by JanaKraemer** [JirkaDellOro/EIA2#333]
Hallo,
Mein Problem ist, dass die Bestellbestätigung immer ins HTML geschriben wird, sobald eine Aktion ausgeführt wird und nicht nur, wenn man die Bestellung abschickt. Da der Button einen Event-Listener hat, sollte die Bestätigun nur dann gesenden werden. Ich weiß nicht, wo der Fehler liegt.  Außerdem sollten auch nur die Elemente aufgelistet werden, die auch ausgewählt wurden, also deren value nicht mehr 0 beträgt, sattdessen werden immer alle Elemente angezeigt.
https://janakraemer.github.io/EIA2-Aufgabe/eis_response/ 
Vielen Dank schonmal :)

**Comment by Plagiatus** [comment]
Das Problem ist, dass du die id `senden` nicht nur für den Button verwendet hast und dadurch der Eventlistener auf dem falschen DOM Element gelandet ist.

Wenn du nur die Elemente auflisten willst, die auch angecheckt wurden, dann musst du das natürlich auch Abfragen beim generieren der Anfrage. Im Moment nimmst du dir einfach alles was einen value hat, bzw dessen value nicht bei 0 liegt. Checkboxen und Radiobuttons haben allerdings immer ein value.

Und dein GET-string sieht noch nicht richtig aus, schau da nochmal rein.
