### ISSUE TITLE
Button generiert keine Server Request

### ISSUE THREAD

**Issue by LucasRohrberg** [JirkaDellOro/EIA2#334]
Bei mir schickt ein Click auf den Button keine Request an den Server. Zumindest bleiben jegliche console.logs aus.. Folglich kriege ich auch die Infos nicht an den Server weitergeleitet.. Hab schon einiges probiert, bin momentan leider ratlos. 

Hier meine aktueller Code. Hoffe da ist was zu finden :/
https://github.com/LucasRohrberg/EIA2/tree/master/task-7

Gruß Lucas

**Comment by Plagiatus** [comment]
bitte noch den ausführbaren Link dazu, sonst sehen wir ja gar nicht dass es nicht funktioniert.

**Comment by LucasRohrberg** [comment]
https://lucasrohrberg.github.io/EIA2/task-7/index.html

Den? Da steht ja aber derzeit noch die localhost Adresse drin. Oder soll ich heroku reinschreiben und neu pushen?

**Comment by LucasRohrberg** [comment]
Ja das wars auch schon. Closed :')
