### ISSUE TITLE
Habe eine Ampel für kein Konzept bekommen, nur weil die Kursseite nicht korrekt updatet..

### ISSUE THREAD

**Issue by LucasRohrberg** [JirkaDellOro/EIA2#335]
Ich hatte Donnerstag ein Konzept hochgeladen und verlinkt. Selbst heute am Sonntag wird es noch nicht auf der Kursseite angezeigt. 

https://github.com/LucasRohrberg/EIA2/blob/master/task-7/konzept.pdf
https://github.com/LucasRohrberg/lucasrohrberg.github.io/blob/master/steckbrief/steckbrief.htm

Hoffe ich muss jetzt wegen der fehlerhaften Kursseite nicht auf einer grün-gelben Ampel sitzen bleiben ._.

Gruß Lucas

**Comment by Plagiatus** [comment]
zuerst einmal ist das kein Fehler der Kursseite, sondern wahrscheinlich von GitHub, da der Steckbrief auf Github.io nicht aktualisiert wurde: 
https://lucasrohrberg.github.io/steckbrief/steckbrief.htm

Normalerweise wenn der Page-Build nicht funktioniert, bekommt man eine Benachrichtigung, dass es nicht funktioniert hat, ggf mit dem Grund warum es nicht funktioniert hat. wenn du keinen Grund bekommen hast, dann kann es gut sein, dass Githubs Server in dem Moment Schluckauf hatte. Aber die Benachrichtigung solltest du trotzdem bekommen haben.

Um das zu reparieren kannst du entweder nochmal etwas pushen um den page build erneut anzustoßen oder pages de- und re-aktivieren um auch da den build zu erzwingen.

**Comment by LucasRohrberg** [comment]
Ah oder so. Danke für das Update. Steckbrief wird ja nochmal gepusht wenn ich die Aufgabe nachher hochlade; das sollte es dann fixen.

closed.
