### ISSUE TITLE
Server response als URL im HTML

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#336]
Wenn ich meinen Code mit dem lokalen Server ausführe, wird die Bestellung einwandfrei im HTML aufgelistet. Mit der Heroku App wird aber wieder die URL angezeigt, obwohl ich nur die Adresse von Lokal, zu Heroku geändert habe. Woran liegt das?

https://mtmatern.github.io/EIA2/Aufgabe7/client/index.html

**Comment by LucasRohrberg** [comment]
Du verlinkst in der package.json noch zu aufgabe6/server.js, einfach auf den Dateipfad von Aufgabe 7 updaten

**Comment by mtmatern** [comment]
Habs jetzt aktualisiert, aber es ist immer noch gleich oder?

**Comment by LucasRohrberg** [comment]
![Unbenannt](https://user-images.githubusercontent.com/44026433/57580632-65a4b200-74ac-11e9-9837-ab8936b3f547.PNG)

Also bei mir wirds unten auf deiner Seite hinzugefügt

**Comment by mtmatern** [comment]
Ja genau, aber es soll ja schön strukturiert sein...

**Comment by LucasRohrberg** [comment]
Also bei mir haben die <br>'s nicht funktioniert, als ich sie versucht hab in der server.ts bei den keys mit einzubauen. Hab sie stattdessen bei dem String der URL mit angehängt, dann ging es.. Also bei dir in der main.ts Zeile 51 & 54 hinten n <br> dran ist meine Vermutung :' )

**Comment by mtmatern** [comment]
![60089760_2394162380820410_8203819583300173824_n](https://user-images.githubusercontent.com/44026438/57580719-68ec6d80-74ad-11e9-8c8c-b635aa4aa809.jpg)

Aber das ergibt doch keinen sinn oder? Wenn ich die Adresse wieder zu Lokal ändere, siehts so aus.

**Comment by LucasRohrberg** [comment]
Die Tutoren / Dozenten haben da bestimmt 'ne bessere Erklärung für. Weiß nur dass es bei mir so geklappt hat..

**Comment by mtmatern** [comment]
Okay vielen Dank trotzdem :) Ich probier mal bischen rum 👍

**Comment by Plagiatus** [comment]
@LucasRohrberg nein, das br hat nichts in der Serveranfrage zu suchen, das sollte schon auf dem Server hinzugefügt werden. Und da `br` sowieso nicht so richtig schön ist, wie ihr bestimmt noch aus dem 1. Semester wisst, solltet ihr das ggf sowieso so ändern dass da was gescheites draus wird und nicht nur meinen Beispielcode unreflektiert übernehmen.

@mtmatern ganz spontan würde ich vermuten, dass der Heroku Server nicht neu deployed wurde, also noch mit der alten Version der Server Datei läuft?

**Comment by mtmatern** [comment]
@Plagiatus Jaawoll. Danke! Neu deployed und jetzt klappts. 👍
