### ISSUE TITLE
Daten der Datenbank werden nicht ausgegeben

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2#338]
ich habe den link verändert und die Daten zu meiner Mongo.db Atlas Datenbank angelegt. Ich habe eine collection namens students angelegt und mehrere students darin gespeichert. allerdings bekomme ich, wenn ich den link aufrufe das result: "Unable to connect to database, error: Error: Missing delimiting slash between hosts and options". Außerdem, wenn ich auf click here drücke, werden mir immer noch die test Daten aus dem Example aufgerufen. Jetzt meine Frage, wie verbinde ich meine Datenbank richtig, damit mir meine Students ausgegeben werden wenn ich auf "click here" drücke?   https://mongodbrowser.herokuapp.com/?u=Regina&p=12345&a=mongodb+srv://reginashood-msrks.mongodb.net/test&n=students&c=students

**Comment by Plagiatus** [comment]
das "click here" ist ein Beispiellink der genau dafür ist: ein vorgefertigtest Beispiel sein. Darum wenn du da drauf klickst kommen natürlich die Beispieldaten.

Obwohl deine Adresse nicht stimmt, kann es auch so nicht funktionieren. Das liegt aber daran, dass der Server auf mlab ausgelegt ist und nicht mit den mongodb.net Datenbanken zurecht kommt.
Ich bin schon dabei, den Server umzuschreiben aber das geht noch ein wenig. Ich schicke dann sobald es geht eine Mail rum.

Also, Aufgabe 4 ist erstmal ausgesetzt.
