### ISSUE TITLE
Verständnisproblem bei den Query-Parametern

### ISSUE THREAD

**Issue by MichelOrlik** [JirkaDellOro/EIA2#339]
Da bei der Aufgabenstellung nun "Link wurde geändert!" steht, gehe ich davon aus, dass nun alles klappen sollte.
Für mich stellt sich nun die Frage, was genau, bei den Query Daten, ich unter a= (database address) schreiben soll? Da ich nirgendwo ein @-Zeichen finde.

**Comment by Plagiatus** [comment]
anleitung zum herausfinden der adresse in wenigen schritten:

## 1. hier drauf
![grafik](https://user-images.githubusercontent.com/7681159/57872983-5192e480-780d-11e9-911e-accc17aab96b.png)

## 2. auf irgendeinen davon drauf
![grafik](https://user-images.githubusercontent.com/7681159/57873175-c6661e80-780d-11e9-9119-f7350cdc0765.png)

## 3. das hier
![grafik](https://user-images.githubusercontent.com/7681159/57873213-db42b200-780d-11e9-8db8-7d22dea152be.png)

**Comment by R4Pi3R** [comment]
Im mLab bzw. cloud.mongodb.com account zu der Übersichtseite der Cluster navigieren.
Im jeweiligen Cluster befindet sich dann ein Button "Connect" - drauf drücken. Dort öffnet sich dann diese Auswahl:
![image](https://user-images.githubusercontent.com/25267269/57873317-26f55b80-780e-11e9-90a6-921bf00ba615.png)

Hier auf "Connect your Application" klicken, dann öffnet sich ein Fenster, in dem der Link angezeigt wird.

**Comment by ivenios** [comment]
Ah da findet man das, doch so einfach. 
Habe ich jetzt auch gemacht, aber wenn ich den Link dann anpasse kommt eine nette Fehlermeldung: 

"Unable to connect to database, error: MongoNetworkError: connection 241 to cluster0-shard-00-01-o78er.mongodb.net:27017 closed"

Mein Link: https://mongodbnetbrowser.herokuapp.com/?u=ivenios&p=Ivenotis1801&a=cluster0-o78er.mongodb.net&n=Cluster0&c=sample_airbnb

**Comment by Plagiatus** [comment]
Cluster0 ist nicht der name deiner Datenbank sondern des Clusters der Datenbanken.
Und bist du dir bei Name/PW auch sicher? eigentlich verhindert der solche einfachen passwörter für die Datenbanknutzer.

**Comment by R4Pi3R** [comment]
Ist der Name der Datenbank tatsächlich cluster0? Klingt für mich eher nach dem Namen des Clusters 😅

**Comment by MichelOrlik** [comment]
Hatte/Habe das selbe Problem. Ich habe es überprüft, und es müsste nun eigentlich stimmen. Jedoch wird weiterhin die Fehlermeldung wie bei Iven angezeigt.
Link: https://mongodbnetbrowser.herokuapp.com/?u=control_username&p=desoxyribonukleinsaeure&a=eia2-aufgabe8-michelorlik-mv4yu.mongodb.net&n=EIA2-A8-Datenbank&c=EIA-A8-Collection

**Comment by ivenios** [comment]
Ja tut auch nach den Änderungen leider nicht: 
https://mongodbnetbrowser.herokuapp.com/?u=hans&p=bringzeflammenwerfer&a=cluster0-o78er.mongodb.net&n=sample_airbnb&c=listingsAndReviews

**Comment by Plagiatus** [comment]
euer Error ist `connection ... closed`. habt ihr unter Security > IP Whitelist einkommende Verbindungen erlaubt?

**Comment by ivenios** [comment]
Noch ne richtig dumme Frage, ist es normal, dass wenn man sich auslogt und wieder neu einlogt das Cluster und die Darin enthaltenen Datenbanken nicht mehr in meinem Mongo Atlas account angezeigt werden? 
Bzw. das einfach alles weg ist und mich atlas begrüßt, als wäre ich ein neuer Account ?

**Comment by Plagiatus** [comment]
nein, eigentlich sollte das natürlich nicht passieren.

**Comment by ivenios** [comment]
mhhhhhhh. 
Naja die verlinkung funktioniert ja noch. Und einen neuen Account habe ich nicht erstenn :/ .

**Comment by JanaKraemer** [comment]
Hallo, ich habe genau das gleiche Problem und leider immernoch keine Lösung gefunden. Ich bekomme "Unable to connect to database, error: MongoError: bad auth Authentication failed." als Fehlermeldung zurückgegeben. 
https://mongodbnetbrowser.herokuapp.com/?u=Jana&p=kraemer99.&a=cluster0-qwseq.mongodb.net&n=sch%C3%BCler&c=students

**Comment by Plagiatus** [comment]
bad authentication heißt, dass das anmelden fehlgeschlagen ist. hast du datenbanknutzer und passwort richtig eingegeben?

**Comment by JanaKraemer** [comment]
Ich habe es nochmal überprüft, das müsste soweit stimmen

**Comment by Plagiatus** [comment]
überprüfe nochmal alle deine Angaben. Hast du den IP Zugriff freigegeben? Die richtigen Werte für Datenbank (nicht cluster) und collection angegeben?
wenn das alles nichts hilft, versuche mal die db nicht "schüler" zu nennen, der umlaut könnte probleme verursachen.

**Comment by JanaKraemer** [comment]
Ich habe mich jetzt nochmal komplett neu angemeldet und jetzt funktioniert es :)
