### ISSUE TITLE
Blumen sind zwar da, aber nicht sichtbar

### ISSUE THREAD

**Issue by SelinaMaz** [JirkaDellOro/EIA2#34]
Hallo :),

in der Entwicklungszeit werden keine Fehler angezeigt, allerdings sind die Blumen die eigentlich da sein sollten nicht sichtbar. Und den Felher in der Konsole zu der Tulpe verstehe ich auch nicht.

Ich stehe gerade auf dem Schlauch. 🙈 Hier ist der Link zu meinem Ordner Aufgabe 8:

(https://github.com/SelinaMaz/EIA2/tree/master/aufgabe_08)

Vielen Dank schonmal

Viele Grüße
Selina

**Comment by RedImp1470** [comment]
In deiner HTML-Datei ist die Tulpe nicht verlinkt und kann daher auch nicht gefunden werden das führt zu: TypeError: a08_Canvas.Tulpe is not a constructor

**Comment by SelinaMaz** [comment]
ok danke :) 
aber warum werden die Blumen nicht sichtbar?

**Comment by RedImp1470** [comment]
Prüfe bitte mal, ob deine ImageData für den Hintergrund gespeichert wird bevor du die Blumen zeichnen lässt.

**Comment by SelinaMaz** [comment]
ok... hmm der Fehler mit der Tuple wird in der Konsole immer noch angezeigt obwohl ich jetzt die Datei im HTML verlinkt habe.

mach ich.

**Comment by SelinaMaz** [comment]
ok also wenn ich mir das jetzt richtig ausgegeben lassen habe dass wird das ImageData für den Hintergrund gespeichert.

**Comment by SelinaMaz** [comment]
ok hab den Tulpen Fehler 🙈

**Comment by RedImp1470** [comment]
Anmerkung zum Hintergrund: die Frage ist hier _wo_ in deiner Init-Funktion der Hintergrund gespeichert wird. Wird er gespeichert _bevor_ du die Blumen malst werden diese später vom gespeicherten Hintergrund (ohne Blumen) übermalt. D. h. erst alles malen, dass im Hintergrund zu sehen sein soll, dann abspeichern.

**Comment by SelinaMaz** [comment]
so hab ich es gemacht ...also erst malen und dann die Blumen 
ich hab sogar die Blumen ganz zum Schluss.

**Comment by SelinaMaz** [comment]
Ich hab jetzt die Fehler beheben können :)

**Comment by JirkaDellOro** [comment]
Klasse!
