### ISSUE TITLE
Kurze Frage

### ISSUE THREAD

**Issue by julianSchubert** [JirkaDellOro/EIA2#340]
Habe eine Frage zu der Aufgabenstellung.

Muss, wenn ich auf Click here drücke meine collection angezeigt werden oder weiterhin deine Beispielcollection.

Aktueller Stand :https://mongodbnetbrowser.herokuapp.com/?u=julian&p=passwort&a=eia2-6f4gn.mongodb.net/test?retryWrites=true&n=EIA2&c=Sammlunng

Und nach meiner Auffassung der Aufgabe bin ich jetzt fertig.

**Comment by Plagiatus** [comment]
nein. vor dem "click here" steht ganz eindeutig "Example". Dies ist und bleibt ein Beispiel damit man weiß was man wo eintragen muss.
Der Link den du hier gepostet hast sollst du so in deinem Steckbrief verlinken, das wars.

**Comment by julianSchubert** [comment]
Vielen Dank.
