### ISSUE TITLE
Mongod.exe will nicht starten

### ISSUE THREAD

**Issue by LucasRohrberg** [JirkaDellOro/EIA2#341]
Heyo,

ich kriege leider mongodb nicht zum laufen :)

Hab die Hinweise in der Aufgabe ausprobiert (https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#run-mdb-edition-from-the-command-interpreter) sowie Kommilitonen gefragt und die Mindmap angeschaut, aber komme nicht voran. 

Erst in VS Code ![2](https://user-images.githubusercontent.com/44026433/57981342-643c3200-7a36-11e9-9284-f85f31ad579d.PNG)

Dann direkt in der CMD 
![3](https://user-images.githubusercontent.com/44026433/57981348-833ac400-7a36-11e9-8332-af49ddf69ae8.PNG)

Danke für Hilfe.

**Comment by LucasRohrberg** [comment]
Habs iwie hinbekommen.

Closed.

**Comment by JirkaDellOro** [comment]
Das waren wohl oben die Anführungszeichen und unten der falsche Pfad
