### ISSUE TITLE
Search Funktion gibt nur eckige Klammern aus

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#342]
Mein Code ist soweit fertig und meiner Meinung nach sollte alles funktionieren. Ich kann auch neue "students" hinzufügen und sie werden dann auf der mongodb Seite und auch wenn ich refresh Drücke im Textfeld angezeigt. Wenn ich aber die eingegebene Matrikel Nummer suche, gibt er mir nur "[]" aus. 
Ich finde leider den Fehler nicht...
https://mtmatern.github.io/EIA2/Aufgabe9/Client/index.html

**Comment by Plagiatus** [comment]
https://github.com/mtmatern/EIA2/blob/master/Aufgabe9/Server/Database.ts#L63

`{matirkel: _input}` sollte matrikel sein vermute ich?

**Comment by mtmatern** [comment]
Oh man 😅Danke, jetzt klappt's. 👍
