### ISSUE TITLE
Aufgabe 9 funktioniert über den Link im Steckbrief nicht mehr

### ISSUE THREAD

**Issue by ghost** [JirkaDellOro/EIA2#343]
Wenn ich Aufgabe 9 über den Link im Steckbrief öffne, funktioniert nichts mehr. Wenn ich aber einfach normal die index Datei in meinem Ordner öffne, funktioniert alles einwandfrei. Irgendwelche Ideen woran es liegen könnte?

**Comment by Plagiatus** [comment]
Nachdem du ja vorbeigekommen bist, bitte das Problem und die Lösung kurz hier posten und dann das Issue schließen. :)
