### ISSUE TITLE
Link zum Konzept geht nicht.

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#347]
Ich hab mich schon dumm und dämlich gesucht nach einem Schreibfehler. Ich finde den Fehler aber leider nicht. Der Index Link müsste aber einwandfrei funktionieren.

**Comment by mtmatern** [comment]
https://github.com/mtmatern/EIA2

**Comment by JirkaDellOro** [comment]
Funktioniert bei mir...
https://mtmatern.github.io/EIA2/Aufgabe10/Aufgabe10_konzept.pdf

**Comment by mtmatern** [comment]
Das wollte ich hören haha. Danke! Bei mir gehts jetzt auch, hat wohl etwas Zeit gebraucht. 👍
