### ISSUE TITLE
404 Page not found problem

### ISSUE THREAD

**Issue by ZenusDesigns** [JirkaDellOro/EIA2#348]
Index wird von GitHub nicht angezeigt/gefunden obwohl link stimmen müsste 

https://zenusdesigns.github.io/EIA2/Aufgabe_10/index.html

Referenz-Link
https://zenusdesigns.github.io/EIA2/Aufgabe_7/index.html

**Comment by Plagiatus** [comment]
geht bei mir.

**Comment by JirkaDellOro** [comment]
Bei mir auch, allerdings wird ein Stylesheet wohl nicht gefunden.
