### ISSUE TITLE
ts lint will immer Whitespace haben

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#349]
Mein Code funktioniert, aber der ts-lint will immer bei this.x oder ähnlichem einen whitespace haben. Ist das normal? Scheint ja aber nichts mit der Funktionalität zu tun zu haben.

https://mtmatern.github.io/EIA2/Aufgabe11/index.html

**Comment by JirkaDellOro** [comment]
Besser einen Screenshot vom Code mit der tslint-Ausgabe posten

**Comment by mtmatern** [comment]
<img width="1280" alt="Bildschirmfoto 2019-06-14 um 16 29 55" src="https://user-images.githubusercontent.com/44026438/59516522-d4b56200-8ec1-11e9-91f8-42b38f95fde3.png">

Bei jeder .ts file ist das so. Sind ja aber nur "Problems" und es funktioniert trotzdem.

**Comment by JirkaDellOro** [comment]
Das ist ungewöhnlich. Auch wenn das Programm funktioniert muss das behandelt werden, sonst gewöhnt man sich daran "Problems" zu ignorieren, das ist ganz schlecht.

Was macht denn der Autoformatter damit? Was bietet QuickFix an?

Bitte mal tslint.json posten.

**Comment by mtmatern** [comment]
Ja, verstehe ich. Der Autoformatter macht garnichts. Quick Fix ist das mit der Glühbirne? Die sagt das, was im screenshot zu sehen ist. Bei Fix all whitespace wird zwischen jedem "Punkt" und "this" ein Leerzeichen eingefügt.

Wie soll ich die tslint.json posten?

<img width="274" alt="Bildschirmfoto 2019-06-14 um 18 46 31" src="https://user-images.githubusercontent.com/44026438/59524792-0b48a800-8ed5-11e9-8d42-92a99070f292.png">

**Comment by JirkaDellOro** [comment]
Siehe unten: "Attach files by...."

**Comment by JirkaDellOro** [comment]
Oder als Text hier rein posten

**Comment by mtmatern** [comment]
.json wird nicht unterstützt. Deshalb hier der kopierte Inhalt der Datei.

{
	"rules": {
		"align": [true, "parameters", "arguments", "statements"],
		"ban": false,
		"class-name": true,
		"comment-format": [false, "check-space", "check-lowercase"],
		"curly": false,
		"eofline": false,
		"forin": false,
		"indent": [true, 4],
		"interface-name": false,
		"jsdoc-format": false,
		"label-position": true,
		"label-undefined": true,
		"max-line-length": [false, 140],
		"member-ordering": [true, "static-before-instance", "variables-before-functions"],
		"no-any": true,
		"no-arg": true,
		"no-bitwise": true,
		"no-console": [false, "debug", "info", "time", "timeEnd", "trace"],
		"no-construct": true,
		"no-constructor-vars": true,
		"no-debugger": true,
		"no-duplicate-key": true,
		"no-duplicate-variable": true,
		"no-empty": true,
		"no-eval": true,
		"no-string-literal": false,
		"no-switch-case-fall-through": false,
		"trailing-comma": [true, {
				"singleline": "never",
				"multiline": "never"
			}
		],
		"no-trailing-whitespace": false,
		"no-unreachable": true,
		"no-unused-expression": true,
		"no-unused-variable": true,
		"no-use-before-declare": true,
		"no-var-requires": false,
		"no-conditional-assignment": true,
		"no-shadowed-variable": false,
		"one-line": [true, "check-open-brace", "check-catch", "check-whitespace"],
		"quotemark": [true, "double"],
		"radix": false,
		"semicolon": true,
		"switch-default": false,
		"triple-equals": [false, "allow-null-check"],
		"typedef": [true, "call-signature", "parameter", "property-declaration", "variable-declaration", "member-variable-declaration"],
		"typedef-whitespace": [true, {
				"call-signature": "nospace",
				"index-signature": "nospace",
				"parameter": "nospace",
				"property-declaration": "nospace",
				"variable-declaration": "nospace"
			}
		],
		"use-strict": [false, "check-module", "check-function"],
		"variable-name": [true, "check-format", "allow-leading-underscore"],
		"whitespace": [true, "check-branch", "check-decl", "check-operator", "check-separator", "check-type"]
	}
}

**Comment by JirkaDellOro** [comment]
Oder einen Link ins Repository...

**Comment by mtmatern** [comment]
https://github.com/mtmatern/EIA2

**Comment by mtmatern** [comment]
https://github.com/mtmatern/EIA2/blob/master/tslint.json

**Comment by JirkaDellOro** [comment]
Ich kann da leider nichts auffälliges erkennen. Welcher Linter ist denn installiert? (Ctrl+Shift+X)

**Comment by mtmatern** [comment]
> Welcher Linter ist denn installiert? (Ctrl+Shift+X)
<img width="1280" alt="Bildschirmfoto 2019-06-15 um 12 28 02" src="https://user-images.githubusercontent.com/44026438/59550284-09c8bf80-8f69-11e9-97c3-2c0323f5cd18.png">

**Comment by JirkaDellOro** [comment]
Den bitte aktualisieren, ich habe Version 1.1.0

**Comment by mtmatern** [comment]
Wo steht das 1.1.0 bei Ihnen? Ich habe ts lint deinstalliert, vs code neu geladen, ts lint neu installiert, vs code neu geladen und es hat sich nichts geändert. Bin auf MacOS, falls das noch was ändert.

**Comment by Plagiatus** [comment]
in der "enabled" liste sollte statt 0.6.0 nach der aktualisierung 1.1.0 stehen

**Comment by JirkaDellOro** [comment]
Hmpf... könnte natürlich sein, dass bei Mac wieder manches anders ist. Man sollte mit anderen Mac-Installationen vergleichen

**Comment by JirkaDellOro** [comment]
Das wäre ein Job für Andre, dann haben wir ein Vergleichsmuster auf dem Spiellabor-Mac

**Comment by Plagiatus** [comment]
@obiwan1337

**Comment by obiwan1337** [comment]
Guten Mittag. 
Die Version von TSLint ist auf dem Apfel hier schon bei 1.2.0

**Comment by obiwan1337** [comment]
Klick doch mal das kleine Zahnrad an das am TSlint angezeigt wird. Da gibts die Option "Install anonther Version" scheinbar kann dort jeder belibige Version installiert werden egal wie alt.

**Comment by mtmatern** [comment]
<img width="1280" alt="Bildschirmfoto 2019-06-19 um 09 51 28" src="https://user-images.githubusercontent.com/44026438/59746761-d5f6de00-9277-11e9-9b0b-2d1b1f9eb95c.png">

Das Zahnrad?

**Comment by obiwan1337** [comment]
Genau das Zahnrad. Komischerweise fehlen Dir Optionen die bei unserem Mac da sind.
<img width="1206" alt="Screen Shot 2019-06-19 at 10 05 32" src="https://user-images.githubusercontent.com/43846856/59747930-8b6e6500-9269-11e9-9ac0-7381b5f10d95.png">


> <img alt="Bildschirmfoto 2019-06-19 um 09 51 28" width="1280" src="https://user-images.githubusercontent.com/44026438/59746761-d5f6de00-9277-11e9-9b0b-2d1b1f9eb95c.png">
> 
> Das Zahnrad?

**Comment by JirkaDellOro** [comment]
Ich denke, ihr solltet euch im Spiellabor treffen und das weiter untersuchen

**Comment by JirkaDellOro** [comment]
Ist das geklärt/behoben?

**Comment by mtmatern** [comment]
Gab keine Probleme mehr
