### ISSUE TITLE
"super(_x,_y)" funktioniert nicht.

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#35]
Für meine Honigbienen möchte ich die x und y der normalen Bienen übernehmen für die Subklasse, allerdings gibt mir das "super(_x, _y) immer den Fehler "Supplied parameters do not match any signature of call target"

https://github.com/MrMarans/EIA2/tree/master/Aufg8

Bereits vielen Dank

MFG

**Comment by MrMarans** [comment]
Okay, gelöst. Dachte, ich muss nicht alle Informationen der Überklasse mitgeben.

**Comment by JirkaDellOro** [comment]
Superklasse, nicht Überklasse
