### ISSUE TITLE
Datenbankinhalt wird nicht angezeigt :(

### ISSUE THREAD

**Issue by Jonas915** [JirkaDellOro/EIA2#350]
Nabend,
ich bin gerade dabei, die Abschlussaufgabe mit einer Datenbank zu verbinden, nur klappt das nicht.
Habe schon zusammen mit Markus Damm und Lukas Rohrberg viele Dinge ausprobiert, aber nichts hat geholfen.
Jetzt dürft ihr.

https://github.com/Jonas915/EIA2/tree/master/Abschlussaufgabe/server

Dankeschön :)

**Comment by Plagiatus** [comment]
a welcher Stelle klemmts denn? Server? Client? Datenbank? Gibt es irgendwelche Fehlermeldungen?

**Comment by Jonas915** [comment]
Das kann ich natürlich nicht 100% genau sagen. Den Error gab es schon bei Aufgabe 9, nur weiß irgendwie niemand mehr, wie der zu fixen war. In der Datenbank wird beim aktualisieren nur /command.br angezeigt und nicht die Dinge, die man in die Highscore Liste eingetragen hat. Fehlermeldungen gibt es jetzt keine mehr, weder im Browser noch vom ts.lint

**Comment by Plagiatus** [comment]
sieht mir sehr danach aus als würde der Server von A7 auf heroku laufen und nicht der von deiner Abschlussaufgabe.

**Comment by Jonas915** [comment]
Achso, muss ein neuer Server dafür angelegt werden, wusste ich nicht. Dann muss ich im Anschluss auch die package json anpassen nehme ich an, oder?

**Comment by Plagiatus** [comment]
nein, es muss kein neuer Server angelegt werden. Du musst einfach nur deinem existierenden Server beibringen, die richtige .js Datei zu laden!

**Comment by Jonas915** [comment]
..oder so. Danke!
