### ISSUE TITLE
Game over trifft ein, obwohl Fisch nicht größer ist

### ISSUE THREAD

**Issue by reginafaller** [JirkaDellOro/EIA2#351]
Mein Fisch sollte eigentlich die Fische essen, welche einen kleineren Skalierungsfaktor a haben, und nur game over gehen, wenn er auf größere trifft. Aber er geht andauernd game over wenn er auf kleinere Fische trifft. Ich lasse mir den Fisch auf den er trifft auf der Console ausgeben und es zeigt an er hätte ein Größeren a wert, aber das muss ein anderer Fisch sein, da der Fisch auf den er wirklich trifft nicht größer als er ist. Ich habe schon im Tutorium nachgefragt, aber mir konnte leider auch nicht geholfen werden.

**Comment by JirkaDellOro** [comment]
Bitte mit dem Issue entsprechende Links zum Quellcode und zur lauffähigen App posten, dann können wir das sicher schnell lösen.

**Comment by reginafaller** [comment]
https://reginafaller.github.io/EIA2/Endabgabe/index.html

**Comment by JirkaDellOro** [comment]
und zum Quellcode im Repository, bitte

**Comment by reginafaller** [comment]
https://github.com/reginafaller/EIA2/tree/master/Endabgabe      tut mir leid, jetzt hab ich es.

**Comment by JirkaDellOro** [comment]
Ich habe kurz reingeschaut, der Code ist leider etwas ungünstig strukturiert und daher nicht sehr intuitiv. Da sollte zunächst ein wenig aufgeräumt werden:
- Wie viele Nemos soll es geben? Falls nur einer existiert, sollte es kein nemoArray geben, in dem nur ein Element drinsteckt und keine Schleifen, nur um dieses eine Element zu bearbeiten. Bitte in diesem Fall nur eine Variable nemo erzeugen, die den einen Nemo referenziert.
- die draw()-Methode der Fische macht nun viel mehr als sie sollte, das ist sehr unintuitiv. Sie nimmt auch die Nemo-Position entgegen und ruft die eat()-Funktion im Hauptprogramm auf, die wieder ganz viel anderes macht. draw() sollte aber nur den Fisch zeichnen. Daher im Hauptprogramm eine Schleife anlegen, die einfach alle Fische auf Kollision mit Nemo prüft und entsprechend agiert. Hierzu sollten die Fische eine Methode zur reinen Kollisionsprüfung besitzen, z.B. mit Hilfe eines einfache rechteckigen Pfades oder durch simple Distanzberechnung.

Zum Fehler: es scheint, dass isPointInPath mit den derzeitigen Zeichenpfaden, die zur Prüfung heran gezogen werden, nicht das gewünschte Ergebnis liefert. Dass sollten wir nach Durchführung der oben genannte Korrekturen prüfen.

**Comment by reginafaller** [comment]
ich habe jetzt die Methode geändert, und prüfe nichtmehr über ispointin path ob zwei fische sich berühren, aber der Gameover trifft trotzdem ein, obwohl er nicht sollte und ich habe keine Ahnung warum. link zum Spiel:  https://reginafaller.github.io/EIA2/Endabgabe_copy/index.html.      link zum repository: https://github.com/reginafaller/EIA2/tree/master/Endabgabe_copy

**Comment by obiwan1337** [comment]
Da schmeißt Dir Deine Konsole einen netten Error. Das kann Auslöser vom Problem sein...

**Comment by reginafaller** [comment]
daran lag es wirklich.. danke! :)
