### ISSUE TITLE
Heroku und Steuerung

### ISSUE THREAD

**Issue by JanaKraemer** [JirkaDellOro/EIA2#352]
Hallo,
ich habe 2 Punkte, an denen ich nicht weiter komme. Zum einen habe ich Probleme mein Spiel mit Heroku zu verknüpfen. Nach dem ich deployed habe, bekomme ich immer die Meldung: application error, obwohl ich die Links mehrmals überprüft habe.
Zum anderen reagieren meine Fische nicht, wenn sie aufeinander treffen. Ich habe versucht ihnen einen Radius mitzugeben und weiß gerade nicht wo der Fehler liegt.
Gerade habe ich versucht an den Fehlern zu arbeiten, aber seitdem lässt sich auch mein Fisch nicht mehr steuern.
Hier die Links zu meinem Spiel und dem Repository.
Ich hoffe mir kann jemand helfen.
LG
https://github.com/JanaKraemer/EIA2-Aufgabe

https://janakraemer.github.io/EIA2-Aufgabe/Abschlussaufgabe/

**Comment by JirkaDellOro** [comment]
Ein Schnellschuss, der vielleicht schon einige Verbesserung bringen kann:

- beim Blick in die Konsole fällt mir auf, dass der Client versucht einige Skripte einzubinden, deren Namen suggerieren, dass sie eher auf die Serverseite gehören. Sie werden auch nicht gefunden. Ich empfehlen zwei Unterordner "Server" und "Client" anzulegen und die Dateien darin sinnvoll zu trennen.
- es ist auch sehr verwirrend, dass es eine Dateigruppe mit dem Namen "Datenbank" und eine mit Namen "datenbank" gibt.
- grundsätzlich empfehle ich beim Coden konsequent die englische Sprache zu nutzen, auch für Dateinamen

Diese Verbesserungen werden möglicherweise nicht gleich die Lösung des Problem bringen, aber sicher eine der Ursachen beseitigen. Und in der Folge ist es sehr viel leichter Fehler zu finden, denn in der Ordnung fallen sie besser auf als im Chaos.

**Comment by JanaKraemer** [comment]
Das Problem mit den fehlenden Skripten habe ich behoben (Diese existieren jetzt nicht mehr, auch nicht die doppelte Datenbank). Leider hat das auch nicht geholfen, was das Zusammentreffen der Fische angeht.
Die Fische bekommen einen Radius und wenn dieser mit einem Radius eines anderen Fisches übereinstimmt, dann soll er wachsen und der kleine Fisch verschwinden, oder er soll selbst gefressen werden und das Spiel endet mit dem Alert: Game over. Aber diese If-Abfrage funktioniert nicht wie gewollt.

**Comment by JirkaDellOro** [comment]
Du bist wahrscheinlich gerade am Code dran, derzeit läuft er nicht. Ich habe ein wenig mehr reingeschaut und es gibt auch im Inneren, z.B. in canvas.ts, rein formal einiges Verbesserungspotential, dass Du zunächst ausschöpfen solltest:
1. schreibe konsequent englisch
2. der kleine Fisch ist der, der vom Spieler kontrolliert wird, korrekt? Da er nur einmal existiert, ist es unsinnig, ihn in einem Array zu verwalten. Das macht alles völlig unnötig kompliziert. Bitte auflösen.
3. Mittelfristig solltest Du dir Gedanken machen, wie Du sinnvoll Polymorphie nutzen kannst. Drei oder vier Arrays für deine Objekte zu verwalten ist unnötig
