### ISSUE TITLE
HFUChat: Seite lädt neu anstelle erstellen von query string

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2#353]
Hallo Zusammen, kleine Verzweiflung hier: 
Ich habe mich an den HFU Chat heran gewagt. Wie schon bei der Matrikelnummer Datenbank, wollte ich auch so den Versand der Login Daten und neuen Registrierungen auch machen. Doch hier das Problem: 

Wenn das form ausgefüllt ist und ich den Button mit dem Versenden (über id und EventListener, nicht type=submit) drücke, wird die Seite neu geladen. Sind die Felder nicht ausgefüllt und ich versende die Daten wird die im EventListener angegebene Funktion ausgeführt. 

Ich habe alles auch mal Rückwärts durch gegangen, aber sobald ein Zeichen in den inputs drin steht, oder ein Radiobutton geklickt ist, geht der Debugger nicht mal mehr in die beim EventListener angegebene Funktion rein. 

Lieben Dank für eure Untertützung. 

Hier sind die Links. 

Repo: [https://github.com/ivenios/EIA2/tree/master/00_Endabgabe](https://github.com/ivenios/EIA2/tree/master/00_Endabgabe)

HFU Chat ( CSS deaktiviert ): [https://ivenios.github.io/EIA2/00_Endabgabe/Programm/index.html](https://ivenios.github.io/EIA2/00_Endabgabe/Programm/index.html)

**Comment by obiwan1337** [comment]
Guten Mittag, bei mir geht der Debugger einmal durch die Funktion, die der jeweilige Knopf aufruft, egal was in den Feldern drinsteht. Und direkt danach lädt die Seite neu. Als Idee eines Versuchs: Schmeiß mal das form  um deine Fieldsets raus. Soweit meine Recherche ergeben hat, wird das Action Attribute des FormElements, wenn nichts zugewiesen wird auf die jetzige Seite gesetzt. Das könnte den "Refresh" verursachen. 
Da du keinen Submitbutton benutzt, brauchst du auch kein FormElement, um die Sachen abzugreifen.

**Comment by ivenios** [comment]
Ah, Wunderbar das war es. Danke.
