### ISSUE TITLE
Schüsse und Treffer

### ISSUE THREAD

**Issue by felixChB** [JirkaDellOro/EIA2#354]
Wie kann man feststellen, ob ein Schuss von meinem Raumschiff einen gegner trifft ohne das über die Distanz zu machen? Ich hatte eine for-Schleife, die mein Array 2mal durchlaufen ist, um immer die Distanz zwischen jedem Schuss und jedem Gegner zu bestimmen aber dadurch ist mein spiel eingefroren weil es zuviel rechnen musste. Gibt es eine einfachere methode?

**Comment by obiwan1337** [comment]
frag doch ab ob dein Geschoss im Pfad eines Raumschiffs ist ?
Also im Raumschiff selber. Canvas gibt dazu die Methode schon mit.

**Comment by felixChB** [comment]
Hab ich versucht aber der Browser laggt einfach schon bevor ich die Seite öffne.

**Comment by obiwan1337** [comment]
Schick mal den Link zu deinem Ordner der Endabgabe? Dann kann auch reingeschaut werden und evtl. findet sich ein Problem?

**Comment by felixChB** [comment]
habs gelöst aber danke
