### ISSUE TITLE
Aktivitätsdiagramme zu jeder einzelnen Funktion?

### ISSUE THREAD

**Issue by felixChB** [JirkaDellOro/EIA2#356]
Müssen wir zu wirklich jedem Teil im Code ein Aktivitätsdiagramm erstellen, also auch zur Server und Datenbank Anbindung und zu jeder einzelnen Abfrage zum Beispiel in den verschiedenen Klassen. Oder reicht es die Hauptaktivitäten abzudecken, gerade weil sich viele kleine Abfragen und Funktionen bis auf kleine Änderungen nicht sehr voneinander unterscheiden.

**Comment by Plagiatus** [comment]
_(wenn du jetzt erst mit den ADs anfängst, muss ich leider davon ausgehen, dass du die vorgeschriebene Reihenfolge nicht eingehalten hast)_

Nein, musst du nicht. Es geht darum, dass ihr euch im Voraus Gedanken macht und plant was ihr tun wollt und welche Probleme dabei auftauchen können. Zitat aus den [Hinweisen zur Abschlussarbeit](https://github.com/JirkaDellOro/EIA2/wiki/Hinweise%3A-Abschlussarbeit): 
>Erstellen Sie daher Aktivitätsdiagramme auf verschiedenen Detailebenen.  

Es macht wenig Sinn zu diesem Zeitpunkt auf die kleinste Detaileben runter zu gehen, also ein "so wie da bloß anders in folgenden Punkten" funktioniert auch. 

_PS: Wenn du ganz oft das gleiche machst mit nur kleinen Änderungen und dafür Code kopierst statt ihn in eine Funktion auszulagern bzw in eine Methode der Superklasse zu verschieben, dann machst du sowieso irgendwas sehr falsch und dann kannst du zur Strafe auch alles einzeln aufmalen! 😜_

**Comment by felixChB** [comment]
Ok danke, aber "(wenn du jetzt erst mit den ADs anfängst, muss ich leider davon ausgehen, dass du die vorgeschriebene Reihenfolge nicht eingehalten hast)" stimmt nicht ganz, weil im lauf der Zeit immer neue Funktionen dazukommen und ich, wenn ich grade mitten im programmieren bin nicht aufhör, ein aktivitätsdiagramm zeichne, obwohl ich schon genau weiß was ich machen muss und dann erst weiterprogrammiere...
