### ISSUE TITLE
Problem mit Einbindung

### ISSUE THREAD

**Issue by RittEvA** [JirkaDellOro/EIA2#357]
Hallo zusammen,
hat jemand vielleicht eine Idee warum mir folgendes die Konsole ausgibt?
wenn ich den BlubStrom komplett aus meinem Code auskommentiere funktioniert alles.
Sobald aber der wieder eingebunden ist treten diese Fehler auf.
Vielen Dank schon mal

die Konsolenausgabe:
[Error] TypeError: undefined is not a constructor (evaluating 'new Endabgabe.BlubStrom()')
	spielStart (canvas.js:46)
[Error] TypeError: undefined is not an object (evaluating 'Endabgabe.meiner.y')
	bewegMeiner (canvas.js:176)
[Error] TypeError: undefined is not an object (evaluating 'Endabgabe.meiner.y')
	bewegMeiner (canvas.js:188)

Seite direkt: https://ritteva.github.io/EIA2-Aufgaben/Endabgabe/index.html

im Repro: https://github.com/RittEvA/EIA2-Aufgaben/tree/master/Endabgabe

**Comment by obiwan1337** [comment]
versuch mal das canvas script im html als letztes einzubinden, damit es auch alle anderen scripte mit den Klassen laedt. 
Mal sehen ob das was bringt

**Comment by R4Pi3R** [comment]
BlubStrom.js existiert nicht im Repository.
Es gibt eine BlubStrom.ts als auch eine Blubstrom.ts, aber nur von zweiterer gibt es auch eine entsprechende .js-Datei

Korrigiere:
es gibt nicht mal eine Blubstrom.ts... hast du die Datei evtl umbenannt und danach nicht nochmal kompiliert?

**Comment by RittEvA** [comment]
Super vielen Dank. 
Es funktioniert jetzt alles und gibt keine Fehlermeldungen mehr.
Ich dachte mir schon das es irgend so ein Fehler ist den ich aus Betriebsblindheit immer übergehe.
