### ISSUE TITLE
Das Spiel läuft nicht wenn es über den Link geklickt wird

### ISSUE THREAD

**Issue by julianSchubert** [JirkaDellOro/EIA2#358]
Hallo,
habe folgendes Problem, öfffne ich meine index über die Dokumente meines Computers läuft mein Spiel problemlos, sobald ich es über den eingebundenen Link in meinem Steckbrief öffne funktioniert es nicht mehr und die Konsole findet viele Fehler, die mir allerdings leider nicht helfen.

Link zur Seite mit den Problemen in der Konsole:

https://julianschubert.github.io/EIA2/Abschlussaufgabe/index.html

Link zum Repository:

https://github.com/julianSchubert/EIA2/tree/master/Abschlussaufgabe

Link zu meiner package.json:

https://github.com/julianSchubert/EIA2/blob/master/package.json

Danke schonmal

**Comment by R4Pi3R** [comment]
Deine im HTML eingebundenen Dateien sind alle klein geschrieben, im Repository beginnen aber die meisten groß.
Kann sein, dass dein Betriebssystem nicht casesensitive sucht, der Browser mach das allerdings schon.

**Comment by julianSchubert** [comment]
So habe die Namen geändert allerdings funktioniert es immer noch nicht.

**Comment by obiwan1337** [comment]
Versuch die doch mal im head einzubinden? Am Ende des bodys gehts zwar auch aber das lädt die halt als letztes...

**Comment by julianSchubert** [comment]
Im head hatte bei mir noch nie irgendeine Einbindung in keiner Aufgabe funktioniert aber mal sehen was ich tun kann.
Hab es im head eingebunden, Problem bleibt bestehen.

**Comment by obiwan1337** [comment]
bei mir sind die scriptabfragen immernoch an großgeschriebene JS Dateien gerichtet.

**Comment by julianSchubert** [comment]
Aber im Repository sind doch fast alle großgeschrieben?! Und ich habe in der Index alle von der  Schreibung angepasst

**Comment by obiwan1337** [comment]
Ohne JS von den TS Dateien wird es wohl trotzdem nicht funktionieren.

**Comment by julianSchubert** [comment]
Danke werde versuchen die irgendwie hochgepushtzubekommen.

Wie bekomme ich die. Im Ordner sind sie drin, aber nicht im repo

Ich habe jetzt im Repo die ekleingeschriebenen js gelöscht und im Ordner sind jetzt die großgeschriebenen drin aber ggithub desktop pusht sie noch obwohl ich die zugehörigen ts geändert habe, und ich habe watch an

**Comment by julianSchubert** [comment]
Issue ist geschlossen Vielen Dank für die Hilfe
