### ISSUE TITLE
Problem mit dem Futter

### ISSUE THREAD

**Issue by mtmatern** [JirkaDellOro/EIA2#359]
Hallo, ich wollte gerade noch eine kleine Sache einbauen, und zwar, dass man über das Essen von Futter, welches man per klick spawnen lassen kann, auch Punkte sammeln kann. Eigentlich sollte pro Snack ein Punkt zum score hinzugefügt werden, irgendwie macht es aber immer mehrere Punkte. Vorallem auch immer unterschiedlich viele. Was ist das Problem?

Gesteuert wird mit WASD.

Link zur HTML:
https://mtmatern.github.io/EIA2/Endabgabe/client/index.html

Mein Repo:
https://github.com/mtmatern/EIA2/tree/master/Endabgabe

**Comment by R4Pi3R** [comment]
```
function spawnSnacks(_event: MouseEvent): void {
        let xMousePos: number = _event.clientX;
        let yMousePos: number = _event.clientY;
        let snackNumber: number = Math.floor(Math.random() * (10 - 1 + 1)) + 1;
        for(let i: number = 0; i < snackNumber; i++){
            let snacks: Snack = new Snack(xMousePos, yMousePos);
            seaworldFoodArray.push(snacks);
            //snacks.draw();
        }
```

Die Schleife erzeugt jedes mal eine zufällige Anzahl von Futterinstanzen mit denselben Koordinaten. Dass du nur eine siehst liegt daran, dass alle gleichzeitig erzeugt werden und sich gegenseitig übermalen.

**Comment by mtmatern** [comment]
Oh man hahaha danke!
