### ISSUE TITLE
Fehlermeldung "HoneyBee is not a constructor"

### ISSUE THREAD

**Issue by MichelleZei** [JirkaDellOro/EIA2#36]
Hallo,

wie auch schon im Praktikum, kommt bei mir die Fehlermeldung "TypeError: L8_Inheritance.HoneyBees is not a constructor". Er hängt in Zeile 75 in der main.ts, obwohl ich es genauso gemacht habe, wie bei der Klasse "NormalBees".
Kann mir da jemdand weiterhelfen?

https://michellezei.github.io/EIA2/aufgabe8/aufgabe8.html

Vielen Dank im Voraus!

**Comment by moritzhfu** [comment]
Siehe Konsole: Unter https://michellezei.github.io/EIA2/aufgabe8/honeybee.js wird nichts gefunden. Ergo: Fehlermeldung. Bitte sicherstellen, dass diese Datei hochgeladen und richtig verlinkt ist.

**Comment by MichelleZei** [comment]
Okay, jetzt funktioniert es
