### ISSUE TITLE
%%20, anstelle sonder Zeichen. Im HFU Chat

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2#360]
Hi, ist zwar voll kosmetisch, aber als ich meinen HFU Chat durchgehend gerade getestet hatte, ist mir aufgefallen, dass bei Sonderzeichen immer ein %%20 geschrieben wird. Kann man das umgehen? Hier ein Screenshot: 
![Screenshot_2019-07-27 Der HFUChat](https://user-images.githubusercontent.com/44029046/61994578-7bbe1980-b07c-11e9-908b-93e0523f8e43.png)

Repo: [Hier](https://github.com/ivenios/EIA2/tree/master/00_Endabgabe)

HFU Chat: [Hier](https://ivenios.github.io/EIA2/00_Endabgabe/Programm/index.html)

Vielen Dank schon einmal im Voraus.

**Comment by ivenios** [comment]
Ähm, was mir gerade auch aufgefallen ist, da gerade magischerweise sich 15 Leute auf einmal eingeloggt hatten, schmiert Heroku ab. 😬 .

**Comment by Plagiatus** [comment]
Kann ich nicht reproduzieren, sorry. Das Einzige Problem das ich habe ist dass mir beim `&` die Nachricht abgeschnitten wird, was bei einer GET Anfrage ja Sinn macht.

mit welchen Sonderzeichen passiert das denn?

**Comment by ivenios** [comment]
bei % und eigentlich allem was man mit shift oder alt so produzieren kann. Das mit der Nachricht, schaue ich mir noch an.

**Comment by ivenios** [comment]
Kappt Heroku den Link ab 255 Zeichen oder bei 2083?

**Comment by Plagiatus** [comment]
Das weiß ich leider nicht. Bei mir hat das % ohne Probleme funktioniert.

%20 in einer URL steht normalerweise für ein Leerzeichen. vgl. https://de.m.wikipedia.org/wiki/URL-Encoding

Könnte es damit zusammenhängen?
