### ISSUE TITLE
Zufälliges Dokument aus Collection auslesen

### ISSUE THREAD

**Issue by LucasRohrberg** [JirkaDellOro/EIA2#362]
Servus :)

Ich habe eine Mongo Collection mit Wörtern, von denen ich eines zufällig auslesen möchte.
Mein Ansatz momentan ist wie folgt:
let cursor: Mongo.Cursor = availableWords.find().skip(randomNumber).limit(1);

Ich lass ihn ohne Vorgaben nach allen Dokumenten suchen, sage ihm aber dass er erst bei einer zufällig generierten Position starten soll und die Ausgabe auf 1 limitiert ist. 
Leider wird weiterhin die gesamte Collection ausgegeben. 
Habe ich skip & limit falsch verstanden?

Ausprobieren kann man das ganze hier, indem man unten auf "NEW" klickt:
https://lucasrohrberg.github.io/EIA2/Endabgabe/index.html

Hier noch mein Repo:
https://github.com/LucasRohrberg/EIA2/tree/master/Endabgabe

Danke :D

**Comment by Plagiatus** [comment]
mach es doch anders herum: hole dir die ganze collection, mache ein Array daraus und nehme dir davon ein zufälliges Element.

**Comment by LucasRohrberg** [comment]
Die Idee hatte ich vorher, aber sobald ich den Ansatz nutze, wirft er Fehlermeldungen bzgl der GET Anfrage und bzgl CORS:
![1](https://user-images.githubusercontent.com/44026433/62000441-4a266c00-b0d7-11e9-9ffc-f5ce10b37013.PNG)

Hier der Code, der dazu führt:
![2](https://user-images.githubusercontent.com/44026433/62000446-590d1e80-b0d7-11e9-89f6-10794b90beaa.png)

Greif ich falsch auf die Stelle im Array zu?

**Comment by LucasRohrberg** [comment]
Im anderen Issue hast du geschrieben, dass das CORS Problem vom Serverabsturz aufgrund des anderen Errors entsteht. Also greif ich wohl wirklich falsch auf die x-te Stelle im Array zu... Würde gern das Problem mit console.logs eingrenzen und lösen, nur weiß ich nicht, wo die angezeigt werden, wenn ich sie in der Database.ts äußere. Send help haha

**Comment by Plagiatus** [comment]
Database.ts läuft wie die Server.ts auch auf Heroku. Bzw bei dir lokal auf dem node.js Server. Dort bekommst du auch die Logs wenn was kaputt gehen sollte.

Der Code sieht nicht schlecht aus, Versuche doch Mal die zufällige Zahl im `else` Block zu generieren wenn du tatsächlich ein Array an der Hand hast. Und was du dann haben solltest ist ja eigentlich auch nur ein String, das heißt du musst da nix durch den json.stringify durchjagen.

**Comment by LucasRohrberg** [comment]
Bin von Heroku auf lokal umgestiegen, um Logs einsehen zu können. Dabei konnte ich herausfinden, dass bei mir alle Dokumente im gleichen Array Slot liegen, 0. Deshalb gibt zB wordArray[3] ein undefined zurück, weils keinen 4. slot hat. Liegt das an toArray()? 
![3](https://user-images.githubusercontent.com/44026433/62005124-ca2bf080-b12e-11e9-82c7-2749cceaaec6.PNG)

Jetzt hab ich versucht mit forEach über das Array zu iterieren und jedes Element in ein neues Array zu pushen, damit auf alle Dokumente aus der DB einzeln zugegriffen werden kann. 
Leider sagt er mir, dass er push von undefined nicht lesen kann... Das Array initialisiere ich doch aber vorher schon? Habs auch versucht global zu initialisieren, hat nichts geändert. 
![4](https://user-images.githubusercontent.com/44026433/62005140-05c6ba80-b12f-11e9-9033-89df1a9bf9a6.PNG)

Ich hab auch schon etliche andere Möglichkeiten versucht die Dokumente zu splitten oder den generierten JSON String zu seperieren, aber man kann wohl nicht mit Indexen auf JSON Objekte zugreifen..

Please send help, danke :')

**Comment by Plagiatus** [comment]
das splitArray deklarierst du in Z36, initialisierst es aber nicht. es fehlt ein `= []`.

**Comment by Plagiatus** [comment]
Oder du könntest deine Datenbank fixen. mir scheint dass du die Collection der Wörter bzw die Dokumente in der Collection falsch angelegt hast, und darum das alles in einem Element ist.

**Comment by LucasRohrberg** [comment]
Hab den generierten JSON String mit .split() in ein String Array zerlegt und daraus die Wörter zufällig ausgelesen. Danke für die Hilfe!

closed.
