### ISSUE TITLE
Feedback über NB Status. 

### ISSUE THREAD

**Issue by ivenios** [JirkaDellOro/EIA2#364]
Hallöle. 
Bekommen wir Feedback, bzw. den genauen Grund warum wir nicht bestanden haben? 
War eigentlich voll stolz auf mein Programm, ist schon ein kleiner Schlag in das Gesicht, wenn man nach viel Arbeit ( ich weiß nicht gerade beim Konzept erstelen :/ ) ein NB bekommen. 

Liebe Grüße 
Iven

**Comment by Plagiatus** [comment]
Auf Nachfrage gerne. 
In deinem Fall war das Konzept leider so schlecht, dass es zum NB geführt hat. Das Konzept war der Hauptteil der Abgabe.

Du kannst stolz auf deine funktionale Abgabe sein, der Chat ist dir sehr gut gelungen. Aber leider ohne zugehöriges Konzept.

**Comment by ivenios** [comment]
Okay hatte ich mir schon fast gedacht. Schade. Hatte dennoch spass gemacht. Wie läuft dass denn jetzt? 
Ich mache denn kommenden Semester nur noch die Endabgabe oder? Das veränderte EIA Konzept hat da höchstwahrscheinlich keinen Einfluss drauf. Angemeldet werde ich ja automatisch wieder für kommendes Semester.

**Comment by Plagiatus** [comment]
Ich bin froh dass es dir trotzdem Spaß gemacht hat. :)

Im Intranet im MKB Forum gibt es einen Thread von @JirkaDellOro, in dem erklärt wird, wie das bei Wiederholern im nächsten Semester gehandhabt wird.
Meistens ist er außerdem so kulant, dass man bei "bestandenem Praktikum aber nicht bestanderner Endabgabe" lediglich die Endabgabe wiederholen muss (wobei das nächstes Semester sowieso anders läuft).

Du bist ja jetzt erstmal im Prax nehme ich an, da bist du automatisch von sämtlichen Prüfungen abgemeldet. Du kannst dich aber auch explizit zu einer Prüfung anmelden, wenn du diese im Prax schreiben möchtest.

**Comment by ivenios** [comment]
Okay wunderbar. Ich schaue mir das mal an.
