### ISSUE TITLE
Gestörte Bienen - Was tun?

### ISSUE THREAD

**Issue by ValentineDe** [JirkaDellOro/EIA2#37]
Hallo,
meine Honigbienen machen nicht das was sie sollen. Sie fliegen nicht von zu Hause aus los zur ihrer Zielblume sondern werden anscheinend immer wieder neu konstruiert (siehe Console) . Weiß nicht genau woran das liegt und komme nicht mehr weiter.  Danke schon einmal im Voraus für die Hilfe.

https://github.com/ValentineDe/EIA2/tree/master/aufgabe8

Grüße Valentine

**Comment by saenglert** [comment]
Hey Valentine,
was störst du auch die armen Bienen beim Honigsammeln? Habe gerade mal bei dir ein bisschen im Code rumgespielt. Deine normalen Bienen, die Blumen und alles andere funktionieren ja wunderbar. D.h. wir können also sehr stark darauf schließen, dass das Problem in deiner honeybee.ts sitzt. Das die Bienen neu erstellt werden kann ich nicht bestätigen, in meiner Console wird mir nur der "Animation called" Text wiederholt ausgegebn.

Ich sehe dein Problem eher hier: 
```
 move(): void {
            let xDiff: number = this.xtarget - this.x;
            let yDiff: number = this.ytarget - this.y;
            if (Math.abs(xDiff) < 0.5 && Math.abs(yDiff) < 0.5)
                this.setRandomFlowerTarget();
            else {
                this.x += xDiff;
                this.y += yDiff;
            }
        }
```

Du berechnest den Abstand in X und Y Richtung zum Ziel, überprüfst ob der Abstand kleiner deines Schwellenwerts ist und wenn ja setzt du ein neues Ziel. So weit so gut.

Ist der Abstand allerdings größer addierst du den Abstand in X bzw. Y Richtung einfach auf die Position deiner Biene oben drauf. 

Abstand - Abstand = 0

D.h. innerhalb eines einzelnen Frames/Logikschritts erreicht deine Biene bereits ihr Ziel, bekommt im nächsten ein neues Ziel, welches sie wiederum im nächsten Frame erreicht usw. ...
Deine Bienen sind also nicht gestört. Sie sind nur überbienlich schnell.

**Comment by ValentineDe** [comment]
Klappt jetzt alles und die Bienen sind jetzt wieder "normal" :) Danke für die Heilung!
