### ISSUE TITLE
Fehler in Konsole nicht nachvollziehbar

### ISSUE THREAD

**Issue by JanaBurger** [JirkaDellOro/EIA2#38]
Hallo,
beim Erkennen der Position der ausgewählten Blume erscheint bei mir ein Fehler in der Konsole:
"Classes8.flowers[randomflower] is undefined", obwohl ich eigentlich alles definiert habe und es auch erkannt wird. Jetzt erscheinen gar keine Bienen mehr. 
Über einen Tipp woran das liegt wäre ich sehr dankbar.
Liebe Grüße, Jana

Links:
https://github.com/JanaBurger/EIA2/tree/master/aufgabe8
https://janaburger.github.io/EIA2/aufgabe8/aufgabe8.html

**Comment by saenglert** [comment]
Hallo Jana,
schau dir mal an auf welchen Index du versuchst zuzugreifen, also welchen Wert randomflower hat und welche Indeces in flowers überhaupt belegt sind zu dem Zeitpunkt wenn du die Bienen erstellst.

**Comment by JanaBurger** [comment]
Danke Sascha. Also die Bienen erscheinen jetzt und manche fliegen gezielt einen Punkt an, jedoch nicht wirklich gezielt Blumen. Und mein Programm stoppt nach einiger Zeit und der Fehler (wie oben) erscheint erneut. Am Anfang ist er aber noch nicht da.

**Comment by saenglert** [comment]
Das liegt daran an 2 Punkten:
a) Du beachtest Punkt vor Strich beim rechnen nicht. Honeybee.ts Zeile 55
`let getRandomFlower: number = Math.round(Math.random() * flowers.length - 1);`
Wichtig ist, dass `flowers.length - 1` in Klammer steht, also:
`let getRandomFlower: number = Math.round(Math.random() * (flowers.length - 1));`
Da du sonst wenn `Math.random() `Null ausgibt bei einem Index von -1 landest, der natürlich nicht existiert.

b) Die Bienen fliegen sogar ganz genau zu zufälligen Blumen. Nur sehen wir die nicht, da du die Blumen die du in Zeile 89 bis 94 erstellst nie zeichnest.

Ich habe mich mal noch etwas durch deinen Code gewühlt und ein paar Kommentare geschrieben, was ich noch besser machen würde. Einen Pull Request (mit dem du meine Änderungen/Kommentare übernehmen könntest) habe ich nicht abgesetzt, da soweit bis auf die eine Rechnung und das Zeichnen der Blumen alles funktioniert und ich dir da nicht noch reinpfuschen will. Anschauen kannst du die Änderungen aber hier:
https://github.com/saenglert/EIA2-6/blob/master/aufgabe8/js/aufgabe8.ts

**Comment by JanaBurger** [comment]
Okay, danke für deine Hilfe:)
Ich denke jetzt schaff ichs. :))
