### ISSUE TITLE
Anmelden

### ISSUE THREAD

**Issue by Leah1995** [JirkaDellOro/EIA2#4]
Wenn ich beim Anmeldeformular meinen Link eingebe, meldet die Seite immer, dass der Link falsch ist.
Ich habe jetzt schon einiges ausprobiert (username.github.io/EIA2, https://github.com/username/EIA2 etc) aber es kommt immer die gleiche Meldung.
Wenn mir das jemand helfen könnte, wäre ich wirklich dankbar.

**Comment by JirkaDellOro** [comment]
Hallo Leah,

es hat für mich den Anschein, dass Sie die Projekt-Page noch nicht eingerichtet haben. Danach sollte der Steckbrief hier auffindbar sein:
https://leah1995.github.io/EIA2

**Comment by Leah1995** [comment]
Hallo,

eigentlich habe ich die Seite schon eingerichtet. Mein Steckbrief ist zu finden unter https://github.com/Leah1995/EIA2
Ich bin auch alle Schritte durchgegangen, die ich sollte.

**Comment by JirkaDellOro** [comment]
steckbrief.htm muss kleingeschrieben sein.

Die Userpage ist noch nicht eingerichtet, das Repository hierfür ist falsch benannt.
