### ISSUE TITLE
Blumenposition will nicht als let gespeichert werden

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#40]
In meiner Zeile 28 und 29 in Honigbiene.ts bekomme ich die Fehler "Index Signature of type implicitly has "any" type", wobei ich allerdings nicht verstehe, warum der Fehler aufkommt.
https://github.com/MrMarans/EIA2/blob/master/Aufg8/Honigbiene.ts

**Comment by saenglert** [comment]
Zeile 27 `this.hungry==true;`
Das doppelte = ist eine Vergleichsopperator und kein Zuweisungsoperator. Entsprechend wirfst du hier den Compiler total aus der Bahn und er versucht das noch irgendwie sinnvoll zu verarbeiten, wodurch die nachfolgenden Zeilen dann falsch interpretiert werden.

**Comment by MrMarans** [comment]
Allerdings ändert sich nichts, wenn ich das zu einem = umstelle. Die Fehlermeldung bleibt die gleiche und ist weiterhin der Punkt, der mit über die Konsole als Fehler markiert wird.

**Comment by MrMarans** [comment]
Gelöst. Hatte anstatt this.Flowers nur "FlowerSettings" geschrieben.
