### ISSUE TITLE
Wie geb ich das Array als Target an ?

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#41]
Guten Abend, 

ich hab meine Blumen seither in einem Switch-Case drin, sodass die Blumen, die auf der Wiese erscheinen, random sind.
Wie sage ich jedoch den Honigbienen nun, dass sie auf diese eine bestimmte Blume fliegen sollen?
Denn es kann sogar vorkommen, dass keine dieser Blumen da ist, wenn die Seite geladen wird.

Zudem:  Meine Bienen fliegen nicht zick zack ohne Target, ist das normal, dass sie sich "normal" benehmen?

Vielen Dank

**Comment by RedImp1470** [comment]
Wenn dein Flowers-Array korrekt gefüllt ist sollte es dir möglich sein daraus eine Blume auszuwählen und den Honigbienen als Target die x und y Koordinate der Blume mitzugeben. Beantwortet das deine Frage?

**Comment by NadiaCredidio** [comment]
Ich weiß halt nicht wo ich genau diese Information mitgebe. In dem Constructor oder in der Main, evtl. ja auch wo anders?

Ich bin da etwas verwirrt ^^'

**Comment by RedImp1470** [comment]
Die das initiale Target kannst du, wenn du möchtest, schon im Konstruktor mitgeben. Hat die Biene dieses erreicht muss allerdings ein neues Target aus dem Flowers-Array ausgewählt werden. Siehe dazu auch Issue #42 - Saschas Antwort.
