### ISSUE TITLE
Bienen nach Erreichung des Ziels neu Positionieren

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#42]
Hallo,
Ich möchte meine Bienen nach oben bewegen, nachdem sie ihre Blume erreicht haben, um ihnen danach ein neues Target übergeben zu können. Ich weiß nicht warum, aber sie zucken nur ein Stück nach oben, anstatt 100px nach oben zu fliegen. Ich denke meine if-Bedingung ist falsch, komme aber nicht darauf, wie es klappen könnte.
https://lisamei.github.io/EIA2/Aufgabe07/start.html

Danke im Voraus!

**Comment by saenglert** [comment]
Hallo Lisa,
um zu bestimmen ob die Biene angekommen ist verwendest du die Bedingung `d < 1` und bewegst, wenn die Bedingung zutrifft, die Biene um `100 * this.speed` in negative Y Richtung.

D.h. im nächsten Logikschritt trifft die Bedingung `d < 1` höchstvermutlich schon nicht mehr zu und das normale Verhalten von "Bewege dich auf dein Ziel zu" wird wieder ausgeführt.

Damit das was du planst funktioniert, würde ich spontan sagen, dass sich Zustände anbieten. D.h. deine Biene ist z.B. im Zustand "Ziel anfliegen" und wenn sie sich bewegen soll bewegt sie sich auf das Ziel zu. Ist das Ziel erreicht, wechselt der Zustand in "Aufsteigen", der die Biene für eine definierte Zeit nach oben fliegen lässt und nach Ablauf der Zeit den Zustand wieder auf "Ziel anfliegen" setzt.

Du kannst dir als Beispiel mal Dominics Abgabe von letzter Woche anschauen, da verwendet er sowas. Oder aber fürs erste einfach der Biene sagen, dass wenn sie ihr Ziel erreicht, sie einfach ein neues Ziel auswählt, denn eine Stunde vor Abgabe würde ich mich persönlich nicht mehr an so ein Feature setzen. :)

**Comment by LisaMei** [comment]
Danke! Das war das Problem. 
Bei dem Übergeben der neuen Zielwerte komme ich leider nicht weiter. Da ich die Targetwerte in der main.ts übergebe, kann ich nicht einfach mit einer Methode in der nectarBee.ts neue übergeben, wenn die Bienen angekommen sind. Die Target-Werte kommen ja aus dem Array, der nur in der main bekannt ist. Ich habe auch versucht, in der nectarBee.ts auf die Targetkoordinaten zuzugreifen über Classes.flowers usw. aber das hat leider auch nicht funktioniert.
Ist er möglich, die Werte weiterhin in der Main zu übergeben kann. Kann ich sie dann trotzdem später neu vergeben?
https://lisamei.github.io/EIA2/Aufgabe07/start.html

**Comment by RedImp1470** [comment]
Eine Möglichkeit wäre es, den Nektarbienen deinen Blumen-Array im Konstruktor mitzugeben, dann kennen die Bienen die Blumen, die sie anfliegen können (und du brauchst targetX und targetY dort nicht mehr). 
Eine andere Möglichkeit ist es, wie du es auch schon mit dem Canvas in der main.ts gemacht hast, den Blumen-Array mit "export" auszuzeichnen, dann ist er in allen Klassen bekannt.

**Comment by LisaMei** [comment]
Klappt! Danke schön.
