### ISSUE TITLE
Funktionsaufruf der Honigbienen

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#43]
Ich habe das Problem, dass die Honigbienen zwar gezeichnet werden sich aber nicht bewegen. Mir ist klar, dass ich irgendwo die flyHoneyBees-funktion irgendwo aufrufen muss, nur habe ich keine Ahnung wann, wie und wo.

Der Link zu meiner Aufgabe:
https://github.com/MichelleFix/EIA2/tree/master/Aufgabe8

Vielen Dank schonmal!

**Comment by saenglert** [comment]
Ich behaupte mal stark an derselben Stelle an der du auch deine bisherigen Bienen dazugebracht hast sich zu bewegen.

**Comment by MichelleFix** [comment]
Das mach ich ja in der flyBees funktion indem ich da diese b.update aufrufe oder?

**Comment by saenglert** [comment]
Probieren geht über studieren!
Lass das nicht Herrn Dell'Oro hören...!

**Comment by MichelleFix** [comment]
Ich probier ja schon die ganze rum und hab an jeder Stelle an der ich es für möglich halte irgendwas ein aber ich komm einfach ned drauf. Sonst hätt ich sicherlich kein Issue angelegt

**Comment by JirkaDellOro** [comment]
In dieser Veranstaltung macht Probieren einen Großteil von Studieren aus. Aber ich möchte Michelle noch mitgeben, dass Sie Polymorphie nutzen soll. Also nicht mehrere Arrays für die verschiedenen Bienentypen verwalten, sondern nur eines für alle Bienen. Hierzu am besten doch noch einmal den Vorlesungscode studieren.

**Comment by MichelleFix** [comment]
Aber ich hab doch nur ein Array wo alle Bienen reinkommen?

**Comment by JirkaDellOro** [comment]
Stimmt, ich hatte mich verguckt. Jetzt wollte ich das Programm mal laufen lassen und mir ist aufgefallen, das die Schreibweise der Dateien nicht mit den Links in der HTML-Datei übereinstimmen.

**Comment by MichelleFix** [comment]
ok habe ich verbessert

**Comment by JirkaDellOro** [comment]
Und schon läuft's? Das war dann einfach...
