### ISSUE TITLE
Bienen-Durcheinander

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#44]
Hallo zusammen,

meine Bienen machen gerade nicht wirklich, was sie sollen, aber ich finde den Fehler nicht. Um Hilfe wäre ich sehr dankbar!
https://fehrenbi.github.io/EIA2/Aufgabe%208/aufgabe8.html
Es soll eigentlich 10 normale und 5 Honigbienen erstellen, die sich auch so alle im Array auffinden lassen. Allerdings führt das Programm nur eine Honigbiene aus, die sich auf eine Blume bewegt. Von den restlichen 10 normalen Bienen fliegt eine schneller als die anderen.

Danke schon im Voraus

**Comment by JirkaDellOro** [comment]
Wenn ich die Konsolenausgabe anschaue, zähle ich 16 Bienen im Array. Das kommt wohl durch folgendes Konstrukt in Main:
```
//neue Biene erstellen
for (let i: number = 0; i < amountBees; i++) {
   let b: Bee = new Bee(130, 385);
   allBees[i] = b;
   allBees.push(b);
}
```
Das heißt, dass in Schublade i eine Biene gelegt wird und dann noch eine in i+1 gepusht. Die wird aber bei der nächsten Schleifeniteration überschrieben. Am Ende sind aber 11 drin...

Das wird aber noch nicht das Kernproblem sein, schätze ich.

**Comment by JirkaDellOro** [comment]
Die Abfragen im move der Honigbienen ergeben keinen Sinn. Einer der Fälle tritt sicher auf (außer xDiff oder yDiff ist exakt 0) und die Konsequenz ist unabhängig davon immer dieselbe.

**Comment by JirkaDellOro** [comment]
Die Nektarblumenblumen werden so erzeugt:
````
        //Array
        for (let i: number = 0; i < 5; i++) {
            let f: Flower = new Flower(x, y, "");
            f.draw();
            flowers.push(f);
        }
        console.log("Blumen-Array: " + flowers);
````
Das heißt, dass die Koordinaten dabei nicht verändert werden und somit alle 5 Blumen auf der gleichen Stelle stehen. Ich schätze, dass die Honigbienen daher auch alle exakt den gleichen Weg fliegen und somit übereinander gemalt werden.

**Comment by JirkaDellOro** [comment]
Jetzt fällt mir auch ein, warum die eine Biene schneller ist, ihre move-methode wird bei jedem animate zweimal aufgerufen, weil sie von zwei Schubladen im Array referenziert wird. Siehe oben.

**Comment by fehrenbi** [comment]
Achso okay. Also das mit den 15 Bienen und der einen, die sich schneller bewegt konnte ich nun beheben. Über die Frage wie die Honigbienen nicht alle den selben Weg fliegen, muss ich wohl noch etwas nachdenken...

**Comment by JirkaDellOro** [comment]
Einfach die Blumen verteilen und nicht auf die selbe Koordinate setzen

**Comment by fehrenbi** [comment]
Das heißt ich muss den x und y Werten in der for-Schleife zufällige Werte zuweisen? Aber dann werden mal 2 mal 3 Bienen irgendwo auf der Biene gesetzt?
Ich habe gerade das Problem dass ich momentan den Zusammenhang nicht ganz verstehe, wie es die Positionen der Blumen erkennt, und dann von diesen eine Zufällige auswählt

**Comment by fehrenbi** [comment]
Moment jetzt habe ich es doch geschafft, dass die Bienen direkt auf die rosanen Blumen fliegen :) Nur dass diese unregelmäßig 2-4 Honigbienen sind, die das tun.

**Comment by fehrenbi** [comment]
Hat jetzt geklappt :) nachzureichende Aufgabe (wegen Aufschub) ist jetzt hochgeladen

**Comment by JirkaDellOro** [comment]
Da es nur wenige Nektarblumen gibt, ist die Wahrscheinlichkeit hoch, dass mehrere Bienen die gleiche anfliegen und sich dabei gegenseitig verdecken.
