### ISSUE TITLE
A8 - Blumen werden nicht gezeichnet

### ISSUE THREAD

**Issue by AlisiaSteiner** [JirkaDellOro/EIA2#45]
Hi

Weder meine Blumen, noch meine Bienen werden gezeichnet. Ich würde das Problem gerne Schritt für Schritt angehen und habe mich erstmal den Blumen zugewandt. 
In der Konsole wird mir angezeigt, dass die Blumen gezeichnet werden und auch ins Blumen-Array gepusht werden. Allerdings werden sie nicht angzeigt.
Ich hab vermutet, dass eventuell etwas mit dem Speichern des Canvas als Bild und dessen Platzierung etwas nicht stimmt, aber das war es anscheinend nicht....
Auch ein extra Aufruf der draw-Funktion in der Main.ts hilft nicht.

https://alisiasteiner.github.io/EIA2/Aufgabe8/A8.html

**Comment by JirkaDellOro** [comment]
1. das draw der Sunflower wird nicht aufgerufen
2. Primrose und Sunflower duplizieren die Eigenschaften x und y, diese sind aber schon in der Blumen-Klasse gegeben!
3. Klasse Blumen sollte besser Blume oder noch besser Flower heißen
4. die Konstruktoren von Primrose und Sunflower verarbeiten die Parameter nicht, daher bleiben die Koordinaten immer undefined.
