### ISSUE TITLE
Aufgabe wird nicht in mein GitHub Repositoriy gepushed 

### ISSUE THREAD

**Issue by hejSalome** [JirkaDellOro/EIA2#46]
Hallo :)

Meine Aufgabe 8 (und auch schon das Konzept dazu) werden nicht in mein GitHub Repository gepushed. Ich habe alles gemacht wie immer und mein Dokumente auf den EIA2 Master gepushed aber dort erscheinen sie nicht. 
Wo könnte hier das Problem sein? 

Grüße 
Salome

**Comment by JirkaDellOro** [comment]
Hallo Salome,

 

hatten Sie vielleicht eine Änderung direkt auf Github vorgenommen? Dann sind ihr lokales und das Remote-Repository nicht mehr in Einklang. Sie müssten zuerst die Änderungen von Github ziehen (Rechtsklick auf Projekt -> Team -> Pull), damit ihr lokales Repository die Änderungen übernimmt, dann können sie auch wieder lokale Änderungen hochpushen.

**Comment by hejSalome** [comment]
Jetzt funktioniert es wieder! 
Hatte dasselbe ausprobiert aber es ging glaube nicht aufgrund von Konflikten im Master. 

Vielen Dank!
