### ISSUE TITLE
Change Event von Input-Elementen in fieldset abfangen

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#47]
Hallo,
Ich erstelle in TS ein fieldset mit der id "toppings". Jetzt möchte ich das change event abfangen, um später die ausgewählten Kugeln zusammenrechnen zu können. In TS habe ich versucht, Veränderungen in der Konsole anzeigen zu lassen, so wie ich es auch mit den Toppings gemacht habe. Das funktoiniert aber leider nicht. Liegt das daran, dass ich verschiedene Input-Elemente im Fieldset habe? Müsste ich an jedes einzelne einen EventListener hängen?

Danke im Vorraus!

**Comment by JirkaDellOro** [comment]
Hallo Lisa,

das ist ein respektabler Stand, der hier bereits erreicht wurde. Der Lösungsvorschlag mit dem dynamischen Formular ist interessant, der Code recht ordentlich und das Konzept schon diskussionswürdig.

Ich habe einen Pullrequest erstellt mit einigen Anmerkungen, bitte diesen öffnen und unter Files meine Anmerkungen identifizieren. Ich hoffe, das bringt schon Klarheit, ansonsten einfach weiterposten. 

Vorsicht bei der Arbeit mit IDs. Die sollen immer eindeutig sein, denn getElementById liefert das zuerst gefundene Element mit der ID und ignoriert andere Elemente mit der gleichen ID! Bei der dynamischen Erzeugung des DOM-Tree kann es leicht passieren, dass man dies nicht berücksichtigt und IDs mehrfach vergibt. Dafür ist es aber in der Regel auch gar nicht erforderlich nach IDs zu suchen, denn die Elemente werden ja erzeugt und somit ist bereits eine Referenz darauf bekannt, die man für das append nutzt. Damit kann man gleich auch alles andere machen...

**Comment by LisaMei** [comment]
Danke für die schnelle Antwort. Ich habe soweit ich weiß aber keinen Pull Request erhalten. In meinem Profil wird mir jedenfalls nichts angezeigt.

**Comment by LisaMei** [comment]
Hat sich erledigt, ich habe es gefunden.

**Comment by LisaMei** [comment]
Danke! Die Kommentare haben mir sehr geholfen.
