### ISSUE TITLE
Value mehrerer Selectboxen in Warenkorb anzeigen

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#48]
Hallo zusammen,
Ich komme mit der Ausgabe der ausgewählten Eissorten nicht weiter. Ich kann die value zwar jeweils anzeigen lassen, jedoch wird bei jeder Änderung im Fieldset wieder eine Sorte in den Warenkorb geschrieben. Auch, wenn man nur die Auswahl verändert. Das heißt es werden immer alle Auswahlen aneinandergehängt. Wäre super, wenn sich das jemand ansehen könnte. Ich komme einfach nicht weiter.

Danke im Voraus!

**Comment by JirkaDellOro** [comment]
Könnte es einfach an Zeile 62 liegen?

`
output.innerText += selectOutput[n];
`

Der innerText wird also immer erweitert...
Was passiert, wenn man statt des Additionszuweisungsoperator einen einfach Zuweisungsoperator (=) einsetzt?

**Comment by LisaMei** [comment]
Dann wird der Inhalt immer überschrieben. Also auch, wenn man mit "add Scoop" eine neue Sorte hinzufügt. Ich habe mir in der Konsole den Array ausgeben lassen und der hat dann tatsächlich die richtigen Einträge. Jedoch bekomme seine Einträge aus irgendeinem Grund nicht im Output angezeigt.

**Comment by JirkaDellOro** [comment]
Ist das Problem noch relevant? Der Code scheint ja deutlich überarbeitet worden zu sein. Mein Tipp: die handleEvent-Funktion nicht zu groß werden lassen und schauen, wo man diese wieder geschickt in kleinere Unterfunktionen aufteilen kann. Dann steht da eher z.B.
`
 if (this.id == "check") {
   checkForm( );
}
`
Dann noch die großen Kommentarblöcke raus und das ganze wird viel übersichtlicher!

Bei jeder Änderung sollte zudem am besten nicht nur der Preis, sondern die ganze Warenkorbanzeige neu aufgebaut werden. Dann sollte auch das vorangegangenen Problem nicht mehr auftauchen.
