### ISSUE TITLE
In Eclipse das Repositorie importiert, allerdings keine Änderungen möglich.

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#5]
Ich hab in Eclipse jetzt schon mehrmals nach Anleitung mein Repositorie eingefügt, hab aber keine Verbindung zu GitHub und zu den Dateien. Es wird nur ausgelesen, was für Dateien ich habe, nicht, was darin steht. 

Wenn ich die Dateien öffne, erscheint in dem Feld für den Code nichts und die Namensleiste bleibt auch leer. Teils bekomme ich sogar Fehlermeldungen.  Gif dazu:
https://gyazo.com/65b04c0c4460b95eb7ae97a2e3508724

Der Fehlercode ist außerdem: java.lang.NullPointerException

**Comment by JirkaDellOro** [comment]
Welche Eclipse-Version ist installiert?

**Comment by MrMarans** [comment]
Eclipse IDE for JavaScript and Web Developers in der Neon.2 Fassung

**Comment by JirkaDellOro** [comment]
Mit Aptana-Plugin? Das hat nämlich gerne diese Blankoseiten in Neon fabriziert.

**Comment by JirkaDellOro** [comment]
Aptana soll nicht installiert sein. Haben Sie einmal versucht die Dateien in einem simplen Texteditor zu öffnen um zu prüfen, ob es nur ein Anzeigeproblem ist oder ob sie tatsächlich keinen Inhalt haben?

**Comment by MrMarans** [comment]
Ja, mit Aptana. Allerdings gerade auch bei Mars.2 probiert, wo Aptana installiert ist. Dort tut es.

Also Dementsprechend Eclipse Neon.2 neu aufsetzen und dann neu versuchen?

**Comment by JirkaDellOro** [comment]
Ich würde ersteinmal nur Aptana bei Neon deinstallieren, vielleicht ist das schon heilsam

**Comment by MrMarans** [comment]
Klappt jetzt
