### ISSUE TITLE
Zuweisung Label Element

### ISSUE THREAD

**Issue by JanaBurger** [JirkaDellOro/EIA2#50]
Hallo,
wir wissen nicht wie bei Klick auf den Namen des Toppings auch die Checkbox aktiviert wird.
Mit append.child hat es irgendwie nicht funktioniert.

https://janaburger.github.io/EIA2/aufgabe9/aufgabe9.html

Liebe Grüße, Jana & Jacqueline

**Comment by moritzhfu** [comment]
https://stackoverflow.com/a/18432439

**Comment by JirkaDellOro** [comment]
Ich präferiere folgende Quelle: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
