### ISSUE TITLE
property value does not exist on type string

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#51]
Hallo zusammen, 

diese Meldung wird mir in der handleChange Funktion angezeigt und leider verstehe ich nicht wirklich, was ich ändern muss, bzw. wo das Problem liegt... Wäre toll, wenn mir jemand einen Tipp hätte und mir beim Verständnis helfen könnte. 

https://github.com/fehrenbi/EIA2/blob/master/Aufgabe%209/eisdiele.ts

Danke im Voraus!

**Comment by JirkaDellOro** [comment]
eissorten taucht im Code als lokale und als globale Variable auf. Die globale ist das String-Array und wir in handleChange verwendet. Die Elemente sind strings und haben keine Eigenschaft "value" beispielsweise                                                                                                                                                                           Von: notifications@github.comGesendet: 3. Juni 2017 11:58 vorm.An: EIA2@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: [JirkaDellOro/EIA2] property value does not exist on type string (#51)

**Comment by fehrenbi** [comment]
Aber eissorten[i] hat doch dann immer einen jeweils zugeordneten Wert, der auch ein value haben kann, oder nicht?

**Comment by JirkaDellOro** [comment]
value ist eine Eigenschaft eines HTMLInputElements, korrekt? Strings haben diese Eigenschaft nicht. Hier hat möglicherweise die Irritation durch die gleichnamige lokale Variable eissorten, die aber eine Liste von Elementen darstellt, durchgeschlagen. Auch damit würde es allerdings nicht funktionieren, da allgemeine HTMLElemente auch keinen value haben.

**Comment by JirkaDellOro** [comment]
Wenn es mit den Input-Elementen funktionieren soll, müsste man TypeScript noch sagen, dass die mit der CSS-Klasse verknüpften HTML-Elemente eben solche sind. Vollständig typisiert sind das dann so aus:
`
        let iceInput: NodeListOf<HTMLInputElement> = <NodeListOf<HTMLInputElement>>document.getElementsByClassName("Sorten");
`

Ich habe die Variable, welche die Liste referenziert, jetzt absichtlich nicht eissorten genannt, um die Mehrdeutigkeit zu vermeiden

**Comment by JirkaDellOro** [comment]
PS: die Funktion "showBestellung" sollte nicht innerhalb einer anderen definiert sein. Solange wie möglich sollten wir diese Konstrukte vermeiden.
