### ISSUE TITLE
Problem mit dem Terminal

### ISSUE THREAD

**Issue by mariosommer** [JirkaDellOro/EIA2#52]
Hallo, ich habe Probleme mit dem Terminal und weis nicht weiter.
(Apple Nutzer) und Node.js wurde installiert.
Aber es kommt immer eine Fehlermeldung im Terminal:
bash-3.2$ node
bash: node: command not found
bash-3.2$ node NodeTest.js
bash: node: command not found
bash-3.2$ 

Vielleicht weis ja jemand wo das Problem liegt, schonmal Danke.

**Comment by moritzhfu** [comment]
Node scheint noch nicht installiert oder eine Systemvariable ist nicht richtig gesetzt.

**Comment by moritzhfu** [comment]
Nach etwas Recherche. Wie ich dachte, $PATH muss angepasst werden. Tutorial hierfür:
http://justjs.com/posts/getting-started-part-i-installing-node

**Comment by saenglert** [comment]
Einfacherer Weg statt die PATH Variable anzupassen ist das Plugin EasyShell über den Eclipse Marketplace zu installieren.

Keine Ahnung warum Eclipse auf Macs ständig versucht das Bash Terminal zu verwenden, wenn standardmäßig die Terminal App da und richtig konfiguriert ist.

**Comment by mariosommer** [comment]
Hat funktioniert, danke.
