### ISSUE TITLE
Probleme bei Deploy Branch in Heruko

### ISSUE THREAD

**Issue by hejSalome** [JirkaDellOro/EIA2#54]
Hallo!

Beim erstellen einer neuen App in Heruko habe ich Probleme bei Deploy Branch. 
Es kommt dann diese Fehlermeldung:

 !     No default language could be detected for this app.

			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.

			See https://devcenter.heroku.com/articles/buildpacks

 !     Push failed

Woran könnte das liegen und was kann ich tun?

Vielen Dank,
Salome

**Comment by saenglert** [comment]
Hi Salome,
welches deiner Repositories versuchst du gerade auf Heroku zu deployen? Aktuell sehe ich da nämlich kein valides NodeJS Repo.

**Comment by hejSalome** [comment]
Hi Sascha,
ich habe versucht ein Repository zu erstellen, doch dieses lässt sich nicht speichern bei mir local. Daher habe ich die Sachen in meinen EIA2 Ordner verschoben. Es liegt glaube ich iein Fehler beim clonen des Repositorys mit eclipse vor....

**Comment by saenglert** [comment]
Mhm, dann denke ich mal, das sollten wir am Besten morgen im Praktikum vor Ort anschauen, da ich von hier aus schlecht schauen kann, was da in die Binsen gegangen ist.

**Comment by hejSalome** [comment]
okey das wäre super, dankeschön!

**Comment by RedImp1470** [comment]
Es könnte auch daran liegen, dass evtl. in Heroku unter Settings --> Buildpacks nicht nodejs eingetragen ist.
![grafik](https://user-images.githubusercontent.com/9215439/27393039-7a4877a6-56a8-11e7-842d-83f67bf6a434.png)

Ansonsten solltest du nochmal vergleichen, ob du alles so eingestellt hast, wie es in der Mindmap steht :)

**Comment by JirkaDellOro** [comment]
Jedenfalls ein eigenes Repo für Node-Code erstellen, das ist Teil der Übung...
