### ISSUE TITLE
Database.ts & Server.ts

### ISSUE THREAD

**Issue by moritzgiuliani** [JirkaDellOro/EIA2#55]
Guten Morgen,

ich habe gestern versucht den VL-Code bei mir zum Laufen zu bringen.
Eine neue Branch mit der Server.ts usw ist eingerichtet und eine eigene MLAB Collection existiert ebenfalls und ist im Code eingepflegt.
Allerdings bekomme ich derzeit die Heroku App nicht zum laufen.

Angeblich ist der Origin Access nicht gestattet (Output wenn ich die Database.html teste).
Allerdings glaube ich, dass es in Wahrheit die App ist, die (laut Heroku log) immer sofort Crashed.

Kann es in der Server.ts etwas mit dem Import database (Zeile 8) zutun haben? So ein Verzeichnis existiert ja garnicht (bzw. in Ihrem GitHub haben Sie einen gitIgnore drauf) oder müsste eine Database Collection das im MLAB kompensieren?
Irgendwas grundsätzliches kriege ich hier irgendwie nicht mit...

MLAB:
https://mlab.com/databases/exer11
(remote:furtwangen)

HEROKU:
https://mkb2eia2db-exer11-0.herokuapp.com

REPO:
https://github.com/moritzgiuliani/mkb_eia2/tree/master/exer_11_0/lesson
https://github.com/moritzgiuliani/mkb_eia2_db/tree/exer_11_0

**Comment by JirkaDellOro** [comment]
In package.json muss eine dependency auf mongo eingetragen werden. Siehe Curriculum in MindMap.

**Comment by JirkaDellOro** [comment]
Ich sehe gerade, dass der Eintrag in meiner Vorlage drin war. Ich habe trotzdem einen Hinweise darauf in der Aufgabenstellung ergänzt.

**Comment by moritzgiuliani** [comment]
Danke!

Habe die package aus dem alten Projekt übernommen und daher Ihren Eintrag übersehen. Habe es im mindmap inzwischen im Curriculum gefunden.
Die App funktioniert nun - dass die Daten korrekt übergeben werden noch nicht (Response: unknown....) , aber das versuch ich jetzt selbst zu lösen. Soweit bin ich noch nicht vorgedrungen da Heroku schon der showstopper war.
