### ISSUE TITLE
automatische Erstellung ts/js

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#57]
Hallo, ich habe wieder mal das Problem, das Eclipse aus ts keine js Dateien erstellt. En/Disabelt habe ich, Clean durchgeführt, PC neu gestartet. Hat aber alles nichts geholfen. Hat jemand noch eine Idee woran das liegen könnte?

**Comment by JirkaDellOro** [comment]
Fehler im Code irgendwo? Dann wir nicht kompiliert. Unter Problems schauen und alle beheben

**Comment by aliciaburger** [comment]
nur warnigs und ich vermute mit dem Linter stimmt etwas nicht wenn ich zB. Autoformatierung mache verschwindet der Fehler nicht.

**Comment by JirkaDellOro** [comment]
Sollen wir einmal eine Ferndiagnose per Skype oder TeamViewer versuchen?

**Comment by aliciaburger** [comment]
Ja wäre vielleicht nicht schlecht. habe bisher noch keine Lösung gefunden. mein Skype name: lissl.burger
