### ISSUE TITLE
Verbindung zu Heroku

### ISSUE THREAD

**Issue by MichelleZei** [JirkaDellOro/EIA2#58]
Guten Abend,

die Verbindung zu Heroku steht, aber wenn man den Submit-Button klickt, wird kurz versucht die Verbindung aufzubauen, bricht dann aber ab. Also es flackert kurz ein weißer Bildschirm auf und unten wird auch angezeigt "Warten auf heroku-app", aber am Ende ist wieder mein Eisshop zu sehen statt der Seite mit der Antwort auf den User.
Ich komme leider nicht drauf, an was das liegen könnte.

**Comment by JirkaDellOro** [comment]
Im Code steht explizit ein location.reload( ). Warum?

**Comment by MichelleZei** [comment]
Stimmt, nachdem die Bestellung erfolgreich war, braucht man das reload nicht. Jetzt funktioniert es

**Comment by JirkaDellOro** [comment]
OK, das ging schnell
