### ISSUE TITLE
Fehler auf Heroku

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#59]
Hallo,
ich bekomme diesen Fehler angezeigt. Ich war schon auf diesem Link von HerokuDevCenter aber das bringt mich auch nicht weiter...

-----> Failed to detect app matching https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz buildpack

       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

 !     Push failed

**Comment by JirkaDellOro** [comment]
Wann kam diese Fehlermeldung? Ich vermute bei dem Versuch, das "EIA2-Heroku"-Repository auf Heroku ausführen zu lassen. In dem Repository liegt aber noch nichts sinnvoll ausführbares.

**Comment by MichelleFix** [comment]
Oh wie blöd, ich habe vergessen die Dateien aus eclipse in github zu pushen. Es zeigt mir jetzt zumindest mal "Build in progress" an

**Comment by fehrenbi** [comment]
@MichelleFix  funktioniert es jetzt bei dir?
Ich glaube ich habe das selbe Problem, allerdings bereits alles hochgepusht. Es zeigt wie auch bei Michelle Push failed an und auf der Übersichtsseite Build failed.

**Comment by MichelleFix** [comment]
Ich hatte ein Problem mit der Verbindung zu Githup bzw. meinem Respository. Ich hatte die Fehlermeldung "Build failed", ich glaube du meinst was anderes oder?

**Comment by JirkaDellOro** [comment]
Häufig ist die mangelnde Anpassung der Datei package.json eine Ursache
