### ISSUE TITLE
Probleme beim Hochpushen

### ISSUE THREAD

**Issue by MichelleZei** [JirkaDellOro/EIA2#6]
Die Aufgabe 1 - HTML konnte ich noch ganz normal hochpushen. Bei den Bilder bzw beim erneuerten Steckbrief kommt immer die Fehlermeldung "Error writing request body to server". An was liegt das?

**Comment by MichelleZei** [comment]
Hat sich erledigt. Jetzt funktionierts.

**Comment by JirkaDellOro** [comment]
Haben Sie eine Idee, woran es lag? Gerne hier kurz schildern, vielleicht können wir alle etwas lernen.

**Comment by MichelleZei** [comment]
Ne, keine Ahnung. Habe es einfach am nächsten Tag nocheinmal probiert.
