### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#60]
Mein Hauptproblem ist gerade dass zwar mein Programm auf localhost soweit läuft, sobald ich es aber auf heroku laufen lassen möchte kommt ein Application error. 
Das 2. Problem ist, das der der Linter einen klammer fehler anstreicht, wo ich eigentlich gar kein Fehler entdecken kann. Deswen kann ich auch keine aktuelle js Datei erstellen.

**Comment by JirkaDellOro** [comment]
Sofern Node10,ts autoformatiert ist, kann ich erkennen, dass die handleRequest-Funktion nicht geschlossen ist. Da fehlt dann tatsächlich die Klammer.

Wenn Node10.js existiert, muss noch package.json entsprechend angepasst werden.

Außerdem: es steht zuviel in der for..in-Schleife unter anderem ein response.end(). Das wird so nicht klappen.
