### ISSUE TITLE
Frage zu Aktivitätsdiagrammen

### ISSUE THREAD

**Issue by braundominik** [JirkaDellOro/EIA2#62]
Hallo,
ich habe mal das berechnen einer Zahl aus der Fibonacci Reihe in einem Aktivitätsdiagramm dargestellt.
Es handelt sich hier um eine Funktion fib(n), welche die Zahl an der Stelle "n" der Fibonacci Reihe zurückgeben soll.
Ich wollte einfach Fragen ob das Aktivitätsdiagramm so passt oder ob irgendwelche Fehler erkennbar sind.

![fibonacci](https://user-images.githubusercontent.com/26409265/27769969-a50d1ef6-5f36-11e7-9c7e-a832d5c2840c.jpg)

**Comment by saenglert** [comment]
<erbsenzähler>
Ich würde in den Kasten obenlinks nur den reinen Namen schreiben, da du ja dann im Kasten in der Mitte die Paramater auflistest, die entgegengenommen werden.
</erbsenzähler>

Jetzt bitte diese Aufgabe nochmal bearbeiten ohne eine Schleife zu verwenden. Stichwort Rekursion.
Tipp: Die Funktion ist mit 5 Zeilen gut zu lösen.

**Comment by braundominik** [comment]
5 Zeilen schaff ich nicht

```
let fib1: number = 1;
let fib2: number = 1;
let i: number = 2;
function fib(n: number, f1:number, f2:number):number {
if(n == 1 || n==2) 
  return 1;

else{
  let fib = fib1 + fib2;
  i++

  if(i>=n) 
    fib(n, fib2, fib);

  else
    return fib;

 }
}
```

**Comment by saenglert** [comment]
Die Wertigkeit der Fibonacci-Folge setzt sich ja aus einer Addition zusammen, die vorherige Zahl (-1) + die vorherige Zahl der vorherigen Zahl (-2). Mit dem Wissen dass fib(n) mit n < 3 gleich 1 ist, kann man folgende rekursive Funktion definieren:
```
function fib(n: number): number {
    if (n < 3)
        return 1;
    else
        return fib(n - 1) + fib(n - 2);
}
```

**Comment by braundominik** [comment]
Oh stimmt. So ists natürlich einfacher.

**Comment by saenglert** [comment]
Ok, dann wie wäre es mit einem Aktivitätsdiagramm für die Funktion? :)

**Comment by JirkaDellOro** [comment]
Das Diagramm ist sehr gut. Man kann noch ein klein wenig vereinfachen, wenn man davon ausgeht, dass alle Werte unter 3 eine 1 liefern sollen. Dann ergibt sich letztlich folgender Code (wobei ich gegenüber dem Diagramm f1 und f2 getauscht habe.
```
function fib(n: number): number {
        let f1: number = 1;
        let f2: number = 0;
        for (let i: number = 1; i < n; i++) {
            let f: number = f2 + f1;
            f2 = f1;
            f1 = f;
        }
        return f1;
    }
```
Ein großer Nachteil von Saschas rekursiver Lösung ist, dass sehr viele überflüssige Berechnungen angestellt werden. Da jede Rekursion zwei neue startet, steigt der Aufwand exponentiell. fib(10) erfordert 109 Iterationen. Ist trotzdem schön knapp und wenn es darum geht könnte man noch steigern zu
```
function fib(n: number): number {
    return (n < 3) ? 1 : fib(n - 1) + fib(n - 2);
}
```

**Comment by saenglert** [comment]
Rekursiom ist auch nicht in jedem Fall die beste Lösung. Herr Eisenbiegler benutzt z.B. gerade eben Fibonacci als Beispiel um zu zeigen, wo Nachteile liegen.

Ich habs jetzt hauptsächlich noch reingebracht, um nochmal ein konkretes Beispiel für ein Aktivitätsdiagramm zu haben. :)

**Comment by braundominik** [comment]
Ja Rekursiv ist natürlich die elegantere Lösung. Wurde aber soweit ich weiß nicht behandelt in der Vorlesung daher habe ich in meinem Diagramm den iterativen Weg gewählt.
Obwohl Fibonacci ja oft eines der Standardbeispiele für Rekursion ist.

Hier das Diagramm für die Rekursive Lösung. Kann ich hier quasi 2 returns einbauen ? Also zwei Ausgaben ? Für eine Funktionsaufruf müsste der Kasten ja eigentlich abgerundet sein. Es ist jedoch ein return weshalb ich den Kasten eckig gemacht habe.

![fibrekursiv](https://user-images.githubusercontent.com/26409265/27772066-9fb8a4c8-5f5b-11e7-8577-8df2288b1243.jpg)

**Comment by JirkaDellOro** [comment]
Nein, keine zwei returns, das kann man eher auf der Implementationsebene machen. Wenn man die "Blackbox" Aktivitätsdiagramm wieder schließt, hätte man zwei Ausgänge, von denen mal der eine, mal der andere einen Wert liefert.  "Early outs" sind aber auch auf der Implementationsebene umstritten, ich finde sie dort aber gut. Im Aktivitätsdiagramm sollte besser ein Ergebnis berechnet werden, dass dann am Ende ausgegeben wird.
Und den Funktionsaufruf tatsächlich in ein abgerundetes Rechteck schreiben, dort den Ein- und Ausgang andeuten, dann weiß man dass Daten rein- und rausgehen.
