### ISSUE TITLE
Verständnis der Abschlussaufgabe

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#63]
Hallo zusammen, 

ich habe mal eine Frage wegen der Formulierung der Abschlussaufgabe.
"eine kleine internetbasierte (und interaktive) Anwendung"
"Eine kurze Anleitung zur Installation der Anwendung"
Was genau ist bei der freien Aufgabe mit internetbasiert gemeint? 
Und reicht es also nicht, die Aufgabe wie gewöhnlich auf Github hochzupushen und den Link von dort zu verlinken?

Schönes Wochenende! LG Luise

**Comment by saenglert** [comment]
Hallo Luise,
internetbasiert heißt, dass die Anwendung im Kontext des Internets arbeitet und auch über dieses erreichbar ist. Interaktiv bedeutet natürlich der User kann etwas mit der Anwendung machen. 

Unsere bisherige Vorgehensweise bildet das genau ab: Unsere Anwendungen sind per Browser erreichbar und sie greifen über das Web auf andere Teile der Anwendung zu (Server über NodeJS, Datenbank über MongoDB). Interagieren konnte der User in dem er z.B. Daten in die Datenbank eingibt oder Daten ausliest.

Ein anderes Beispiel für eine internetbasierte Anwendung versus eine klassische Desktopanwendung ist Google Docs vs Microsoft Word:
Während Word und seine Anwendung an deinen PC gebunden ist (die ganzen Cloudgeschichten von Microsoft lassen wir jetzt mal weg) und nur du an einem Dokument arbeiten kannst, erreichst du Google Docs über deinen Browser und bist nur einer von vielen möglichen Clients die mit dem Dokument auf dem Server interagieren.

Hoffe das hat dir erstmal klar gemacht, wo es hingehen soll und wo der Unterschied ist.

**Comment by fehrenbi** [comment]
Hm okay ja das habe ich soweit verstanden.
In der freien Canvas-Aufgabe ist die Arbeit mit einer Datenbank ja aber nicht verpflichtend, richtig? Wenn ich jetzt also ein kleines Game programmieren möchte, dass ich ähnlich aufbaue wie die Bienen-Aufgabe (klar der Nutzer muss damit interagieren können) und das somit nur über Github hochgepusht habe und damit über den Browser aufrufbar ist, zählt das dann bereits als internetbasiert? Weil dann ist es ja ähnlich wie dein Word Beispiel zwar an meinen PC gebunden, aber über den Browser erreichbar.

**Comment by saenglert** [comment]
Ja, ein kleines Spiel auf dem Canvas ist völlig ausreichend, nur deine Begründung ist nicht ganz korrekt:

Wenn du dir unsere EIA2 Landschaft nochmal anschaust ( https://github.com/JirkaDellOro/EIA2/blob/master/DIA2Landscape.png ), siehst du, dass nachdem du deinen Programmcode auf Github pusht, ist nicht mehr dein Rechner für die Verteilung zuständig an den Browser anderer User zuständig, sondern Github. 

Auf Github läuft ein Http Server der mir wenn ich z.B. http://fehrenbi.github.io/abschlussarbeit/client.html aufrufe die Datei client.html liefert, die im Unterverzeichnis abschlussarbeit, auf der Domain github.io, mit der Subdomain fehrenbi liegt.

Würde ich dieselbe Anfrage an deinen Rechner stellen (von dem ich ja nichtmal weis wo er im Web ist, da er keine Domain oder eindeute IP hat), würde mir nur ??? zurückkommen bzw. überhaupt keine Antwort, da dein Rechner in der Regel keinen eigenen http Server hat und auch nicht direkt erreichbar ist.

Jetzt kann man sich natürlich die Frage stellen, warum konnten wir dann unsere Sachen überhaupt lokal testen, bevor wir sie auf Github gepusht haben? Ziehe dazu mal einen HTML File aus Eclipse in deinen Brauser und betrachte das URL Feld. Es wird ungefähr so aussehen: file:\\c:\benutzer\luise\workspace\abschlussaufgabe\client.html .Hier wird also keine http:// Anfrage vom Browser an eine Webseite gesendet, sondern dein Browser greift auf das File/Dateisystem deines Rechners zu und ruft die Datei client.html am Ende des gegebenen Pfades auf und kann dann den Inhalt verarbeiten.

Kurzgesagt, das Internet ist die Summe der Server die ihre Dienste anbieten. Unsere eigenen PCs sind nur Clienten die diese Service in Anspruch nehmen.

**Comment by NadiaCredidio** [comment]
Demnach reicht es, des Canvasdings auf Github zu laden, um die Aufgabe zu beenden. Sprich, keine Server, Mongo etc. notwendig?

**Comment by saenglert** [comment]
So wie ich die Aufgabenstellung lese ja, mal schauen was Herr Dell'Oro dazu sagt, wenn er das hier liest

**Comment by JirkaDellOro** [comment]
Dem habe ich eigentlich nichts hinzuzufügen, ihr scheint alles mit Saschas Hilfe verstanden zu haben. Man kann natürlich auch ohne Canvas und grafische Ausgabe arbeiten, dann ist aber eine sinnvolle Datenbankanbindung zu üben. Besonders gerne gesehen ist natürlich die Kombination und ein paar von euch arbeiten bereits daran...
