### ISSUE TITLE
Event Mousedown

### ISSUE THREAD

**Issue by fehrenbi** [JirkaDellOro/EIA2#64]
Hallo alle zusammen,

in meiner bisherigen Abschlussaufgabe hätte ich gerne, dass sich der Hai (bisher nur grauer Kreis) dorthin bewegt, wo ich mit der Maus hinklicke. 
Ich habe jetzt lange und ausgiebig recherchiert, es mit event.clientX und event.clientY versucht, doch irgendwie komme ich nicht so recht weiter. 
Leider wird clientX und clientY bei meinem Event nicht erkannt (woher weiß es überhaupt, welches Event angesprochen wird?). Hat jemand vielleicht einen Tipp für mich, der mir auf die Sprünge helfen kann?
LG Luise

https://github.com/fehrenbi/EIA2/tree/master/Abschlussarbeit/selber%20gemachte%20Aufgabe
https://fehrenbi.github.io/EIA2/Abschlussarbeit/selber%20gemachte%20Aufgabe/abschlussaufgabe.html

**Comment by saenglert** [comment]
Hallo Luise,
dein Problem liegt in der move Funktion deines Haies:
```
move(): void {
            var mouseX: number = event.ClientX;
            var mouseY: number = event.ClientY;
            this.x = mouseX;
            this.y = mouseY;
        }
```
Du fragst schon ganz richtig nach der Position des Mauszeigers beim Event. Nur gibt es in deiner move Funktion gar kein Event, das man befragen könnte. Deswegen ist `event.clientX/Y` auch `undefined` und es bewegt sich nichts.

Wo kann also die Information über das Event herkommen? An der Stelle an der das Event ausgelöst wird:
```
canvas.addEventListener("mousedown", moveShark);
        
        function moveShark(): void {
            let s: Shark = new Shark(220, 220);
            s.move();
        }
```
Wird das Event ausgelöst, soll die Funktion moveShark aufgerufen werden. Jedesmal wenn ein Event ausgelöst wird, wird auch ein Objekt erstellt, welches die Informationen über das entsprechende Event beinhaltet (u.a. clientX/Y uvm.). 

Damit wir mit dieser Information arbeiten können, muss unsere Funktion dieses Eventobjekt auch entgegennehmen. Wie das funktioniert kannst du in deinen Unterlagen nachlesen.

Gut, jetzt haben wir die Information in der Hand und müssen sie an den Hai weiterreichen, damit es sich in die entsprechende Richtung bewegen kann. Das ist auch wieder ein Problem, das dir bekannt vorkommen sollte.

Grüße
Sascha

**Comment by fehrenbi** [comment]
Danke für deine Antwort Sascha! Ich habe jetzt noch einmal daran gearbeit und der Code sieht jetzt folgendermaßen aus:

canvas.addEventListener("mousedown", moveShark);

        function moveShark(_event: MouseEvent): void {
            var mouseX: number = event.ClientX;
            var mouseY: number = event.ClientY; 
            let s: Shark;
            s.x = mouseX;
            s.y = mouseY;
        }

Allerdings zeigt es mir egal was ich mache "ClientX does not exist on Type 'Event'" an...

**Comment by JirkaDellOro** [comment]
Da stimmt die Schreibweise nicht, sowohl beim Parameter selbst wie auch bei der Eigenschaft.
