### ISSUE TITLE
Cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#65]
Hi,
folgender Fehler wird mir in der Konsole angezeigt, wenn die HTML im Browser öffne:
"main.ts:31 Uncaught TypeError: Cannot read property 'canvas' of undefined". Ich komme nicht darauf, wieso die Variable undefined sein soll. Ist wahrscheinlich ein ganz doofer Fehler...

https://lisamei.github.io/EIA2/Final%20Project/start.html

Danke schonmal!

**Comment by saenglert** [comment]
Tipp: Nur weil etwas nach der Funktion steht heißt es nicht, dass es erst nach dieser ausgeführt wird. Stichwort init Funktion.

**Comment by LisaMei** [comment]
Oh danke! Ich habe den init-Aufruf verschoben, aber der Fehler wird immer noch angezeigt...

**Comment by saenglert** [comment]
Ist die neue Version schon online? Ich sehe gerade keine Änderung.
Auf jedenfall liegt das Problem in der Zeile 27 in der die Variable ball definiert wird.

**Comment by LisaMei** [comment]
Ja eigentlich schon also die ist schon auf Gihub. Also die Init wird doch als aller erstes aufgerufen und definiert den canvas. Wieso ist es dann in Zeile 27 undefined?

**Comment by saenglert** [comment]
Da landen wir wieder genau bei meiner ersten Antwort:

Nur weil etwas nach der Funktion steht heißt es nicht, dass es erst nach dieser ausgeführt wird. 

Wenn du in Zeile 12 den Eventlistener hinzufügst, heißt das nicht, dass dann an dieser Stelle solange gewartet wird, bis das Event eintritt.

Stell dir eher vor, der Browser macht sich jedesmal, wenn du einen Eventlistener hinzufügst eine kleine Post-It-Note mit der Aufschrift "Wenn Event X, dann Funktion Y" und klebt sie sich an den Monitor während er weiter deinen Programmcode liest. Erst wenn das Event ausgelöst wird, geht er seine Zettel durch und schaut ob er etwas machen muss.

D.h. dein Programmablauf sieht aktuelle so aus:
Zeile 12
Zeile 13
Zeile 27 // Absturz

Denn wenn du in Zeile 27 versuchst crc2.canvas.width usw. aufzurufen, war dein Programm noch garnicht in der Zeile 19, in der crc2 definiert wird.

**Comment by LisaMei** [comment]
Ahh ja ich stand auf dem Schlauch :D danke. Noch eine kleine Frage. Ich bin mir nicht sicher, ob ich verstehe wie setInterval funktioniert. Ich lasse im Intervall die Update Methode vom Ball aufrufen, jedoch bewegt dieser sich nicht. Wenn ich das Intervall verändere, kann ich sehen, dass irgendetwas passiert. Was mache ich hier falsch? Ich möchte eigentlich, dass mit x+=xD und y+=yD die Position verändert wird und sich der Ball in diese Richtung bewegt.

**Comment by saenglert** [comment]
Deine Bedingungen in move werden niemals wahr.

Außerdem kleiner Tip: Lass nicht ein spezifisches Objekt dein Canvas übermalen, sondern mach das am Start deiner animate Funktion. So kann es z.B. nicht passieren, dass wenn du zwei Objekte dieses Typs hast, dass sie sich gegenseitig übermalen.

**Comment by LisaMei** [comment]
Ich habe die Bedingungen schon auskommentiert., ich glaube es war noch nicht aktualisiert. Aber danke für den Tipp.

**Comment by saenglert** [comment]
Du erhälst wenn du deinen neuen Ball erstellst aus irgendeinem Grund NaN statt die korrekte Höhe des Canvas. ich finde gerade nicht den Grund, muss jetzt aber auch erstmal Schluss machen, da ich heute fürs Mittagessen zuständig bin :)

**Comment by LisaMei** [comment]
Danke:D kein Stress

**Comment by LisaMei** [comment]
Okay ich habs. Aus irgendeinem Grund hat die übergabe con xD und yD nicht funktioniert. Wenn ich direkt Zahlen und nicht die Variablen zuweise funktioniert es.

**Comment by saenglert** [comment]
Jup, da bin ich auch gerade: In Ball.ts Zeile 22 und 23 soll das zweite xD vermutlich yD sein.

Entsprechend bleibt die yD undefined und wenn du in Move y + yD rechnest kommt natürlich NaN raus.

PS: Um die Bewegung zu sehen, musst du in deiner Draw Methode natürlich noch statt statischen Werten x und y als Position einsetzen.

**Comment by saenglert** [comment]
Apropos statische Werte in der Draw Funktion. Jetzt ist mir auch aufgefallen, warum das mit dem Abprallen in Move nicht klappt:

Du weist `radius` niemals einen Wert zu, also ist es auch `undefined`. Irgendwas größer oder kleiner `undefined` ist immer falsch. Im Konstruktor einfach `radius` auf 10 setzen und in `draw` statt them festen Wert auch `radius` einsetzen.

**Comment by LisaMei** [comment]
Klappt jetzt :) Bin gerade dabei, dass mit dem Radius einzubauen, damit der Ball nicht halb verschwindet

**Comment by LisaMei** [comment]
Hallo,
ich scheitere daran, dass der Ball, wenn der den Balken trifft, wieder nach oben fliegt. Ich finde aber keinen Weg der funktioniert. Ich glaube ich verrenne mich gerade. Das hier war meine Idee:
![imag2546](https://user-images.githubusercontent.com/26438966/28238791-a26bfe2c-695b-11e7-8d85-47a450e1df0c.jpg)
Die if-Abfrage soll genau den Fall abfangen, dass der Ball innerhalb der Balkenbreite ist und gerade nach unten fliegt. Wäre super, wenn sich das jemand ansehen könnte.
https://lisamei.github.io/EIA2/Final%20Project/start.html
Die if-Anfragen zur Canvas-Begrenzung befinden sich in der ball.js in der move-Methode.

Danke im Voraus :)

**Comment by JirkaDellOro** [comment]
Hallo Lisa,

zunächst: der Code wird besser lesbar, wenn man noch zwei Variablen spendiert, so dass in der move-Methode des Balls oben folgendes steht:

let newX = this.x + this.xd;

und dann weiter
            //linker oder rechter Rand erreicht
            if (newX > crc2.canvas.width - this.radius || newX < this.radius) {
                this.xd = -this.xd;
}

usw

das Gleiche dann für y

**Comment by JirkaDellOro** [comment]
Desweiteren: grundlegend passt schon alles ganz gut. Man sollte aber den y-Durchgang gegen den Bar prüfen, nicht gegen den Spielfeldrand. Sonst wird das sonderbar.

Kernproblem scheint aber derzeit zu sein, dass gegen die globalen Variablen barX und barWidth geprüft wird, die aber nur bei der Initialisierung verwendet werden. Das bewegte Objekt ist aber eine Instanz der Klasse Bar

**Comment by LisaMei** [comment]
Ah danke, das macht es auf jeden Fall übersichtlicher!
Mein Problem ist glaube ich, dass ich die Position des Balkens nicht richtig übergebe. Ich muss irgendwie in der main und in der ball Klasse darauf zugrefien.

**Comment by JirkaDellOro** [comment]
Das bar-Objekt mit export deklarieren und in ball.move dann gegen bar.x prüfen

**Comment by LisaMei** [comment]
Aber die x Koordinate und die width von bar sollte ich parallel auch abfragen oder? Kann ich das ganze Objekt exportieren? Also sozusagen mit export let bar:Bar= new Bar?

**Comment by saenglert** [comment]
Hallo Lisa,
neuer Tag, neues Glück? :)

Was mir hier gerade schon bei deiner Zeichnung aufgefallen ist, du bedenkst bei deiner Kollisionsabfrage mit dem Balken garnicht die Y-Position des Balls.

In deinem Code sieht das ja aktuell so aus.
```
Abfrage Canvasgrenzen links rechts;
Abfrage Canvasgrenze oben;
Abfrage Canvasgrenze unten {
    Abfrage Balkenbreite
}
```
Die einzige Situation in der der  Inhalt der letzen Bedingung ausgeführt wird, ist wenn der Ball am Boden ist und innerhalb der **vordefinierten** Position und Breite des Balken. Der Ball müsste eigentlich seine Richtung ändern wenn er in diesem Bereich des Canvas landet und auf Höhe des Balken landet. Nicht erst, wenn der Ball ins Aus rollt.

Weshalb ich des vordefiniert hervorgehoben habe: Du verwendet ist ein deinem Code viele einzelne Variablen, die du per `export` global machst und auch verwendetst, aber deren Inhalt nicht aktuell sind.
Z.B. deine `barX` und `barY` Variablen, werden beim Start des Programmes mit den Ausgangswerten gefüllt, aber nie mit den neuen Werten der Position des Balkens aktualisiert.

Es macht aber auch wenig Sinn diese einzelnen Variablen aktuell zu halten, denn du hast bereits etwas, das alle wesentlichen Infos im neuesten Zustand speichert. Nämlich dein `ball` Objekt, dass du in der Init Methode erstellst. Verschiebe die ball Variable einfach in den Namespace und markiere sie mit `export`, genau wie du gerade gesagt hast.

Zuletzt muss ich dir noch auf die Finger klopfen, da du gerade wieder in alte Gewohnheiten verfällst und anonyme und geschachtelte Funktionen verwendest, wo wir sie nicht brauchen und sie sogar kontraproduktiv sind.

Nimm dir nochmal 10min und drösel deine init Funktion auf.

**Comment by LisaMei** [comment]
Danke!!! Neuer Tag, neue Probleme :D Ich werde das alles mal durchgehen und versuchen die Tips umzusetzen.

**Comment by saenglert** [comment]
Bevor ichs wieder vergesse, die Seite hat ein paar Tutorials zum Thema Spiele und Mechaniken in TypeScript:
http://www.typescriptgames.com/BasicCollisionDetection.html

**Comment by LisaMei** [comment]
Cool gucke ich mir an :)
