### ISSUE TITLE
Hilfe! Mein "display:none" will nicht wirken.

### ISSUE THREAD

**Issue by JanettStuewe** [JirkaDellOro/EIA2#66]
Hallo,

Mein Ziel:
Ich möchte je nach Ergebnis (ob es richtig, falsch oder keine Ziffer ist) ein andres Bild im HTML Dokument zeigen nach dem schließen der Alert-Ausgabe.

Mein Problem:
Allerdings werden immer alle 3 Bilder angezeigt und und die Alert-Ausgabe wird auch nicht mehr nach dem beantoworten der Rechenaufgabe ausgegeben, seit dort "....style.display = "block"; " drin steht.

-Link zu meinem Github der Abschlussaufgabe:
[https://github.com/JanettStuewe/EIA2/tree/master/Abschlussaufgabe](url) 
-Link zur Ansicht meiner Abschlussaufgabe:
[https://janettstuewe.github.io/EIA2/Abschlussaufgabe/Abschlussaufgabe.html](url)

Liebe Grüße :)

**Comment by saenglert** [comment]
Hallo Janett,
Ich gehe jetzt einfach mal der Reihe nach durch, was mir bei dir aufgefallen ist. Meine übliche Prosa kann ich hier leider nicht anwenden, da es einfach zu viele Sachen sind :/

HTML: Im `<meta>` Tag deiner html Datei hast du 2x ein `charset` definiert. Erlaubt ist max. eines.

CSS: Deine css Datei enthält mehrere Schreibfehler und u.a. ist deine Klasse falsch geschrieben, weswegen die Bilder nicht ausgeblendet werden

JS Allgemein: Zahlen rundet man einfach mit `Math.round()`. Das casten nach `String`, dann abschneiden und wieder zurückcasten ist unnötig aufwendig und fehleranfällig.

`Cookies`: Du übergibst Werte als Position und überschreibst diese dann sofort wieder mit einer Funktion die Zufallswerte auswürfelt. Entweder übergebe Zufallswerte und speicher diese oder übergebe gar keine und nutze die Funktion.

`Cookie.draw`: Mit ist nicht ganz klar, warum deine `draw` Funktion als Parameter einen `Cookie` benötigt. Sie ist Teil eines `Cookies` und hat damit Zugriff auf alle Informationen.

Bilder: Du versuchst im TS-Code deine Bilder in Variablen abzulegen, aber das schlägt durch die Bank weg fehl, bzw. die Inhalte der Variablen sind `undefined`. Überleg dir bitte ab wann die Bilder überhaupt zur Verfügung stehen.

`prompt`: Die `prompt` Funktion liefert dir als Rückgabewert einen `string`. Nämlich die Zeichenkette, die der User über die Tastatur eingibt.

`getElementById`: Die Funktion liefert dir ein einzelnes Elememt, da auch nur ein einzelnes Element eine Id haben kann. Entsprechend gibt es an dieser Stelle kein Array auf das du mit `[0]` zugreifen kannst.

**Comment by JanettStuewe** [comment]
Ich habe deine Tipps alle umgesetzt, nur ist mir nicht klar wieso, dass mit den Bildern in eine Variable nicht geht (https://wiki.selfhtml.org/wiki/JavaScript/DOM/Document/images - hier steht das es geht oder meinst du ich sollte sie lieber erstellen mit ts?) und wenn es nicht geht, wie man es sonst machen soll. Ich entschuldige mich, dass ich deinen vermutlich für jeden verständlichen Rat nicht verstehe >.<

Und das mit prompt funktionierte doch soweit, bevor ich halt das image mit rein nahm, wieso hast du das erwähnt?

Und mein zweites Problem hat nach dem entfernen **[0]** nun eine neue Fehlermeldung:
**let canvasEins: HTMLCanvasElement;
        canvasEins = document.getElementById("richtigesErgebnis");**

-> mit der Fehlermeldung: **Type 'HTMLElement' is not assignable to type 'HTMLCanvasElement'.
  Property 'height' is missing in type 'HTMLElement'.**
Als HTMLElement kann ich es aber nicht speichern, dann gilt **getContext** wieder nicht für diesen Typ.

**Comment by saenglert** [comment]
Es geht dabei nicht darum wie du sie in JS/TS ablegst, sondern ab wann du überhaupt auf die Frage "Welches Element hat die ID Salat?" eine korrekte Antwort bekommen kannst. 

Thema prompt: 
a) Weil du eigentlich den TSLinter mit der vordefinierten Konfigurationsdatei von Herrn Dell'Oro anhaben solltest, der dir verbietet den `any` Type zu verwenden. Starke Typisierung ist u.a. einer der  Hauptgründe warum in EIA I/II in TypeScript und nicht reinem JavaScript verwendet wird.
b) Dein Kommentar `//eigentlich number, aber prompt spackt sonst rum`. Der prompt spacket nicht rum, du hast nur keine Ahnung wie er funktioniert, was relativ traurig ist, da er mehrmals in den Aufgaben vorkam. Deswegen, der kurze Primer was eigentlich passiert. 

```
let canvasEins: HTMLCanvasElement;
canvasEins = document.getElementById("richtigesErgebnis");
```
Eclipse liefert dir standardmäßig eigentlich automatisch Informationen über Standard JavaScript Funktionen und zeigt dir z.B. den Rückgabewert an, der im Fall von `getElementById` vom Typ `HTMLElement` ist. Die Variable `canvasEins` ist jedoch als vom Typ `HTMLCanvasElement`, welcher mehr Informationen enthält (wie z.B. height, was dir Eclipse anzeigt). Wenn wir uns, wie in diesem Fall, ganz sicher sind, dass das Element das wir hier erhalten auch vom gesuchten Typ ist können wir das Programm anweisen es auch als einen solchen zu betrachen, in dem wir es typecasten:
```
let canvasEins: HTMLCanvasElement;
canvasEins = <HTMLCanvasElement>document.getElementById("richtigesErgebnis");
```
