### ISSUE TITLE
bei setIntervall verschwinden gezeichnete Objekte

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#67]
Beim erstellen neuer Objekte, wird sobald ich ein setInterval hinzufüge(um sie zeitversetzt erscheinen zu lassen) keine Dinge mehr gezeichnet. Lt. Konsolenausgabe wird zwar ein Objekt erstellt aber es gibt mir in der animate Funktion einen Fehler aus das die Variable b undefined sei. komischerweise habe ich diesen Fehler davor nie bekommen. Kann mir da jemand helfen?
https://github.com/aliciaburger/EIA2/blob/master/Aufgabe%2012/main.ts
https://aliciaburger.github.io/EIA2/Aufgabe%2012/start.html

**Comment by saenglert** [comment]
Hallo Alicia,
dein Problem besteht eigentlich aus zwei Problemen. Ich habe dir einen Pullrequest mit meiner Version erstellt.

Zum einen wird dein for-loop in der `animate` Funktion immer 10x ausgeführt, egal wie viele `Things` existieren. Wichtig ist hier also den Loop nur so oft auszuführen wie es `Things` gibt.

Zweitens hast du einen Fehler in der Abfolge deiner Operationen in der anonymen Funktion innerhalb von setInterval. Kurzes Zwischenspiel: Auch hier brauchst du keine anonyme Funktion, wie du in meiner Änderung sehen kannst. Das größere Problem ist, dass du in der Funktion im Interval zu aller erst `j` um eins erhößt und somit der erste Index im Array `things` 1 ist und nicht 0. Da Standardarrays nicht assioziative sind, müssen die Indeces durchgängig erstellt werden. Das Ende vom Lied ist, dass wenn du dein erstes `Thing` erstellst und ins Array einfügst du gleich zwei Indeces im Array besetzt `[ null, Thing{}]`. Wird jetzt in der `animate` auf den Index 0 zugegriffen wird an der stelle natürlich kein `Thing` gefunden und der Aufruf `b.update()` schlägt natürlich fehlt.

**Comment by aliciaburger** [comment]
Ah vielen vielen Dank! Jetzt gibt das endlich Sinn...
