### ISSUE TITLE
Gemaltem Objekt im Canvas EventListener anhängen?

### ISSUE THREAD

**Issue by wuerstle** [JirkaDellOro/EIA2#68]
Ich würde gerne einem gemalten Tier im Canvas ein EventListener anhängen. Ist das möglich?
Ich habe schon versucht im Internet was zu finden, bin aber leider nicht fündig geworden.

Hier der Link zu meiner Abschlussaufgabe: 
https://wuerstle.github.io/EIA2/Abschlussaufgabe/start.html

Danke schonmal :)

**Comment by saenglert** [comment]
Hallo Lisa,
grundsätzlich ist das umsetzbar, aber das geht etwas aus dem Umfang der Veranstaltung raus.

Bisher haben wir ja nur Eventlistener an vorgefertigte Elemente angehängt (divs, inputs oder das XMLHttpRequest Objekt), für eigene Objekte müssen wir dann definiere, was es für Events gibt, wann sie ausgelöst werden etc. etc..

Was hast du denn vor? Dann kann man sich sicherlich eine Alternative  finden.

**Comment by wuerstle** [comment]
Hi Sascha, 

Ich wollte ein kleines Lern-Interface machen. Mein Ziel war es verschienden Lebewesen im Meer einen EventListener anzuhängen dass wen man auf das Tier klickt, sich ein kleiner Info Text öffnet.

**Comment by saenglert** [comment]
Dann würde ich dir folgende CanvasContext Methode ans Herz legen:
[context.isPointInPath(x, y)](https://www.w3schools.com/tags/canvas_ispointinpath.asp)

Mein Gedanke wäre jetzt, du legst einen Click-Eventlistener auf das Canvas. Jedesmal wenn der User klickt, wird die Liste/Array aller anklickbaren Elemente auf dem Canvas durchgegangen und jedem Element wird die Info übergeben wo hingeklickt und es soll dann antworten mit `Ja, ich wurde geklickt` oder `Nein, daneben`. Wird ja zurückgegeben, kannst du die entsprechende Info einblenden.

**Comment by wuerstle** [comment]
Ok aber wird das nicht kompliziert, da sich bei jedem mal Browser neu laden die Tiere wo anders befinden?

**Comment by saenglert** [comment]
Das Prinzip bleibt jedes mal das gleiche, nur die tatsächlichen Werte ändern sich.

Denk mal zurück die Bienen, die zu den Blumen geflogen sind. Die hatten wir ja auch so programmiert, dass es egal war wo die Biene schlussendlich hingeflogen ist, wir haben nur das Ziel angegeben (das zufällig war).

**Comment by wuerstle** [comment]
Ok ja das habe ich verstanden, ich stehe nur voll auf dem Schlauch wo genau ich die Methode context.isPointInPath(x, y) in meinem Code unterbringen soll.

**Comment by wuerstle** [comment]
Wenn ich das hier versuche wird mir überall falsch angezeigt, auch wenn ich auf den Seestern klicke.
function onClick(_event: Event): void {
        for (let i: number = 0; i < StarFish.length; i++) {
            console.log(context.isPointInPath(this.x, this.y));
        } 
    }

Meine Aufgabe: https://github.com/wuerstle/EIA2/tree/master/Abschlussaufgabe

**Comment by JirkaDellOro** [comment]
Achtung Sascha, ich antworte gerade...

**Comment by JirkaDellOro** [comment]
isPointInPath bezieht sich auf den zuletzt angelegten Pfad, also wahrscheinlich auf das Objekt was vor dem Test zuletzt gezeichnet wurde. Sascha dagegen schrieb:

" und jedem Element wird die Info übergeben wo hingeklickt und es soll dann antworten mit Ja, ich wurde geklickt oder Nein, daneben. "

Das heißt, dass eine Methode in der Klasse der Elemente implementiert werden soll, die dann prüft, ob das Element getroffen wurde. Für das erste würde ich einfach die übergebene Position mit der Position des Elements vergleichen und bei "Nähe" ein true zurück geben. Das ist möglicherweise zunächst intuitiver als isPointInPath

**Comment by saenglert** [comment]
Gegenargument:
Es ist ebenfalls sehr einfach nochmal den selben Pfad zu ziehen wie und im Anschluss bei mit isPointInPath zu überprüfen ob der übergebene Punkt in diesem Pfad liegt. Außerdem es so sehr einfach die Form des Objekts mit einzubrechnen. "Manuell" wäre nur eine Kreisfläche leicht abzubilden.
```
isClickedOn(_x, _y): boolen {
    context.openPath();
    ...
    context.closePath();
    return context.isPointInPath(_x, _y);
}
```

**Comment by JirkaDellOro** [comment]
Richtig, aber es ist ein neues Konstrukt, dass man erstmal begreifen muss. Die Toleranzprüfung ist wahrscheinlich gerade intuitiver, wie ich sagte.

**Comment by wuerstle** [comment]
Ok danke für die Antworten. Muss die Interaktion denn mit dem Canvas sein? Weil ich hatte noch die Idee unter dem Canvas kleine Bildchen der Tiere anzubringen und bei einem Klick auf diese einen info text erscheinen zu lassen. Wäre das in ordnung?

Ungefähr so: https://wuerstle.github.io/EIA2/Abschlussaufgabe/start.html
Ist jedoch noch nicht fertig.

**Comment by JirkaDellOro** [comment]
Canvas und HTML-Elemente sollten nicht zwei unabhängig Bereiche sein. Gerne kann z.B. bei Klick auf ein Tier im Canvas ein HTML-Element beschrieben werden oder umgekehrt.
