### ISSUE TITLE
Manche Canvas-Objekte updaten und andere stehen lassen?

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#69]
Hallo,

Die Bricks in meinem Spiel sollen verschwinden, wenn der Ball sie trifft. Jetzt habe ich das Problem, dass ich die Bricks zeichnen lasse und zwischendurch clear canvas verwende, um die Spuren der alten Ballpositionen zu löschen. Ich habe erst mit save image data gearbeitet, aber dann kann ich die Bricks nicht so einfach verschwinden lassen... Wenn ich sie aber in der set interval funktion versuche zu zeichnen, werden sie nicht angezeigt. Ich habe ein Array mit allen Bricks, den ich mit einer For-Schleife ablaufen wollte. Wenn man die Bricks im Intervall immer wieder neu zeichnen würde, müsste es ja eigentlich funktionieren oder? Oder macht es Sinn verschiedene Intervalle zu setzen?

Leider kann ich den aktuellen Code nicht hochladen, da ich auf einen anderen Computer ausweichen musste. Ich hoffe ich konnte das Problem einigermaßen beschreiben. Die TS Dateien wurden hochgepushed, aber leider sind die anderen Files aus irgendeinem Grund nicht aktuell. Ich arbeite daran.

https://github.com/LisaMei/EIA2/tree/master/Final%20Project

**Comment by saenglert** [comment]
Hallo Lisa,
über die anonymen und geschachtelten Funktionen haben wir uns ja bereits unterhalten ... *haarerauf*

Im Großen und Ganzen würde ich das Problem so angehen wie wir sämtliche Bienenaufgaben angegangen sind: Eine init Funktion, die alles erledigt was vor der Animation passieren muss und die dann eine animate Funktion aufruft, die sich darum kümmert alle animierten Objekte darzustellen und sich immer wieder selbst aufruft (btw: Warum verwendet auf einmal eigentlich jeder Intervalle statt Timeouts?). Diese animierten Objekte könnten dann z.B. in einem Array abgelegt sein. Und wenn das Element nicht mehr dargestellt werden soll löscht du es aus dem Array einfach heraus.

**Comment by LisaMei** [comment]
Ist schon nicht mehr verschachtelt aber noch nicht hochgeladen sorry:D. Müsste das mit dem Array dann nicht auch genau so gut mit der set Interval funktionieren? Also mit dem bricks Array und put image data? Ich werde das mal ausprobieren. Als ich das mit Timeouts gemacht habe, hat nicht mehr alles funktioniert, aber ich bleibe dran.

**Comment by LisaMei** [comment]
Hi, ich schon wieder...

Ich habe jetzt soweit alles verändert und timeouts eingebaut. Leider komme ich nicht mehr weiter. Ich habe versucht zu prüfen, ob ein brick getroffen wurde, oder nicht. Der boolean active ist je nach dem dann true oder false. Ich habe einen Arrray, aus dem dann die getroffenen bricks mit splice entfernt werden sollen. Irgendwas geht aber schief. Jetzt werden nur noch 3 statt 20 bricks gezeichnet. Im array sind aber tatsächlich 20, das heißt irgendwas geht mit meiner if Bedingung schief glaube ich.
Ich möchte in der animate den aktuellen Inhalt des arrays immer wieder zeichnen lassen.

Danke schonmal:)

https://lisamei.github.io/EIA2/FinalProject2/start.html

**Comment by JirkaDellOro** [comment]
Im Debugger einen Breakpoint z.B. auf Zeile 37 setzen, dann erkennt man gleich, dass die Schleife 20 mal durchlaufen wird und also auch 20 Bricks erzeugt werden. Die werden aber offensichtlich übereinander gemalt, weil der Algorithmus derzeit nur 3 Positionen ausspuckt...

**Comment by LisaMei** [comment]
Danke. Ich hatte versehentlich etwas an der Schleife verändert. Jetzt platziert es die Steine wieder richtig. Jedoch klappt das leider nur, wenn ich save image data verwende. Ich bekomme es nicht hin, die Steine aus dem Array immer wieder zeichnen zu lassen und die getroffenen zu löschen...

**Comment by JirkaDellOro** [comment]
Ach herrje, jetzt sehe ich noch etwas. Es wird tatsächlich nur ein Brick erzeugt, der durch die Gegend geschoben und immer wieder gezeichnet. Im Array stehen 20 Referenzen auf denselben Brick

**Comment by LisaMei** [comment]
Oh mist. Aber wenn ich die Objekte in der Schleife erzeuge, zeigt er nur noch einen an.

**Comment by JirkaDellOro** [comment]
Die Erzeugung eines Bricks muss natürlich auch in die Schleife!

Dann sollten auch besser zuerst die Positionen berechnet und dann die Bricks mit diesen erzeugt werden, hierzu wurde wohl auch einst der Constructor erschaffen. Hätte man das konsequent genutzt, wäre das Problem gar nicht erst zustande gekommen.

**Comment by JirkaDellOro** [comment]
Aufräumen!

Eine Funktion zur Erzeugung der Bricks, eine zum Zeichnen der Bricks im Array.

Erstere wird von init() aus aufgerufen, die andere in animate(). Dann sollte alles klar und einfach werden.

Den Hintergrund zu speichern sollte man sich sparen, sofern der keine komplexe grafische Erzeugung erfährt.

**Comment by LisaMei** [comment]
Danke! Ich verstehe. Das hat echt keinen Sinn ergeben, wie ich die Position übergeben habe.  Ich arbeite daran.

**Comment by LisaMei** [comment]
Hi,
ich arbeite schon die ganze Zeit an einem vernünfigen Weg um herauszubekommen, ob ein Stein getroffen wurde. Jetzt habe ich eine ziemlich komplizierte Abfrage gebaut, die ich später auch für den Spieler also den Balken benutzen möchte. Ich bekomme es aber nicht hin, dass wirklich nur einzelne Steine verschwinden. Manche Steine werden einzeln gelöscht, aber meistens verschwinden ganze Reihen. Ich verstehe nicht ganz warum. Ich vermute es liegt an der Funktion createBrickField mit der ich den Bricks Array fülle, aber ich komme auf keine Lösung. 
Wenn Einträge mit splice gelöscht werden, verändern sich dann die Indexzahlen der übrigen Einträge? Wäre es sonst vielleicht sinvoll mit tables zu arbeiten, um das brickField aufzubauen?

Danke im Voraus:)

**Comment by JirkaDellOro** [comment]
Ja, beim Splice rutschen die restlichen Element auf, bzw. werden verschoben. Das Problem ist aber eher der zweite Splice-Parameter. Nochmal in der Doku schauen, z.B. hier:

https://wiki.selfhtml.org/wiki/JavaScript/Objekte/Array/splice

**Comment by JirkaDellOro** [comment]
Ansonsten schon super gemacht, das ist keine triviale Aufgabe!

**Comment by LisaMei** [comment]
Okay danke! Ich versuche das mit dem splice zu reparieren.

**Comment by LisaMei** [comment]
Klappt :)
