### ISSUE TITLE
Aufgabenstellung Aufgabe 2

### ISSUE THREAD

**Issue by hejSalome** [JirkaDellOro/EIA2#7]
Hallo! 
Bei der aktuellen Aufgabe muss sowohl das Schachbrett durch einen Code in JS aufgebaut werden als auch die Reiskörner - Zunahme oder kann das Schachbrett auch mit CSS erstellt werden? 

Viele Grüße,
Salome

**Comment by JirkaDellOro** [comment]
Die Erzeugung der Elemente muss in TS/JS geschehen. Ansonsten können und sollten Sie CSS beliebig einsetzen. Ich würde das selbst auch tun, um nicht sämtliches Styling in TS/JS abbilden zu müssen.

**Comment by hejSalome** [comment]
Okey, vielen Dank!
