### ISSUE TITLE
place img into canvas 

### ISSUE THREAD

**Issue by hejSalome** [JirkaDellOro/EIA2#70]
Hallo,

ich versuche gerade mit verschiedenen Methoden ein Bild in den Canvas einzufügen aber keine möchte richtig funktionieren. 

Hier mein Code:

https://github.com/hejSalome/EIA2/blob/master/abschlussaufgabe/aA.ts
https://github.com/hejSalome/EIA2/blob/master/abschlussaufgabe/aA.html
place img into Canvas Option 1 and Option 2 

Vielen Dank! 
Salome

**Comment by hejSalome** [comment]
Ich habe nun statt einem Bild die Box gezeichnet. Nun habe ich aber das Problem dass ich diesem Element keinen EventListener hinzufügen kann.  (ich möchte neue boxen erstellen wenn ich auf die Hauptbox klicke)
Was kann ich hier tun?
https://github.com/hejSalome/EIA2/blob/master/abschlussaufgabe/mb.ts

**Comment by saenglert** [comment]
Laaaaaaangsam, du kannst doch nicht einfach das Thema wechseln, während ich gerade tippe D:

**Comment by saenglert** [comment]
Also zum Thema Bild auf Canvas habe ich erstmal diese beiden Links für dich:

https://www.w3schools.com/tags/canvas_drawimage.asp
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

Soweit ich das sehe verwendest du das auch ganz korrekt in Option 1. Das klappt bei dir nicht?

**Comment by saenglert** [comment]
Zwecks dem zweitem Problem "Wie klicke ich ein Element auf dem Canvas an" solltest du mal in folgendem Issue spicken #68

**Comment by hejSalome** [comment]
okey, vielen Dank!

Ich habe es nun nochmal mit der ersten Methode versucht, das funktioniert soweit. 

Das mit context.isPointInPath(x, y) werde ich nun noch versuchen.
