### ISSUE TITLE
Meine Elemente werden nicht gezeichnet, aber kein Error ausgegeben

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#72]
Wenn ich meinen Canvas betrachten möchte, seh ich nur den "Himmel" der drin ist, um zu sehen ob man überhaupt etwas sieht.
Ich sehe sonst nichts anderes wie das Monster oder die Süßigkeiten und weiß nicht woran es liegt.

https://nadiacredidio.github.io/EIA2/Semesteraufgabe/Basis.htm

**Comment by JirkaDellOro** [comment]
Was war denn los?

**Comment by NadiaCredidio** [comment]
Zwecks Ordentlichkeit hatte ich ein paar der Scripte in einen Ordner gelegt, dadurch hat er die Verbindung verloren und mir diese nicht angezeigt. Nun zeigt er mir das Monster nicht an, aber die Süßigkeiten.

**Comment by JirkaDellOro** [comment]
Ordentlichkeit ist sehr gut und wichtig.

Wo werden denn die Monster erzeugt...?

**Comment by NadiaCredidio** [comment]
Das ist eine gute Frage. Ich habe eben nur ein Monster, das einfach auf dem Canvas erscheinen soll, da es sich später von dort aus bewegt. Ich bekomme es jedoch nie zu Gesicht, egal wie ich es probiere.

Wenn ich versuche es in die Init zu schreiben, erscheint nichts anderes mehr, da es sich dort aufhängt.

**Comment by JirkaDellOro** [comment]
Hmm...

**Comment by JirkaDellOro** [comment]
Du legst ein Monster-Array an, scheinst also offensichtlich zu planen, mehr als ein Monster im Spiel zu haben. Die Funktion drawMonster würde tatsächlich eine Instanz der Monsterklasse erschaffen und im Array speichern, sie wird aber nie aufgerufen. Ich wüsste jetzt gar nicht, warum ein Monster erscheinen können sollte...

**Comment by NadiaCredidio** [comment]
Sie ist nun aufgerufen.
