### ISSUE TITLE
Ich habe 4 Fehler in meinem Code die ich nicht gelöst bekomme

### ISSUE THREAD

**Issue by SelinaMaz** [JirkaDellOro/EIA2#73]
Hallo,

ich möchte einen Canvas machen in dem sich viele Kreise bewegen und wenn man mit der Maus über die Kreise fährt sollen diese ihre Größe verändern. Momentan sieht man leider noch nichts aber ich hoffe, dass man etwas sieht wenn ich die Lösung zu meinen Errors habe.

Das ist der Link zu meinen Dateien. Die Fehler sind in der main.ts und in der circle.ts
[https://github.com/SelinaMaz/EIA2/tree/master/Abschluss](url)

vielen Dank schonmal für die Hilfe.
Viele Grüße,
Selina Mazzaro

**Comment by JirkaDellOro** [comment]
Der Link ist kaputt

**Comment by JirkaDellOro** [comment]
Welcher Art sind die Fehler, Laufzeit oder Entwicklungszeit?

**Comment by JirkaDellOro** [comment]
In circle.ts
            this.color = colorArray[Math.floor[Math.random() * colorArray.length]];
-> falscher Klammertyp für die floor-Methode

**Comment by JirkaDellOro** [comment]
````
    export var mouse = {
        x: undefined,
        y: undefined
    };
````
"undefined" ist kein Typ. So haben wir im übrigen auch nicht die Programmierung solcher Strukturen gelernt. Bitte ein Interface implementieren!

**Comment by JirkaDellOro** [comment]
In main.ts

        circleArray.push(new Circle(x, y, dx, dy, radius, color));

da heißt es, er kann color nicht finden. Ich auch nicht...

**Comment by SelinaMaz** [comment]
Ja der Link geht irgendwie nicht ich weis auch nicht wieso...
Ok danke ich probiers gleich aus :)

**Comment by SelinaMaz** [comment]
Ok die Fehler sind in der Entwicklungszeit gelöst, aber jetzt hab ich Fehler in der Laufzeit also in der Konsole gitbt es TypeErrors

**Comment by JirkaDellOro** [comment]
Räume mal deine main.ts ein bißchen auf und bringe alle Zeilen, die sofort, also noch beim Laden der HTML-Seite ausgeführt werden, nach oben. Darunter ordnest Du die Funktionen an. Dann sollte schon klar werden, warum das mit canvas nicht klappt.

Und mouse hast Du zwar deklariert, TypeScript ist also bekannt, von welchem Typ die Variable sein soll, sie wird aber nicht erzeugt. Deswegen kann man auch nichts reinschreiben. Weise ihr also zu Beginn ein passendes assoziatives Array zu mit dem Startwert 0 für x und y

**Comment by SelinaMaz** [comment]
ok

**Comment by SelinaMaz** [comment]
...Ich habs schlimmer gemacht :D da tut sich gar nichts mehr. Und mouse ist weiterhin undefined.

**Comment by JirkaDellOro** [comment]
Ok, ich guck

**Comment by JirkaDellOro** [comment]
In der Tat, Du hast es schlimmer gemacht. Wo willst Du hiermit hin?
```` export var mouseArray: number[] = [];````

Schau nochmal nach, Wie definiert man die Werte in einem assoziativen Array? Findest Du z.B. in unserer ersten StudiVZ-Aufgabe

**Comment by SelinaMaz** [comment]
ok

**Comment by SelinaMaz** [comment]
Ich versteh nicht warum es die Kreise nicht malt obwohl alle Daten dafür da sein sollten..
Und den Part mit der Maus hab ich auch noch nicht geklärt.. 🙈

**Comment by SelinaMaz** [comment]
achso ja, es zeichnet nicht weil die update function wegen den Mausdaten nicht geht 🙈

**Comment by JirkaDellOro** [comment]
Ein assoziatives Array definieren wir so zum Beispiel:
````
.... = { a: "Hallo", b: 123 }
````

**Comment by SelinaMaz** [comment]
Ok jetzt tut sich was. Zwar noch nicht das was ich vor habe aber immerhin etwas.

**Comment by SelinaMaz** [comment]
Herr Dell'Oro, wissen Sie vielleicht warum meine Punkte jetzt flackern statt sich einfach nur zu bewegen?
Villeicht hat es was mit der Reihenfolge in meinem Code zu tun, aber eigentlich ergibt es so für mich Sinn.

**Comment by JirkaDellOro** [comment]
Noch nicht, aber ich schau mal nach

**Comment by JirkaDellOro** [comment]
Ja, doch, ich weiß es, denke ich. Aber ich frage lieber nach:

Warum erhält die update-Methode der Circles Parameter vom Hauptprogramm? Sollten die Circles nicht mit ihren eigenen Eigenschaften arbeiten?

**Comment by SelinaMaz** [comment]
Stimmt eigentlich sollten sie das schon.

**Comment by SelinaMaz** [comment]
Aber haben wir das mit den Bienen nicht auch so gemacht ? Also die Parameter sind da auch im Hauptprogramm erst festgelegt worden.

**Comment by SelinaMaz** [comment]
ok ich habs verstanden und verbessert es läuft jetzt so wie ich es wollte 😃

**Comment by JirkaDellOro** [comment]
Super! Und selbst durchgehirnt!!

**Comment by SelinaMaz** [comment]
Hallo :)
Wissen Sie vielleicht warum GlowCircle kein constructor ist?
Ich versteh den Error nicht wirklich.

Und die Mauskoordinaten stimmen nicht wirklich überein. 😅  Da muss ich nochmal schauen woran das liegt. Ich hab da einiges ausprobiert aber ohne Erfolg.

**Comment by JirkaDellOro** [comment]
Ohne nachzuschauen: vielleicht in der HTML-Datei ein neues Skript nicht verlinkt?

**Comment by JirkaDellOro** [comment]
Nachgeschaut: genau!

**Comment by SelinaMaz** [comment]
ahja stimmt was für ein Anfängerfehler :D

**Comment by JirkaDellOro** [comment]
Passiert auch mir immer wieder... ;-)
