### ISSUE TITLE
Monster bewegt sich nicht

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#74]
Eigentlich müsste das Monster in der Klasse alle Informationen haben, um sich bewegen zu können. Demnach habe ich etwas vergessen. Vllt die Aufforderung in der Basis ts? Aber ich wüsste nicht mehr wie ich es aufrufe.

https://nadiacredidio.github.io/EIA2/Semesteraufgabe/Basis.htm 

https://github.com/NadiaCredidio/EIA2/blob/master/GetTheCandy-Semesteraufgabe/Monster-Script.ts

**Comment by JirkaDellOro** [comment]
Der Link zur Runtime-App ist kaputt

**Comment by JirkaDellOro** [comment]
Es wird offensichtlich ein Monster kreiert, aber Breakpoints im Debugger bei move oder update werden nicht angelaufen. Offensichtlich sagt niemand dem Monster, dass es etwas tun soll. Einfach in unseren Bienenaufgaben nachschauen...
