### ISSUE TITLE
Canvas-Objekte drag & drop

### ISSUE THREAD

**Issue by ValentineDe** [JirkaDellOro/EIA2#75]
Hallo und guten Abend,

für meine Abschlussaufgabe möchte ich gerne verschiedene Schafe (im Code noch Wattebäuschchen) die durcheinander geraten sind wieder sortieren und in die richtigen Gehege bringen. Dafür würde ich die einzelnen Schafe gerne nehmen und sie ins richtige Gehege setzten können.  Leider bin ich bei meiner Recherche nicht wirklich schlauer geworden und habe höchstens Code für einfache Objekte wie zb. Rechtecke gefunden, der bei mir aber trotzdem nicht recht funktioniert hat. Jetzt weiß ich nicht ob das für selbst gezeichnete Tiere überhaupt funktioniert oder ob das nicht einfach viel zu kompliziert wird.... :/  Ursprünglich wollte ich die Schafe mit dem Cursor anschupsen/treiben bis sie am richtigen Platz sind, aber da bin ich auch nicht weiter gekommen und ziemlich ratlos. Deshalb auch der MousePositionTracker. Kann mir da jemand bitte bitte bitte weiterhelfen???

**Comment by ValentineDe** [comment]
Ach ja hier der Link: https://github.com/ValentineDe/EIA2/tree/master/abschlussarbeit

**Comment by JirkaDellOro** [comment]
Hallo Valentine,

es ist nicht ganz trivial, aber es gibt eine Möglichkeit, das sehr zu vereinfachen. 

- Führe eine Variable ein, welche eine Referenz auf ein Objekt halten kann und setze die Position dieses Objektes in der Animationsfunktion auf die Mausposition (+ggf einen konstanten Versatz)
- Das Funktioniert natürlich nur, wenn die Variable auch eine Referenz enthält. Ist dies nicht so, sollte sie den vordefinierten Wert null haben und Du überspringst das Mitführen der Position.
- Klickt man nun auf ein Schaf, soll die Variable die Referenz auf das angeklickte Schaf erhalten. Sofern Du die Referenzen auf die Schafe in einem Array verwaltest, löschst Du es da raus
- Somit hängt das Schaf an der Maus.
- Klickt man nun woanders hin und es soll etwas mit dem Schaf an der Maus passieren, kannst Du dir anschauen ob und welche Art Schaf am Cursor hängt und entsprechend reagieren.
- Soll so ein Schaf in ein anderes Array eingefügt werden, kann man die Referenz einfach dort reinsplicen und die Referenzvariable am Mauscursor wieder auf null setzen.

PS: mit null meine ich nicht die Zahl 0 sondern die Buchstabenfolge null. Das ist ein reserviertes Wort für eine undefinierte Referenz
