### ISSUE TITLE
drawImage funktioniert nicht.

### ISSUE THREAD

**Issue by braundominik** [JirkaDellOro/EIA2#76]
Hallo,
ich habe folgendes Problem.  Folgenden Code benutze ich um Image Dateien auf mein Canvas zu zeichnen.

```
        let img: HTMLImageElement;
        img = document.createElement("img");
        img.src = "bild.gif";
        crc.drawImage(x, y);
```

Hier funktioniert das wunderbar:
https://github.com/braundominik/EIA2/blob/master/SFD/Minion.ts
https://github.com/braundominik/EIA2/blob/master/SFD/Sword.ts

In meiner main.ts funktioniert dies jedoch nicht:
https://github.com/braundominik/EIA2/blob/master/SFD/main.ts

Ich rufe hier in der init Funktion die Funktion "buildBackground" auf, welche das Bild laden sollte. Das Bild wird jedoch nicht angezeigt. Ich weiß leider nicht warum.

Link zur gesamten Aufgabe: https://github.com/braundominik/EIA2/tree/master/SFD
Link zur Ansicht: https://braundominik.github.io/EIA2/SFD/main.html

**Comment by saenglert** [comment]
Wenn du die Quelle eines Bildes definierst (also das src Attribute setzt), ist diese Bilddatei nicht sofort verfügbar, sondern muss erst geladen werden. Das passiert in einem asynchronen Prozess, den dein Browser im Hintergrund für dich erledigt. Wenn du in der Zwischenzeit versuchst auf die Bildinformation zuzugreifen, wird dein Browser natürlich keine Information liefern können, entsprechend ist nichts zu sehen.

**Comment by braundominik** [comment]
Ok also ich habe jetzt versucht, dass Bild zu zeichnen und dann mittels callback den Rest des Codes auszuführen aber das scheint auch nicht zu funktionieren.
Wie wäre denn das am besten zu lösen ?

**Comment by braundominik** [comment]
Ok es geht jetzt rufe erst die background funktion auf füge dann einen load Event Listener an das Image und rufe dann eine Funktion mit dem weiteren Vorgehen auf.
Auf Firefox funktioniert es auf Chrome bekomme ich jedoch folgenden Fehler:
`Access to Image at 'file:///C:/Users/Dominik/git/EIA2/SFD/background.jpg' from origin 'null' has been blocked by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.`

**Comment by saenglert** [comment]
Da sind wir jetzt wieder im Bereich des `Cross Origin Resource Sharings`, was wir ja schon mit dem XMLHttpRequest Objekt angesprochen hatten.

Ich würde dir empfehlen, packe alle Bilder die du brauchst in einen festen img Tag im HTML und gib denen eine CSS Klasse die du konstant mit `display: none` ausblendest. Anschließend müsstest du die Bildinformation trotzdem per JS nutzen können. Das hat außerdem den Vorteil, dass du die asynchrone Event Funktion vermeiden kannst und alles wie gehabt von oben nach unten abläuft.

**Comment by JirkaDellOro** [comment]
Ich schließe mich Saschas Empfehlung an. Dabei ist darauf zu achten, dass die ganze Chose erst bei "load" anläuft, nicht schon bei "DomContentLoaded"
