### ISSUE TITLE
Probleme mit der Animation

### ISSUE THREAD

**Issue by wuerstle** [JirkaDellOro/EIA2#77]
Hallo,

ich hätte gerne das wenn ich unten auf ein Bild klicke, im Canvas ein neues Tier erscheint. Bei den Bakterien funktioniert das auch, bei dem Seestern und dem Fisch jedoch nicht. 
Wenn ich jetzt auf einen Seestern klicke, wird zwar ein neuer gemalt, jedoch verschwindet dieser wieder. Ich denke es liegt an der animate funktion, bin aber noch nicht drauf gekommen woran genau.

https://wuerstle.github.io/EIA2/Abschlussaufgabe/start.html
https://github.com/wuerstle/EIA2/tree/master/Abschlussaufgabe

**Comment by saenglert** [comment]
Hallo Lisa,
das Problem liegt bei deinen `add[Tier]` Funktionen. Wie du schon sagst, bei den Bakterien funktioniert es ja, von daher vergleiche mal was du bei den anderen beiden Funktion nicht machst.

**Comment by wuerstle** [comment]
Ok ja ich habe den neuen Fisch nicht dem Animal Array hinzugefügt. Aber wenn ich es umänder verschwindet der Fisch trotzdem wieder :(

**Comment by JirkaDellOro** [comment]
Hier ist die Polymorphie noch nicht konsequent eingesetzt
1. es werden am Anfang 15 Instanzen der Klasse Animal erzeugt und Referenzen darauf in des animals-Array gepusht. Animal scheint aber eine "abstrakte" Klasse zu sein, die lediglich als Superklasse für andere auftritt und von der keine Instanzen erzeugt werden sollten.
2. diese Klasse implementiert eine update()-Methode, die eine Methode drawAnimal aufruft. Letztere hat keinen Inhalt, da die Klasse Animal keine Erscheinungsform hat. Die Subklassen implementieren aber keine anderen drawAnimal()-Methoden, weshalb die Methode der Superklasse genutzt wird und folglich nichts gezeichnet wird.

Also statt drawAnimal, drawStarFish, drawLittleFish etc. einfach jeder Klasse eine passende Methode mit dem Namen draw() spendieren. Ein Fisch ist ein Tier und wenn das Tier nun gesagt bekommt, es soll sich zeichnen, wird das Tier draw() aufrufen aber vorher nachschauen, was es denn für ein Tier ist und die hierzu passende draw()-Methode wählen. Heißen die Methoden aber unterschiedlich, funktioniert dieser Mechanismus nicht...

**Comment by saenglert** [comment]
Soooooo, nach genauerer Analyse deines Programmcodes sind mir da ein paar Sachen aufgefallen:

- Verschwindende Tiere
Die verwendest zwar Vererbung und Polymorphy, aber ein kritischer Punkt ist dir nicht geglückt: Das Überschreiben der `drawAnimal` Funktion. Die Funktionen in deinen abgeleiteten Klassen `LittelFish `und `StarFish` heißen jeweils anders. Dementsprechend wenn du in der Schleife deiner `animate` Funktion `drawAnimal` aufrufst, wird nicht wie beabsichtigt die Funktion der Subklasse aufgerufen, sondern die leere Funktion der Superklasse `Animal`. Benne die Funktionen exakt gleich und es funktioniert.

- Unnötige Parameter
Wie schon bei einigen anderen gesehen, übergibst du auch Parameter für die Positionierung an die neuen Objekte, überschreibst diese aber sofort wieder mit einer `setRandomPosition` Funktion. Mach das Eine oder das Andere, beides macht den Code nur schwierig zu lesen.

- Schleife der komischen Sachen
Folgende Schleife musst du mir mal erklären, was du da vor hast, da sich hier mehrere Sachen gedanklich bei mir überschneiden:
```
//StarFish and LittleFish random position 
        for (let z: number = 0; z < 15; z++) {
            let n: number = Math.floor((Math.random() * 3) + 0);
            if (n == 0) {
                let f1: StarFish = new StarFish(x, y);
                f1.setRandomPosition();
                f1.drawStarFish();
            }
            else {
                let f2: LittleFish = new LittleFish(x, y);
                f2.setRandomPosition();
                f2.drawLittleFish();
            }
            animals.push(new Animal(x, y));
        }

        //save background
imgData = context.getImageData(0, 0, canvas.width, canvas.height);
```

Du erstellst neue Objekte deiner zwei Klassen und zeichnest diese auf das Canvas, da im Anschluss gleich über `getImageData` der Hintergrund gespeichert wird, bleiben sie auch sichtbar. Allerdings am Ende der Schleife pushst  du ein neues `Animal` Objekt in dein Array, das allerdings im Anschluss in `animate` nicht dargestellt werden kann, da die `drawAnimal` Funktion leer ist und ja eigentlich nur als Superfunktion für die Funktionen der zwei Subklassen dienen soll.

Erklär mal in deinen Worten, was du da geplant hast, dann biegen wir das schon zurecht.

**Comment by wuerstle** [comment]
Ok :D also..

Das Verschwinden der Tiere ist jetzt kein Problem mehr. Ich habe die draw Funktionen gleich genannt und jetzt werden sie ganz normal gemalt. 

Mit der Schleife wollte ich erreichen dass die Seesterne und Fische an verschiednen Positionen gemalt werden und auch jedes Tier immer unterschiedlich oft.
