### ISSUE TITLE
Ball natürlich abprallen lassen - Collision Handling

### ISSUE THREAD

**Issue by LisaMei** [JirkaDellOro/EIA2#78]
Hallo,
ich habe ein Problem meinen Ball physikalisch korrekt von den Bricks beziehungsweise vom Spielerbalken abprallen zu lassen. Ich habe versucht die Bewegung in der Methode detectCollision zu handlen, aber der Ball ändert beim Abprallen an der oberen und unteren Begrenzung der Bricks nicht nur die y-Richtung, sondern auch die x-Richtung. Ich vermute es liegt daran, dass ich parallel in der move Methode die Richtung verändere, aber ich komme einfach auf keine Lösung, die funktioniert.

Wäre cool, wenn sich das jemand ansehen könnte. Hier ist der Link:
https://lisamei.github.io/EIA2/FinalProject2/start.html

Danke :)

**Comment by JirkaDellOro** [comment]
meiner!

**Comment by JirkaDellOro** [comment]
Die Richtungsänderung in der move-Methode kommt ja nur zustande, wenn der Ball das Spielfeld zu verlassen droht. Übrigens, wenn der Brick-Abpraller gut funktioniert, könnte man mit speziellen Bricks alles abbilden, also auch den Spielfeldrand und den Schläger. Das wäre höchsteffizient.

Zum Problem: es liegt eher an der Abfrage, fürchte ich. Wenn der Ball z.B. von unten kommt und den Brick berührt, ist die vertikale Distanz kleiner als der Ballradius. Da aber testX nicht verändert wurde und den Startwert this.x besitzt, ist die horizontale Distanz sogar 0. Damit sind beide Bedingungen wahr und der Ball wechselt die Richtung in beiden Dimensionen.

Versuch' mal, die Distanzen gegen 0 zu prüfen. Wenn distX den Wert 0 hat, müsste eine vertikale Richtungsänderung angebracht sein, bei distY eine horizontale. Hat keiner den Wert 0, sind wir an einer Ecke, dann ändern wir wohl beide. Das ist nur ein Gedanke, mal sehen ob es klappt.

PS: bei Fließkommazahlen kann die Prüfung gegen 0 aufgrund von Rundungsfehlern fehlschlagen. Da wir aber nur zuweisen, sollte es funktionieren.

**Comment by LisaMei** [comment]
Danke das versuche ich !

**Comment by LisaMei** [comment]
Bei der Zuweisung hatte ich nur einen blöden Dreher, das funktioniert jetzt tatsächlich ganz gut, aber jetzt habe ich ein anderes Problem: 
Wenn der Ball von oben auf einen Brick trifft, prallt er immer noch in die falsche Richtung ab und wenn ich die Methode für den Spielerbalken verwende, passiert das gleiche, wenn der Ball auf seine Oberseite trifft. Ich komme nicht darauf, warum. Eigentlich sollte sich doch nur das Vorzeichen verändern, genau wie, wenn der Ball von unten gegen die Steine fliegt. Ich verstehe nicht, woran das liegen könnte.

**Comment by JirkaDellOro** [comment]
Ist der Code gepusht?

**Comment by LisaMei** [comment]
Ja

**Comment by LisaMei** [comment]
https://lisamei.github.io/EIA2/FinalProject2/start.html

**Comment by JirkaDellOro** [comment]
Ich würde es mal mit der von mir beschriebenen Weise probieren.

**Comment by LisaMei** [comment]
Das habe ich schon, aber leider prallt der Ball dann nicht mehr von allen Steinen ab. Je nachdem , in welchem Winkel er Sie trifft, fliegt er einfach normal weiter und die Steine verschwinden.

**Comment by JirkaDellOro** [comment]
OK, dann schaue ich da jetzt mal genauer rein...

**Comment by JirkaDellOro** [comment]
Erstaunlich, es funktioniert genauso wie ich beschrieben hatte. Du hattest wahrscheinlich einen kleinen Fehler bei der Umsetzung. Setze mal diesen Code ein:
````
    if (dist <= this.radius) {
                if (distX == 0)
                    this.yd *= -1;
                else if (distY == 0)
                    this.xd *= -1;
                else {
                    this.xd *= -1;
                    this.yd *= -1;
                }
                return true;
````
Das *= -1 macht übrigens auch nur den Vorzeichenwechsel, ist für mich aber so klarer zu erkennen, da ich nicht vergleichen muss, was vor und hinter dem Zuweisungsoperator steht.

**Comment by LisaMei** [comment]
Stimmt ich hatte Fehler im Vorzeichenwechsel. Jetzt funktioniert es! Danke für die Hilfe!

**Comment by LisaMei** [comment]
Eine Frage habe ich doch noch. Ich möchte mein brickField mit einem 2D-Array erstellen. Jedoch zeigt mir Eclipse immer einen Fehler an, wenn ich erst einen normalen Array erstelle und ihn dann mit Arrays fülle. Das Problem ist die Typenbezeichnung. Welchen Typ hat mein leerer Array zu Beginn?

Der Plan:

var bricks = [];   hier fehlt der Datentyp
for(let c=0; c<columnNr; c++) {
    bricks[c] = [];
    for(let r=0; r<rowNr; r++) {
        bricks[c][r] = { x: 0, y: 0 };

-neuen Brick erstellen und zeichen-
    }
}

Danke :)

**Comment by moritzhfu** [comment]
Aus der Hüfte geschossen würde ich hier als Datentyp: `var bricks: Brick[][] = [];` vermuten. Bitte mal probieren und berichten.

**Comment by LisaMei** [comment]
Klappt :D danke! Ich hatte anfangs let bricks: Brick[][]=[][]; , deshalb hat es nicht geklappt.

**Comment by moritzhfu** [comment]
Bitte Update beachten. Hatte eine falsche Syntax verwendet. Gerade nochmals getestet.

**Comment by LisaMei** [comment]
Ich habe mir das nochmal angesehen... wenn ich das so wie in dem Code oben mache, also erst einen normalen leeren Array erstelle und ihn dann mit Arrays fülle, funktioniert das so nicht. Eclipse bezieht x und
 y dann nicht auf die Array-Einträge, sondern auf die Eigenschaftn von brick.
Wenn ich einen einzelnen Array erstelle, meckert es aber, weil es vom Typ any ist.

**Comment by JirkaDellOro** [comment]
In deinem Repository liegt eine Kopie meines Codes zu multidimensionalen Arrays. Den müsstest Du als Grundlage hernehmen können.

**Comment by LisaMei** [comment]
Ich habe die ganze Zeit versucht, Ihren Code zu verstehen, aber ich musste mir ja eigentlich nur die Typisierung abgucken. Ich glaube, ich habe es jetzt. Danke :)
