### ISSUE TITLE
Objekte entfernen

### ISSUE THREAD

**Issue by aliciaburger** [JirkaDellOro/EIA2#79]
In meiner Aufgabe hätte ich gerne dass, sobald ein schwarzer Kreis die Position des Weißen Kreises erreicht der Schwarze Kreis vom Canvas verschwindet. Jedoch kriege ich ihn nicht einmal aus dem Array entfernt. 
Glaube ich habe da einen Denkfehler, komme aber nicht drauf.
Anmerkung: der weiße Kreis kann über die grünen Buttons verschoben werden.
https://github.com/aliciaburger/EIA2/blob/master/Aufgabe%2012/main.ts
https://aliciaburger.github.io/EIA2/Aufgabe%2012/start.html

**Comment by JirkaDellOro** [comment]
Meiner

**Comment by JirkaDellOro** [comment]
Ich schätze, dass es schlichtweg eine Frage der Wahrscheinlichkeit. Die schwarzen Kreise bewegen sich mit einer etwas zufälligen Geschwindigkeit, ihre Positionen sind daher wohl ganz krumme Zahlen. Die Wahrscheinlichkeit, dass die Abfrage
````` if (_b.x == f.x && _b.y == f.y) {````
true ergibt, ist daher sehr nahe 0.

Es muss abgefragt werden, ob sich der schwarze Kreis innerhalb eines bestimmten Bereiches befindet.

**Comment by aliciaburger** [comment]
Danke , habe jetzt die spanne vergrößert, jedoch kriege ich jetzt nachdem das Objekt entfernt wurde bei b ein undefined.

**Comment by JirkaDellOro** [comment]
Ich schaue

**Comment by JirkaDellOro** [comment]
das Problem ist, dass neue "Things" nicht ans Ende des Arrays gepusht werden, sondern an einer fortlaufenden Position eingesetzt werden. Wird davor aber etwas herausgespliced, entstehen Löcher...->undefined

Bitte unbedingt den Code aufräumen, er ist sehr unangenehm zu lesen. Da steht Things wo nur eines gemeint ist, Thing hat keine wirkliche Aussage, myFunction auch nicht, es wimmelt noch von Bienen und Blumenwiesen  etc.
So ist er Support schwierig und freudlos...

**Comment by aliciaburger** [comment]
Ah, ja dankeschön! Jetzt klappts 
Ja ich werde den Code noch aufräumen kann noch einiges zusammengefasst werden.
