### ISSUE TITLE
Ordner lokal gelöscht und keine Synchronisation möglich

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#8]
Guten Tag,

ich hab gerade ein paar Probleme bei der Hausarbeit. Das größte ist, dass ich den Ordner der Aufg2 aus versehen lokal gelöscht habe. Ich kann diesen auch nicht erneut aus der Cloud runterladen, da es irgendwie nicht funktioniert. 

Ich wollte mich deshalb nochmal erkundigen wie man es genau macht, damit es funktioniert.

Vielen Dank im voraus,
Nadia

**Comment by saenglert** [comment]
Hallo Nadia,
wenn du versuchst aus dem Github Repository zu pullen gibt dir Eclipse doch sicherlich eine Fehlermeldung aus, oder?

Was steht denn dabei? (Im Zweifelsfall auf "Details" klicken)

Grüße
Sascha

**Comment by moritzhfu** [comment]
Sollte es nur um die Einrichtung der Synchronisation gehen, gibt es eine Kurzanleitung in der Mindmap:
_https://jirkadelloro.github.io/EIA2/EIA2.mm.html_

**Unter:** _Installations_ --> _Git in Eclipse_
