### ISSUE TITLE
Anzeige Canvas

### ISSUE THREAD

**Issue by JacquelineWagner** [JirkaDellOro/EIA2#80]
Hallo,

ich habe ein Problem mit der Anzeige des Canvas auf Handys und Tablets.
Auf iPhones / iPads wird der Canvas überhaupt nicht angezeigt und auf Android-Handys / Tablets auch nicht auf jedem Modell. Kann ich dagegen etwas machen?

Des Weiteren habe ich über den Canvas unsichtbare Buttons auf den See und den Ameisenhaufen gelegt, um diese Objekte klickbar zu machen, jedoch verschieben sich diese Buttons bei der mobilen Ansicht, obwohl ich den Canvas und die Buttons in CSS angepasst habe.
Mir ist auch schon aufgefallen, sobald ich die Buttons sichtbar mache, dann liegen diese bei  der Desktopansicht über dem Canvas, aber auf den Handys unter dem Canvas.
Eine andere Möglichkeit, um auf die gezeichneten Objekte im Canvas zu klicken, habe ich nicht gefunden.

Viele Grüße 
Jacqueline

**Comment by JacquelineWagner** [comment]
Hier noch der Link
https://jacquelinewagner.github.io/EIA2/abschlussaufgabe1/abschlussaufgabe.htm

**Comment by JirkaDellOro** [comment]
Das ist eigentlich eine schöne Idee, mit HTMLButtonElements zu arbeiten, die über dem Canvas liegen. Allerdings hat man dann wieder mit CSS zu tun, und das ist manchmal kniffelig. Da müsste ich auch herumprobieren. Man kann z.B. die z-Order, also die Tiefenebene für ein Element, beeinflussen, das kann das eine Problem vielleicht schonmal lösen. Angezeigt werden sollte der Canvas immer, mit welchen Browsern wurde getestet?

**Comment by JacquelineWagner** [comment]
Ich habe schon versucht die z-Order zu verwenden, jedoch hat das auch nicht funktioniert.
Auf dem iPhone wurde es mit den Browsern Safari, Firefox und Chrome getestet, jedoch haben alle nicht funktioniert. 
Bei den anderen Handys wurde der Browser Chrome verwendet.

**Comment by JirkaDellOro** [comment]
Mir war bislang nichts bekannt, dass die Darstellung auf dem iOS verhindert. Aber vielleicht hat dies etwas damit zu tun?
https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element

Ist schon ein älterer Post, aktuelles konnte ich noch nicht finden

**Comment by JirkaDellOro** [comment]
... aber dein Canvas ist eigentlich ziemlich klein, es würde mich wundern...

**Comment by JacquelineWagner** [comment]
Also der Canvas selbst ist auf dem iPhone zu sehen, jedoch wird dieser leer angezeigt. 
Es sind keine Zeichnungen zu sehen.

**Comment by JirkaDellOro** [comment]
Mach' mal bitte ein winziges neues Projekt, in dem Du nur z.B. ein Rechteck auf dem Canvas darstellst, bzw. deaktiviere (durch Kommentarmarken) den größten Teil deines Codes und stelle etwas primitives dar, bis Du ein Bild hast. Dann kann man von dort aus nach und nach mehr wieder aktivieren, bis man erkennt, ab wann es nicht mehr funktioniert. Dann kennt man den kritischen Teil

**Comment by JacquelineWagner** [comment]
Ich hab das jetzt versucht. Es wird alles angezeigt, wenn die for-Schleife für die drei Ameisen am Anfang auskommentiert ist. Ist diese wieder aktiviert, wird nichts angezeigt.

**Comment by JirkaDellOro** [comment]
Cool, dann haben wir jetzt sogar etwas Fehlersuchstrategie geübt. Mal schauen, ob mir an der Schleife etwas auffällt

**Comment by JirkaDellOro** [comment]
Hmm... ich nehme an, das mit den Honeybees war vorher auch schon auskommentiert und spielt keine Rolle. Das sollte dann ganz raus aus dem Code, für einen Aussenstehenden schafft es nur Verwirrung. Da der Code ja auf andern Geräte zu funktionieren scheint, muss es ein spezifisches Problem mit der Verarbeitung desselben sein. Als nächstes würde ich ausprobieren was passiert, wenn man in der HTML-Datei die main.js als letztes Skript aufruft. Sollte eigentlich keine Rolle spielen, aber....

**Comment by JacquelineWagner** [comment]
Das habe ich jetzt gemacht, aber jetzt erscheinen die Zeichnungen wieder nicht mehr.
Ich lass die Schleife jetzt einfach weg.

**Comment by JirkaDellOro** [comment]
OK
