### ISSUE TITLE
Probleme beim zeichnen und bei der Animation

### ISSUE THREAD

**Issue by MichelleZei** [JirkaDellOro/EIA2#81]
Hallo,

ich hab gleich zwei Fragen und zwar (1) warum zeichnet es mir nicht die UfosRechts und UfosLinks gleichzeitig, sondern immer nur eins von den beiden abhängig davon welche for-Schleife ich in der init-Funktion als erstes stehen hab? (2) Wenn man auf den Canvas geklickt hat und der Klick mit der Position eines Ufos übereinstimmt, soll es runterfallen. Aber des funktioniert nicht ganz. Irgendwie werden die ganzen Ufos um +10 in die y- Richtung verschoben, fliegen dann aber ganz normal weiter. Ich hab da glaube ich einen Denkfehler, aber ich komme nicht drauf an was das liegt.

Hier noch der Link: https://github.com/MichelleZei/EIA2/blob/master/abschlussaufgabe/abschlussaufgabe.html 

Vielen Dank schonmal im Voraus!

**Comment by moritzhfu** [comment]
Ich schaue mal fix.
Für alle anderen habe ich hier mal direkt die Abschlussaufgabe verlinkt:
https://michellezei.github.io/EIA2/abschlussaufgabe/abschlussaufgabe.html

Somit ist es einfacher direkt mit dem Debuger o.ä, zu arbeiten.

**Comment by moritzhfu** [comment]
**Zur Frage (1):** Was mir hier zuerst auffällt. In Zeile 42 & 46 wird jeweils ein UFO erstellt und hierbei ein x- und y-Wert von _undefined_ übergeben. Das ist weiter kein Problem, da Du die eigentlichen x- und y-Werte im Konstruktor des UFOs festlegst. Dass jedoch ein Konstruktor zum Einsatz kommt, der x- und y-Werte entgegennimmt und damit dem Benutzer suggeriert, er könne die Position bei Erzeugung selbstständig festlegen, ist unglücklich.

In Zeile 108 der Update-Methode läuft die for-Schleife gegen den Wert `n`, dieser wird mit dem Wert 5 initialisiert.
`for (let i: number = 0; i < n; i++)`
Dein Array aus UFOs besteht jedoch aus mehr als 5 Objekten die auch alle gezeichnet werden wollen. Hier ist es also günstig mit dem variablen Wert der Arraylänge des UFO-Arrays, in diesem Fall: `ufos.length,` zu arbeiten.

**Zur Frage (2):** 
Zuerst: In Zeile 89 der gleiche Fehler in der for-Schleife. Diese läuft gegen `n`.

Diese Frage ist insgesamt etwas komplizierter. Vom Code her geht das schon in die richtige Denkrichtung. Problem ist hier u.a., dass die Methode falldown mit einem Timeout versehen wird, jedoch die Übergabeparamter der Funktion nach dem Ablaufen des ersten Timeouts verschwunden sind. D.h.
`window.setTimeout(falldown, 20);` liefert hier nicht die benötigten Parameter `_i: number, _u: Ufos` mit.

Ich würde an Deiner Stelle folgenden Denkansatz verfolgen:

- Jedes UFO hat eine boolsche Variable, die den eigenen Treffer-Status beinhaltet.
- In der Move-Methode des UFOs wird diese Variable abgefragt, sofern ich - als UFO - getroffen wurde, verhält sich meine Move-Methode anders. Ich bewege mich nur noch in y-Richtung gen unteren Spielfeldrand. Dies ist bei Dir ja bereits in der fall()-Methode hinterlegt. In der Main.ts setzt Du nur noch den Treffer-Status des UFOs und zählst die Punkte. Um das Fallen kümmert sich jedes UFO selber.
- Für das Aufräumen der abgeschossenen UFOs gibt es mehrere Möglichkeiten. Eine ist z. B.: In der Update-Methode überprüfst du alle UFOs. Wer in y-Richtung das Spielfeld verlassen hat, also wessen y-Position signifikant größer als die Spielfeldgröße ist, wird aus dem UFO-Array gespliced.

**Comment by MichelleZei** [comment]
Okay ich habe es jetzt soweit hinbekommen, aber ich bekomme immer die Meldung "too much recursion". Das Ufo, das angeklickt wurde, verschwindet zwar, aber das ganze Programm stockt und es kommt eben diese Fehlermeldung.

**Comment by moritzhfu** [comment]
Schreibt....

**Comment by MichelleZei** [comment]
Okay aber die Ufos fallen immernoch nicht runter. :(
Und das mit dem "ein Ufo aus dem Array splicen", indem ich das in eine Methode unterbringe, versteh ich nicht ganz.

**Comment by moritzhfu** [comment]
Die UFOs fallen nicht, da du gar keine UFOs ansprichst:

```
 for (let i: number = 0; i < ufos.length; i++) { // gehe das komplette Array mit allen UFOs durch

[...]

            // ob es in der Nähe des Klicks war. Wenn ja, 

            if (Math.abs(diffx) < 60 && Math.abs(diffy) < 60) {
                if (status == false) { // Hier überprüfst du einen globalen Status und nicht den des getroffenen UFOs
                    status = true; // // Hier änderst du einen globalen Status, es soll aber der Status des getroffenen UFOs geändert werden
              
[...]
                }
            }
        }
```

Mit der Methode meinte ich folgendes:

Schreibe eine Methode, die alle UFOs innerhalb des Arrays iteriert und die y-Position gegen den Canvas prüft. Ist die y-Position höher als der Canvas entferne das UFO aus dem Array in dem alle UFOs gehalten werden. 
Installiere diese Methode innerhalb der Update-Methode, so dass diese jeden Frame aufgerufen wird.

Den Code des Methodenrumpfes hattest du bereits innerhalb der setTimeout-Funktion geschrieben.

**Comment by MichelleZei** [comment]
Aber es die fallen auch nicht, wenn ich ein Ufo anspreche.

Okay das mit der Methode hab ich glaub ich verstanden.

**Comment by MichelleZei** [comment]
Ich habs jetzt:)

**Comment by moritzhfu** [comment]
Jetzt sprichst du das UFO an. Nun muss nur noch in der Klasse UFO links & rechts die move-Methode umgebaut werden. 
Diese war vorher bereits korrekt umgebaut jedoch von Dir auskommentiert.
 Z. z. arbeitet das UFO ja gar nicht mit dem Status und überprüft ob es abgeschossen wurde, sondern bewegt sich ständig nur in x-Richtung
