### ISSUE TITLE
neues Objekt erscheint kurz, verschwindet wieder

### ISSUE THREAD

**Issue by JanaBurger** [JirkaDellOro/EIA2#82]
Hallo, 
ich möchte nur, dass (zunächst) bei Klick auf den gesamten Canvas ein neues Flugzeug erscheint und sich bewegt durch die move Funktion. Jedoch erscheint das Flugzeug nur ganz kurz und verschwindet dann wieder, so als ob es gelöscht wird.
Sieht da zufällig jemand gleich den Fehler? Würde mir sehr weiterhelfen, da ich sonst nicht weiterkomme :(
Schonmal danke, 
Jana

https://janaburger.github.io/EIA2/Abschluss/abschluss.html

**Comment by MichelleZei** [comment]
Ich bin mir nich sicher, aber in deiner startingAirplane Funktion reicht wenn du a.update() hast und da musst du bei deiner airplane.ts draw und move tauschen also dass sich des Flugzeug erst bewegt und dann gemalt wird. Probiers mal obs klappt :)

**Comment by JanaBurger** [comment]
Danke, aber da ändert sich leider nichts :(

**Comment by moritzhfu** [comment]
Ich schaue mal!

**Comment by JanaBurger** [comment]
danke danke danke :))

**Comment by JanaBurger** [comment]
Ich hätte jetzt gerne, dass bei Klick auf den Flughafen das neue Flugzeug erscheint (funktioniert) und dann bis zu einem bestimmten Punkt (200, 385) geradeaus fliegt, und ab diesem Punkt dann nach oben (wie ein Flugzeug beim Start). Ich habe es schon mit setTimeout und Veränderungen in der move Methode probiert aber ich bin etwas ratlos wie genau ich das bei mir einbinde.

**Comment by JirkaDellOro** [comment]
Meiner

**Comment by JirkaDellOro** [comment]
Im Augenblick scheinst Du die Flugzeuge entsprechend ihrer Aktivität als Instanzen unterschiedlicher Klassen abbilden zu wollen. Das geht, erscheint mir aber ziemlich unintuitiv.

Schöner wäre es, wenn ein Flugzeug verschiedene Zustände hat. Der Zustand wäre eine Eigenschaft des Flugzeugs und somit in einer Variablen vielleicht vom Typ string gespeichert. Er könnte dann Werte haben wie "fly", "start", "land" etc. Dann sollte man verschiedene Bewegungsmethoden implementieren, welche den Zustand darstellen und ein der move-Methode wird einfach per switch die richtige ausgewählt.

Die Polymorphie würde ich dann für ganz andere Flugzeugarten nutzen, z.B. einen Helikopter...

Verständlich?

**Comment by JanaBurger** [comment]
Ja, ist verständlich. Dann probiere ich das mal aus, danke.

**Comment by JanaBurger** [comment]
Also ich habe mich jetzt entschieden bei den verschiedenen Klassen zu bleiben, da das mit der switch case nicht so funktioniert hat wie ich dachte. 
Ich habe versucht in der move Function des startenden Flugzeugs zu sagen wie das Flugzeug ab bestimmten Positionen fliegen soll:

if (this.x >= 200) {
                if (this.y >= 250) {
                    this.x += - 2;
                    this.y += - 1;
                    this.speed = 0.03;
                }
            }

            else {
                this.x += (Math.random() * (-3 + 1)) - 1;
                this.y += (Math.random() * (-3 + 1)) + 1;
                this.speed = 0.03;
            }

...So bleibt das Flugzeug jedoch an der Position 200, 250 einfach stehen und fliegt nicht geradeaus weiter.
Gibt es da einen Trick, dass das geht?

**Comment by JanaBurger** [comment]
Hat sich erledigt:)

**Comment by JirkaDellOro** [comment]
OK. Übrigens: was Du das machst ist bereits eine Zustandsunterscheidung. Nur das der Zustand allein durch die Position ständig neu bestimmt und nicht als Eigenschaft gespeichert wird. Dadurch wird das ganze komplizierter und weniger leserlich.

Als ich von den verschiedenen Flugzeugtypen sprach, die Du angelegt hattest, meinte ich "NormalAirplane", "StartingAirplane" und "LandingAirplane". Es schien als hättest Du vor, eine Instanz von StartingAirplane starten zu lassen und dann zu einem bestimmten Zeitpunkt durch eine Instanz von NormalAirplane zu ersetzen.

**Comment by JanaBurger** [comment]
Hallo nochmal,
da ich dem Flugzeuge in der move-Methode durch x und y Angaben sage, wie es zu fliegen hat, "startet" das StartingAirplane wenn es nochmals von rechts ins Bild fliegt nochmal. Ich frage mich ob es eine Möglichkeit gibt, dem startenden Flugzeug, wenn es eine bestimmte Position im Canvas erreicht hat, zu sagen, dass es jetzt ein "NormalAirplane" ist, und somit ganz normal weiterfliegt.

**Comment by JirkaDellOro** [comment]
Meiner

**Comment by JirkaDellOro** [comment]
OK, nun haben wir uns einmal im Kreis gedreht. Meine Empfehlung bleibt bestehen. Führe eine Zustands-Eigenschaft ein, die nach dem Start von "start" auf "fly" geändert wird. In deiner move-Methode sollte dann etwa so etwas stehen:
````
switch (this.state) {
  case "start":
    this.x += - 2;
    this.y += - 1;
    if (this.x > 200) this.state = "fly";
    break;
  case "fly":
    this.x += (Math.random() * (-3 + 1)) - 1;
    this.y += (Math.random() * (-3 + 1)) + 1;
    break;
}
````

**Comment by JanaBurger** [comment]
Ok, danke. Ich habe das nun bei mir so ähnlich eingefügt, jedoch bewegt sich das Flugzeug jetzt gar nicht mehr. Muss ich in meiner main.ts Datei irgendwie sagen, welcher case ausgeführt werden soll?

**Comment by JanaBurger** [comment]
Habe den Fehler gefunden. Hatte vergessen, im Constructor den state auf "start" zu setzen. Es geht jetzt!!! :)

**Comment by JirkaDellOro** [comment]
Hurra! :-)
