### ISSUE TITLE
Vom Monster gefressene Candys zählen

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#83]
Hallo, ich wollte implementieren, dass das Monster nur 3 Candys essen darf, bevor der Nutzer verloren hat.
Ich weiß gerade leider nicht so genau, wie ich abfangen soll, dass er schon drei verputzt hat, um dann einschreiten zu können.

Der Monster Code:
https://github.com/NadiaCredidio/EIA2/blob/master/GetTheCandy-Semesteraufgabe/Monster-Script.ts

Danke.

**Comment by JirkaDellOro** [comment]
Meiner

**Comment by JirkaDellOro** [comment]
Zunächst: der Methodenname search ist irreführend, da ja zunächst geprüft wird, ob das Monster in der Nähe einer Süßigkeit ist. Erst dann wir die gefressen und ein neues Ziel gesucht. So etwas wie eatCandyIfClose wäre aussagekräftiger. Die kann dann ggf. search() aufrufen, was nur ein neues Ziel festlegt, dann wäre es perfekt.

In einer solchen eatCandyIfClose sollte dann einfach ein Zähler hochgezählt werden, der eine Eigenschaft des Monsters darstellt und die Anzahl der gefressenen Süßigkeiten darstellt.

**Comment by NadiaCredidio** [comment]
Ich hatte da irgendwie einen Hänger, aber danke, nun klappt es .

**Comment by JirkaDellOro** [comment]
Gut!
