### ISSUE TITLE
Kreise abprallen lassen

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#84]
Hallo,

ich habe ungefähr das selbe Problem wie Lisa. Meine Kreise sollen am canvas Rand abprallen und dann sich in die andere Richtung weiter bewegen. Ich kapier einfach nicht was ich falsch mache, ich hab mir ihr Code angeschaut und ein Tutorial aus dem Internet aber keins von beidem funktioniert. 

https://github.com/MichelleFix/EIA2/tree/master/Semesteraufgabe

Vielen Dank schonmal!

**Comment by MichelleFix** [comment]
Ok ich hab es rausgefunden, ich musste die move Funktion raus werfen

**Comment by JirkaDellOro** [comment]
Sehr schön
