### ISSUE TITLE
Frage: Sind Alerts zur Erklärung des Spiels, Win und Game Over Situation okay?

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#85]
Hallo,

ich habe nun Alerts eingebaut, um den User das Spiel zu erklären, sowie rückzumelden, wenn er gewonnen oder verloren hat. Ist das okay ?

**Comment by JirkaDellOro** [comment]
Klar, was spricht dagegen?

**Comment by NadiaCredidio** [comment]
Nichts? Das passt so, danke.
