### ISSUE TITLE
Nur bei neu laden in gewünschter Größe responsiv

### ISSUE THREAD

**Issue by NadiaCredidio** [JirkaDellOro/EIA2#86]
Hallo, meine Spiel ist zwar responsiv, aber nur bei neu laden in gewünschter Größe, das müsste doch passen =)?

**Comment by JirkaDellOro** [comment]
Hmm... wie ist die Responsivität denn umgesetzt?

**Comment by NadiaCredidio** [comment]
Über das Window =)

Zudem stellen sich gerade meine Mitstudenten die Frage, ob es wirklich responsiv sein muss, da nur lauffähig in der Aufgabe steht?

**Comment by JirkaDellOro** [comment]
Stimmt, Responsivität habe ich nicht erfordert. Wohl aber, das die App auf den verschiedenen Endgerätetypen nutzbar ist.
