### ISSUE TITLE
Neu-gezeichnete Objekte erscheinen nur kurz

### ISSUE THREAD

**Issue by AlisiaSteiner** [JirkaDellOro/EIA2#87]
Hallo,

Die Timeouts in meiner Main.ts lösen aus, dass
1) Zwei "Explosionen" gezeichnet werden (bzw zwei neue Instanzen der Klasse " Explosion" erstellt werden) und
2) der "Winning Screen" auf die gleiche Weise gezeichnet wird. 
Sowohl Explosionen als auch Winnin Screen werden allerdings nur ganz kurz angezeigt und verschwinden dann wieder. Bei den Explosionen ist das nicht so schlimm, da sie ja wieder verschwinden sollen, allerdings soll der Winning Screen dauerhaft über dem Hintergrund angezeigt werden, da dort der Spieler über das Ende des Spiels informiert werden soll.

Jetzt meine Frage: Liegt es daran, dass die Funktion durch ein Timeout ausgelöst wird? 
Auch wird doch eigentlich nicht nochmal das gespeichert Hintergrundbild vom Anfang auf den Canvas gelegt. Woran könnte es also liegen, dass der Winning Screen(oder auch die Explosionen) nur so kurz angezeigt wird?

[Evtl. Frage 2: Wieso erscheint ab und zu nur eine Explosion?]
Hier meine Abschlussaufgabe:

https://alisiasteiner.github.io/EIA2/Semesteraufgabe/SpookySpook.html
https://github.com/AlisiaSteiner/EIA2/tree/master/Semesteraufgabe

Danke

**Comment by RedImp1470** [comment]
Zum Winning Screen: in deiner _Animate_-Funktion rufst du ja immer wieder _putImageData_ mit dem Parameter _imgData_ auf. Dadurch wird der Winning Screen wieder mit dem Inhalt von _imgData_ überschrieben. D.h. du könntest z.B. in deiner _StartEndOfGame_-Funkton _imageData_ updaten, dann sollte es funktionieren. 

Den Sinn der vielen _SetTimeouts_, außer bei der Verzögerung für das Respawnen der Geister, habe ich noch nicht ganz verstanden. Ist es Absicht, dass du hier mit Bruchteilen von Sekunden rechnest (1000 wäre eine Sekunde, siehe auch https://www.w3schools.com/jsref/met_win_settimeout.asp)?

Den Rest schau ich mir an.

**Comment by RedImp1470** [comment]
Das die Explosionen nur kurz zu sehen sind hat den selben Grund und ich schätze daran liegt es auch, dass manchmal nur eine Explosion zu sehen ist:

_drawExplosion_  wird aufgerufen, im _else_ gibst du an, dass sich die Funktion nach 300 ms wieder aufruft.
Zwischen durch wird wieder _Animate_ aufgerufen und übermalt die Explosion, bis nach den 300 ms wieder eine neue Explosion durch den verzögerten Aufruf von _drawExplosion_ gemalt wird usw...

Das lässt sich auch schön im Debuger des Brwosers durch das Setzen von Breakpoints nachvollziehen.

**Comment by AlisiaSteiner** [comment]
Hi

Ach, dass die Immer wieder aufgerufen wird, hab ich total übersehen. Ist ja logisch, dass es dann nicht geht. 

Danke !
