### ISSUE TITLE
Konfetti wird nicht gezeichnet

### ISSUE THREAD

**Issue by MrMarans** [JirkaDellOro/EIA2#88]
Aktuell, wenn man auf die Tür drückt, soll Konfetti gezeichnet werden und von oben nach unten fliegen. Allerdings passiert da nichts. Die Konfetti werden generiert, sie Console, aber nicht sichtbar.

Link zum Programm: https://mrmarans.github.io/EIA2/Abschluss/index.html
Main.ts: https://github.com/MrMarans/EIA2/blob/master/Abschluss/main.ts
confetti.ts: https://github.com/MrMarans/EIA2/blob/master/Abschluss/confetti.ts

Edit: Egal was ich schreibe, es scheint, wie als würden die Konfettis dazu auch immer an x und y = 10 platziert.

**Comment by MrMarans** [comment]
Gelöst. Problem war, dass die änderungen nicht in Javascript kompiliert wurden. Daher hat sich auch nicht verändet, vollkommen egla der änderungen.

**Comment by MrMarans** [comment]
Die animierung wird eindeutig ausgeführt (siehe Konsole) allerdings kein Konfetti angezeigt. Ich bin alles durchgegangen und verstehe/finde den Fehler nicht.

**Comment by MrMarans** [comment]
Gestern gelöst. schrieb anstatt lineTo einfach moveTo

**Comment by JirkaDellOro** [comment]
Interessant, hier war einmal ein Ausbleiben der Reaktion unsererseits zielführend...
