### ISSUE TITLE
1 Bündel mit Problemen

### ISSUE THREAD

**Issue by MichelleFix** [JirkaDellOro/EIA2#89]
Der rote Kreis macht ein paar Probleme:
Zunächst kommt es vor, dass er machmal nach dem Starten den Spiels nur am Canvas Rand hängt und sich nicht richtig bewegen kann. Lade ich das Spiel neu dann läuft er auch wieder normal. Aber es wär schön wenn das immer funktionieren würde.

Dann sollte er nach jedem Klick schneller werden um die Schwierigkeit zu erhöhen. Das passiert entweder auch nur manchmal oder er wird zuerst langsamer und dann nach ein paar weiteren Klicks wird er schneller, was ja so nicht sein sollte.

Zum Klicken allgemein, der rote Kreis registriert manchmal nicht, dass er angeklickt wurde. Es wird dann angezeigt, dass man den Kreis verfehlt hat...

Ich weiß leider nicht mehr weiter, ich hoffe Sie können mir helfen.
Vielen Dank schonmal !

**Comment by MichelleFix** [comment]
Und nachdem man 5 mal auf den roten Kreis gedrückt hat, soll ein zweiter gezeichnet werden

**Comment by JirkaDellOro** [comment]
Bitte Links zu der App und den Repositories zur Verfügung stellen. Siehe Hinweise zu Abschlussaufgabe

**Comment by MichelleFix** [comment]
Ups hab ich vergessen
https://github.com/MichelleFix/EIA2/tree/master/Semesteraufgabe

**Comment by moritzhfu** [comment]
Ich schaue mir mal den hängenden Kreis am Canvasrand an.

**Comment by moritzhfu** [comment]
1. Du hältst ein Array für rote Kreise vor, hast aber in der Szene immer nur einen roten Kreis am Fliegen, oder?
Hier kann fantastisch mit Polymorphie gearbeitet werden. Der rote Kreis erbt vom schwarzen Kreis und verhält sich bis auf die draw-Methode genauso wie ein schwarzer Kreis. Somit sparst du dir extra Aufrufe.
Um die 5 angeklickte Kreise zu zählen langt dann eigentlich auch eine number-Variable.

2.  Die Zufallsposition, die der rote Kreis zu Beginn des Spiels einnimmt ist zu nah am Rand und somit - in Verbindung mit der Funktion für das Abprallen - bleibt er an Ort und Stelle stecken. Hier die Parameter etwas "tweaken".

3. Die Geschwindigkeit wird z. Z. bei einem Treffer mit folgendem Code beschleunigt:
```
 // Kreis bewegt sich schneller
        rc.vx += 3;
```
Was ist denn aber, wenn der Kreis in die andere x-Richtung fliegt? Am Bildschirmrand wird die Orientierung ja umgedreht, siehe:
```
            //linker oder rechter Rand erreicht
            if (newX > crc2.canvas.width - this.radius || newX < this.radius) {
                this.vx = -this.vx;
            }
```
Wenn hier mit `+=` gearbeitet wird, nimmt natürlich die Geschwindigkeit ab.

4.  In Zeile 139 steht folgender Code:

```
    let miss: number = 0;
        miss += 1;
```
D.h. selbst wenn `miss ` vorher 1 war wird es immer erst wieder auf 0 gesetzt und danach um 1 erhöht. 
Lösung ist hier `miss ` zu einer Variable außerhalb jeglicher Funktion umzugestalten.
Danach nochmal den Bug mit dem verfehlten Klick überprüfen. Sollte er immer noch vorhanden sein kurz melden!

**Comment by MichelleFix** [comment]
Ok ich probiers aus, vielen Dank!

**Comment by MichelleFix** [comment]
Ok also es funktioniert jetzt soweit alles. Mich stört es nur, dass die schwarzen Kreise sich alle in die gleiche Richtung bewegen. Ich dachte das geht wenn ich bei jedem einzelnen Erstellen der Kreise die setRandomPosition Funktion aufrufe. Ich hab jetzt schon paar Sachen ausprobiert aber ich komm nicht drauf..

**Comment by moritzhfu** [comment]
Du setzt die Bewegungsrichtung aller Kreise im Konstruktor fest:

```
            this.vx = 2;
            this.vy = -2;
```

Damit bewegen sich natürlich alle in positiv x und negativ y. Hier kann mit Math.random gearbeitet werden.

**Comment by MichelleFix** [comment]
Ok perfekt dankeschön!!

**Comment by MichelleFix** [comment]
Ich habe noch ein Problem, es kommt mir so vor als wird nicht richtig registriert, dass man mit dem klick den roten Kreis getroffen hat, obwohl es offensichtlich ist dass man getroffen hat. 
Außerdem wird nachdem man 5 mal getroffen hat kein zweiter Kreis erstellt.

**Comment by moritzhfu** [comment]
Zeile 37:  `for (let i: number = 0; i < b; i++) {`

Deine Array läuft gegen einen festen Wert, jedoch ist ja neben den schwarzen Kreis auch rote Kreise enthalten. Bitte soviel wie möglich mit der `.length`-Methode des Arrays arbeiten.

**Comment by moritzhfu** [comment]
Warum der Kreis nicht angeklickt wird: 
Die Klickberechnung scheint mir so:

```
  let diffX: number = rc.x - _event.clientX;
 let diffY: number = rc.y - _event.clientY;

        if (Math.abs(diffX) < rc.radius && Math.abs(diffY) < rc.radius) {
           // getroffen
        }

```

nicht ganz zu funktionieren. Debugge da mal rein und schaue vor allem darauf, was der y-Wert für Werte annimmt.

**Comment by moritzhfu** [comment]
Ich habe gerade selber etwas rumprobiert. Nimm mal anstatt `_event.clientX `bzw. Y `_event.offsetX` bzw. Y.

**Comment by MichelleFix** [comment]
Ok alles klar, mit dem offset funktioniert es jetzt. 
Wegen der anderen Sache muss ich jetzt mal schauen, ich meld mich nochmal wenn ich es nicht hinbekomm.

**Comment by MichelleFix** [comment]
Was ich nicht so ganz check, was das Verdoppeln mit dem Array für die schwarzen oder allen Kreisen zu tun hat. Ich will ja nur kontrollieren, wie viele Kreise in dem Array für die angeklickten Kreise sind.

**Comment by moritzhfu** [comment]
Welches Verdoppen?

Warum stopfst du die angeklickten Kreise überhaupt in ein Array und zählst nicht einfach von 0 bis 5. Und bei 5 getroffenen Kreisen wird in das globale Kreise-Array ein neuer roter Kreis eingefügt. Damit sind 2 Kreise auf der Szene.

**Comment by MichelleFix** [comment]
Ich weiß nicht, für mich war das so logisch und auch einfacher, ich dachte mir dass es jawohl ned so schwer sein kein, einfach nochmal einen neuen Kreis zeichnen zu lassen. Wir hatten das bei den Bienen auf die gleiche Art gemacht und da hat es ja auch funktioniert. Aber wo ist der Unterschied ob ich eine Variable oder so bis 5 zählen lassen oder die Elemente im Array zähle? Muss ich am Ende nicht sowieso das gleiche machen? Ich steh glaub voll auf dem Schlauch

**Comment by JirkaDellOro** [comment]
Hallo Michelle,

habe die Mail erhalten. Da hier auch ein ganzes Bündel behandelt wird, stelle mir bitte nochmal dein aktuelles und akutes Problem dar. Prinzipiell scheint die Anwendung ja zu funktionieren.

**Comment by MichelleFix** [comment]
Ja also die Anwendung funktioniert auf jeden Fall. Nur sollte sich ab dem 5
Level, ein weiterer roter Punkt erstellt werden. Ich hatte eigentlich gedacht,
dass ich das ganz logisch gemacht hab und hab auch nochmal die Bienen Aufgabe
angeschaut weil das mit dem Erstellen der Bienen mit einem Klick ähnlich war.
Aber ja, es funktioniert halt trotzdem nicht

JirkaDellOro <notifications@github.com> hat am 21. Juli 2017 um 22:01
geschrieben:

**Comment by JirkaDellOro** [comment]
Ich bin leider zu ungeschickt, um bis zu 5 zu kommen :-(

Aber ich sehe, dass in der animate-Funktion die Schleife bis b läuft. Wird b irgendwo verändert? Wenn nicht, sieht man immer nur die gleichen 20 Kreise...
Grundsätzlich ist es hier sicher besser, mit der Länge des Arrays zu arbeiten, als mit einer zusätzlichen Variablen.

**Comment by MichelleFix** [comment]
Ja genau das meinte Moritz auch, aber ich will doch die Anzahl der roten Kreise
verändern. Die Variable hat doch nur was mit den schwarzen Kreisen zu tun? Oder
seh ich das völlig falsch?

JirkaDellOro <notifications@github.com> hat am 21. Juli 2017 um 22:38
geschrieben:

**Comment by JirkaDellOro** [comment]
ach jetzt sehe ich, dass Du noch einen rc hast, der upgedated wird. Aber den nächsten redcircle pushst Du in das Array mit den Schwarzen. Das ist auch gut so, der erste redcircle sollte besser auch da drin sein.

**Comment by JirkaDellOro** [comment]
Ich muss jetzt auch weg... hoffe Du kommst klar.

**Comment by MichelleFix** [comment]
Also ich habe jetzt die Variable b auf ++ gesetzt. Ein zweiter Kreis wird
erstellt aber er zappelt im Eck. Die roten Kreise landen jetzt im allgemeinen
Circles Array. Aber ich weiß echt nicht wie ich das hinbekommen soll, dass er
sich ganz normal bewegt

JirkaDellOro <notifications@github.com> hat am 21. Juli 2017 um 23:02
geschrieben:

**Comment by JirkaDellOro** [comment]
Kleine Fehler sind kein Problem für die Abgabe, dies erstmal zur Beruhigung. Wir geben noch Rückmeldung zu dem Fehler.
