### ISSUE TITLE
erstellte Tabelle in HTML zeigt die Anzahl der Reiskörner nicht an .

### ISSUE THREAD

**Issue by sailechr** [JirkaDellOro/EIA2#9]
Wie kann ich Werte von JavaScript in eine Tabelle, die mit HTML erstellt wurde übermitteln?
Ich weiß da nicht mehr weiter.
https://github.com/sailechr/EIA2/blob/master/Aufgabe2/schachbrett.ts

Grüße Christian Saile

**Comment by RedImp1470** [comment]
Versuche mal die Elemente mit "createElement" zu erstellen. Wenn du das machst gibt es eine Funktion die diesen HTML-Elementen einen Text hinzufügt.
Siehe: https://www.w3schools.com/jsref/met_document_createelement.asp
und: https://wiki.selfhtml.org/wiki/JavaScript/DOM/Node/textContent

**Comment by sailechr** [comment]
okay dankeschön :) ich versuche es mal :))
Aber anders geht es nicht oder ?

**Comment by moritzhfu** [comment]
Als Ergänzung: Es gibt neben von Dir verwendetem _document.write()_ auch noch _innerHTML_:
https://www.w3schools.com/jsref/prop_html_innerhtml.asp
Damit lässt sich der content von DOM-Elementen manipulieren.

Persönlich würde ich jedoch mit oben genanntem _createElement_ arbeiten. Hier können bereits im Vorfeld alle properties festgelegt werden und anschließend im DOM angehängt werden.

**Comment by RedImp1470** [comment]
Achtung: lt. Herr Dell'Oro soll _innerHTML_ in dieser Aufgabe nicht verwendet werden, sondern das Erwähnte _textContent._

**Comment by JirkaDellOro** [comment]
Korrekt! Auch kein write, bitte, nur createElement und was sich daran anschließt ist zulässig für die Aufgabe.
