### ISSUE TITLE
Abgabekriterien Unklarheit

### ISSUE THREAD

**Issue by fehren1a** [JirkaDellOro/EIA2#90]
Was genau ist bei den Hinweisen zur Abgabe mit "Eine kurze Anleitung zur Installation" gemeint bzw. abzugeben? Die Aufgabe muss ja eigentlich nicht installiert werden, da man ja den Link dazu hat.

**Comment by JirkaDellOro** [comment]
Ihr sollt euer Projekt auch gepackt zum Download zur Verfügung stellen. Was muss getan werden, um die App daraus wieder zum Laufen zu bringen, wenn eure Repositories einmal nicht mehr existieren?

**Comment by fehren1a** [comment]
Und wie kann ich das als Download zur Vefügung stellen?

**Comment by saenglert** [comment]
Auf die selbe Art und Weise, wie du uns schon sämtliche Abgaben dieses Semester zum Download angeboten hast: Du lädst es in dein Github Repository.

**Comment by fehren1a** [comment]
Achso okay, verstehe. Dachte zuerst damit ist gemeint, wenn das Online Github Repositiory mal nicht mehr existieren sollte.
Danke!

**Comment by braundominik** [comment]
Ich häng mich hier mal mit einer weiteren Frage zur Abgabe an diesen Thread an.
Bei der technischen Analyse ist nicht gefordert, dass man jeden kleinsten Aspekt der Anwendung beleuchtet oder ? Also reicht es wenn man die größten Problemfragen der Anwendung behandelt ?

**Comment by MrMarans** [comment]
Und Abgabeuhrzeit ist 18 Uhr oder theoretisch 23:59 Uhr?

**Comment by fehren1a** [comment]
Und wie kann ich denn in Github einen einzelnen Ordner downloaden? Kenne das bisher nur von einem ganzen Repo.

**Comment by MrMarans** [comment]
Komprimiere das doch einfach als .zip oder .rar Datei. Das sind im Prinzip Ordnerdateien. Ich denke, so ist das auch gemeint. In der Whatsappgruppe von MKB hab ich bereits beschrieben, wie man das zumindest auf Windows auch ohne diverse Zusatzprogramme tun kann. 

Aber noch einmal hier: Dateien anwählen, rechtsklick, senden an, Zip komprimierter Ordner.
Den dann hochladen auf GitHub und als downloadlink zur Verfügung stellen.

**Comment by RedImp1470** [comment]
Wir haben grade nochmal bei Herrn Dell'Oro wegen dem genauen Abgabezeitpunkt nachgefragt.
Die Uhrzeit wurde nicht definiert, d.h. der späteste Abgabezeitpunkt ist heute 23:59 Uhr!

**Comment by JirkaDellOro** [comment]
Wählt man in Github im Repository ein Archiv an, wird eine Download-Option angezeigt. Ihr sollt aber tatsächlich einen Link im Steckbrief zur Verfügung stellen. Das Archiv im Repository ist auch über Github-Pages verfügbar, so wie eure üblichen Abgaben auch. Darauf macht ihr einen Verweis.
