### ISSUE TITLE
Schwierigkeiten beim Zeichnen eines neuen Objektes

### ISSUE THREAD

**Issue by Matthias-Fischer** [JirkaDellOro/EIA2#92]
Bei einem bestimmten Punktestand soll ein neuer Komet in das Array gepusht (funktioniert) und gezeichnet (funktioniert nicht) werden. 
Ich habe bereits versucht n um 1 zu erhöhen (n = n +1) aber dadurch sind die Kometen nur schneller geworden.

https://github.com/Matthias-Fischer/EIA2/blob/master/abschlussaufgabe4/L7_Classes/Main.ts

**Comment by moritzhfu** [comment]
Tippt....

**Comment by moritzhfu** [comment]
Zeile 61 ` for (let i: number = 0; i < n; i++) {`

Zeile 67 `for (let i: number = 0; i < m; i++) {`

Zeile 73 `for (let i: number = 0; i < l; i++) {`

Alle Schleifen laufen gegen einen festen Wert. Wenn jetzt ein weiterer Komet dazukommt wird dieser nicht gezeichnet, da vorher abgebrochen wird. Alle festen Werte - zumindest in der Update-Methode - durch die passende `.length-Methode` des dazugehörigen Arrays ersetzen. Dann sollte es klappen.

**Comment by moritzhfu** [comment]
Nachtrag:
Zeile 87: `document.onkeydown = function(_event: KeyboardEvent): void {`

Solche Konstrukte bitte vermeiden! Hier soll mit `document.addEventListener("keydown", fooBar);` gearbeitet werden.

**Comment by Matthias-Fischer** [comment]
Das Problem ist mir nun klar. Dass man durch .length keine festen Werte mehr erzeugt ist mir auch klar. Jedoch weiß ich nicht was dabei in der Update Methode geändert werden soll

**Comment by Matthias-Fischer** [comment]
Danke für Deine Hilfe Moritz habe es nun auf eine andere Art hinbekommen :)
