### ISSUE TITLE
BigFish bewegt sich nicht

### ISSUE THREAD

**Issue by muelle1t** [JirkaDellOro/EIA2#93]
Ich bin mir nicht sicher ob Issues noch bearbeitet werden aber ich dachte ich versuche es mal.

Da ich Aufschub bis morgen erhalten habe stehe ich erst jetzt vor den kleinen Hindernissen.

Ich habe zwei Fischarten im Aquarium, die aber nicht Teil der selben Klasse sind. Die kleinen Fische funktionieren einwandfrei aber der "Böse" Fisch wird zwar gezeichnet bewegt sich aber einfach nicht.

https://muelle1t.github.io/EIA2//Semesteraufgabe/Aquarium.html

https://github.com/muelle1t/EIA2/tree/master/Semesteraufgabe

Ich wäre über jegliche Hilfe dankbar.

Vielen Dank im Voraus!

**Comment by MrMarans** [comment]
Du hast, soweit ich das auf die schnelle erkannt habe, bei bigfish, was wahrscheinlich der böse Fisch ist bei Update 3 Sachen drin.

1. Er soll sich mit Math.random()*4-2 bewegen.
2. Er soll auf x300 und y200 platziert werden
3. Er soll gezeichnet werden.

Natürlich bewegt er sich nicht, wenn nach jeder Rechnung für die Bewegung das Ereignis überschrieben wird und du x von z.B. vorher 302 wieder auf 300 setzt.

Daher dürfte das this.setStartPosition wohl der Fehler sein.

**Comment by muelle1t** [comment]
Danke aber das scheint es nicht nur zu sein ... 
Hab es auskommentiert und es klappt immer noch nicht.

**Comment by saenglert** [comment]
Moin moin,
helfen würde ich nach wie vor, nur wäre es besser, wenn das nicht immer kurz vor knapp wäre.
Zur Sache: Houston, wir haben nicht nur ein Problem.

**waterworld.ts**
Dass dein Programm grundlegend nochmal überdacht werden sollte, da du zum Beispiel mit zwei seperaten Timeoutbefehlen arbeitest, lasse ich mal so stehen, da ja scheinbar etwas die Zeit drängt.

Um einen kleinen Rewrite kommen wir aber nicht herum. 

**1)**Deine `updateBigFish` Funktion scheint das zu tun (zumindest für den großen Fisch), was die animate bei unseren Sommerlandschaften macht, nämlich die Animation zu aktualisieren. 

Bei dir allerdings wird durch die Zeile 112
`let bady: BigFish = new BigFish(300, 100);`
die globale `bady` Variable die du in Zeile 21 anlegst, für die weitere Aufgabe der Funktion verdeckt. Das führt dazu, dass es nie einen globalen `BigFish` gibt, sondern immer nur einen im Funktion Scope der nach Ausführung der Funktion dann auch weg ist und beim nächsten Aufruf wieder neu erstellt wird. Stattdessen muss die globale `bady` Variable mit einem `BigFish` gefüllt werden.

**2)** Die `animatefish` Funktion scheint dasselbe für die kleinen Fische zu tun, was die `updateBigFish` für den großen macht. Hier baust du deinen zweiten Timeout ein.  Bedingt durch die unterschiedlichen Laufzeiten der Funktionen, ist aber nicht sichergestellt, dass die Timeouts zur gleichen Zeit beginnen oder enden. 

Dadurch ergibts sich manchmal ein Flackern des großen Fischs auf dem Canvas: `animateFish` wird aufgerufen, erneuert den Hintergrund des Canvas und zeichnet die kleinen Fische. `updateBigFish` ist allerdings noch im Timeout, also wird auch der große Fisch noch nicht gezeichnet. Ergo sieht man für ein paar Millisekunden keinen großen Fisch, bis der zweite Timeout endet und `updateBigFish` den großen Fisch zeichnet. Um solche Timingprobleme zu vermeiden, hatten wir mit der animate Funktion immer eine zentrale Schaltstelle die sich um alle Updatevorgänge kümmert.

Ein schneller Fix ist es den Timeout aus `animateFish` zu entfernen und die Funktion innerhalb von `updateBigFish` mit aufzurufen.

TL:DR
Zeile 139 raus
Zeile 112 raus
Zeile 115 einfügen `animateFish();`
Zeile 81 einfügen `bady: BigFish = new BigFish(300, 100);`

**BigFish.ts**
**1)**Ich nehme mal nicht an, dass du ein regelmäßiger Nutzer der Konsole des Browser bist, denn dann wäre dir aufgefallen, dass du in Zeile 64 und 65 `NaN` als Ergebnis deiner Addition erhälst. Das wiederum bedeutet einer der der beiden Werte ist keine Zahl. Dabei handelt es sich um deine Werte für `xTarget` und `yTarget`, aufgrund der Tatsache, dass im Konstruktor die Zeile 25 mit der `setRandomTargetPosition` Funktion auskommentiert ist und dadurch auch keine Werte für diese Variablen gesetzt werden.

**2)**Zu guter Letzt deine `move` Funktion. Ohne groß auf die Mathematik einzugehen (es ist 3 Uhr morgens, hallo), verwende folgende Formel für die Bewegung in X- bzw. Y-Richtung um ein relativ geschmeidiges Ergebnis zu erziehlen:
```
this.x += xDiff / distance * this.speed;
this.y += yDiff / distance * this.speed;
```
Wie sich die Distanz zwischen zwei Punkten im zweidimensionalen Raum berechnet, traue ich dir zu. Du hast es ja immerhin schon bis zur Hochschulreife gebracht.

Desweiteren solltest du die maximale Distanz in Zeile 67 erhöhen, die der Fisch entfernt sein darf und trotzdem ein neues Ziel zugewiesen bekommt. 0,5 Pixel Genauigkeit ist für unsere Berechnungen schon verdammt viel. Bei einer heute üblichen 1920x1080 Auflösung von Bildschirmen fällt es auch nicht auf wenn der Fisch schon bei 5 Pixel Abstand umdreht.

Und jetzt aber gute Nacht und vor heute 12 Uhr wird es vermutlich von mir keine Antwort hier mehr geben. zzZz
