### ISSUE TITLE
Ich habe eine Frage

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/EIA2#94]
Ich habe sie vergessen...

**Comment by saenglert** [comment]
> Ich habe eine Frage
 a minute ago
> Ich habe sie vergessen...
 a minute ago

Das Alterswohnheim ist gegenüber vom L-Bau ... nur so als Vorsichtsmaßnahme.

**Comment by JirkaDellOro** [comment]
Ha, der Sascha ist noch dabei.

Lieben Gruß!
