### ISSUE TITLE
Inhalt wird nicht angezeigt

### ISSUE THREAD

**Issue by MonettaMarchiano** [JirkaDellOro/EIA2#95]
Hey,
mein Inhalt in der html-Datei wird nicht angezeigt obwohl es richtig verlinkt sein müsste.

**Comment by moritzhfu** [comment]
Hey,

bei mir geht es. Manchmal dauert es etwas bis alles von Github bzw. -Pages kopiert wurde.

Ansonsten hast Du noch einen Fehler in deiner Typescript-Datei. Den solltest Du aber selber geheilt bekommen.

Bitte immer direkt auf die entsprechende problematische Seite verlinken:
[https://monettamarchiano.github.io/EIA-2/Aufgabe0/Mini-Page.html](url)
