### ISSUE TITLE
Hochgeladene Datein werden nicht in GIT angezeigt

### ISSUE THREAD

**Issue by vanessanova** [JirkaDellOro/EIA2#96]
Wenn ich meine Datein von Eclipse über Commit&Push hochgeladen habe auf Github wird es mir nicht in meinem EIA2 Repository angezeigt. 
Es gibt allerdings keine Fehlermeldung. 
Warum? :smile: 

Viele Grüße 
Vanessa

**Comment by moritzhfu** [comment]
Ferndiagnose so schwierig.
Der letzte Push vor einer Stunde (Steckbrief geändert) hat funktioniert.

Irgendetwas an der Konfiguration geändert?
Auch die Dateien via Drag-And-Drop unter Staged Changes abgelegt?
