### ISSUE TITLE
HTTP Adresse der Abgaben

### ISSUE THREAD

**Issue by RomanBayer** [JirkaDellOro/EIA2#97]
Hallo,

ich habe das Problem, dass ich die HTTP Adressen für die Registrierung des Steckbriefs sowie für die Verlinkung der Abgaben nicht herausfinde. 
Für die Adresse https://romanbayer.github.io/EIA2neu/00Miniseite/Miniseite.html
kommt dann die Meldung
404-There isn't a GitHub Pages site here.

Gruß Roman

**Comment by JirkaDellOro** [comment]
Ist denn die Projektseite für Pages freigeschaltet?

**Comment by RomanBayer** [comment]
Das war der Fehler!
Wenn ich für die Registrierung meines Steckbrief die Ordneradresse angeben muss, bekomme ich aber wieder die Meldung 404...
Auf die Miniseite kann ich allerdings zugreifen

**Comment by moritzhfu** [comment]
GitHub Pages bietet keine Möglichkeit einzelne Dateien im Ordner darzustellen.
Findet er eine Readme.me oder eine index.html stellt er diese dar.

Sollte jedoch der Ordner z.B. nur aus einer steckbrief.htm und portrait.jpg bestehen, so findet er keins von beiden Obengenannten und gibt dementsprechend einen 404 (nicht gefunden) Fehler aus.

Solange diese Dateien aber explizit per Eingabe abrufbar sind sollte es mit der Kursseite funktionieren. 
Was es auch tut: https://romanbayer.github.io/EIA2neu/Steckbrief/steckbrief.htm
