### ISSUE TITLE
Datei kann nicht hochgeladen werden

### ISSUE THREAD

**Issue by vanessanova** [JirkaDellOro/EIA2#98]
Troz richtigem Link im Steckbrief wird meine Datei nicht hochgeladen. 
Warum? 
Sorry für die vielen Fragen :smile: 

Viele Grüße Vanessa

**Comment by JirkaDellOro** [comment]
Hallo Vanessa,

Sie haben ihre Links in den style des bodies geschrieben, nicht in den HTML-Body!
