### ISSUE TITLE
Dateien können nicht auf Kursseite hochgeladen werden

### ISSUE THREAD

**Issue by muellisa** [JirkaDellOro/EIA2#99]
Trotz richtiger Verlinkung wird weder mein Steckbrief inklusive verlinkter Aufgaben noch mein Foto auf der Kursseite angezeigt. Ich finde das Problem nicht , mein Repository müsste auch für Pages freigeschaltet sein.

**Comment by saenglert** [comment]
Hallo Isabell,
dein Link zum Steckbrief/Portrait ist leider nur zu 99% korrekt:

`https://muellisa.github.io/EIA2/Steckbrief/steckbrief.htm?r=753663 // funktioniert nicht`
vs
`https://muellisa.github.io/EIA2/steckbrief/steckbrief.htm?r=753663 // funktioniert`
Groß/Kleinschreibung ist auch in URLs wichtig. Ändere einfach den Namen des Ordners 'steckbrief' in 'Steckbrief' in deinem Projekt.

Außerdem fehlt noch dein Portrait in dem Ordner. Verschieb es ebenfalls aus deinem Hauptordner in den Ordner 'Steckbrief', da du folgenden Link fürs Portrait angeben hast:

`https://muellisa.github.io/EIA2/Steckbrief/portrait.jpg`

Grüße
Sascha
